#define main fixture_main
#include "xdg-origin-client.c"
#undef main
static unsigned checks, failures, connections;
#define CHECK(name, condition) do { ++checks; if(!(condition)){++failures;fprintf(stderr,"FAIL %s\n",name);} } while(0)
struct wl_display *__wrap_wl_display_connect(const char *name){(void)name;++connections;return NULL;}
int main(void){
    struct profile p; int v,lw,lh,bw,bh;size_t bytes;
    char *defaults[]={"fixture","--validate"};
    CHECK("defaults",parse_profile(2,defaults,&p));
    CHECK("nonzero-defaults",p.x==16 && p.y==24 && p.scale==1);
    CHECK("default-dimensions",dimensions(&p,320,180,&lw,&lh,&bw,&bh,&bytes) && lw==352 && lh==228 && bw==352 && bh==228 && bytes==352u*228u*4u);
    p.scale=2;
    CHECK("buffer-times-scale-only",dimensions(&p,320,180,&lw,&lh,&bw,&bh,&bytes) && lw==352 && lh==228 && bw==704 && bh==456 && bytes==704u*456u*4u);
    CHECK("outside-pad",color(&p,320,180,0,0,7)==0xff202020);
    CHECK("top-left",color(&p,320,180,20,28,7)==0xffff3030);
    CHECK("top-right",color(&p,320,180,332,28,7)==0xff30ff30);
    CHECK("bottom-left",color(&p,320,180,20,200,7)==0xff3030ff);
    CHECK("bottom-right",color(&p,320,180,332,200,7)==0xffffff30);
    CHECK("edge",color(&p,320,180,16,64,7)==0xffffffff);
    CHECK("interior-serial",color(&p,320,180,176,114,7)==interior(7));
    CHECK("serial-color-changes",interior(7)!=interior(8));
    CHECK("minimum-landmark-extent",dimensions(&p,32,32,&lw,&lh,&bw,&bh,&bytes));
    CHECK("center-smallest",color(&p,32,32,32,40,7)==interior(7));
    CHECK("reject-small",!dimensions(&p,31,32,&lw,&lh,&bw,&bh,&bytes));
    CHECK("reject-zero",!dimensions(&p,0,32,&lw,&lh,&bw,&bh,&bytes));
    CHECK("reject-negative",!dimensions(&p,-1,32,&lw,&lh,&bw,&bh,&bytes));
    CHECK("reject-per-buffer-cap",!dimensions(&p,4096,4096,&lw,&lh,&bw,&bh,&bytes));
    p.scale=3;CHECK("reject-invalid-scale",!dimensions(&p,320,180,&lw,&lh,&bw,&bh,&bytes));
    CHECK("uint-zero",number("0",4096,&v)&&v==0);
    CHECK("uint-max",number("4096",4096,&v)&&v==4096);
    CHECK("reject-overflow",!number("999999999999999999999999999",4096,&v));
    CHECK("reject-leading-zero",!number("01",4096,&v));
    CHECK("reject-negative-text",!number("-1",4096,&v));
    CHECK("reject-sign",!number("+1",4096,&v));
    CHECK("reject-space",!number(" 1",4096,&v));
    CHECK("reject-empty",!number("",4096,&v));
    CHECK("reject-null",!number(NULL,4096,&v));
    char *zero[]={"fixture","--validate","--origin-x","0","--origin-y","0","--right-pad","0","--bottom-pad","0","--scale","2"};
    CHECK("zero-profile",parse_profile(12,zero,&p) && p.x==0 && p.y==0 && p.scale==2);
    CHECK("zero-scale2-map",dimensions(&p,320,180,&lw,&lh,&bw,&bh,&bytes) && lw==320 && lh==180 && bw==640 && bh==360);
    char *hints[]={"fixture","--validate","--min-width","108","--min-height","42","--max-width","0","--max-height","42"};
    CHECK("fixed-hints-preserved",parse_profile(10,hints,&p) && p.minw==108 && p.minh==42 && p.maxw==0 && p.maxh==42);
    CHECK("initial-hint-mismatch-refused",!dimensions(&p,320,180,&lw,&lh,&bw,&bh,&bytes));
    CHECK("valid-fixed-hint-size",dimensions(&p,320,42,&lw,&lh,&bw,&bh,&bytes));
    CHECK("raw-minimum-refused",!dimensions(&p,64,42,&lw,&lh,&bw,&bh,&bytes));
    char *bad[]={"fixture","--max-width","7","--min-width","8"};
    CHECK("reject-inverted-hints",!parse_profile(5,bad,&p));
    char *dup[]={"fixture","--scale","1","--scale","2"};CHECK("reject-duplicate",!parse_profile(5,dup,&p));
    char *missing[]={"fixture","--origin-x"};CHECK("reject-missing",!parse_profile(2,missing,&p));
    char *unknown[]={"fixture","--command","anything"};CHECK("reject-unknown",!parse_profile(3,unknown,&p));
    CHECK("actual-main-validate",fixture_main(2,defaults)==0 && connections==0);
    CHECK("actual-main-invalid",fixture_main(2,missing)==64 && connections==0);
    struct client c={.surface=(struct wl_surface *)(uintptr_t)1,.width=320,.height=180};
    pointer_enter(&c,NULL,99,(struct wl_surface *)(uintptr_t)2,wl_fixed_from_int(20),wl_fixed_from_int(28));
    CHECK("foreign-surface-no-event",!c.pointer_owned && c.sequence==0);
    pointer_enter(&c,NULL,100,c.surface,wl_fixed_from_double(20.25),wl_fixed_from_double(28.5));
    CHECK("owned-enter",c.pointer_owned && c.sequence==1 && c.pointer_x==wl_fixed_from_double(20.25) && c.pointer_y==wl_fixed_from_double(28.5));
    pointer_button(&c,NULL,101,50,272,1);CHECK("owned-button",c.sequence==2);
    pointer_leave(&c,NULL,102,c.surface);CHECK("owned-leave",!c.pointer_owned && c.sequence==3);
    pointer_button(&c,NULL,103,51,272,0);CHECK("outside-no-button",c.sequence==3);
    struct client config={0};uint32_t state=XDG_TOPLEVEL_STATE_MAXIMIZED;struct wl_array array={.size=sizeof state,.data=&state};
    toplevel_configure(&config,NULL,798,550,&array);CHECK("actual-configure-state",config.staged_width==798 && config.staged_height==550 && config.pending_maximized && !config.failed);
    array.size=3;toplevel_configure(&config,NULL,798,550,&array);CHECK("actual-configure-malformed-array",config.failed && config.quit);
    config=(struct client){0};array=(struct wl_array){.size=4,.data=NULL};toplevel_configure(&config,NULL,798,550,&array);CHECK("actual-configure-null-array",config.failed);
    config=(struct client){0};array=(struct wl_array){0};toplevel_configure(&config,NULL,-1,550,&array);CHECK("actual-configure-negative",config.failed);
    config=(struct client){0};toplevel_configure(&config,NULL,0,0,&array);CHECK("actual-configure-zero-axes",config.staged_width==0 && config.staged_height==0 && !config.failed);
    int cw,ch;struct profile choice={.x=16,.y=24,.right=16,.bottom=24,.scale=1,.width=320,.height=180,.maxw=400,.maxh=300};
    CHECK("ordinary-finite-proposal",choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch) && cw==400 && ch==300);
    CHECK("MAX-finite-incompatible-refused",!choose_geometry(&choice,800,600,320,180,true,false,false,&cw,&ch));
    CHECK("MAX-finite-exact",choose_geometry(&choice,400,300,320,180,true,false,false,&cw,&ch) && cw==400 && ch==300);
    CHECK("ordinary-zero-fallback",choose_geometry(&choice,0,0,320,180,false,false,false,&cw,&ch) && cw==320 && ch==180);
    CHECK("ordinary-zero-fallback-clamped",choose_geometry(&choice,0,0,800,600,false,false,false,&cw,&ch) && cw==400 && ch==300);
    CHECK("MAX-zero-client-choice",choose_geometry(&choice,0,0,800,600,true,false,false,&cw,&ch) && cw==400 && ch==300);
    CHECK("fullscreen-finite-within-proposal",choose_geometry(&choice,800,600,320,180,false,true,false,&cw,&ch) && cw==400 && ch==300);
    CHECK("resizing-finite-within-proposal",choose_geometry(&choice,800,600,320,180,false,false,true,&cw,&ch) && cw==400 && ch==300);
    choice.minw=320;choice.maxw=320;choice.minh=180;choice.maxh=180;
    CHECK("ordinary-fixed-choice",choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch) && cw==320 && ch==180);
    CHECK("ordinary-fixed-smaller-proposal",choose_geometry(&choice,100,50,320,180,false,false,false,&cw,&ch) && cw==320 && ch==180);
    CHECK("MAX-fixed-incompatible",!choose_geometry(&choice,800,600,320,180,true,false,false,&cw,&ch));
    CHECK("MAX-fixed-exact",choose_geometry(&choice,320,180,320,180,true,false,false,&cw,&ch));
    CHECK("fullscreen-below-minimum-refused",!choose_geometry(&choice,100,50,320,180,false,true,false,&cw,&ch));
    CHECK("resizing-below-minimum-refused",!choose_geometry(&choice,100,50,320,180,false,false,true,&cw,&ch));
    choice=(struct profile){.scale=1,.minw=108,.minh=42};
    CHECK("GTK-minimum-choice",choose_geometry(&choice,64,32,320,180,false,false,false,&cw,&ch) && cw==108 && ch==42);
    CHECK("MAX-minimum-incompatible",!choose_geometry(&choice,64,32,320,180,true,false,false,&cw,&ch));
    CHECK("ordinary-unbounded",choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch) && cw==800 && ch==600);
    CHECK("proposal-over-buffer-ceiling-clamped",choose_geometry(&choice,INT32_MAX,INT32_MAX,320,180,false,false,false,&cw,&ch) && cw==4096 && ch==4096);
    CHECK("MAX-over-buffer-ceiling-refused",!choose_geometry(&choice,INT32_MAX,600,320,180,true,false,false,&cw,&ch));
    choice.maxw=400;choice.maxh=0;
    CHECK("independent-max-axis",choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch) && cw==400 && ch==600);
    CHECK("negative-proposal-refused",!choose_geometry(&choice,-1,600,320,180,false,false,false,&cw,&ch));
    choice.minw=401;CHECK("empty-interval-refused",!choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch));
    choice=(struct profile){.scale=2,.x=16,.y=24,.right=16,.bottom=24,.maxw=400,.maxh=300};
    CHECK("scale2-choice-stays-logical",choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch) && cw==400 && ch==300);
    CHECK("scale2-chosen-buffer",dimensions(&choice,cw,ch,&lw,&lh,&bw,&bh,&bytes) && bw==864 && bh==696);
    choice.maxw=31;CHECK("tiny-max-no-legal-landmarks",!choose_geometry(&choice,800,600,320,180,false,false,false,&cw,&ch));
    printf("{\"helperChecks\":%u,\"failures\":%u,\"connections\":%u}\n",checks,failures,connections);
    return failures?1:0;
}
