import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=3770
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report132.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v132',['PROGRESS PUBLIC97 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI132 actual normal GUI close/reopen two pointer cycles/same policy/native binding/fresh fixed-grant pure renderer/strict C Bootstrap closes/epoch navigation lease request1->2/current source URI red19200 each/opacity0 closed output. Native14546checks18normalexits retains original29; Native14429/13 and delayed14618/8 unchanged regressions/private cleanups pass. Full119, Quint9named200samples and six stages coupled to actual observations; failed131 held. Native issuer/policy/physical product/deadlines unchanged/no resets; pending-intent code/model only not actual qualified, broader async/process/reload/Unknown/physical ongoing conceal reveal hardware/pressure workload RSS/full preview/release open. Next fresh actual pending-intent and old-context qualification; installed/drafts/foreign preserved.'],'progress',['docs/warlock-preview/v93/component-report132.json','implementation/warlock-preview-provider-v132/component-manifest.json','implementation/warlock-client-provider-native-v145/component-manifest.json','docs/warlock-repository/v97/publication/delivery.json']);print(e)
