import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=4025
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report130.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v130',['PROGRESS PUBLIC96 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI130 same persistent Elm policy C/JSC realm reuse143 checks/two sealed-FD captures/same binding and policy pointer/permanent retired21 replay rejection/new Active22 capture/strict final close. Original2261+9/current full119/Quint8named200samples/six stages coupled to11 concrete observations pass. Actual Native142 unchanged29checks13normalexits and delayedNative14318checks8normalexits/private cleanups pass. Native original grants/issuer/policy/physical product/deadlines unchanged/no grant reset; popup quarantine precedes permanent retirement. Direct-retirement failed fixture retained/unqualified. Actual GUI rebind/fixed-grant context replacement and normal reopen not yet wired; physical reveal/ongoing conceal/hardware/pressure/workload/RSS/reload/process/uncertain recovery/full preview/release open. Next fresh native host lifecycle integration; installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-report130.json','implementation/warlock-preview-provider-v130/component-manifest.json','implementation/warlock-client-provider-native-v142/component-manifest.json','implementation/warlock-client-provider-native-v143/component-manifest.json','docs/warlock-repository/v96/publication/delivery.json']);print(e)
