import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=2265
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report118.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v118',['PROGRESS PUBLIC87 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI118 readonly visual custody with parent Elm policy/native issuer/effects/physical unchanged. Original C/JSC/native207 plus90 visual/74 readonly/two epochs/unchanged grant/normal; lifetime37+15/13 pre-grant faults/Quint14/26 actual C+JSC traces/430 states/200 samples/five compiled guards; backpressure48+28 explicitly synthetic facts; full112 retains112. Getter invokes no JS/model/effect/ordinal, copies survive caller mutation, original ordinary input block and refuse missing/foreign/absent/closed/unknown/inflight authority. Next authenticated ordered native current-projection channel/renderer lease/reload concealment and durable original host input/native-ticket custody/retry before actual WebKit/Core. Copies alone provide no freshness/order/DOM/URI/physical/recovery/full release proof. Native130 legacy2518/278 remains actual bounded baseline; installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/component-report118.json','implementation/warlock-preview-provider-v118/component-manifest.json','docs/warlock-repository/v87/publication/delivery.json']);print(e)
