// Exact unchanged product capture helper, actual QProcess/kernel observer.
// The server's native projection is the reviewed inert CPU fixture. This does
// not establish actual Quickshell Process, native capture or Pin UI authority.
#define main retained_generic_cpu_main
#include "cpu_process_runtime.cpp"
#undef main
#include <fcntl.h>
#include <sys/stat.h>
#include <thread>
int main(int argc,char**args){QCoreApplication app(argc,args);try{
 std::cout<<"{\"requesterPID\":"<<getpid()<<"}"<<std::endl;std::string payload;std::getline(std::cin,payload);const auto config=strictObject(QByteArray::fromStdString(payload));const auto path=config["configPath"].toString(),manifestPath=config["manifestPath"].toString();const auto raw=guardedRegular(path,0600,getuid(),1048576);const auto pin=strictObject(raw);const auto entry=pin["captureEntry"].toObject()["path"].toString();const auto input=config["publicJSON"].toString();const auto packet=strictObject(boundedFile(manifestPath,16*1024*1024),16*1024*1024);const auto wanted=pin["captureEntry"].toObject()["sha256"].toString().toLatin1();check(digest(guardedRegular(entry,0700,getuid(),1048576))==wanted,"actual unchanged product capture entry source");
 Registry base;ProcessRegistry observer(base);Case c(base,QStringList{entry,"capture",input});auto spec=c.arm(packet);spec.role="CPUProductCaptureFixture";spec.kernel.executable=pin["interpreter"].toObject()["path"].toString();spec.kernel.executableSHA256=pin["interpreter"].toObject()["sha256"].toString().toLatin1();spec.kernel.argv=argv(QStringList{"/usr/bin/python3","-I","-S",entry,"capture",input});spec.kernel.environment.clear();const auto selectors=pin["selectors"].toObject();QProcessEnvironment env;for(auto i=selectors.begin();i!=selectors.end();++i){env.insert(i.key(),i.value().toString());spec.kernel.environment[i.key().toUtf8()]=i.value().toString().toUtf8();}env.insert("PATH","/usr/bin");spec.kernel.environment["PATH"]="/usr/bin";
 const auto declaredObserver=pin["requestRoots"].toArray()[0].toObject();spec.kernel.observerExecutable=declaredObserver["executable"].toString();spec.kernel.observerSHA256=declaredObserver["executableSHA256"].toString().toLatin1();QStringList declaredARGV;for(const auto&part:declaredObserver["argv"].toArray())declaredARGV<<part.toString();spec.kernel.observerARGV=argv(declaredARGV);spec.kernel.observerCgroup=declaredObserver["cgroup"].toString().toUtf8();for(auto i=selectors.begin();i!=selectors.end();++i)if(qEnvironmentVariableIsSet(i.key().toUtf8().constData()))spec.kernel.observerEnvironment[i.key().toUtf8()]=qgetenv(i.key().toUtf8().constData());spec.kernel.observerEnvironment["PATH"]=declaredObserver["environment"].toObject()["PATH"].toString().toUtf8();
 spec.sourceGuard=[&]{if(guardedRegular(path,0600,getuid(),1048576)!=raw||digest(guardedRegular(entry,0700,getuid(),1048576))!=wanted)throw Refused("Actual immutable product helper/config changed");};
 spec.receiptGuard=[&](const QByteArray&out,const QByteArray&err,const KernelWitness&w,int code){
  if(code!=0||!err.isEmpty())throw Refused("Actual unchanged capture helper positive exit required");const auto r=strictObject(out),authority=r["authority"].toObject(),frontend=authority["frontend"].toObject();if(r["result"]!=QJsonValue("captured")||r["nativeWrites"]!=QJsonValue(0)||r["automaticRetries"]!=QJsonValue(0)||r["nativeCompletionClaimed"]!=QJsonValue(false)||frontend!=QJsonObject{{"pid",w.pid},{"start",w.start},{"parent",w.parent},{"pgid",w.group}})throw Refused("Actual capture helper kernel/outcome projection differs");const auto requester=authority["requester"].toObject(),root=pin["requestRoots"].toArray()[0].toObject()["identity"].toObject(),server=pin["compositor"].toObject()["identity"].toObject();if(requester!=root||requester["pid"].toInt()!=getpid()||authority["compositor"].toObject()!=server||authority["role"]!=QJsonValue("harness"))throw Refused("Actual private requester/server projection differs");const auto transport=r["transport"].toObject(),peer=transport["peer"].toObject();if(transport["sendStarted"]!=QJsonValue(true)||transport["completeServerEOF"]!=QJsonValue(true)||peer["pid"]!=server["pid"]||peer["uid"].toInt()!=int(getuid())||r["publicIdentity"].toObject()!=strictObject(input.toUtf8()))throw Refused("Actual private capture identity/peer/EOF differs");const auto captured=r["captured"].toObject();if(captured!=r["rawNativeResult"].toObject()||captured["compositorPid"]!=server["pid"]||captured["compositorStart"]!=server["start"])throw Refused("Actual capture token projection differs");const auto file=pin["evidenceDirectory"].toString()+'/'+QString::number(w.pid)+'-'+w.start+".json";if(strictObject(guardedRegular(file,0600,getuid(),1048576))!=r)throw Refused("Actual durable private helper receipt differs");
 };
 const auto rearmSpec=spec;const auto lease=observer.arm(std::move(spec));QObject::disconnect(&c.process.child,&QProcess::started,&c.process,nullptr);QObject::connect(&c.process.child,&QProcess::started,&c.process,[&]{emit c.process.started();}); // actual started, no generic fixture stdin barrier
 c.process.child.setProcessEnvironment(env);c.process.child.setProgram(entry);c.process.child.setArguments({"capture",input});QEventLoop loop;QTimer timer;timer.setSingleShot(true);timer.setInterval(4000);QObject::connect(&timer,&QTimer::timeout,&loop,&QEventLoop::quit);QTimer observe;observe.setInterval(1);QObject::connect(&observe,&QTimer::timeout,&loop,[&]{if(c.process.child.state()==QProcess::NotRunning&&observer.terminalInventory()["allWorkersJoined"].toBool())loop.quit();});timer.setInterval(2000);timer.start();c.process.child.start();observe.start();loop.exec();observe.stop();const auto inventory=observer.terminalInventory();const auto state=observer.state(&c.process);const bool baseline=c.process.child.state()==QProcess::NotRunning&&state["normalLifecycle"].toBool()&&state["complete"].toBool();check(baseline,"Actual unchanged fast helper must be accepted before registry negative");QVariantList negatives;QVariantMap negativeEvidence;const auto scenario=config["registryCase"].toString();
 auto record=[&](const QString&name,bool passed){negatives<<QVariantMap{{"name",name},{"passed",passed}};if(!passed)std::cout<<QJsonDocument(QJsonObject{{"result","fail"},{"actualRegistryNegatives",QJsonArray::fromVariantList(negatives)},{"failedObservation",QJsonObject::fromVariantMap(negativeEvidence)}}).toJson(QJsonDocument::Compact).constData()<<std::endl;check(passed,qPrintable(name));};
 if(scenario=="old-current-rearm"){
  const auto before=observer.state(&c.process);const auto invBefore=observer.terminalInventory();for(int kind=0;kind<=4;++kind)observer.callback(&c.process,lease-1,kind,3,QProcess::CrashExit);record("actual old owner-thread callbacks preserve accepted exact record",observer.state(&c.process)==before&&observer.terminalInventory()==invBefore);
  std::thread old([&]{for(int kind=0;kind<=4;++kind)observer.callback(&c.process,lease-1,kind,3,QProcess::CrashExit);});old.join();record("actual old foreign callbacks drain inert before query",observer.state(&c.process)==before&&observer.terminalInventory()==invBefore);QCoreApplication::processEvents();record("actual queued old callbacks remain inert",observer.state(&c.process)==before);
  std::thread current([&]{observer.callback(&c.process,lease,2);});current.join();bool refused=false;try{observer.arm(rearmSpec);}catch(const Refused&){refused=true;}const auto after=observer.state(&c.process);record("actual current foreign callback immediately before rearm cannot become stale",refused&&after["lease"]==before["lease"]&&after["fault"].toBool()&&!after["kernelBound"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());QCoreApplication::processEvents();record("queued current fault retains normal joined worker inventory",observer.terminalInventory()["allWorkersJoined"].toBool());
 }else if(scenario=="duplicate-eof"){
  emit c.out.streamFinished();const auto after=observer.state(&c.process);record("actual native collector duplicate current EOF faults",after["fault"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="duplicate-start"){
  emit c.process.started();const auto after=observer.state(&c.process);record("actual native Process duplicate current Started faults",after["fault"].toBool()&&!after["complete"].toBool());
 }else if(scenario=="source-replacement"){
  const auto encoded=path.toUtf8();const int fd=open(encoded.constData(),O_WRONLY|O_CLOEXEC);check(fd>=0,"Owned private config mutation fixture FD");check(pwrite(fd," ",1,raw.size())==1&&fsync(fd)==0,"Owned private config mutation persisted");close(fd);const auto after=observer.state(&c.process);record("actual source bytes replacement revokes accepted completion",after["fault"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="context-replacement"){
  const auto priorContext=QQmlEngine::contextForObject(&c.row);QQmlContext replacement(c.engine.rootContext());QQmlEngine::setContextForObject(&c.row,&replacement);const auto observedContext=QQmlEngine::contextForObject(&c.row);const auto after=observer.state(&c.process);negativeEvidence={{"contextActuallyChanged",observedContext!=priorContext},{"newContextActuallySelected",observedContext==&replacement},{"after",after}};record("actual lexical QQmlContext replacement revokes completion",after["fault"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="retire"){
  observer.cancel(&c.process);const auto after=observer.state(&c.process);record("actual current consumer retire forbids completion retains historical normal life",!after["current"].toBool()&&!after["complete"].toBool()&&after["normalLifecycle"].toBool()&&after["workerJoined"].toBool());
 }else if(scenario=="collector-pointer"){
  StdioCollector foreign;c.process.outAllocation=&foreign;const auto after=observer.state(&c.process);record("actual native parser getter pointer replacement revokes completion",after["fault"].toBool()&&!after["complete"].toBool());
 }else throw Refused("Declared exact registry negative scenario required");
 record("all actual readonly worker jobs remain normally joined",observer.terminalInventory()["allWorkersJoined"].toBool());const bool pass=true;QJsonObject report{{"result",pass?"pass":"fail"},{"lease",qint64(lease)},{"registryCase",scenario},{"actualRegistryNegatives",QJsonArray::fromVariantList(negatives)},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)},{"actualUnchangedFastCaptureHelperExecuted",true},{"actualUnchangedFastCaptureHelperRegistryAccepted",pass},{"syntheticNativeServerOnly",true},{"actualQSProcessAccepted",false},{"nativePinEffectAccepted",false},{"helperWaitSleepOrRetryAdded",false},{"originalHelperTransactionSeconds",2}};std::cout<<QJsonDocument(report).toJson(QJsonDocument::Compact).constData()<<std::endl;return pass?0:1;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
