import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=1884
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report126.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v126',['PROGRESS PUBLIC93 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI126/Native136 actual pure WebKit renderer/native scoped URI/320x240 Core client image at160x120 and original independent pixel oracle19200red/zero green and blue with mapped unrelated green peer. Original16 admission/drain checks retained;21checks10normalexits/privatecleanup/full119/originaldeadline6/core16/plugin19/AQ155. Native-current snapshot request and callback guards implemented; actual stale-callback fault qualification remains open. Original Elm policy/native issuer/physical/journal/independent confirmation/strict close unchanged. Physical curtain stays closed; frame/concealment/reveal/workload/RSS/pressure/reload/uncertain recovery/full S09 preview13 and release gates open. Next actual frame/physical concealment and stale async snapshot qualification. Legacy2518/278, failed integrations and125/135 preserved; installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-report126.json','implementation/warlock-preview-provider-v126/component-manifest.json','implementation/warlock-client-provider-native-v136/component-manifest.json','docs/warlock-repository/v93/publication/delivery.json']);print(e)
