#include "CommitLedger.hpp"
#include <iostream>
using namespace OwnedRoute;
static size_t checks=0;
static void check(bool yes){++checks;if(!yes)throw std::runtime_error("continuous ledger check "+std::to_string(checks)+" failed");}
static std::vector<Source> sources(){return {{{"aa01",41},std::string(64,'a'),{104,130,380,240},{100,100,388,274},{20,700,28,28}},{{"bb02",42},std::string(64,'b'),{154,180,280,180},{150,150,288,214},{20,700,28,28}},{{"cc03",43},std::string(64,'c'),{204,230,180,100},{200,200,188,134},{20,700,28,28}}};}
static std::vector<Identity> ids(){std::vector<Identity> v;for(const auto& s:sources())v.push_back(s.identity);return v;}
static CommitLedger setup(){CommitLedger l;l.configure({{"left",1},{"right",2}});l.seedContinuousFamily(sources(),"0123456789ab-1",std::string(64,'d'),"minimize",.220);return l;}
static Frame issue(CommitLedger& l,const std::string& name,uint64_t time){auto sample=l.continuousSample(name,name=="left"?1:2,time);check(bool(sample));auto frame=l.prepareContinuousFamily(*sample,time+1,1600,1000);check(bool(frame));check(frame->members==sample->members);check(frame->kinematics==std::optional<Kinematics>(sample->timing));return *frame;}
static void present(CommitLedger& l,const Frame& f,uint64_t time,uint64_t msc=1,bool early=false){if(early){check(l.present(f.sequence,time,msc)==Result::Deferred);check(l.swapReturned(f.sequence,true)==Result::RecordedCurrent);}else{check(l.swapReturned(f.sequence,true)==Result::Deferred);check(l.present(f.sequence,time,msc)==Result::RecordedCurrent);}check(l.presentedOrigins().at(f.output).frame.members==f.members);}
static void ready(CommitLedger& l){auto left=issue(l,"left",1000),right=issue(l,"right",1000);present(l,left,1010);present(l,right,1010);check(!l.nativeReady());check(l.promoteFamily(ids(),l.token()));check(l.nativeReady());check(l.startContinuousFamily(ids(),l.token(),2000));}
template<class F>static void refuses(F f){bool refused=false;try{f();}catch(const std::invalid_argument&){refused=true;}check(refused);}
int main(){
 {auto l=setup();check(l.continuous());auto a=l.continuousSample("left",1,1000);check(a&&a->timing.elapsedSeconds==0);for(const auto& m:a->members)check(m.velocity==ContinuousMotion::Vector{});auto bad=*a;bad.members[0].velocity[0]=1;check(!l.prepareContinuousFamily(bad,1001));bad=*a;bad.members[0].rectangle.x+=1;check(!l.prepareContinuousFamily(bad,1001));bad=*a;std::swap(bad.members[0],bad.members[1]);check(!l.prepareContinuousFamily(bad,1001));bad=*a;bad.generation=2;check(!l.prepareContinuousFamily(bad,1001));bad=*a;bad.timing.epoch++;check(!l.prepareContinuousFamily(bad,1001));bad=*a;bad.token="0123456789ab-2";check(!l.prepareContinuousFamily(bad,1001));check(!l.nativeReady());auto f=l.prepareContinuousFamily(*a,1001);check(bool(f));check(!l.prepareContinuousFamily(*a,1002));present(l,*f,1010);auto copy=*f;copy.members[0].velocity[0]=999;check(l.presentedOrigins().at("left").frame.members!=copy.members);}
 {auto l=setup();auto a=issue(l,"left",1000);check(l.present(a.sequence,1010,1)==Result::Deferred);check(l.records().empty());check(l.swapReturned(a.sequence,false)==Result::Rejected);check(!l.isActive()&&!l.nativeReady()&&l.records().empty());check(l.present(a.sequence,1020,2)==Result::Rejected);}
 {auto l=setup();auto a=issue(l,"left",1000);present(l,a,1010,1,true);check(l.records()[0].frame.kinematics==a.kinematics);check(l.present(a.sequence,1020,2)==Result::Rejected);auto b=issue(l,"left",1030);check(l.swapReturned(b.sequence,true)==Result::Deferred);check(l.present(b.sequence,1000,2)==Result::Rejected);l.discarded(b.sequence);check(!l.isActive()&&!l.nativeReady());}
 {auto l=setup();auto a=issue(l,"left",1000);l.outputRemoved("left",1);check(!l.isActive());check(l.present(a.sequence,1010,1)==Result::Rejected);check(!l.continuousSample("left",1,1020));}
 {auto l=setup();auto a=issue(l,"left",1000);check(l.timedOut(2000001002ULL));check(!l.nativeReady());check(l.present(a.sequence,2000002000ULL,1)==Result::Rejected);}
 {auto l=setup();ready(l);check(l.continuousStartNs()==2000);check(l.startContinuousFamily(ids(),l.token(),9000));check(l.continuousStartNs()==2000);auto a=issue(l,"left",30000000),b=issue(l,"right",50000000);present(l,a,30000010,2);present(l,b,50000010,2);check(a.members!=b.members);check(a.kinematics->durationSeconds==b.kinematics->durationSeconds);auto left=a.members,right=b.members;check(l.retargetContinuousFamily(ids(),"0123456789ab-2","restore",.220,60000000));check(!l.nativeReady());auto ao=l.continuousSample("left",1,60000000),bo=l.continuousSample("right",2,60000000);check(ao&&bo);check(ao->members==left&&bo->members==right);check(ao->timing.durationSeconds==bo->timing.durationSeconds);auto af=l.prepareContinuousFamily(*ao,60000001),bf=l.prepareContinuousFamily(*bo,60000001);check(af&&bf);present(l,*af,60000010,3);present(l,*bf,60000010,3,true);check(l.promoteFamily(ids(),"0123456789ab-2"));check(l.startContinuousFamily(ids(),"0123456789ab-2",70000000));check(l.continuousStartNs()==60000000);check(!l.promoteFamily(ids(),"0123456789ab-1"));check(!l.startContinuousFamily(ids(),"0123456789ab-1",80000000));}
 {auto l=setup();ready(l);const auto token=l.token();const auto epoch=l.continuousEpoch();check(!l.retargetContinuousFamily(ids(),"0123456789ab-2","restore",0,3000));check(l.token()==token&&l.continuousEpoch()==epoch);check(!l.isActive()&&!l.nativeReady());}
 {auto l=setup();ready(l);auto incomplete=ids();incomplete.pop_back();check(!l.retargetContinuousFamily(incomplete,"0123456789ab-2","restore",.22,3000));check(l.token()=="0123456789ab-1"&&!l.nativeReady());}
 {auto l=setup();auto a=issue(l,"left",1000);present(l,a,1010);check(!l.retargetContinuousFamily(ids(),"0123456789ab-2","restore",.22,3000));check(!l.nativeReady()&&l.token()=="0123456789ab-1");}
 {auto l=setup();ready(l);check(!l.retargetContinuousFamily(ids(),"0123456789ab-2","restore",.22,0));check(!l.nativeReady());}
 {auto l=setup();ready(l);refuses([&]{l.continuousSample("left",1,1999);});check(!l.continuousSample("left",99,3000));check(!l.prepareFamily("left",1,.5,3000));check(!l.retargetFamily(ids(),"0123456789ab-2","restore"));check(!l.retarget(ids()[0],"0123456789ab-2"));l.cancel();check(!l.nativeReady()&&!l.continuous());}
 {using namespace ContinuousMotion;Origin small{{0,0,1,20},{0,0,-1e6,0},{0,0,1,20}},large{{0,0,20,20},{0,0,0,0},{400000,0,20,20}};FamilyTrajectory a({small},.22),b({large},.22);check(a.seconds()>0&&b.seconds()>0);refuses([&]{CommonTrajectoryPlan({{"left",{small}},{"right",{large}}},.22);});refuses([&]{CommonTrajectoryPlan({{"left",{large}},{"right",{large,large}}},.22);});refuses([&]{CommonTrajectoryPlan({},.22);});refuses([&]{CommonTrajectoryPlan({{"left",{large}}},.5e-9);});refuses([&]{elapsedSeconds(10,20);});refuses([&]{elapsedSeconds(UINT64_MAX,1);});}
 {auto captured=sources();for(size_t i=3;i<64;++i){auto m=captured[0];m.identity={"aa"+std::to_string(i),int64_t(100+i)};captured.push_back(m);}CommitLedger l;l.configure({{"a",1},{"b",2},{"c",3},{"d",4}});l.seedContinuousFamily(captured,"0123456789ab-1",std::string(64,'d'),"minimize",.22);double duration=0;for(const auto& [name,gen]:std::map<std::string,uint64_t>{{"a",1},{"b",2},{"c",3},{"d",4}}){auto sample=l.continuousSample(name,gen,1000);check(sample&&sample->members.size()==64);if(duration)check(sample->timing.durationSeconds==duration);duration=sample->timing.durationSeconds;}check(duration==.22);}
 {auto l=setup();ready(l);uint64_t base=2000;for(int turn=0;turn<40;++turn){base+=10000000;auto a=issue(l,"left",base),b=issue(l,"right",base+1000);present(l,a,base+2000,turn+2);present(l,b,base+2000,turn+2);const auto next="0123456789ab-"+std::to_string(turn+2);check(l.retargetContinuousFamily(ids(),next,turn%2?"minimize":"restore",.22,base+3000));auto x=l.continuousSample("left",1,base+3000),y=l.continuousSample("right",2,base+3000);check(x&&y&&x->members==a.members&&y->members==b.members);check(x->timing.durationSeconds==y->timing.durationSeconds);for(const auto& member:x->members)check(member.rectangle.width>0&&member.rectangle.height>0);base+=3000;}}
 std::cout<<"{\"result\":\"pass\",\"continuousLedgerChecks\":"<<checks<<",\"nativeAccepted\":false}\n";
}
