#!/usr/bin/env python3
"""Prepare a fresh package only; never signal, install or reload live Files."""
from pathlib import Path
import hashlib,json,shutil
B=Path(__file__).resolve().parent;P=B/'deployment-prepared';LIVE=Path.home()/'.local/share/omarchy-files'
assert not P.exists(),'Do not replace a frozen package'
P.mkdir();shutil.copytree(B/'app',P/'app');shutil.copytree(B/'WindowAccessibilityV5',P/'native')
old='file://'+str(B/'WindowAccessibilityV5');destination=Path.home()/'.local/share/omarchy-files-native/WindowAccessibilityV5_guard_20261001';new='file://'+str(destination)
for f in (P/'app').rglob('*.qml'):f.write_text(f.read_text().replace(old,new))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
source=json.loads((B/'source-hashes.json').read_text())
qml=[dict(item,deploymentSha256=sha(P/'app'/item['path'])) for item in source['changedQml']]
plan={'execution':'Prepared only. Root must review and grant copied native proof before any installation/reload.', 'original':{'pid':667402,'instance':'yyaefmu6mt','processStart':'1275224','requiredHidden':True},'nativeDestination':str(destination),'nativeFiles':[{'path':f.name,'sha256':sha(f)} for f in sorted((P/'native').iterdir())], 'sourceManifestSha256':sha(B/'source-hashes.json'),'changedQml':qml,'unchangedOperationsAndSpec':source['unchangedOperationsAndSpec'],'legacyMigrationRequired':False,'stateContract':{'PersistentPropertiesReloadableId':'files-ui-persistence-v1','required':'Canonical equality of every pre-existing public/full UI state field after watcher and post-model restoration, same PID/start/instance, hidden before map. The optional new focusIdentity field must be empty for the existing hidden responsive state. No FILES_OPEN initialization or files open/toggle IPC.','additionalField':{'focusIdentity':''}},'steps':['First prove fresh durable native URL resolves and copied same-PID hidden reload transfers PersistentProperties, with no popup/window mapping. Fresh destination must not exist before installation; never overwrite a loaded SO.','Capture a new private 0700/0600 backup of all changed source bytes, scripts/spec hashes, public/full UI state, four catalog bytes, dashboard, typed clipboard/primary hashes, process identity, canonical clients, focus/cursor/layers, a11y flags and socket. Retain backup after success.','Revalidate exact live baseline hashes, PID start/instance, hidden idle state immediately before mutation. Open pidfd for exact original.','Prepare all 15 temporary QML files. Root briefly SIGSTOPs exact pidfd, atomically replaces files, restores all originals before SIGCONT if any write fails. Resume once; no termination or state migration file.','Wait ready/watchers/PersistentProperties/post-model restoration, prove original hidden-before-map and canonical UI equality with only explicitly allowed empty focusIdentity addition.','Compare complete canonical client projection (address/stableId/PID/class/title/workspace/monitor/geometry/pin/fullscreen/floating), same original focus/cursor/layers, all four catalog bytes, dashboard, clipboard/primary MIME/content hashes, flags/socket and operation hashes. Do not erase failed gates; retain rollback package.'],'pending':['Actual broad silent Orca reader/native input coverage','Copied durable URL reload proof','Root review and concrete live prestate snapshot']}
(P/'plan.json').write_text(json.dumps(plan,indent=2)+'\n');print(json.dumps({'planSha256':sha(P/'plan.json'),'changedQml':len(qml),'destination':str(destination)}))
