"""Prepare qualified async GUI89/native126 and retained failed90 publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');d=json.loads((r/'docs/warlock-preview/v89/report.json').read_text())
assert d['passed'] and d['nativeChecks']==2465 and d['normalOwnedExits']==277 and d['prior125FixedOrderedControls']==2457
out=r/'docs/warlock-repository/v63/publication';assert not out.exists();out.mkdir(parents=True)
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(r/'docs/warlock-repository/v62/publication/publish.py').read_text()
s=s.replace("BASE='b78826aa09d271ef0d1c879cb3e0a38bc77c72c2'","BASE='8e68d74b293ebe134ba7f504064f81678ee0ff58'").replace('fec65e7df2829e90f60bd3d7e0ecc729079acdb6..','8b9c5938ed8c35e1d4ec27c8286b8ae10373cd82..')
allowed=('docs/warlock-preview/v89/','docs/warlock-repository/v62/publication/','docs/warlock-repository/v63/publication/','implementation/warlock-preview-provider-v89/','implementation/warlock-preview-provider-v90/','implementation/warlock-client-provider-native-v126/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Qualify independently delivered Elm window retirement\n\nCurrent GUI89/native126 on core16/plugin18 passes2465 checks,277 normal owned exits and ordered cleanup; all2457 prior125 fixed controls and original allocator/deadline oracles remain. Full95/all original12/C96/decoder13-25-439states-three mutations/aggregate9068 through280 synthetic subjects/Elm33/control-prefix7-15-180states-three mutations/adapter10 pass. Asynchronous retirement9 controls and10 explicit selected Quint scenarios match actual compiled Elm across30 traces/641 observed state-and-command comparisons. Three named model mutations and three separately compiled Elm mutations are detected. Preserve the earlier failed witness selection and held ancestor88 sibling-order counterexample. Retain failedGUI90 native completion-journal implementation: full95 compiled, but actual C/socket closure discarded an unacknowledged final completion. Add EARS/OpenSpec retained-delivery contracts; native readiness and completion receipts never grant physical cleanup. Mutable correctiveGUI91 is excluded. Actual Elm/host completion routing, captured physical retirement, continuing >256 real native/Elm windows, ordinary capture and every original GUI release gate remain open.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v89/report.json').read_text());assert qualification['passed'] and qualification['nativeChecks']==2465 and qualification['normalOwnedExits']==277 and qualification['prior125FixedOrderedControls']==2457 and qualification['asynchronousRetirementScenarios']==10 and qualification['asynchronousRetirementTraces']==30 and qualification['asynchronousRetirementStates']==641 and qualification['unsafeAsynchronousElmMutants']==3 and not qualification['actorTurnoverAccepted'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:]
put('publish.py',s)
s=(r/'docs/warlock-repository/v62/publication/record_delivery.py').read_text().replace('warlock-repository/v62','warlock-repository/v63').replace('warlock-preview/v88','warlock-preview/v89').replace('warlock-preview-provider-v88','warlock-preview-provider-v89').replace('warlock-client-provider-native-v125','warlock-client-provider-native-v126')
start=s.index("['PROGRESS PUBLIC exactowner publication62 ");end=s.index(",'progress'",start)
s=s[:start]+"['PROGRESS PUBLIC exactowner publication63 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. CurrentGUI89/native126 exactcore16/plugin18 PASS2465/277normalclean/all2457prior125fixed; full95/original12 and all original retirement regressions. Async10selected/30actualElmtraces/641state-command comparisons and3model+3compiledElm mutants. Heldfailed90 unconfirmed-completion owner-close counterexample retained. MutableGUI91 close barrier and C/native unissued/turnover/receipt journal work excluded. Next actual immutable Elm processing-prefix/ACK wrappers, native/host routing and retained completion delivery, >256real native/Elm turnover and all original release gates. Main desktop/drafts/five foreign tracked changes preserved.']"+s[end:]
put('record_delivery.py',s)
s=(r/'docs/warlock-preview/v88/commit_owned.py').read_text().replace('72ee067a6572addd8b9809e7f5809d705cad2f37','b3a53964e6318a4024b9dfc3e96e2b301a37fcde')
s=s.replace("[('warlock-preview-provider-v86',True),('warlock-preview-provider-v87',False),('warlock-preview-provider-v88',True),('warlock-client-provider-native-v125',True)]","[('warlock-preview-provider-v89',True),('warlock-preview-provider-v90',False),('warlock-client-provider-native-v126',True)]")
s=s.replace("[r/'docs/warlock-preview/v87',r/'docs/warlock-preview/v88',r/'docs/warlock-repository/v62/publication']","[r/'docs/warlock-preview/v89',r/'docs/warlock-repository/v63/publication']")
s=s.replace('Qualify native retirement ownership and ordered Elm controls','Qualify asynchronous Elm retirement and retain completion delivery failure')
ast.parse(s);(r/'docs/warlock-preview/v89/commit_owned.py').write_text(s)
s=(r/'docs/warlock-repository/v62/publication/commit_receipt.py').read_text().replace('b78826aa09d271ef0d1c879cb3e0a38bc77c72c2','8e68d74b293ebe134ba7f504064f81678ee0ff58').replace('Record public native retirement and Elm control qualification','Record public asynchronous Elm retirement qualification')
put('commit_receipt.py',s)
print(out)
