import hashlib,json
from pathlib import Path
root=Path(__file__).resolve().parents[3];p=root/'docs/elm-roadmap';reqs=json.loads((p/'requirements.json').read_text())['requirements'];sha=hashlib.sha256((p/'requirements.json').read_bytes()).hexdigest()
def ids(text):return {'ELM-'+x for x in text.split()}
specs=[
('S01','P0','Baseline and inherited acceptance','Make every inherited acceptance obligation executable and establish the project controls.','Frozen source/ABI and case ledger, owners and original-deadline fixtures; project backlog and QA operating contract.','Every inherited case has its original identity/oracle/deadline or a blocking missing-evidence entry; no historical CPU pass is relabeled native.',''),
('S02','P0','Product policy and measured budgets','Freeze what correct and usable behavior means before judging candidate implementations.','Versioned scene/switcher policy, workload budgets, readability matrix and participant usability protocol; isolated layering diagnosis.','Numeric applicable budgets and usability criteria are frozen; Heroic/Brave regression fixtures and native diagnosis evidence are retained.','S01'),
('S03','P1','Native host and protocol spikes','Display a minimal Elm surface through isolated host candidates with a validated transport boundary.','GTK/WebKit and comparative Qt host prototypes; surface/input-region adapters; lossless schema, clock/queue/refusal tables; protected lifecycle harness.','A real native shell surface, passthrough regions and versioned decoder/ABI rejection fixtures pass; no main-desktop activation.','S02'),
('S04','P1','Accelerated and accessible host selection','Select a host from measured rendering, input and lifecycle evidence.','Hardware webview render probe, separately qualified WebGPU result, hybrid-device ledger, IME and minimal native accessibility/chord probes; host ADR.','Nonsoftware webview composition and measured budgets pass; actual IME/popup/focus/AT route passes; unavailable WebGPU is honestly conditional.','S03'),
('S05','P2','Typed Elm policy and reliable authority','Implement one receipt-driven path from a pure Elm reducer to validated native effects.','Domain types/replay, bridge sequencing and gap barrier, cancel/deadline/dedup/dependency guards, bounded queues, authenticated session and settings boundary.','Named Quint/fuzz/replay tests and native stale/cancel/Unknown rejection pass; no effect is inferred from send or transport acceptance.','S04'),
('S06','P2','Canonical layering and focus','Make eligibility, painting, hit testing and focus agree under a committed native policy.','Shared scene transaction, modal/transient constraints, MAX/pin behavior, minimize focus succession, cross-workspace activation, lock/protected capture policy.','Heroic inactive-minimized and Brave MAX regressions, genuine blocker/no-focus cases and scoped workspace races pass with pixel/input receipts.','S05'),
('S07','P3','Taskbar vertical slice','Ship an isolated selectable Elm taskbar with truthful actions and feedback.','Left layout/catalog/pin/group projection, primary-action table, overflow, pending/refusal/Unknown feedback and AT announcements.','Zero/single/group/active/minimized action fixtures, delayed/refused outcomes and keyboard overflow pass without duplicate effects.','S06'),
('S08','P3','Switcher and shell interaction lifecycle','Complete native chord handling and usable shell focus scopes.','MRU chord reducer, forward/reverse/cancel/retire fixtures, multi-output projections, focus scopes and subscriptions; proxy/modal handoff contract.','Release-before-open, cancellation, incarnation reuse, native popup changed/same/stale routes and actual taskbar/switcher accessibility pass.','S07'),
('S09','P4','Retained family captures','Keep authorized preview pixels valid after their source stops.','Opaque lease/fence API, source-stop ownership, frame identity/timestamps, composed-family fidelity and explicit preview states.','Native source-stop and family pixel/fence/capability fixtures pass; historical/live/unavailable labels match actual source state.','S08'),
('S10','P4','Minimize and restore transactions','Restore correctly within the original deadline using inert proxies and current native authority.','Minimize/seed/live workflows, reversal/cancellation/retirement, native caption/edge integration, live reduced-motion profiles.','Original baseline38/recovery34 and case-34 deadline oracle pass; atomic proxy-to-live handoff and exact normal retirement receipts hold.','S09'),
('S11','P4','Graphics fault and resource qualification','Survive lock, revocation, output changes and GPU loss without stale pixels or runaway work.','Native preview interoperability, device/allocation failure handling, privacy/unlock, transfer budgets, generation transforms and demand-driven quiescence.','Fault/lock/fence/output cases and whole-tree preview budgets pass; device loss retires invalid storage or exposes unavailable state.','S10'),
('S12','P5','Launcher, menus and system integration','Deliver complete discoverable application and settings journeys.','Generation-safe search, jump lists, settings/themes entry points, notifications, system adapters, Files integration and first-use help.','Current-query launch/refusal and notification identity cases pass; adapters expose unavailable state; Files semantics and shortcut preferences persist.','S11'),
('S13','P5','Task View, snapping and physical outputs','Make workspace and output journeys visibly correct and recoverable.','Overview navigation/transfer, snap chooser, exclusive/menu policy, output-removal recovery and physical display acceptance.','Workspace transfer/refusal, scale/rotation/hotplug and active fullscreen/pin/modal policies pass; no invisible focus trap remains.','S12'),
('S14','P5','Accessibility and representative user flows','Qualify every migrated surface through keyboard, speech, braille and real application flows.','Full semantic control inventory, focus scopes, supported text/reflow themes, IME reruns on actual surfaces and formative usability results.','Every surface passes keyboard/AT and configured usability thresholds; original pin/input/popup/drag and representative app cases have exact receipts.','S13'),
('S15','P6','Reproducible release and recovery','Build a deployable candidate with independently usable recovery.','Dependency/ABI locks, SBOM/notices, offline build and target matrix, atomic installation/settings migration, restart/suspend/interrupted-upgrade and rollback tooling.','One release tuple is reproducible; restart/resync and offline rollback restore compatible settings; only qualified targets are advertised.','S14'),
('S16','P6','Integrated release qualification','Produce a concrete release decision from one coherent tuple.','Combined regression and UX ledger, whole-tree performance/power/soak, high-refresh evidence, incident runbook and activation review packet.','All applicable mandatory gates pass with the same source/runtime/ABI tuple; failed/unobserved outcomes block release; authorized activation has rollback receipts.','S15'),
('C00','P7','Optional compositor feasibility','Decide whether replacing Hyprland is justified by an isolated native prototype.','Substrate/license/maintenance ADR, Wayland/Xwayland protocol matrix and explicit scope/resource decision.','Representative native compatibility evidence and a documented go/no-go decision; a no-go does not block the mandatory shell.','S06'),
('C01','P8','Optional compositor roles and lifecycle','Prove a minimal native substrate with real application lifecycle.','xdg roles/configure/ack, Xwayland window/focus integration and approved backend skeleton.','Representative native role/lifecycle and legacy X11 fixtures pass in nested sessions.','C00'),
('C02','P8','Optional compositor outputs and seat','Prove native hardware/input lifecycle independently of Elm timing.','Outputs/modes/leases, input device lifecycle and suspend/resume.','Isolated hotplug and input/output transition fixtures pass without losing ownership.','C01'),
('C03','P8','Optional compositor IME and portals','Prove text input, capture consent and revocation.','Native IME/text-input and PipeWire/screencopy portal adapters.','Current-focus IME and session-bound portal consent/revocation fixtures pass.','C02'),
('C04','P8','Optional compositor isolation and policy','Harden native isolation and bounded policy fallback.','Threat-model fixtures, lock/client/buffer isolation and asynchronous Elm policy snapshots.','Malformed clients and stalled frontend cannot bypass lock isolation or native input deadlines.','C03'),
('C05','P8','Optional compositor compatibility qualification','Qualify all parity and compositor-specific behaviors on the new backend.','New backend release matrix and fresh compatibility receipts.','No Hyprland-only receipt substitutes for a new-compositor gate; all applicable mandatory scenarios rerun.','C04'),
('C06','P8','Optional compositor hardware and cutover','Prepare a reversible hardware rollout after native acceptance.','Sacrificial hardware qualification and draft-preserving activation/recovery packet.','Hardware acceptance and independently rehearsed rollback pass before any authorized session cutover.','C05')]
# Each phase is decomposed semantically; every row has exactly one accountable delivery slot.
early={
'P0':ids('ARC-001 DEL-001 DEL-002 QA-001 QA-002 QA-016 REN-001 REV-005 REV-006 REV-035 UX-001'),
'P1':ids('ARC-002 ARC-003 ARC-004 ARC-005 ARC-021 ARC-022 ARC-024 ARC-025 DEL-006 DEL-013 DEL-014 QA-009 QA-010 QA-011 QA-012 QA-013 REN-002 REV-007 REV-012 REV-014 REV-015 REV-027 REV-029 REV-030 REV-034 TEA-005'),
'P2':ids('ARC-006 ARC-007 ARC-008 ARC-009 ARC-010 ARC-011 ARC-012 ARC-013 ARC-014 ARC-015 ARC-016 ARC-026 DEL-010 DEL-011 DEL-012 DEL-015 DEL-017 QA-004 QA-005 QA-006 QA-007 QA-008 REV-001 REV-008 REV-009 REV-010 REV-011 TEA-001 TEA-002 TEA-003'),
'P3':ids('DEL-009 UI-004 UI-007 UI-008 UI-010 UI-015 UX-002 UX-003 UX-004 UX-005 UX-008 UX-009'),
'P4capture':ids('ARC-019 REN-003 REN-004 REN-005 REN-014 REV-023 UX-006 UX-007 UI-016'),
'P4motion':ids('ARC-020 GNO-008 KDE-006 QA-003 REN-006 REN-007 REN-008 REN-009 REN-010 REN-011 REN-013 UI-014 UI-018 UX-021 UX-022'),
'P5shell':ids('UI-005 UI-020 UX-010 UX-029 UX-030 UX-031 UX-032 UX-033 UX-034'),
'P5outputs':ids('KDE-008 QA-020 REN-017 REN-020 UI-006 UI-019 UX-017 UX-018 UX-019 UX-020'),
'P6':ids('ARC-027 DEL-003 DEL-004 DEL-005 DEL-007 DEL-008 DEL-016 DEL-018 DEL-019 DEL-020 DEL-021 DEL-022 REV-028')}
phase_pairs={'P0':('S01','S02'),'P1':('S03','S04'),'P2':('S05','S06'),'P3':('S07','S08'),'P6':('S15','S16')}
p8={'ELM-ARC-029':'C01','ELM-REN-024':'C01','ELM-REN-025':'C02','ELM-REN-026':'C03','ELM-REN-027':'C03','ELM-REN-028':'C04','ELM-REN-029':'C04','ELM-QA-028':'C05','ELM-REN-030':'C06'}
backlog=[]
for x in reqs:
 phase=x['phase'];i=x['id']
 if phase in phase_pairs:sprint=phase_pairs[phase][0 if i in early[phase] else 1]
 elif phase=='P4':sprint='S09' if i in early['P4capture'] else 'S10' if i in early['P4motion'] else 'S11'
 elif phase=='P5':sprint='S12' if i in early['P5shell'] else 'S13' if i in early['P5outputs'] else 'S14'
 elif phase=='P7':sprint='C00'
 else:sprint=p8[i]
 backlog.append(dict(id=i,taskId=x['taskId'],sprint=sprint,phase=phase,capability=x['capability'],title=x['task'],ownerRole=x['accountableOwnerRole'],verifierRole=x['verifierRole'],priority=x['priority'],execution='implement the next smallest demonstrable slice',status='backlog',verification=x['verification'],acceptanceScenarioIds=[i+' '+s['name'] for s in x['scenarios']]))
sprints=[dict(id=i,phase=ph,title=t,goal=g,deliverables=d,exitGate=e,dependsOn=dep.split(),completion='exit-gate-driven',track='mandatory-shell' if i.startswith('S') else 'conditional-compositor',status='queued',items=[x['id'] for x in backlog if x['sprint']==i]) for i,ph,t,g,d,e,dep in specs]
plan=dict(schema=2,requirementsSHA256=sha,baselineCommit='d99d677',executionMode='AI-assisted outcome-driven build cycles',advanceWhen='Required checks and exit gate pass; otherwise fix or record the blocker.',sprints=sprints,backlog=backlog)
(p/'delivery/sprint-backlog.json').write_text(json.dumps(plan,indent=2)+'\n')
lines=['# Build cycles', '', 'Baseline: `{sha}` (242 requirements, 417 scenarios). The [backlog](delivery/sprint-backlog.json) preserves each requirement, owner and acceptance scenario. S01–S16 are work packages; each is implemented through small runnable slices.', '', '## Build loop', '', 'Pick the next unblocked slice, implement it, compile it, run the relevant Quint/replay checks, exercise native behavior where required, and show the result. Fix failures immediately. Move on when the evidence passes. There are no calendar durations, staffing forecasts, story points or meeting cadence attached to these cycles.', '', 'Use AI to write code, explore alternatives, produce fixtures and review changes. Parallelize independent work only after interfaces are clear; native GUI campaigns remain serialized. Keep one coherent source/ABI tuple and preserve original acceptance deadlines.', '', '## Work packages', '', '| Cycle | Outcome | Prerequisite | Requirements |', '| --- | --- | --- | --- |']
lines=[line.replace('{sha}',sha) for line in lines]
for s in sprints:lines.append(f"| {s['id']} | {s['title']} | {', '.join(s['dependsOn']) or 'Baseline reviewed'} | {len(s['items'])} |")
lines+=['', '## Execution rules', '', 'Start coding as soon as a slice has a clear oracle, its dependencies and a runnable fixture. Split broad requirements into small experiments and implementations as needed. Each review shows working behavior and exact check results. Update the backlog with accepted, partial, failed or blocked outcomes.', '', 'Done means reviewed code, relevant compiler/replay/fuzz/Quint checks, mapped native acceptance where required, source/ABI receipts and safe recovery. Model checks do not substitute for actual rendering, input or GPU evidence. Conditional cases require an explicit applicability decision.', '', 'Develop typed Elm reducers and Quint models with each feature. Replay counterexamples as messages; retain failures. Accessibility, privacy and resource bounds belong in each slice. S14 adds complete-system checks.', '', 'Host selection includes a minimal accessibility probe; complete taskbar/switcher semantics close in S08. IME starts in the minimal host and reruns in actual fields. S08 proves proxy handoff with a deterministic fixture; S09–S11 prove actual capture and restore.', '', '## Dependencies', '', 'Listed prerequisites constrain acceptance, not every line of coding. Pure Elm prototypes and native layering diagnosis can progress independently while host experiments run. Keep shared interfaces stable and serialize native campaigns. Hardware checks remain measured gates.', '', 'Record decisions and blockers as they arise. A failed experiment guides the next implementation; it does not complete an acceptance requirement. New requirements get EARS/OpenSpec scenarios and backlog mappings.', '', 'C00 explores compositor feasibility independently of the mandatory shell. C01–C06 are optional work packages, subdivided as experiments reveal the actual implementation. Passing a prototype does not complete a compositor. A no-go leaves the shell on Hyprland.', '', '## Cycle backlog and exit gates', '']
byid={x['id']:x for x in backlog}
for s in sprints:
 lines.extend([f"### {s['id']} — {s['title']}",'',s['goal'],'','Deliverables: '+s['deliverables'],'','Exit gate: '+s['exitGate'],'','Demo: show the stated behavior or experiment outcome with matching acceptance receipts; disclose failures and unexecuted scenarios.',''])
 for i in s['items']:
  x=byid[i];lines.append(f"- [ ] **{i}** — {x['title']} Owner: {x['ownerRole']}; verifier: {x['verifierRole']}. Acceptance: {len(x['acceptanceScenarioIds'])} unchanged scenario(s) in the machine backlog.")
 lines.append('')
lines+=['## Start here', '', 'S01: verify source/ABI lineage and recover the original native case definitions. Build runnable fixtures as cases are recovered; keep missing evidence blocked. In parallel, prepare the minimal Elm host and canonical-scene experiments against existing contracts. Freeze measured budgets before host qualification.', '']
(p/'SPRINTS.md').write_text('\n'.join(lines))
print(json.dumps(dict(requirements=len(backlog),scenarios=sum(len(x['acceptanceScenarioIds']) for x in backlog),mandatorySlots=16,conditionalSlots=7)))
