"""Coordinator requirements for GPU steering and observed layering regression."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
rows=[]
def add(num,capability,pattern,ears,phase,verification,task,given,when,then,priority='must'):
 rows.append({'id':f'ELM-GPU-{num:03d}','capability':capability,'pattern':pattern,'ears':ears,'phase':phase,'priority':priority,'verification':verification,'legacyEvidence':'docs/elm-roadmap/GPU.md; docs/elm-roadmap/gpu-inventory.json','task':task,'scenarios':[{'name':f'gpu-{num:03d}','given':given,'when':when,'then':then}]})
add(1,'elm-gpu','ubiquitous','The Elm desktop SHALL require measured hardware-accelerated rendering in the selected native host before host selection and accelerated release admission.','P1','Pinned engine/driver diagnostics plus a deterministic displayed workload on a nonsoftware device.','Qualify the actual host GPU path.','a candidate pinned host on the target machine','host selection evaluates rendering','software-only execution cannot pass the GPU gate')
add(2,'elm-gpu','ubiquitous','The graphics qualification SHALL distinguish hardware discovery, native GPU rendering, accelerated webview composition and WebGPU adapter/device execution as separate evidence claims.','P0','Evidence ledger with four separate verdicts linked to executed probes.','Create acceleration evidence categories.','Vulkan enumerates physical devices','the inventory is recorded','WebGPU and displayed-render verdicts remain unproven until their probes pass')
add(3,'elm-gpu','event-driven','WHEN WebGPU is evaluated, the native host SHALL expose bundled assets through a qualified secure local origin without disabling renderer sandboxing.','P1','Origin/security-state probe, effective sandbox flags and denied remote navigation.','Qualify WebGPU origin and sandbox.','a local shell asset bundle','the host loads its GPU probe','the probe uses the approved secure origin and the renderer sandbox remains enabled')
add(4,'elm-gpu','event-driven','WHEN a WebGPU adapter or device is unavailable, the host SHALL reject WebGPU qualification and preserve an accepted alternative hardware-rendering route.','P1','Null-adapter, rejected-device and unsupported-feature fault reports.','Implement capability negotiation and API rejection.','an accepted native GPU path and a WebGPU probe','requestAdapter returns null','WebGPU is unqualified while the native GPU path remains usable')
add(5,'elm-gpu','ubiquitous','The WebGPU qualification SHALL verify a deterministic render and compute result using supported adapter limits and features and independently observe the native displayed frame.','P1','WGSL validation/readback results plus output capture and backend classification.','Build isolated render and compute qualification probes.','a nonsoftware adapter and accepted device','the deterministic workload completes','known results match and the rendered native frame is independently observed')
add(6,'elm-gpu','state-driven','WHILE GPU effects are active, the renderer SHALL own GPU objects locally and keep per-frame pixel buffers outside Elm port messages.','P4','IPC payload and resource-allocation traces over motion/reversal workload.','Keep GPU ownership and frame scheduling in the renderer.','an Elm view with a GPU effect','motion is sampled for successive frames','ports carry bounded control metadata and GPU objects remain renderer-owned')
add(7,'elm-gpu','event-driven','WHEN the GPU device is lost, the host SHALL invalidate dependent resources and the rendering generation before rebuilding them without replaying stale application-window effects.','P4','Device-loss injection and generation/effect logs with no stale native mutation.','Implement bounded device-loss recovery.','GPU resources and an old pending window intent','device loss occurs','old resources become unusable and the old intent is not automatically committed')
add(8,'elm-gpu','ubiquitous','The preview qualification SHALL measure actual native-buffer import, synchronization and copy volume instead of inferring zero-copy support from WebGPU availability.','P4','Native fence/import trace and copy bytes/counts on both GPU configurations.','Qualify the preview interoperability path.','a native frame lease and a WebGPU-capable host','a preview is rendered','the report records actual copies and fences without claiming an untested DMA-BUF import')
add(9,'elm-gpu','unwanted','IF every qualified GPU path becomes unavailable, THEN the host SHALL expose essential recovery controls in a disclosed degraded mode and block accelerated release admission.','P6','All-backend-failure fault plus offline recovery/qualification report.','Qualify degraded recovery and release refusal.','all GPU backends unavailable','recovery mode starts','essential controls remain accessible and the report identifies software/degraded execution')
add(10,'elm-gpu','ubiquitous','The GPU qualification SHALL compare integrated and discrete execution, where selectable, against frozen latency, memory, power and transfer budgets on the actual output configuration.','P1','Hardware profile manifest and controlled sample distributions including cross-GPU transfers.','Compare available GPU profiles without assuming power hints choose an adapter.','Intel and NVIDIA devices in the inventory','qualified selectable profiles are compared','each profile identifies the actual device and measured workload verdict')
for num,text,phase,given,when,then in [
 (1,'IF a window is minimized or belongs to an inactive nonsticky workspace, THEN the native authority SHALL exclude its live surface from display and application input regardless of prior raise or fullscreen permissions.','P2','Heroic is minimized while a terminal is active','an old raised/maximized surface is considered for scene publication','Heroic receives neither live drawing nor application input; an independently owned inert preview may remain'),
 (2,'WHEN a scene revision is committed, the native authority SHALL derive painting, hit testing and focus eligibility from the same accepted surface identities and ordered scene revision.','P2','overlapping application windows with an accepted stack revision','painting and pointer routing execute','the top eligible painted application receives the corresponding hit and focus, subject to explicit input regions and modal constraints'),
 (3,'WHEN a minimized window is restored, the native authority SHALL make it eligible in one accepted scene transition while preserving its normal workspace identity and rejecting old transition generations.','P3','a minimized window with retained preview and original workspace identity','restore completes through a current generation','one current live surface becomes eligible and no stale overlay remains')]:
 rows.append({'id':f'ELM-LAY-{num:03d}','capability':'elm-layering','pattern':'unwanted' if num==1 else 'event-driven','ears':text,'phase':phase,'priority':'must','verification':'Protected native pixel/hit/focus fixture reproducing the recorded Heroic-versus-terminal symptom with visibility, stack and generation receipts.','legacyEvidence':'docs/elm-roadmap/heroic-layering-observation.json','task':['Create minimized/inactive-workspace eligibility regression.','Implement canonical scene-revision publication and hit/focus observation.','Qualify atomic restore eligibility and stale overlay retirement.'][num-1],'scenarios':[{'name':f'layer-{num:03d}','given':given,'when':when,'then':then}]})
(root/'coordinator-requirements.json').write_text(json.dumps(rows,indent=2)+'\n')
print(f'{len(rows)} coordinator requirements')
