"""Own next GUI derivative for typed native admission without deadline renewal."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v61';target=repo/'implementation/warlock-preview-provider-v62';manifest=parent/'component-manifest.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();data=json.loads(manifest.read_text());assert data['passed'] and not target.exists()
for rel,row in data['files'].items():assert sha(parent/rel)==row['sha256'],rel
shutil.copytree(parent,target,ignore=shutil.ignore_patterns('build-*','check-*','metadata-check-*','catalog-check-*','delivery-check-*','intent-check-*','component-manifest.json','elm-stuff','mutable-elm-home','__pycache__','ANCESTRY.json','current-build.json'))
(target/'ANCESTRY.json').write_text(json.dumps({'schema':1,'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(manifest),'purpose':'Typed imported native admission outcomes and retained original unissued-intent deadline/identity before dynamic C wrapper integration. Capacity is local no-job/no-receipt feedback; reject renewed deadline or changed original intent, retain request floors and original legacy two-subject behavior. Current owning native105 qualifies previousGUI60 only.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
event=loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(target.relative_to(repo)),['Previous status-only turn NO PROGRESS revalidated. GUI61 new explicitly selected intent6/150samples/16traces363states/2mutants passes, original build92/controls27/models retained and held. Fresh62 owns dynamic C enrollment and atomic receiver/deadline admission, retained real jobs and explicit same bootstrap journal extension. No live prior QA handles; native105 qualifies60 only. Complete actual compile/selected coupling/own native qualification then ordinary Elm eligible capture and all original release gates; no second policy, no original source promotion.'],'progress',['implementation/warlock-preview-provider-v62/ANCESTRY.json','implementation/warlock-preview-provider-v61/component-manifest.json'])
print(json.dumps({'source':str(target),'checkpoint':str(event)}))
