"""Own next GUI derivative for typed native admission without deadline renewal."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v60';target=repo/'implementation/warlock-preview-provider-v61';manifest=parent/'component-manifest.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();data=json.loads(manifest.read_text());assert data['passed'] and not target.exists()
for rel,row in data['files'].items():assert sha(parent/rel)==row['sha256'],rel
shutil.copytree(parent,target,ignore=shutil.ignore_patterns('build-*','check-*','metadata-check-*','catalog-check-*','delivery-check-*','component-manifest.json','elm-stuff','mutable-elm-home','__pycache__','ANCESTRY.json','current-build.json'))
(target/'ANCESTRY.json').write_text(json.dumps({'schema':1,'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(manifest),'purpose':'Typed imported native admission outcomes and retained original unissued-intent deadline/identity before dynamic C wrapper integration. Capacity is local no-job/no-receipt feedback; reject renewed deadline or changed original intent, retain request floors and original legacy two-subject behavior. Current owning native105 qualifies previousGUI60 only.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
event=loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(target.relative_to(repo)),['PROGRESS GUI60/native105 bounded2405/all1783/265normalclean committed4e07eff/publishing53. Fresh61 own typed native StartAttempt with original native intent/deadline retained across Capacity; no fakejob/refusal/no reneweddeadline; keep legacy start compatible and original source guard false. Compile/replay actual carrier then integrate dynamic C enrollment/own receiver epoch/same retained journal and Elm single policy. Fullrelease/ordinaryeligible/hardware remainopen.'],'progress',['implementation/warlock-preview-provider-v61/ANCESTRY.json','docs/warlock-preview/v71/report.json'])
print(json.dumps({'source':str(target),'checkpoint':str(event)}))
