import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=5570
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report121.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v121',['PROGRESS PUBLIC91 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI121 normal native output reservation8192/batches3195/bytes26173440 under held original producer contract, serializer20/max1544bytes, positive synthetic FD2261/late quarantine2269/stricter compiled pressure2270; no native grant reset, normal accepted exits. Explicit Quint first-ticket8/200/eight actual C/JSC traces/48states/two compiled guards/full116 retains116. Two failed attempts retained. Actual output exhaustion/full-workload progress/RSS remain unqualified; actual legacy Native131GUI119/core16/plugin19/AQ1552518/278 unchanged. Next actual controlled host/pure renderer GTK admission/native grant/poll pausing/WebKit identity/async DOM/frame/physical concealment/URI. Uncertain live/process recovery, delayed never-issued proposals and all full release gates remain open. No installed/draft/foreign changes.'],'progress',['docs/warlock-preview/v93/component-report121.json','implementation/warlock-preview-provider-v121/component-manifest.json','docs/warlock-repository/v91/publication/delivery.json']);print(e)
