"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const {Elm}=require(path.resolve(process.argv[2])),fixture=JSON.parse(fs.readFileSync(process.argv[3],"utf8"));
assert.equal(crypto.createHash("sha256").update(fs.readFileSync(fixture.sourceReport)).digest("hex"),fixture.sourceReportSHA256);
const source=fixture.clientScope,frame=fixture.terminalReceipts[0].event.event.frame,job=frame.job,identity="family:"+job.context.incarnation;
let checks=0;const check=(a,b,msg)=>{assert.deepEqual(a,b,msg);checks++;};
const commands=r=>r.commands.flatMap(row=>row.commands),model=r=>r.models[0].model,metadata=r=>r.metadata[0];
const wrapped=event=>({kind:"event",identity,event});
const seed={kind:"source-seed",publication:"1",lease:"1",identity,source,title:"Initial title",application:"own.app"};
const presentation={surfaceProtocol:2,publication:"1",lease:"1",mode:"picker",status:"",bar:[],popup:[{id:identity,domId:"client",label:"Client",ariaLabel:"Client",detail:"",enabled:true}]};
const message=(revision="1")=>({kind:"metadata",identity,binding:structuredClone(job.binding),subject:job.context.incarnation,revision,title:"Actual λ 🌙 title",application:"own.app",icon:"1".repeat(64),iconKind:"application"});
function worker(){const app=Elm.PreviewMetadataReplay.init();let pending=null;app.ports.outgoing.subscribe(value=>{assert(pending);const done=pending;pending=null;done(value);});return (kind,value)=>new Promise((resolve,reject)=>{assert.equal(pending,null);const timer=setTimeout(()=>{pending=null;reject(Error("Original three-second Elm metadata replay deadline"));},3000);pending=v=>{clearTimeout(timer);resolve(v);};app.ports.incoming.send({kind,value});});}
async function prepared(stage="capturing"){const send=worker();await send("presentation",presentation);await send("native",seed);const trigger=structuredClone(job);delete trigger.request;let result=await send("native",wrapped({kind:"request",trigger}));check(commands(result),[{kind:"acquire",job}],"Original exact Acquire retained");if(stage!=="capturing")result=await send("native",wrapped({kind:"offer",frame:{...frame,signaled:false}}));if(stage==="accepted")result=await send("native",wrapped({kind:"fence",frame}));return {send,result};}
async function runControls(){
 let {send,result}=await prepared();const original=model(result);result=await send("native",message("9007199254740993"));check(metadata(result),{identity,title:"Actual λ 🌙 title",application:"own.app",revision:"9007199254740993",iconKind:"application",hasIcon:true,visible:true},"Lossless positive current metadata and actual label");check(model(result),original,"Metadata does not mutate lifecycle");check(commands(result),[],"Metadata emits no policy command");const current=structuredClone(result);
 const mutations=[m=>m.extra=true,m=>m.binding.extra=true,m=>m.binding.session="999",m=>m.subject="999",m=>m.identity="family:999",m=>m.revision="9007199254740993",m=>m.revision="9007199254740992",m=>m.revision=9007199254740994,m=>m.revision="0",m=>m.revision="01",m=>m.revision="18446744073709551616",m=>m.icon="0".repeat(64),m=>m.icon="a".repeat(63),m=>m.icon="elm-shell://icon/"+m.icon,m=>m.icon=null,m=>m.iconKind="unavailable",m=>m.iconKind="foreign",m=>m.title="x".repeat(1025),m=>m.title="λ".repeat(513),m=>m.title="secret\u007f",m=>m.title="secret\u0085",m=>m.application="x\nsecret",m=>delete m.binding.frontend];
 for(const mutate of mutations){const m=message("9007199254740994");mutate(m);result=await send("native",m);check(result,current,"Malformed/foreign/stale metadata cannot alter policy, labels or commands");}
 result=await send("native",{...message("9007199254740994"),icon:null,iconKind:"unavailable",title:"Fallback only"});check(metadata(result).hasIcon,false,"Explicit unavailable icon is truthful");check(metadata(result).revision,"9007199254740994","UInt64 ordering preserved");
 result=await send("native",{...message("18446744073709551615"),iconKind:"generic"});check(metadata(result).iconKind,"generic","Generic icon remains explicitly distinct");check(commands(result),[],"No capture for generic icon");
 result=await send("native",seed);check(metadata(result).title,"Actual λ 🌙 title","Unversioned source seed cannot downgrade newer metadata");
 for(const stage of ["capturing","candidate","accepted"]){({send,result}=await prepared(stage));await send("native",message());const before=model(result);let denied={kind:"source-denied",job,reason:"locked"};for(const mutate of [e=>e.job={...job,request:"999"},e=>e.reason="transport-error",e=>e.extra=true]){const value=structuredClone(denied);mutate(value);result=await send("native",wrapped(value));check(metadata(result).visible,true,"Foreign/malformed denial cannot conceal metadata");}
 result=await send("native",wrapped(denied));check(metadata(result).visible,false,"Exact locked denial conceals without waiting for scope");check(model(result).scope,before.scope,"No fabricated clock/scope");check(commands(result),[stage==="capturing"?{kind:"cancel",job}:{kind:"release",frame:stage==="candidate"?{...frame,signaled:false}:frame}],"Original exact cleanup retained");
 result=await send("native",message("2"));check(metadata(result).visible,false,"Metadata cannot clear locked concealment");check(commands(result),[],"Metadata never replays cleanup");result=await send("native",wrapped({...denied,reason:"source-unavailable"}));check(metadata(result).visible,false,"Different denial cannot clear concealment");result=await send("native",wrapped({kind:"observe",scope:source.scope}));check(metadata(result).visible,false,"Stale unlock cannot clear concealment");
 const fresh={...source.scope,observation:String(BigInt(source.scope.observation)+1n),now:String(BigInt(source.scope.now)+1n)};result=await send("native",wrapped({kind:"observe",scope:fresh}));check(metadata(result).visible,true,"Only coherent fresh native unlock restores metadata visibility");check(model(result).known.length,1,"Unlock retains physical cleanup obligation");check(commands(result),[],"Unlock cannot acquire or forge terminal proof");
 }
 ({send,result}=await prepared());await send("native",message("9007199254740993"));
 const oldJob=structuredClone(job),freshBinding={...job.binding,session:"3"},freshScope={...source.scope,binding:freshBinding,observation:"1",now:String(BigInt(source.scope.now)+1n)};
 result=await send("native",wrapped({kind:"attach",previous:job.binding,scope:freshScope}));
 check(commands(result),[{kind:"cancel",job:oldJob}],"Reattach retains original old-binding cleanup");
 check(metadata(result),{identity,title:"Preview unavailable",application:"",revision:null,iconKind:"unavailable",hasIcon:false,visible:true},"New binding cannot inherit old title/icon or metadata revision floor");
 const pending=structuredClone(result);result=await send("native",message("9007199254740994"));check(result,pending,"Old binding cannot restore metadata after attach");
 result=await send("native",{...message("1"),binding:freshBinding,title:"Actual reattached title"});check(metadata(result).title,"Actual reattached title","Fresh binding admits its own positive revision domain");check(metadata(result).revision,"1","Metadata revision floor is scoped to exact owner binding");check(commands(result),[],"New metadata does not erase old cleanup or emit a capture");check(model(result).known,[oldJob],"Old native job remains owned across re-enrollment");
 console.log(JSON.stringify({passed:true,checks,nativeAcceptance:false,fullReleaseAccepted:false,scope:"Actual optimized Elm presenter/lifecycle metadata revision and locked concealment with controlled authenticated deliveries; no native icon-resolution/pixels/hardware claim"}));
}
async function replay(trace){const {send}=await prepared();let revision=0,cancels=0;let result=await send("native",{kind:"invalid"});const actual=[];
 for(const name of trace){const prior=model(result);let value;
 switch(name){case "Fresh":value=message(String(revision+1));revision++;break;case "Stale":value=message(String(revision));break;case "Foreign":value={...message(String(revision+1)),subject:"999"};break;
 case "Lock":value=wrapped({kind:"source-denied",job,reason:"locked"});break;case "OtherDenial":value=wrapped({kind:"source-denied",job,reason:"source-unavailable"});break;case "ForeignLock":value=wrapped({kind:"source-denied",job:{...job,request:"999"},reason:"locked"});break;
 case "ObserveLocked":value=wrapped({kind:"observe",scope:{...prior.scope,locked:true,observation:String(BigInt(prior.scope.observation)+1n),now:String(BigInt(prior.scope.now)+1n)}});break;
 case "UnlockFresh":value=wrapped({kind:"observe",scope:{...prior.scope,locked:false,observation:String(BigInt(prior.scope.observation)+1n),now:String(BigInt(prior.scope.now)+1n)}});break;
 case "UnlockStale":value=wrapped({kind:"observe",scope:{...prior.scope,locked:false}});break;default:throw Error("Unknown Quint action "+name);}
 result=await send("native",value);const emitted=commands(result);if(emitted.length){assert.deepEqual(emitted,[{kind:"cancel",job}]);cancels++;}const m=metadata(result);actual.push({revision:Number(m.revision||0),visible:m.visible,capturing:!model(result).cancelling.length,cancels,history:[]});
 }
 process.stdout.write(JSON.stringify(actual)+"\n");
}
(async()=>{if(process.argv[4]==="--replay"){let raw="";for await(const chunk of process.stdin)raw+=chunk;await replay(JSON.parse(raw));}else await runControls();})().catch(error=>{process.stderr.write(error.stack+"\n");process.exitCode=1;});
