"""Prepare exact existing-history publication55 and its delivery checkpoint."""
import pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');old=r/'docs/warlock-repository/v54/publication';target=r/'docs/warlock-repository/v55/publication';assert not target.exists();target.mkdir(parents=True)
s=(old/'publish.py').read_text()
s=s.replace("BASE='6d98bb1a385ae674b68820f163a50232c9c96861'","BASE='0374bad7c76b9696c8453bbc7cba75437d76ba68'")
s=s.replace("COMMITS=['cd372c98502e57125b35dd62b3d57941fcccd648',args.source_commit]","COMMITS=[]")
marker="head=source(['rev-parse',args.source_commit],text=True).strip();paths=set()";assert s.count(marker)==1
s=s.replace(marker,marker+";COMMITS=source(['rev-list','--reverse','d2ddb6c3c697787abdccf8d76e763d46ded50f70..'+head],text=True).splitlines()")
start=s.index('allowed=(');end=s.index('\nassert all(',start)
allowed=['docs/warlock-preview/v74/','docs/warlock-preview/v75/','docs/warlock-preview/v76/','docs/warlock-repository/v54/publication/','docs/warlock-repository/v55/publication/','openspec/changes/warlock-preview-resume-intents/','implementation/warlock-client-provider-native-v109/']+['implementation/warlock-preview-provider-v'+str(n)+'/' for n in range(66,72)]
s=s[:start]+'allowed='+repr(tuple(allowed))+s[end:]
start=s.index(' qualification=json.loads(');end=s.index('\n published=mirror(',start)
s=s[:start]+''' qualification=json.loads((REPO/'docs/warlock-preview/v76/report.json').read_text());assert qualification['passed'] and qualification['receiptModelStates']==214 and qualification['resumeCControls']==79 and qualification['nativeChecks']==2419 and qualification['normalOwnedExits']==270 and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']
 message='Retain preview resume deadlines and exact Elm terminal ownership\\n\\nNative resume checks the original receiver epoch before any scope query, preserves the original two-second intent cutoff through capacity, and registers every real issued rejected job for settlement. One immutable Elm policy now refuses premature future terminal ACKs, retains an exact bounded terminal replay tuple, and preserves its native request history. Current full GUI71 build94, actual C/Elm79 controls including17 same-owner history/receipt controls, selected receipt8/214states and two preserved actual unsafe programs pass. Current metadata/catalog models and unchanged native resume8/584states/three mutants plus original demand/delivery/intent/enrollment proofs remain explicit. Native109 on the owning core/plugin tuple passes2419 checks with270 normal exits and clean teardown. Its dynamic C125 controls include real capacity return, retained resume deadline, independent resumed PNG, physical/backend/FD/GIO drain before exact final ACK and receiver refusal before native queries. All2411 stable prior108 identities and original1783/prior105 guards remain preserved. Five additive EARS requirements/eleven scenarios retain frozen242/417 and separate right-click24/48. Failed component/fixture/model attempts are archived. Ordinary eligible capture, original fullS09, hardware and coherent full release remain open; main desktop and concurrent workers are preserved.\\n'
''' + s[end:]
(target/'publish.py').write_text(s)
(target/'record_delivery.py').write_text('''import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;delivery=json.loads((base/'delivery.json').read_text());assert delivery['pushCompleted'] and delivery['ownedFiles']>4000
visibility=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert visibility['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(visibility,indent=2)+'\\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
event=loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v109',['PROGRESS published55 remote'+delivery['publishedCommit']+' exact'+str(delivery['ownedFiles'])+' rawownerblobs PUBLICverified. GUI71 full94/C79/Elm17/receipt8/214states2actualunsafeoldcounterexamples/currentmetadata/catalog; native resume8/584states3mutants/demand/delivery retained exact69. Native109 PASS2419/270normalclean/dynamic125 withactualcapacity retainedoriginalcutoff, original receiverqueryguard andnativeFD/GIO/backenddrain/exactACK/resumedgreenPNG; all2411 stableprior108 andoriginal1783/prior105 retained. AllGUI/CPU/native/publicationhandles terminal atdeliveryrecord. Next integrate typedlocaldemandfeedback throughsamefullGUI, define distinctlaterintent/historyretirement, ordinaryeligiblecapture thenalloriginalS09/S01-S16/restore38/recovery34/case34/two-second/cursor/drag52/input/hardware/ATIME/resources/journeys/coherentdeploymentrollback gates. No externalblocker orfullreleaseclaim.'], 'progress',['docs/warlock-preview/v76/report.json','implementation/warlock-preview-provider-v71/component-manifest.json','implementation/warlock-client-provider-native-v109/component-manifest.json','docs/warlock-repository/v55/publication/delivery.json']);print(event)
''')
print(str(target))
