"""Couple actual failed/passed rapid traces to unchanged/new producer gates."""
import hashlib,json,pathlib,resource,shutil,subprocess,sys,time
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');gui=r/'implementation/warlock-preview-provider-v134';old=r/'implementation/warlock-preview-provider-v133';sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();load=lambda p:json.loads(pathlib.Path(p).read_text())
failed=next((r/'implementation/warlock-client-provider-native-v149/qa').glob('native-controlled-*/report.json'));passed=next((r/'implementation/warlock-client-provider-native-v152/qa').glob('native-controlled-*/report.json'));f=load(failed);p=load(passed)
assert not f['passed'] and 'drained(1)' in f['traceback'] and f['cleanupPassed'] and p['passed'] and p['cleanupPassed'] and len(p['checks'])==51 and len(p['ownedExitCodes'])==17
for report,d in [(failed,f),(passed,p)]:
 for n,h in d['inputs'].items():assert sha(n)==h,n
 for n,h in d['artifacts'].items():assert sha(report.parent/n)==h,n
log=failed.parent/'private-evidence/controlled-host.log';lines=log.read_text().splitlines();states=[json.loads(l.split(': ',1)[1]) for l in lines if l.startswith('controlled-native-private-status: ')];ownership=[json.loads(l.split(': ',1)[1]) for l in lines if l.startswith('native-imported-ownership: ')];last=states[-1];model=last['privatePolicy']['models'][0]['model']
assert not model['known'] and not model['retiring'] and last['privatePolicy']['realm']['closing'] and not last['privatePolicy']['realm']['closed'] and last['privatePolicy']['realm']['retained']==1 and last['privatePolicy']['visuals']['surface']['lease']=='2'
assert all(x['mappedFDClosed'] and x['exportReleased'] and x['producerRetired'] and not x['retirementPending'] and x['charge']=='0' and x['records']==0 for x in ownership[-1])
checks={x['name']:x for x in p['checks']};assert all(x['passed'] for x in p['checks']);pending=checks['controlledActualLaterGTKPopupKeepsOldReaderDuty']['state'];closed=checks['controlledFirstRealmStrictlyClosedBeforeFreshRenderer']['state']
assert pending['privatePolicy']['realm']['closing'] and pending['privatePolicy']['realm']['epoch']=='1' and pending['privatePolicy']['visuals']['surface']['lease']=='2' and pending['privatePolicy']['models'][0]['model']['retiring'][0]['owned']
assert closed['privatePolicy']['realm']['closed'] and not closed['privatePolicy']['models'] and not closed['retainedInputs'] and not closed['postedTickets'] and not closed['confirmations'] and closed['transport']['pending']==0
old_host=old/'native/controlled-preview-host.h';new_host=gui/'native/controlled-preview-host.h';before=old_host.read_text();after=new_host.read_text();poll='        if(!surface_popup_ready() || !popup_owner || !popup_owner->active || !client_frame_target(surface_snapshot,qa_import_subjects[0],&publication,&lease) || publication!=surface_gate.publication || lease!=surface_gate.lease)publication=lease=0;';inventory='        if(subject_present && !surface_popup_ready()) {'
assert before.count(poll)==1 and before.count(inventory)==1
expected=before.replace(poll,poll.replace('if(!surface_popup_ready()','if(controlled_retiring || !surface_popup_ready()')).replace(inventory,'        /* Sticky old-realm retirement survives every later popup intent.\n         * Its original detachment facts/receipts must keep progressing; only\n         * strict Native closure can admit that later popup as a fresh realm. */\n        if(subject_present && (controlled_retiring || !surface_popup_ready())) {')
assert expected==after
names=['rapidLegacyCounterexample','stickyPendingObservation','heldReaderStillBlocks','emptyJobListIsNotRetirement'];sources=[gui/'spec/closing_observation_v3.qnt',gui/'spec/closing_observation_tests_v3.qnt'];tool=pathlib.Path('/home/hoskinson/.local/share/mise/installs/npm-informalsystems-quint/latest/node_modules/.bin/quint')
out=pathlib.Path(__file__).with_name('closing-observation-coupling-'+str(time.time_ns()));out.mkdir();(out/'inputs').mkdir()
for s in sources:shutil.copy2(s,out/'inputs'/s.name)
inputs={str(x):sha(x) for x in [failed,passed,log,old_host,new_host,*sources,pathlib.Path(__file__)]};d=dict(passed=False,inputs=inputs,quint=dict(path=str(tool),sha256=sha(tool)),commands=[],nativeObservations={'failedPhysicallyEmptyButSubjectRetained':last,'failedOriginalResourceZero':ownership[-1],'currentPendingOriginalOwnedJob':pending,'currentStrictOldRealmClosed':closed},selected=names,scope='Four producer-scheduling model cases coupled to actual unchanged-oracle Native149 deadline failure and Native15251/17 success, original resource-zero/subject-retained state, current real-reader/owned Retiring job/new popup and strict independent native close. Exact source comparison limits production fix to two sticky old-realm producer gates. dutiesSettled describes independent physical/journal/confirmation obligations BEFORE subject detachment, not Native owner empty or retirement. No complete implementation refinement, fair-scheduling proof, all rapid timings, ongoing physical reveal/hardware or full release acceptance.',nativeAcceptance=False,fullReleaseAccepted=False)
try:
 for name,args in [('typecheck',[str(tool),'typecheck',sources[1].name]),('selected',[str(tool),'test',sources[1].name,'--main=closing_observation_tests_v3','--backend=typescript','--match=^('+'|'.join(names)+')$','--seed=1520042','--max-samples=1','--out-itf='+str(out/'coupled-{test}-{seq}.itf.json')])]:
  q=subprocess.run(args,cwd=out/'inputs',capture_output=True,text=True,timeout=180);(out/(name+'.stdout')).write_text(q.stdout);(out/(name+'.stderr')).write_text(q.stderr);d['commands'].append(dict(name=name,argv=args,exitCode=q.returncode));print(name,q.returncode,flush=True);assert q.returncode==0,q.stdout+q.stderr
 assert len(list(out.glob('coupled-*.itf.json')))==4 and all(sha(n)==h for n,h in inputs.items())
 d.update(passed=True,coupledQuintChecks=4,actualFailureAndFixQualified=True)
except Exception as error:d['error']=repr(error)
d['artifacts']={str(x.relative_to(out)):sha(x) for x in out.rglob('*') if x.is_file()};(out/'report.json').write_text(json.dumps(d,indent=2)+'\n');print(json.dumps({'passed':d['passed'],'report':str(out/'report.json'),'error':d.get('error','')}),flush=True);raise SystemExit(not d['passed'])
