"""Hold readonly native visual custody and exact original source/evidence identity."""
import hashlib,json,pathlib,resource,stat,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');root=repo/'implementation/warlock-preview-provider-v118';sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
names={'nativeElmOutbox':'readonly-visual-native-check-1791369815363217451','lifetime':'readonly-policy-lifetime-check-1791370405260041629','backpressure':'readonly-policy-backpressure-check-1791370478900181453'}
builds=list((root/'qa').glob('build-*/report.json'));assert len(builds)==1;names['build']=builds[0].parent.name
paths={k:root/'qa'/v/'report.json' for k,v in names.items()};declared=set();reports={}
for key,path in paths.items():
 d=json.loads(path.read_text());assert d['passed'] and not d['nativeAcceptance'] and not d['fullReleaseAccepted'],path
 for rel,value in d.get('inputs',{}).items():assert sha(root/rel)==value,(path,rel)
 for rel,value in d.get('artifacts',{}).items():
  p=path.parent/rel;assert sha(p)==value,(path,rel);declared.add(str(p.relative_to(root)))
 for category in ['compilerDependencies','linkedLibraries','tools']:
  for name,row in d.get(category,{}).items():assert sha(name)==row['sha256'],(category,name)
 reports[key]=d
n=reports['nativeElmOutbox']['evidence'];assert n['checks']==207 and n['visualProjectionChecks']==90 and n['readonlyProjectionChecks']==74 and n['singlePreviewPolicy'] and n['normalOwnedExit'] and n['realmEpochs']==2 and n['nativeGrantResets']==0 and n['syntheticNativeRemainsActive'] and n['persistentPolicyContexts']==1 and n['rendererWindowPolicyInstances']==0 and n['freshJSContexts']==2
l=reports['lifetime'];assert l['boundaryChecks']==37 and l['readonlyBoundaryChecks']==15 and len(l['constructorFaults'])==13 and l['namedScenarios']==14 and len(l['coupledTraces'])==26 and l['statesCompared']==430 and l['invariantSamples']==200 and l['unsafeCompiledNativeVariantsDetected']==5
p=reports['backpressure'];assert p['checks']==48 and p['readonlyProjectionChecks']==28 and p['explicitWouldBlockControls']==3 and p['normalOwnedExit'] and p['syntheticNativeIssuedFacts']
b=reports['build'];assert len(b['commands'])==112 and all(x['exitCode']==0 for x in b['commands']);assert sha(paths['build'].parent/'elm-host')==b['binarySHA256']
a=json.loads((root/'ANCESTRY.json').read_text());parent=pathlib.Path(a['parent']);manifest=parent/'component-manifest.json';assert sha(manifest)==a['parentManifestSHA256'];prior=json.loads(manifest.read_text());assert prior['sourceHeld'] and prior['passed'] and prior['fullBuildCommands']==112
for rel,row in prior['files'].items():assert sha(parent/rel)==row['sha256'],rel
changed={'native/elm-preview-policy.h','native/elm-preview-policy.cpp','native/persistent-policy-lifetime-fixture.cpp'}
for base in ['native','assets','adapter','src']:
 for f in (parent/base).glob('*'):
  if f.is_file() and str(f.relative_to(parent)) not in changed:assert sha(root/base/f.name)==sha(f),f
old=(parent/'native/elm-preview-policy.cpp').read_text();fresh=(root/'native/elm-preview-policy.cpp').read_text();start=fresh.index('gboolean warlock_preview_policy_visual_projection(');end=fresh.index('gboolean warlock_preview_policy_close(',start);assert fresh[:start]+fresh[end:]==old
assert [x['name'] for x in b['commands']]==[x['name'] for x in json.loads(pathlib.Path(prior['reports']['build']['path']).read_text())['commands']]
assert set((root/'qa').glob('*/report.json'))==set(paths.values()),'Unreviewed phase report'
result={'schema':1,'owner':a['owner'],'sourceHeld':True,'passed':True,'evidenceIntegrityPassed':True,'reports':{k:{'path':str(p),'sha256':sha(p)} for k,p in paths.items()},'heldFailedReports':[], 'singlePreviewPolicy':True,'parentElmPolicyUnchanged':True,'parentNativeIssuerAndPhysicalProductUnchanged':True,'parentAssetsAndAdaptersUnchanged':True,'nativeOwnedJavaScriptCore':True,'persistentPolicyContexts':1,'nativeElmOutboxChecks':207,'additiveVisualProjectionChecks':90,'readonlyProjectionChecks':74,'lifetimeBoundaryChecks':37,'readonlyBoundaryChecks':15,'constructorFaults':13,'lifetimeScenarios':14,'lifetimeTraces':26,'lifetimeStates':430,'lifetimeSamples':200,'lifetimeCompiledNativeVariantsDetected':5,'backpressureChecks':48,'backpressureReadonlyChecks':28,'backpressureFactsSynthetic':True,'realmEpochs':2,'nativeGrantResets':0,'fullBuildCommands':112,'originalBuildCommands':112,'readonlyVisualCPUQualified':True,'realHostPolicyActivated':False,'actualRendererProjectionActivated':False,'actualDOMQualified':False,'projectionDeliveryOrderingQualified':False,'realHostInputBackpressureQualified':False,'nativeDelayedProposalLivenessQualified':False,'uncertainLiveWorkerRecoveryQualified':False,'fullElmRecoveryQualified':False,'typedHostRoutingActivated':False,'webKitActivated':False,'actualWaylandWindowAcceptance':False,'nativeAcceptance':False,'fullReleaseAccepted':False,'parentManifest':str(manifest),'parentManifestSHA256':sha(manifest),'scope':(root/'READONLY-VISUAL-HANDOFF.md').read_text()}
files={}
for f in sorted(root.rglob('*')):
 rel=f.relative_to(root);name=str(rel)
 if any(part in {'elm-stuff','mutable-elm-home','elm-home','__pycache__'} for part in rel.parts) and 'toolchain' not in rel.parts and name not in declared:continue
 assert not f.is_symlink(),f
 if f.is_file():files[name]={'kind':'file','sha256':sha(f),'size':f.stat().st_size,'mode':oct(stat.S_IMODE(f.stat().st_mode))}
result['files']=files;assert not (root/'component-manifest.json').exists();(root/'component-manifest.json').write_text(json.dumps(result,indent=2)+'\n')
out=pathlib.Path(__file__).parent/'component-report118.json';assert not out.exists();out.write_text(json.dumps({k:v for k,v in result.items() if k!='files'},indent=2)+'\n')
task=repo/'openspec/changes/warlock-preview-actor-retirement/tasks.md';text=task.read_text();old='- [ ] Freeze CONTROL-031 creator-owned read-only visual copies';assert text.count(old)==1;task.write_text(text.replace(old,'- [x] Freeze CONTROL-031 creator-owned read-only visual copies'))
handoff=repo/'docs/warlock-preview/v93/HANDOFF.md';text=handoff.read_text();text+='\nGUI117 PUBLIC86 99c357235f940af304314501ce76efe76cbd91c5/3186 exact owned blobs;\nsource356ebb9de9a5c203f67c4fd40b614ecd22d39c76;\nreceiptc226d97a29289e6edccbe784ab9591eee02bd31f.\nGUI118 held creator-owned readonly visual custody: unchanged original Elm policy/\nissuer/effects/physical product; no JS invocation or model/ordinal advance; detached\ncaller-mutable copies. Original C/JSC/native207 plus90 visual and74 readonly\ncomparisons/two epochs/unchanged grant/normal exits. Lifetime37+15/13 pre-grant\nfaults/Quint14/26 actual C+JSC traces/430 states/200 samples/five compiled guards;\nbackpressure48+28 with explicit synthetic ticket/terminal/close facts; full112\nretains112. CONTROL031/OpenSpec five scenarios. Next PUBLIC87 then native\nauthenticated ordered current-projection channel and renderer lease/reload\nconcealment, durable input/native-ticket custody/retry before actual WebKit/Core.\nCommitted copies alone qualify no freshness, live uncertain worker recovery,\ndelayed proposal outcome, actual DOM/URI/captured FD or full release. Native130\nlegacy2518/278 remains actual baseline; installed desktop/foreign paths preserved.\n';handoff.write_text(text)
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(repo,a['owner'],str(root.relative_to(repo)),['PROGRESS heldGUI118 creator-owned readonly visual custody. Exact parent original Elm policy/native issuer/effects/physical remain unchanged; getter calls no JS/model/command/ordinal; copies survive caller mutation and ordinary WOULD_BLOCK, refuse foreign/missing/absent/closed/unknown/inflight authority. Original C/JSC/native207 plus90 visual/74 readonly/two epochs/unchanged grant/normal; lifetime37+15/13 pre-grant faults/Quint14/26 actual C+JSC traces/430 states/200 samples/five compiled guards; backpressure48+28 explicitly synthetic native ticket/terminal/close facts; full112 retains112. CONTROL031/OpenSpec five scenarios. Next PUBLIC87 then authenticated ordered native current-projection custody with renderer lease/reload concealment and durable original host input/native-issued-ticket custody/retry before actual WebKit/Core. Copies provide no freshness/order proof. Uncertain JSC/process/revoked delayed proposal/actual DOM/URI/captured FD/full release remain open; Native130 legacy2518/278 remains actual bounded baseline; installed/foreign paths preserved.'],'progress',[str((root/'component-manifest.json').relative_to(repo)),str(out.relative_to(repo))]))
print(json.dumps({'heldFiles':len(files),'fullBuildCommands':112}))
