"""Prepare held shared visual projection publication under existing authorization."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v86/publication';assert not out.exists();out.mkdir(parents=True)
base='c026b4b106dc0c4e62b9aecdc853d5bf81931707';local='81205931d581c2ba5e4e9f4dfc4f6efb11fbe339';previous='2fcb2afdbd87a3d0cfba5b09233eb47e94e76091'
proof=json.loads((r/'docs/warlock-preview/v93/component-report117.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeElmOutboxChecks']==207 and proof['additiveVisualProjectionChecks']==90
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v117/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v85/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='1d89276d5d6b8d7dbd24d79e20073608589da795'","BASE='"+base+"'").replace('9825a9d59f35bb3a7eb6bc637291c7f2b60ed24f..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v85/publication/','docs/warlock-repository/v86/publication/','implementation/warlock-preview-provider-v117/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report117.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['singlePreviewPolicy'] and qualification['originalLifecycleTransitionsUnchanged'] and qualification['sharedVisualDecisionsImplemented'] and qualification['typedVisualProjectionImplemented'] and qualification['pureRendererDecoderWindowPolicies']==0 and qualification['nativeOwnedJavaScriptCore'] and qualification['persistentPolicyContexts']==1 and qualification['nativeElmOutboxChecks']==207 and qualification['additiveVisualProjectionChecks']==90 and qualification['visualDecoderChecks']==101 and qualification['visualPolicyChecks']==150 and qualification['visualPolicyFactsSynthetic'] and qualification['lifetimeBoundaryChecks']==37 and qualification['constructorFaults']==13 and qualification['backpressureChecks']==48 and qualification['lifetimeScenarios']==8 and qualification['lifetimeTraces']==20 and qualification['lifetimeStates']==405 and qualification['lifetimeCompiledNativeVariantsDetected']==3 and qualification['fullBuildCommands']==112 and qualification['originalBuildCommands']==110 and len(qualification['heldFailedReports'])==3 and qualification['visualProjectionCPUQualified'] and not qualification['realHostPolicyActivated'] and not qualification['actualRendererProjectionActivated'] and not qualification['actualDOMQualified'] and not qualification['projectionDeliveryOrderingQualified'] and not qualification['realHostInputBackpressureQualified'] and not qualification['nativeDelayedProposalLivenessQualified'] and not qualification['uncertainLiveWorkerRecoveryQualified'] and not qualification['fullElmRecoveryQualified'] and not qualification['typedHostRoutingActivated'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Share typed visual projections with the original single Elm preview policy\n\n'+proof['scope'];s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v85','warlock-repository/v86').replace('component-report116.json','component-report117.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v117',['PROGRESS PUBLIC86 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI117 shared typed visuals with original single unchanged lifecycle/native transitions. Native C/JSC207 plus90 visual comparisons/two epochs/unchanged Native grant/normal exits; codec101/client-family display150 explicitly synthetic native facts/current lifetime37/13 faults/backpressure48/Quint8/20/405/three compiled guards/full112 retains110. Three compile failures held. Pure decoder adds no window policy; original issuer/physical/assets/adapters unchanged except private worker output union. Actual host/renderer route inactive, no actual DOM or projection freshness/reload/URI proof. Next authenticated ordered native current-projection custody and durable input/ticket custody/retry before actual WebKit/Core/URI activation; uncertain JSC/process and delayed expired/revoked original proposals remain open. Native130 legacy2518/278 remains actual bounded baseline; every original full release gate remains, installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/component-report117.json','implementation/warlock-preview-provider-v117/component-manifest.json','docs/warlock-repository/v86/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('1d89276d5d6b8d7dbd24d79e20073608589da795',base).replace('Record public persistent native Elm policy qualification','Record public shared visual projection qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit116.py').read_text().replace('060a36829fdb934ab03a6f21d9a7df6b1697c07c',local).replace("[('warlock-preview-provider-v116',True)]","[('warlock-preview-provider-v117',True)]").replace('warlock-repository/v85/publication','warlock-repository/v86/publication').replace('Own the retained Elm policy in a persistent native JavaScriptCore worker','Share typed visual projections with the original single Elm preview policy')
p=r/'docs/warlock-preview/v93/commit117.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
