"""Own the actual controlled host derivative; held source stays immutable."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v127';root=repo/'implementation/warlock-preview-provider-v128';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=parent/'component-manifest.json';d=json.loads(m.read_text());assert d['sourceHeld'] and d['passed'] and d['normalControlledHostClosureQualified'] and d['cpuBuildPassed'] and d['actualNativeGTKAdmissionObserved'] and not root.exists()
for rel,row in d['files'].items():assert sha(parent/rel)==row['sha256'],rel
native=repo/'implementation/warlock-client-provider-native-v138/component-manifest.json';n=json.loads(native.read_text());assert n['sourceHeld'] and n['passed'] and n['normalControlledHostClosureQualified'] and n['privateSessionCleanupPassed']
for rel,row in n['files'].items():assert sha(native.parent/rel)==row['sha256'],rel
def ignore(path,names):
 if pathlib.Path(path)==parent:return [x for x in names if x in {'component-manifest.json','ANCESTRY.json','__pycache__'}]
 if pathlib.Path(path)==parent/'qa':return [x for x in names if (pathlib.Path(path)/x).is_dir() and x!='toolchain']
 return [x for x in names if x in {'__pycache__','elm-stuff'}]
shutil.copytree(parent,root,ignore=ignore)
(root/'ANCESTRY.json').write_text(json.dumps({'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(m),'nativeBaselineManifest':str(native),'nativeBaselineManifestSHA256':sha(native),'purpose':'QA-only intentional unsafe negative control derived from held positive GUI127/Native138. Change only the native controlled curtain setter from opacity0 to1 so the unchanged live Native138 original region oracle must detect actual exposed preview pixels. Preserve original native/Elm/GTK authority, effect/deadline6/input/journal/confirmation/strict closure and all original controls. Never activate this unsafe variant in installed or default GUI paths. Retain the expected failed report and uncertain normal-close refusal; detector evidence does not qualify physical reveal or full release.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(root.relative_to(repo)),['PROGRESS ownGUI128 actual private QA-only intentional unsafe-curtain negative control after held positiveGUI127/Native13829checks13normalexits. Change only controlled native opacity setter0to1; unchanged actual Native138 region oracle must see original preview pixels and reject. Original native/Elm issuer/effects/GTK/context/deadline6/journal/confirmation/strict close unchanged, retain expected failed report/closure refusal. Never installed/default activated; no physical reveal/full release claim. Current119 build then serial Native139 on original core16/plugin19/AQ155; compare actual pixels and popup opacity, not old diagnostic labels. Installed/drafts/foreign preserved.'],'progress',[str(m.relative_to(repo)),str(native.relative_to(repo)),str((root/'ANCESTRY.json').relative_to(repo))]))
