"""Prepare exact owned failure and actual rapid pending-intent fix publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v98/publication';assert not out.exists();out.mkdir(parents=True)
base='8496ca6e461a1e6f4d17df21c19f4bdb6347f80c';local='a92e3a4978f6c420cf612cb2b573e6b8188220df';previous='fcd4371992e09699567841eed40ab3848bcc595d';oldbase='455421e67ebb431a32669e5dab23578a350dc99b'
components=[('warlock-preview-provider-v133',False),('warlock-preview-provider-v134',True),*[(f'warlock-client-provider-native-v{v}',v!=149) for v in range(147,154)]];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report134.json').read_text());assert held['passed'] and held['actualRapidPointerCloseReopenQualified'] and held['rapidPendingReaderNativeChecks']==51 and held['closingProducerQuintScenarios']==8 and held['fullBuildCommands']==119
prior=r/'docs/warlock-repository/v97/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('5f9ed867f5bbb8ef19377051486a682ccb55be8f..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v97/publication/','docs/warlock-repository/v98/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report134.json').read_text());assert qualification['passed'] and qualification['actualGUIRealmReopenQualified'] and qualification['actualPendingIntentReopenQualified'] and qualification['actualRapidPointerCloseReopenQualified'] and qualification['stickyClosingRealmProducerQualified'] and qualification['rapidPendingReaderNativeChecks']==51 and qualification['rapidPendingReaderNormalOwnedExits']==17 and qualification['pendingReaderNativeChecks']==51 and qualification['pendingReaderNormalOwnedExits']==18 and qualification['readerQuintScenarios']==6 and qualification['readerInvariantSamples']==200 and qualification['readerCoupledStages']==8 and qualification['closingProducerQuintScenarios']==8 and qualification['closingProducerInvariantSamples']==200 and qualification['closingProducerCoupledChecks']==4 and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['delayedResultNativeChecks']==18 and qualification['delayedResultNormalOwnedExits']==8 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Finish retiring the old preview realm during rapid popup reopening\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-report132.json','component-report134.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v134',['PROGRESS PUBLIC98 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI134 fixes actual rapid149 original6s closing-subject deadlock with two sticky old-realm producer gates; original failure/source/host1/private cleanup retained. Current same byte-identical rapid15251/17 normal exits, slower15151/18, unchanged normal15029/13 and delayed15318/8 cleanups/full119 pass. Real original GIO reader/owned Retiring job across later GTK popup, held/fresh read denial/one actual close then independent strict Native retirement, same popup lease/new fixed renderer/same policy binding and current source URI/red19200 both epochs/monotonic chronology/opacity0 output. Reader Quint6/200/8coupled and producer8/200/4failure-fix cases; scope actual fixture schedules not all timings. Native issuer/policy/physical gates/deadlines unchanged/no resets. Next old-context actual delayed result across reopened epoch; ongoing physical conceal/reveal/hardware/pressure/workload/RSS/process/reload/Unknown/full preview/release open. Installed/drafts/foreign preserved.'],'progress',['docs/warlock-preview/v93/component-report134.json','implementation/warlock-preview-provider-v134/component-manifest.json','implementation/warlock-client-provider-native-v149/component-manifest.json','implementation/warlock-client-provider-native-v152/component-manifest.json','docs/warlock-repository/v98/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record public normal GUI close and reopen qualification','Record public rapid popup retirement repair qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui132_normal_reopen.py').read_text().replace('24497b0bd5480a9c7441f28d7114d77b1a63b2fa',local).replace('Reopen the native GUI with one persistent Elm policy','Finish retiring the old preview realm during rapid popup reopening')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v98/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui134_sticky_retirement.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
