"""Publish bounded current failure proof and actual mandatory drain counterexample."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v101/publication';assert not out.exists()
base='5ad30ad20254454a534adfa7ae0fee3eb7a3733c';local='f7cc7be0173f8f6ef3fb07c3e3be6fddc966d518';previous='dd836cb2b40daf793b41a5a6cd9f76253c69c911';oldbase='2873c6289af212c6b64002cd42dad9a21e0eca68'
components=[('warlock-preview-provider-v138',False),('warlock-client-provider-native-v165',True),('warlock-client-provider-native-v166',True),('warlock-client-provider-native-v167',True),('warlock-client-provider-native-v168',False)];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report-gui138-current-failure.json').read_text());assert not held['passed'] and held['actualCurrentMatchingErrorNativeQualified'] and held['actualCurrentFailureDrainCounterexample'] and not held['gracefulCurrentFailureDrainQualified'] and held['fullBuildCommands']==119
out.mkdir(parents=True);prior=r/'docs/warlock-repository/v100/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('506e513b61961a46dbca3e9a21e3957c61276d70..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v100/publication/','docs/warlock-repository/v101/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report-gui138-current-failure.json').read_text());assert not qualification['passed'] and qualification['actualCurrentMatchingErrorNativeQualified'] and qualification['actualCurrentCancellationConsumedOnce'] and qualification['actualCurrentFailureStrictTeardownRefusalObserved'] and qualification['currentFailureNegativeControls']==22 and qualification['currentFailureExpectedExitCode']==1 and qualification['currentFailureOtherNormalOwnedExits']==7 and qualification['actualCurrentFailureDrainCounterexample'] and not qualification['gracefulCurrentFailureDrainQualified'] and qualification['actualCancelledOldResultQualified'] and qualification['cancelledOldResultNativeChecks']==36 and qualification['cancelledOldResultNormalOwnedExits']==13 and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['retainedAsyncErrorScopeQuintScenarios']==10 and qualification['retainedAsyncErrorScopeInvariantSamples']==200 and qualification['currentErrorScopeCoupledCases']==4 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Qualify current snapshot failure and retain native drain counterexample\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text();a=s.index('report=json.loads(');b=s.index('\nsys.path.insert',a);s=s[:a]+"report=json.loads((r/'docs/warlock-preview/v93/component-report-gui138-current-failure.json').read_text());assert not report['passed'] and report['actualCurrentMatchingErrorNativeQualified'] and report['actualCurrentFailureDrainCounterexample'] and not report['gracefulCurrentFailureDrainQualified']"+s[b:]
s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v138',['PROGRESS PUBLIC101 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. '+report['scope']+' Next fresh139 actual current-error quarantine/continued native drain/strict close before failure1 exit with unchanged168 oracle, original normal/old-error regressions; full release remains active.'],'progress',['docs/warlock-preview/v93/component-report-gui138-current-failure.json','implementation/warlock-preview-provider-v138/component-manifest.json','implementation/warlock-client-provider-native-v166/component-manifest.json','implementation/warlock-client-provider-native-v168/component-manifest.json','docs/warlock-repository/v101/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record public retired WebKit error guard qualification','Record current failure and native drain counterexample publication');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui137_stale_snapshot_error_guard.py').read_text().replace('2f3def1c88547c67499336de276e23f2b9002e3d',local).replace('Reject retired WebKit errors before current GUI failure handling','Qualify current snapshot failure and retain native drain counterexample')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v101/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui138_current_failure.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
