"""Own the actual controlled host derivative; held source stays immutable."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v127';root=repo/'implementation/warlock-preview-provider-v129';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=parent/'component-manifest.json';d=json.loads(m.read_text());assert d['sourceHeld'] and d['passed'] and d['normalControlledHostClosureQualified'] and d['cpuBuildPassed'] and d['actualNativeGTKAdmissionObserved'] and not root.exists()
for rel,row in d['files'].items():assert sha(parent/rel)==row['sha256'],rel
native=repo/'implementation/warlock-client-provider-native-v138/component-manifest.json';n=json.loads(native.read_text());assert n['sourceHeld'] and n['passed'] and n['normalControlledHostClosureQualified'] and n['privateSessionCleanupPassed']
for rel,row in n['files'].items():assert sha(native.parent/rel)==row['sha256'],rel
def ignore(path,names):
 if pathlib.Path(path)==parent:return [x for x in names if x in {'component-manifest.json','ANCESTRY.json','__pycache__'}]
 if pathlib.Path(path)==parent/'qa':return [x for x in names if (pathlib.Path(path)/x).is_dir() and x!='toolchain']
 return [x for x in names if x in {'__pycache__','elm-stuff'}]
shutil.copytree(parent,root,ignore=ignore)
(root/'ANCESTRY.json').write_text(json.dumps({'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(m),'nativeBaselineManifest':str(native),'nativeBaselineManifestSHA256':sha(native),'purpose':'Fresh safe derivative of held positive GUI127/Native138, not the intentional unsafe GUI128. Preserve opacity0 and all original GTK/native policy/issuer/physical/journal/confirmation/strict close. Add one explicit QA-only retained actual WebKit GAsyncResult/view/snapshot slot, once per host without reset, to exercise the original snapshot completion after actual popup closure. Finish that original result once and revalidate original context/projection; stale pixels must be rejected without artifact publication or effect settlement. Normal route remains unchanged. Rerun current full119 and original29 positive controls, then a distinct actual stale-result scenario under original16 admission/drain identities/deadline6. No physical reveal/recovery/full release acceptance from preparation.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(root.relative_to(repo)),['PROGRESS ownGUI129 fresh SAFE opacity0 lineage from held positiveGUI127/Native13829checks13normalexits, after actual unsafe128/139 was rejected by original region oracle with19200 previewpixels and opacity1. Add explicit QA-only one retained real WebKit snapshot GAsyncResult/view/original scope slot, finish once after actual closure and require stale callback rejection/no pixels artifact while original policy/native custody drains. Never inherit unsafe setter or reset grant. Normal route original29/current full119 then separate actual stale-result Native141 with original16 admission/drain checks/deadline6/core16/plugin19/AQ155. Physical frame/reveal/ongoing transitions/recovery/full release remain open; installed/drafts/foreign preserved.'],'progress',[str(m.relative_to(repo)),str(native.relative_to(repo)),str((root/'ANCESTRY.json').relative_to(repo))]))
