"""Prepare held GUI107 persistent realm/race qualification publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v75/publication';assert not out.exists();out.mkdir(parents=True)
base='806c609195d742d2a97e5d845c4c9cad1d45b2c7';local='67d8b7e46e719509f8afbe635c1f082530d7a8ae';previous='3f40039fbec11bbacf5bafb33a17427cc13c3d68'
proof=json.loads((r/'docs/warlock-preview/v93/component-report107.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['realmCChecks']==111 and proof['realmRaceChecks']==36 and proof['realmStates']==711
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v107/component-manifest.json').read_text())['files'])
prior=r/'docs/warlock-repository/v74/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='daed06a2a125f729eb5e9ec3ddf585d160031247'","BASE='"+base+"'").replace('9a47a8668676458f6eaf01116a654a690c910806..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v74/publication/','docs/warlock-repository/v75/publication/','implementation/warlock-preview-provider-v107/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
message='Preserve native preview realm identity across settled owner replacement\n\nAllocate receiver epochs from the original Native transport before admission, consume failed-constructor epochs and refuse exhaustion without replacing the shared binding/session/frontend. Release published ownership only after original physical/proof/actor/final-processing/independent-confirmation strict close. A persistent atomic closed marker prevents delayed legacy zero-CAS admission from crossing a complete controlled lifecycle; preserve the actual threaded counterexample and six failed fixture reports. Current111 C replacement/exhaustion controls,36 threaded controls,16 selected Quint/28 coupled actual C traces/711 states, precise compiled variants, full95 and original resource/capture/ticket/SCM_RIGHTS/GIO/post-adoption allocation regressions pass. Elm/assets remain byte-identical to held106; parent compiled Elm ACK evidence retains its own source. GUI107 is inactive CPU evidence. Actual native GUI92/native129/core16/plugin19 remains2517 checks/278 normal exits/full cleanup. Live-window detachment, Bootstrap receipt reattachment, typed frontend realm scoping, renderer native outbox/WebKit/current controlled Core integration and all original release gates remain open; no installed changes.\n'
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report107.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['realmCChecks']==111 and qualification['realmRaceChecks']==36 and qualification['realmScenarios']==16 and qualification['realmTraces']==28 and qualification['realmStates']==711 and qualification['fullBuildCommands']==95 and len(qualification['heldFailedReports'])==6 and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v74','warlock-repository/v75').replace('native-report129.json','component-report107.json')
old="d['ownedFiles']>=580";assert s.count(old)==1;s=s.replace(old,"d['ownedFiles']>="+str(minimum))
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v107',['PROGRESS PUBLIC75 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI107 inactive CPU persistent realm/native claim ownership:111 C replacement/exhaustion controls,36 threaded controls,16 selected Quint/28 actual C traces/711 states/current full95/original resource/capture/ticket/FD regressions; six failures preserved. Native129/public74 GUI92/core16/plugin19 remains2517 checks/278 normal exits/full cleanup. Next freshGUI108 distinct live-window detachment/Bootstrap borrowed receipt reattachment/current controlled Core/native renderer outbox/WebKit; original full release gates remain open. No installed changes.'],'progress',['docs/warlock-preview/v93/component-report107.json','implementation/warlock-preview-provider-v107/component-manifest.json','docs/warlock-repository/v75/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('daed06a2a125f729eb5e9ec3ddf585d160031247',base).replace('Record public Core capture resource qualification','Record public preview realm ownership qualification');assert s.count(old)==1;s=s.replace(old,"d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit129.py').read_text().replace('448b229ee11a4bb2299e7099e7306c45e5865108',local).replace("[('warlock-client-provider-native-v129',True)]","[('warlock-preview-provider-v107',True)]").replace('warlock-repository/v74/publication','warlock-repository/v75/publication').replace('Qualify scoped native capture resource recovery on the owning Core pair','Preserve native preview realm identity across settled owner replacement')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit107.py';assert not p.exists();p.write_text(s)
print(out)
