"""Prepare exact held single Elm realm policy publication under existing authorization."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v82/publication';assert not out.exists();out.mkdir(parents=True)
base='a03d4953d8ed1ab2f500ababc1dbdc5a0c367ce8';local='5ca2631493281c0adcc21e07b798ac4506a00bac';previous='0da2d5bf6c4565345cd150c30d7225f6065dab11'
proof=json.loads((r/'docs/warlock-preview/v93/component-report113.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeElmOutboxChecks']==175 and proof['scopedStates']==469
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v113/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v81/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='620566103509a1469c6d75401f753dc32a4bcb3c'","BASE='"+base+"'").replace('d8a51e4141fe3d7d7eb033002fdf37594f23060c..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v81/publication/','docs/warlock-repository/v82/publication/','implementation/warlock-preview-provider-v113/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report113.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['singlePreviewPolicy'] and qualification['boundaryChecks']==44 and qualification['nativeElmOutboxChecks']==175 and qualification['scopedScenarios']==20 and qualification['scopedTraces']==32 and qualification['scopedStates']==469 and qualification['unsafeCompiledElmVariantsDetected']==6 and qualification['coldCohortChecks']==1549 and qualification['fullBuildCommands']==103 and qualification['originalBuildCommands']==98 and len(qualification['heldFailedReports'])==8 and not qualification['fullElmRecoveryQualified'] and not qualification['typedHostRoutingActivated'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Integrate native preview realms and scoped detachment in the single Elm policy\n\n'+proof['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v81','warlock-repository/v82').replace('component-report112.json','component-report113.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v113',['PROGRESS PUBLIC82 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI113 single Elm policy/typed native realms/scoped detachment: boundaries44/native C+Elm+outbox175/two epochs/unchanged Native grant/normal exits; Quint20/32/469/200 samples/six compiled variants; cold256/1549; original permanent45/native20+C34/model14/34/667; full103 retains98. Eight failed attempts and historical phases remain. Next actual typed shared-host realm/recovered transport/stable WebKit/Core integration and full Elm recovery. Native130 current110 legacy2518/278/full cleanup remains bounded actual baseline. Original full release gates open; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report113.json','implementation/warlock-preview-provider-v113/component-manifest.json','docs/warlock-repository/v82/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('620566103509a1469c6d75401f753dc32a4bcb3c',base).replace('Record public native realm recovery qualification','Record public single Elm preview realm qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit112.py').read_text().replace('d029415cf596ad30892b1fe3e8ed851fa3bf89d7',local).replace("[('warlock-preview-provider-v112',True)]","[('warlock-preview-provider-v113',True)]").replace('warlock-repository/v81/publication','warlock-repository/v82/publication').replace('Recover original native preview tickets after renderer context loss','Integrate native preview realms and scoped detachment in the single Elm policy')
p=r/'docs/warlock-preview/v93/commit113.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
