"""Own the actual controlled host derivative; held source stays immutable."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v123';root=repo/'implementation/warlock-preview-provider-v124';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=parent/'component-manifest.json';d=json.loads(m.read_text());assert d['sourceHeld'] and not d['passed'] and d['cpuBuildPassed'] and d['actualNativeGTKAdmissionObserved'] and not root.exists()
for rel,row in d['files'].items():assert sha(parent/rel)==row['sha256'],rel
native=repo/'implementation/warlock-client-provider-native-v133/component-manifest.json';n=json.loads(native.read_text());assert n['sourceHeld'] and not n['passed'] and n['privateSessionCleanupPassed']
for rel,row in n['files'].items():assert sha(native.parent/rel)==row['sha256'],rel
def ignore(path,names):
 if pathlib.Path(path)==parent:return [x for x in names if x in {'component-manifest.json','ANCESTRY.json','__pycache__'}]
 if pathlib.Path(path)==parent/'qa':return [x for x in names if (pathlib.Path(path)/x).is_dir() and x!='toolchain']
 return [x for x in names if x in {'__pycache__','elm-stuff'}]
shutil.copytree(parent,root,ignore=ignore)
(root/'ANCESTRY.json').write_text(json.dumps({'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(m),'nativeBaselineManifest':str(native),'nativeBaselineManifestSHA256':sha(native),'purpose':'Fresh correction of held failed GUI123/Native133: reference original compiled native-visual-renderer.js in page/allowlist and verify packaged page asset closure. Preserve the accepted persistent outer mount correction and disabled legacy imported wake. Actual QA-only controlled GTK/WebKit host route: presentation-only admission placeholder, single persistent native policy driver, native producer pause/retained exact inputs, fixed one-time pure renderer grant and native context-owned URI routing. Preserve original GTK admission, physical/terminal/confirmation and no-reset gates. Keep native opacity curtain closed until actual DOM/frame/physical reveal acceptance. No release or installed activation follows source preparation.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(root.relative_to(repo)),['PROGRESS ownGUI124 after held failedGUI123/Native133. Actual second failure is packaged asset naming: HTML/allowlist requested native-preview-renderer.js while original compiler emits native-visual-renderer.js. The held failed123 manifest scope and actual log are authoritative; its copied checkpoint mistakenly repeated prior mount-node cause, corrected here without editing it. Persistent outer native-owned mount and no legacy imported wake corrections preserved; original scenario/deadline6/strict close unchanged. Correct page/allowlist to original compiled filename; add all HTML script/style exact package closure and scheme allowlist QA/preflight. Current full build and serial Native134 next; one preview policy, fixed grant, closed curtain and original native closure duties remain. Native1312518/278 baseline and full release/installed/drafts/foreign preserved.'],'progress',[str(m.relative_to(repo)),str(native.relative_to(repo)),str((root/'ANCESTRY.json').relative_to(repo))]))
