"""Prepare positive region and actual rejected curtain-control publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v94/publication';assert not out.exists();out.mkdir(parents=True)
base='6723ef8d72aea0ead4b3434f5fdff1825db93144';local='2e567bce2a3458bef1782e308ab19c1888b0071b';previous='a32af78b824c79f6e77214739dfcc1594a45c04d'
components=[('warlock-client-provider-native-v137',True),('warlock-preview-provider-v127',True),('warlock-client-provider-native-v138',True),('warlock-preview-provider-v128',False),('warlock-client-provider-native-v139',False)];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-curtain-control-report.json').read_text());assert held['passed'] and held['boundedClosedCurtainRegionQualified'] and not held['unsafeVariantAccepted'] and held['positiveNativeChecks']==29 and held['positiveNormalOwnedExits']==13 and held['negativeExposedPixels']==19200 and not held['physicalRevealQualified'] and not held['nativeAcceptance']
prior=r/'docs/warlock-repository/v93/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='76e246bc803755b2a0c15bfac249c147dba5a9fa'","BASE='"+base+"'").replace('2caa20036f23d3da9960a2771764a8d5560b5233..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v93/publication/','docs/warlock-repository/v94/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-curtain-control-report.json').read_text());assert qualification['passed'] and qualification['boundedClosedCurtainRegionQualified'] and qualification['originalNativeOracleUnchanged'] and qualification['positiveNativeChecks']==29 and qualification['positiveNormalOwnedExits']==13 and qualification['positiveSamples']==248976 and qualification['negativeExposedPixels']==19200 and qualification['fullBuildCommands']==119 and not qualification['unsafeVariantAccepted'] and not qualification['normalCloseClaimed'] and not qualification['physicalConcealmentQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Bind native popup paint observations and verify the closed curtain detector\n\nHeld positive GUI127/Native138 passes29 checks/13 normal exits with zero preview pixels in248976 live native region samples. Actual unsafe GUI128/Native139 exposes19200 preview pixels and is rejected by the byte-identical original native oracle. Both full119 builds and exact original deadlines/core16/plugin19/AQ155 preserved.\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-report126.json','component-curtain-control-report.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v127',['PROGRESS PUBLIC94 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. PositiveGUI127/Native13829checks13normalexits/native GTK paint/current geometry/private output region248976opaque samples no previewcolors, pure source reference19200red. Actual intentional unsafeGUI128/Native139 opacity1 exposes19200 previewpixels and byte-identical original native oracle rejects; host1/strict close refusal/privatecleanup/other normal exits retained. Full119/deadline6/core16/plugin19/AQ155 unchanged. Bounded region detector qualified; GTK phase is not compositor/hardware proof and ongoing transition concealment/reveal/stale callbacks/pressure/workload/RSS/recovery/full S09 preview13/release stay open. Next resume safe positiveGUI127 lineage for actual stale async callbacks and physical frame/reveal qualifications. Native13726/12 output observation preserved. Unsafe variant never installed/default accepted; installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-curtain-control-report.json','implementation/warlock-preview-provider-v127/component-manifest.json','implementation/warlock-client-provider-native-v138/component-manifest.json','implementation/warlock-preview-provider-v128/component-manifest.json','implementation/warlock-client-provider-native-v139/component-manifest.json','docs/warlock-repository/v94/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('76e246bc803755b2a0c15bfac249c147dba5a9fa',base).replace('Record public pure renderer pixel qualification','Record public native curtain detector qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit126.py').read_text().replace('c1ef4a20a938a62bf771070e49cbd42747005f56',local).replace('warlock-repository/v93/publication','warlock-repository/v94/publication').replace('Qualify pure WebKit preview pixels through the original native URI','Bind native popup paint observations and verify the closed curtain detector')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
p=r/'docs/warlock-preview/v93/commit127.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
