"""Prepare exact inactive frontend confirmation/close barrier publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=repo/'docs/warlock-repository/v68/publication';assert not out.exists();out.mkdir(parents=True)
base='f6b9ef964d1551178fb3c21693da957feb44d0d7'
proof=json.loads((repo/'docs/warlock-preview/v93/component-report96.json').read_text());assert proof['passed'] and proof['confirmationNativeControls']==58 and proof['outboxConfirmationStates']==404
minimum=len(json.loads((repo/'implementation/warlock-preview-provider-v96/component-manifest.json').read_text())['files'])
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(repo/'docs/warlock-repository/v67/publication/publish.py').read_text().replace("BASE='d67896fdde83540561f5097b22c59f19010e39f8'","BASE='"+base+"'").replace('20bd7a8d5229d26afaaa56f190e94967017b4a65..','579a0fdd3d8c7d71518dc31c6ccece83c36d0d37..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v67/publication/','docs/warlock-repository/v68/publication/','implementation/warlock-preview-provider-v96/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Keep native transport open until the frontend confirms final delivery receipts\n\nHeld GUI96 adds an inactive native original-frontend receipt confirmation prefix and separate prefix-confirmed close predicate. Frontend retries keep a bounded compact confirmation, including with an empty data queue; old receipts cannot recreate packets or rewind confirmation. Actual C20 selected Quint scenarios/28 coupled traces/221 states/four compiled mutants and actual JS13 selected scenarios/25 traces/404 states/three syntax-checked variants pass. Actual compiled native metadata/JS58 controls validate lost receipts and confirmations, receipt rebroadcast without another Unknown invocation, cumulative/old confirmation, failed posting, future/foreign refusal, reopened barrier, callback reentrancy and normal owned close. Activated production modules remain byte-identical; no WebKit activation or current host/native runtime acceptance is claimed. Prefix confirmation is separate from native effect success, terminal proof and physical/actor retirement. Next derive and reserve actual worst-case cleanup queue/ordinal capacity before native admission, reconcile receiver replacement, and activate actual WebKit outgoing and retirement routing together. Fully qualified GUI92/native128/core16/plugin18 and all original GUI release gates remain unchanged.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report96.json').read_text());assert qualification['passed'] and qualification['nativeConfirmationScenarios']==20 and qualification['nativeConfirmationTraces']==28 and qualification['nativeConfirmationStates']==221 and qualification['unsafeCompiledNativeVariantsDetected']==4 and qualification['outboxConfirmationScenarios']==13 and qualification['outboxConfirmationTraces']==25 and qualification['outboxConfirmationStates']==404 and qualification['unsafeActualJSVariantsDetected']==3 and qualification['confirmationNativeControls']==58 and qualification['unchangedActivatedProductionModulesVerified'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:]
put('publish.py',s)
s=(repo/'docs/warlock-repository/v67/publication/record_delivery.py').read_text().replace('warlock-repository/v67','warlock-repository/v68').replace('component-report95.json','component-report96.json').replace("d['ownedFiles']>=777","d['ownedFiles']>="+str(minimum))
start=s.index('e=loop.write_checkpoint(')
s=s[:start]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v96',['PROGRESS PUBLIC68 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI96 inactive confirmation closebarrier native20selected/28traces/221states/4compiled variants,JS13selected/25traces/404states/3variants,58actualMetadata+JS loss/retry/Unknown/cumulative/foreign/normalclose controls. Activatedproduction unchanged, fullqualifiedGUI92/native128 unchanged. Next actual worst-case cleanup queue/ordinal reservation before native admission, fresh-grant reconciliation and actual WebKit activation. All original release gates remain.'],'progress',['docs/warlock-preview/v93/component-report96.json','implementation/warlock-preview-provider-v96/component-manifest.json','docs/warlock-repository/v68/publication/delivery.json']);print(e)\n"
put('record_delivery.py',s)
s=(repo/'docs/warlock-repository/v67/publication/commit_receipt.py').read_text().replace('d67896fdde83540561f5097b22c59f19010e39f8',base).replace('Record public bounded outgoing control primitive qualification','Record public frontend receipt confirmation qualification').replace("d['ownedFiles']>=777","d['ownedFiles']>="+str(minimum))
put('commit_receipt.py',s)
s=(repo/'docs/warlock-preview/v93/commit95.py').read_text().replace('a324243c1bcf2b8dfec2c780270905e41d23ae09','9c6804a5c2b462dda63d2fa6d0844afced3d2acd').replace("[('warlock-preview-provider-v95',True)]","[('warlock-preview-provider-v96',True)]").replace('warlock-repository/v67/publication','warlock-repository/v68/publication')
s=s.replace('Qualify bounded outgoing control retry primitives without effect replay','Preserve native transport until original frontend receipt confirmation')
ast.parse(s);(repo/'docs/warlock-preview/v93/commit96.py').write_text(s);print(out)
