"""Fresh QA-only real snapshot completion spanning strictly closed old realm."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=r/'implementation/warlock-preview-provider-v134';root=r/'implementation/warlock-preview-provider-v135';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();m=parent/'component-manifest.json';d=json.loads(m.read_text());assert d['sourceHeld'] and d['passed'] and d['actualRapidPointerCloseReopenQualified'] and not root.exists()
for n,row in d['files'].items():assert sha(parent/n)==row['sha256'],n

def ignore(path,names):
 if pathlib.Path(path)==parent:return [n for n in names if n in {'component-manifest.json','ANCESTRY.json','__pycache__'}]
 if pathlib.Path(path)==parent/'qa':return [n for n in names if (pathlib.Path(path)/n).is_dir() and n!='toolchain']
 return [n for n in names if n in {'__pycache__','elm-stuff'}]
shutil.copytree(parent,root,ignore=ignore)
p=root/'native/shared-host.c';s=p.read_text();needle='static gboolean qa_controlled_delayed_snapshot;';assert s.count(needle)==1;s=s.replace(needle,needle+'\nstatic gboolean qa_controlled_reopened_snapshot;')
needle='        else if (g_str_equal(argv[i],"--qa-preview-delayed-snapshot")) qa_controlled_delayed_snapshot=TRUE;';assert s.count(needle)==1;s=s.replace(needle,needle+'\n        else if (g_str_equal(argv[i],"--qa-preview-reopened-snapshot")) {qa_controlled_delayed_snapshot=TRUE;qa_controlled_reopened_snapshot=TRUE;}');p.write_text(s)
p=root/'native/controlled-preview-host.h';s=p.read_text();needle='    controlled_delayed_snapshot=NULL;\n    client_snapshot_complete(row->view,row->result,row->snapshot);';assert s.count(needle)==1;s=s.replace(needle,'    controlled_delayed_snapshot=NULL;\n    if(qa_controlled_reopened_snapshot) {\n        g_print("controlled-native-snapshot-crossed-realm: retainedEpoch=%" G_GUINT64_FORMAT " currentEpoch=%" G_GUINT64_FORMAT " retainedNavigation=%" G_GUINT64_FORMAT " currentNavigation=%" G_GUINT64_FORMAT " replacedView=%d originalResult=1 originalFinishCalls=0 nativeSettlement=0\\n",row->snapshot->controlled_epoch,controlled_epoch,row->snapshot->controlled_navigation,controlled_navigation,row->view!=G_OBJECT(popup_view));fflush(stdout);\n    }\n    client_snapshot_complete(row->view,row->result,row->snapshot);')
needle='    if(!surface_popup_ready())controlled_release_snapshot();';assert s.count(needle)==1;s=s.replace(needle,'    if(!surface_popup_ready() && !qa_controlled_reopened_snapshot)controlled_release_snapshot();')
needle='static gboolean controlled_retire_current(GError **error) {';a=s.index(needle);b=s.index('static gboolean controlled_tick(',a);part=s[a:b];needle='    controlled_curtain();controlled_paint_cancel();controlled_release_snapshot();';assert part.count(needle)==1;part=part.replace(needle,'    controlled_curtain();controlled_paint_cancel();\n    if(!qa_controlled_reopened_snapshot)controlled_release_snapshot();');s=s[:a]+part+s[b:]
needle='        controlled_paint_request();\n    }\n    g_clear_error(&error);return TRUE;';assert s.count(needle)==1;s=s.replace(needle,'        controlled_paint_request();\n        /* Explicit QA only: consume the original retained result once after a\n         * later original realm/view receives its own current native projection.\n         * Original finish/scope rejection owns the old result; no native fact,\n         * grant, effect or physical settlement is supplied by this stimulus. */\n        if(qa_controlled_reopened_snapshot && controlled_delayed_snapshot &&\n           controlled_delayed_snapshot->snapshot->controlled_epoch<controlled_epoch &&\n           controlled_delayed_snapshot->view!=G_OBJECT(popup_view))controlled_release_snapshot();\n    }\n    g_clear_error(&error);return TRUE;');p.write_text(s)
(root/'ANCESTRY.json').write_text(json.dumps({'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(m),'scope':'Fresh GUI135 disabled-by-default QA stimulus retains one actual original WebKit GAsyncResult/strong old view across original popup closure, strict C/Bootstrap close, renderer replacement and later same-policy native epoch. It finishes once only after current new-view native projection acknowledgement; original scope guard must reject old pixels, while current new image/snapshot and strict normal teardown continue. Original completion guard, Native policy/issuer/physical product/readers/custody/deadlines/sticky producer fix unchanged. Original normal/delayed/rapid controls remain separate. No grant/navigation/request reset, no fabricated completion, installed/drafts/foreign preserved.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(root.relative_to(r)),['PROGRESS ownGUI135 real original snapshot result across strict old realm close/fresh renderer and later same-policy/native epoch; disabled-by-default QA flag only defers the one actual original completion until new current native projection receipt. Original finish/current epoch navigation view projection rejection retained, zero Native facts/effects/grant resets. Full119 then actual old-result rejection/new current source URI/red pixels/ordinal2/closed output/normal teardown and unchanged normal/delayed/rapid regressions; original6s source/ABI/physical/journal/confirmation gates stay. Full release/reload/Unknown/ongoing physical reveal/resource remain open.'],'progress',[str((root/'ANCESTRY.json').relative_to(r))]))
