"""Prepare publication of held readonly visual custody with exact owner paths."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v87/publication';assert not out.exists();out.mkdir(parents=True)
base='99c357235f940af304314501ce76efe76cbd91c5';local='c226d97a29289e6edccbe784ab9591eee02bd31f';previous='356ebb9de9a5c203f67c4fd40b614ecd22d39c76'
proof=json.loads((r/'docs/warlock-preview/v93/component-report118.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['readonlyVisualCPUQualified'] and proof['readonlyProjectionChecks']==74
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v118/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v86/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='c026b4b106dc0c4e62b9aecdc853d5bf81931707'","BASE='"+base+"'").replace('2fcb2afdbd87a3d0cfba5b09233eb47e94e76091..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v86/publication/','docs/warlock-repository/v87/publication/','implementation/warlock-preview-provider-v118/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report118.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['singlePreviewPolicy'] and qualification['parentElmPolicyUnchanged'] and qualification['parentNativeIssuerAndPhysicalProductUnchanged'] and qualification['parentAssetsAndAdaptersUnchanged'] and qualification['nativeOwnedJavaScriptCore'] and qualification['persistentPolicyContexts']==1 and qualification['nativeElmOutboxChecks']==207 and qualification['additiveVisualProjectionChecks']==90 and qualification['readonlyProjectionChecks']==74 and qualification['lifetimeBoundaryChecks']==37 and qualification['readonlyBoundaryChecks']==15 and qualification['constructorFaults']==13 and qualification['backpressureChecks']==48 and qualification['backpressureReadonlyChecks']==28 and qualification['backpressureFactsSynthetic'] and qualification['lifetimeScenarios']==14 and qualification['lifetimeTraces']==26 and qualification['lifetimeStates']==430 and qualification['lifetimeCompiledNativeVariantsDetected']==5 and qualification['fullBuildCommands']==112 and qualification['originalBuildCommands']==112 and qualification['heldFailedReports']==[] and qualification['readonlyVisualCPUQualified'] and not qualification['realHostPolicyActivated'] and not qualification['actualRendererProjectionActivated'] and not qualification['actualDOMQualified'] and not qualification['projectionDeliveryOrderingQualified'] and not qualification['realHostInputBackpressureQualified'] and not qualification['nativeDelayedProposalLivenessQualified'] and not qualification['uncertainLiveWorkerRecoveryQualified'] and not qualification['fullElmRecoveryQualified'] and not qualification['typedHostRoutingActivated'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Copy committed visual data from the native-owned Elm policy\n\n'+proof['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v86','warlock-repository/v87').replace('component-report117.json','component-report118.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v118',['PROGRESS PUBLIC87 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI118 readonly visual custody with parent Elm policy/native issuer/effects/physical unchanged. Original C/JSC/native207 plus90 visual/74 readonly/two epochs/unchanged grant/normal; lifetime37+15/13 pre-grant faults/Quint14/26 actual C+JSC traces/430 states/200 samples/five compiled guards; backpressure48+28 explicitly synthetic facts; full112 retains112. Getter invokes no JS/model/effect/ordinal, copies survive caller mutation, original ordinary input block and refuse missing/foreign/absent/closed/unknown/inflight authority. Next authenticated ordered native current-projection channel/renderer lease/reload concealment and durable original host input/native-ticket custody/retry before actual WebKit/Core. Copies alone provide no freshness/order/DOM/URI/physical/recovery/full release proof. Native130 legacy2518/278 remains actual bounded baseline; installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/component-report118.json','implementation/warlock-preview-provider-v118/component-manifest.json','docs/warlock-repository/v87/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('c026b4b106dc0c4e62b9aecdc853d5bf81931707',base).replace('Record public shared visual projection qualification','Record public readonly visual custody qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit117.py').read_text().replace('81205931d581c2ba5e4e9f4dfc4f6efb11fbe339',local).replace("[('warlock-preview-provider-v117',True)]","[('warlock-preview-provider-v118',True)]").replace('warlock-repository/v86/publication','warlock-repository/v87/publication').replace('Share typed visual projections with the original single Elm preview policy','Copy committed visual data from the native-owned Elm policy');s=s.replace('exact held GUI81/failed117/passed118','exact held GUI118 readonly visual custody')
p=r/'docs/warlock-preview/v93/commit118.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
