"""Prepare exact held single Elm realm policy publication under existing authorization."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v84/publication';assert not out.exists();out.mkdir(parents=True)
base='16d4f7dc97ddb9934341bb60eac1decd74b895e4';local='3527bb5dca16bfa997b3e2d1007baade1cae85bf';previous='8776582022f14f9c633d6219211a6f434d3e1eae'
proof=json.loads((r/'docs/warlock-preview/v93/component-report115.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeElmOutboxChecks']==206 and proof['ingressStates']==468
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v115/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v83/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='0670a4500e3b668285b43e163adda958d1996f82'","BASE='"+base+"'").replace('d7ff0259f7a6bf3783ee44d45d48966ce604e0ba..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v83/publication/','docs/warlock-repository/v84/publication/','implementation/warlock-preview-provider-v115/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report115.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['singlePreviewPolicy'] and qualification['nativeElmOutboxChecks']==206 and qualification['boundaryChecks']==98 and qualification['ingressScenarios']==16 and qualification['ingressTraces']==28 and qualification['ingressStates']==468 and qualification['ingressCompiledVariantsDetected']==6 and qualification['urgentScenarios']==6 and qualification['urgentTraces']==18 and qualification['urgentStates']==406 and qualification['urgentCompiledVariantsDetected']==2 and qualification['coldCohortChecks']==3608 and qualification['legacyRetirementChecks']==45 and qualification['legacyNativeRoundtripChecks']==20 and qualification['legacyCChecks']==34 and qualification['fullBuildCommands']==108 and qualification['originalBuildCommands']==104 and len(qualification['heldFailedReports'])==6 and qualification['proposalRetentionCPUQualified'] and not qualification['realHostInputBackpressureQualified'] and not qualification['nativeDelayedProposalLivenessQualified'] and not qualification['popupTypedPortsWebKitExecuted'] and not qualification['fullElmRecoveryQualified'] and not qualification['typedHostRoutingActivated'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Retain original Elm proposals and revoke quarantined demand during backpressure\n\n'+proof['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v83','warlock-repository/v84').replace('component-report114.json','component-report115.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v115',['PROGRESS PUBLIC84 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI115 immutable retained intents/single unchanged window policy/urgent quarantine under blocked input: boundaries98/native C+Elm206/two epochs/unchanged Native grant/normal exits; ingress Quint16/28/468/six compiled variants; urgent6/18/406/two variants; cold256/3608 retains original1549 with synthetic ticket facts; wrapper legacy45/native20+C34; full108 retains104 and earlier106. Six failed attempts and original phase evidence held. Native/assets/adapters unchanged114; Popup typed ports compiled only. Next actual host input backpressure/issued facts/ticket custody/retry/persistent Elm policy lifetime and WebKit/Core activation, with delayed expiry/revocation outcome/order liveness qualification. All original release gates remain; Native130 legacy2518/278/full cleanup remains actual baseline; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report115.json','implementation/warlock-preview-provider-v115/component-manifest.json','docs/warlock-repository/v84/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('0670a4500e3b668285b43e163adda958d1996f82',base).replace('Record public native proposal ingress qualification','Record public retained Elm proposal qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit114.py').read_text().replace('a470c667232b0e4a6b9044e79bf3a4647e003e42',local).replace("[('warlock-preview-provider-v114',True)]","[('warlock-preview-provider-v115',True)]").replace('warlock-repository/v83/publication','warlock-repository/v84/publication').replace('Validate native proposal ingress and compile typed Popup realm ports','Retain original Elm proposals and revoke quarantined demand during backpressure')
p=r/'docs/warlock-preview/v93/commit115.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
