"""Prepare real known-preview retirement with lost window receipt and Restart.

Retain qualified199 window recovery assertions and original controlled-reader
stimuli. The fresh supervisor changes only protected QA launch options.
"""
import ast,hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-client-provider-native-v199';root=repo/'implementation/warlock-client-provider-native-v202'
old_sup=repo/'implementation/warlock-window-restart-supervisor-v1';sup=repo/'implementation/warlock-window-restart-supervisor-v2'
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
held=json.loads((parent/'component-manifest.json').read_text());assert held['passed'] and held['sourceHeld'] and held['actualWindowCommandRestartQualified']
for rel,row in held['files'].items():assert sha(parent/rel)==row['sha256'],rel
pre=json.loads((parent/'qa/preflight.json').read_text())
for path,h in pre['inputs'].items():assert sha(path)==h,path
assert not root.exists() and not sup.exists();root.mkdir(mode=0o700);(root/'qa').mkdir(mode=0o700);sup.mkdir(mode=0o700)
for base,target in [(parent,root),(parent/'qa',root/'qa')]:
 for p in base.iterdir():
  if p.is_file() and p.name not in {'preflight.json','ANCESTRY.json','component-manifest.json'}:shutil.copy2(p,target/p.name)
for name in ['supervisor.py','cohort.py']:shutil.copy2(old_sup/name,sup/name)
p=sup/'supervisor.py';source=p.read_text()
def sup_replace(old,new):
 global source
 assert source.count(old)==1,old;source=source.replace(old,new)
sup_replace('import signal\n','import signal\nimport resource\n')
sup_replace('def run(manifest_path, authority_path, qa=False, qa_log_directory=None):','def run(manifest_path, authority_path, qa=False, qa_log_directory=None, qa_preview_subject=None):')
sup_replace('        while not stopping:\n',"        if qa_preview_subject is not None:\n            if not qa or log_directory is None or resource.getrlimit(resource.RLIMIT_CORE)!=(1,1) or type(qa_preview_subject) is not str or not qa_preview_subject.isascii() or not qa_preview_subject.isdigit() or qa_preview_subject.startswith('0') or not 0<int(qa_preview_subject)<=18446744073709551615:\n                raise ValueError('Controlled preview needs exact protected QA subject and log directory')\n            import sys\n            sys.path.insert(0,'/home/hoskinson/window-integration-qa')\n            from qa_launch import require_qa_scope\n            require_qa_scope()\n        while not stopping:\n")
sup_replace('            generation += 1\n',"            generation += 1\n            if qa_preview_subject is not None:\n                reader=log_directory/('controlled-reader-generation-'+str(generation))\n                fd=os.open(reader,os.O_WRONLY|os.O_CREAT|os.O_EXCL|os.O_NOFOLLOW,0o600)\n                with os.fdopen(fd,'wb') as stream:stream.write(b'hold\\n');stream.flush();os.fsync(stream.fileno())\n                snapshot=log_directory/('controlled-webkit-generation-'+str(generation)+'.png')\n                command += ['--qa-preview-controlled',qa_preview_subject,'--qa-preview-snapshot',str(snapshot),'--qa-controlled-preview-reader',str(reader)]\n")
sup_replace('    args = parser.parse_args()\n',"    parser.add_argument('--qa-preview-subject')\n    args = parser.parse_args()\n")
sup_replace('return run(args.manifest, args.authority_config, args.qa, args.qa_log_directory)','return run(args.manifest, args.authority_config, args.qa, args.qa_log_directory, args.qa_preview_subject)')
ast.parse(source);p.write_text(source)
p=sup/'cohort.py';source=p.read_text()
for old,new in [('    stopping = False\n',"    if args.qa_preview_subject is not None:\n        if not args.qa or not args.qa_log_directory:raise ValueError('Controlled preview subject requires QA')\n        command += ['--qa-preview-subject',args.qa_preview_subject]\n    stopping = False\n"),('    args = parser.parse_args()\n',"    parser.add_argument('--qa-preview-subject')\n    args = parser.parse_args()\n")]:
 assert source.count(old)==1;source=source.replace(old,new)
ast.parse(source);p.write_text(source)
runtime=json.loads((old_sup/'runtime-manifest.json').read_text());runtime['scope']='Current GUI143 controlled-preview reader retirement plus main-window command recovery; protected QA options only, no release acceptance'
runtime['files']={n:h for n,h in runtime['files'].items() if pathlib.Path(n).parent!=old_sup}
for name in ['supervisor.py','cohort.py']:runtime['files'][str(sup/name)]=sha(sup/name)
(sup/'runtime-manifest.json').write_text(json.dumps(runtime,indent=2)+'\n')
observer=pathlib.Path(__file__).with_name('combined_preview_observer.py');ast.parse(observer.read_text());shutil.copy2(observer,root/'qa/combined_preview_observer.py')
p=root/'qa/native-window-restart.py';source=p.read_text()
def replace(old,new):
 global source
 assert source.count(old)==1,old;source=source.replace(old,new)
replace("SUP=REPO/'implementation/warlock-window-restart-supervisor-v1'","SUP=REPO/'implementation/warlock-window-restart-supervisor-v2'")
replace("result=subprocess.CompletedProcess(command,proc.returncode,'','')","result=subprocess.CompletedProcess(command,proc.returncode,(OUTPUT/(name+'.log')).read_text(errors='replace'),'')")
replace("   supervisor=s.host.launch('elm-supervisor'", "   preview_fixtures=[]\n   for name in ['source','companion']:\n    process=s.host.launch('combined-'+name,[pre['fixtureClient']],env=dict(env,WARLOCK_CHILD_CONTROL_PATH=str(OUTPUT/(name+'-control'))));apps.append(process);preview_fixtures.append((name,process))\n    wait(lambda:len(s.data('clients'))==1+len(preview_fixtures))\n   for window in s.data('clients'):\n    target_selector='address:'+window['address']\n    if not window['floating']:check('combinedFixtureActuallyFloating-'+window['title'],s.ctl('dispatch',\"hl.dsp.window.float({action='set',window='\"+target_selector+\"'})\").strip()=='ok')\n    check('combinedFixtureActualSize-'+window['title'],s.ctl('dispatch',\"hl.dsp.window.resize({x=320,y=240,window='\"+target_selector+\"'})\").strip()=='ok')\n    x,y=(40,80) if window['title']=='ELM-AUTHORITY-FIXTURE' else (420,300)\n    check('combinedFixtureNonoverlappingRegion-'+window['title'],s.ctl('dispatch',\"hl.dsp.window.move({x=\"+str(x)+\",y=\"+str(y)+\",window='\"+target_selector+\"'})\").strip()=='ok')\n   actual_fixture=next(w for w in s.data('clients') if w['title']=='ELM-AUTHORITY-FIXTURE')\n   check('combinedRealFixtureFocusBeforeCommand',s.ctl('dispatch',\"hl.dsp.focus({window='address:\"+actual_fixture['address']+\"'})\").strip()=='ok')\n   native_scene=client.scene_facts('439')\n   subject=next(w['incarnation'] for w in native_scene['facts']['windows'] if w['application']=='warlock-child-probe')\n   supervisor=s.host.launch('elm-supervisor'")
replace("'--qa-log-directory',str(OUTPUT)],env=dict(env,ELM_WINDOW_RECOVERY_FAULT=", "'--qa-log-directory',str(OUTPUT),'--qa-preview-subject',subject],env=dict(env,ELM_WINDOW_RECOVERY_FAULT=")
replace('   from inspection import Collector','   from combined_preview_observer import BarCollector as Collector,PreviewObserver')
replace("g['label'].startswith(action) and not g['disabled']","g['title']=='ELM-AUTHORITY-FIXTURE' and g['label'].startswith(action) and not g['disabled']")
replace("return p['groups'][0] if p and p['phase']=='Coherent' and len(p['groups'])==1 and not p['groups'][0]['disabled'] else None","return next((g for g in p['groups'] if g['title']=='ELM-AUTHORITY-FIXTURE' and not g['disabled']),None) if p and p['phase']=='Coherent' else None")
replace("len(initial_facts['facts']['windows'])==1 and not initial_facts['facts']['windows'][0]['minimized']", "len(initial_facts['facts']['windows'])==3 and not next(w for w in initial_facts['facts']['windows'] if w['application']=='GTK Application')['minimized']")
replace("target=initial_facts['facts']['windows'][0]['incarnation']","target=next(w['incarnation'] for w in initial_facts['facts']['windows'] if w['application']=='GTK Application')")
replace("   attached=next(f for f in reversed(frames('backend-frame: ')) if f['kind']=='attached')", "   preview=PreviewObserver(OUTPUT,pre,lambda:current_log,projection,click,owned_helper,check,wait)\n   first_preview=preview.capture(1);report['originalControlledPreview']=first_preview\n   preview.begin_close(1)\n   attached=next(f for f in reversed(frames('backend-frame: ')) if f['kind']=='attached')")
replace("   s.guard();os.kill(renderer['pid'],signal.SIGKILL)\n   wait(lambda:'native-recovery-ready:' in current_log.read_text())", "   check('combinedWindowPendingAndOriginalPreviewUnretiredAtFailure','controlled-native-realm-retired:' not in preview.text() and 'controlled-native-reader-released:' not in preview.text(),state=preview.states()[-1],admission=record)\n   s.guard();os.kill(renderer['pid'],signal.SIGKILL)\n   retired=preview.release_after_renderer_fault(1);report['originalControlledPreviewStrictClose']=retired\n   report['combinedKnownPreviewBeforeRestartQualified']=True\n   wait(lambda:'native-recovery-ready:' in current_log.read_text())")
replace("final_facts['facts']['windows'][0]['incarnation']==target", "any(w['incarnation']==target for w in final_facts['facts']['windows']) and {w['incarnation'] for w in final_facts['facts']['windows']}=={w['incarnation'] for w in initial_facts['facts']['windows']}")
replace("   second_tree=sample_tree(web_pid,web_start);", "   fresh_preview=preview.capture(2);report['freshControlledPreview']=fresh_preview\n   old_scope=first_preview['model']['scope'];new_scope=fresh_preview['model']['scope']\n   check('combinedFreshHostPreviewUsesNewNativeOwnerSameCompositor',old_scope['binding']!=new_scope['binding'] and old_scope['binding']['lifetime']==new_scope['binding']['lifetime'] and old_scope['context']['incarnation']==new_scope['context']['incarnation'] and old_scope['clock']==new_scope['clock'] and first_preview['model']['image']!=fresh_preview['model']['image'] and int(new_scope['now'])>int(old_scope['now']),oldScope=old_scope,newScope=new_scope)\n   preview.begin_close(2);preview.release(2)\n   check('combinedFreshPreviewNativeClosePreservesHistoricalWindowUnknown',historical in json.loads((recovery_dir/'ledger-v6.json').read_text())['releases'])\n   report['combinedControlledPreviewRestartQualified']=True\n   second_tree=sample_tree(web_pid,web_start);")
replace("   temp=control.with_suffix('.tmp');temp.write_text(json.dumps({'op':'quit'}));temp.replace(control);fixture.wait(timeout=5);check('fixtureNormalExit',fixture.returncode==0)", "   for name,process in preview_fixtures:\n    control_file=OUTPUT/(name+'-control');temporary=control_file.with_suffix('.tmp');temporary.write_text('1 quit\\n');temporary.chmod(0o600);temporary.replace(control_file);process.wait(timeout=5);check('combined'+name.title()+'FixtureNormalExit',process.returncode==0)\n   temp=control.with_suffix('.tmp');temp.write_text(json.dumps({'op':'quit'}));temp.replace(control);fixture.wait(timeout=5);check('fixtureNormalExit',fixture.returncode==0)")
replace("report['scope']='Private single-window real minimize/restore interrupted before broker read or after native commit; Unknown/no auto replay, current-state primary action, actual pixels/keyboard and serial cleanup; original restore timing/full release open'", "report['scope']='Current GUI143/core16/plugin19/AQ155 actual controlled-preview reader/known Native duty retained across real window command receipt loss, broker and shared renderer failure. Original reader revocation/close and strict Native empty custody precede original GTK Restart; durable original window Unknown/no replay and fresh explicit advanced command survive same-compositor fresh host. Fresh own native preview namespace captures same source pixels and strictly closes while preserving historical window Unknown. Original deadlines; no production/installed changes. Actual uncertain preview effects, full restore timing/physical/hardware/workload/S09/release remain open.'")
ast.parse(source);p.write_text(source)
inputs=dict(pre['inputs']);inputs[str(parent/'component-manifest.json')]=sha(parent/'component-manifest.json');inputs[str(parent/'qa/preflight.json')]=sha(parent/'qa/preflight.json');inputs[str(pathlib.Path(__file__))]=sha(__file__);inputs[str(observer)]=sha(observer)
for base in [root,root/'qa',sup]:
 for p in base.iterdir():
  if p.is_file():inputs[str(p)]=sha(p)
pre.update(inputs=inputs,scope=runtime['scope'],retainedWindowQualification=str(parent/'component-manifest.json'),combinedPreviewWindowRecoveryPrepared=True)
(root/'qa/preflight.json').write_text(json.dumps(pre,indent=2)+'\n')
(root/'ANCESTRY.json').write_text(json.dumps({'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(parent/'component-manifest.json'),'supervisor':str(sup),'change':'Retain all199 command recovery assertions with unrelated native source/companion fixtures, exact bar-only DOM observer, actual held GIO reader blocking strict preview retirement through broker/shared renderer failure and actual native Restart, then fresh own native capture. QA launch options only; same GUI143119 build/core16/plugin19/AQ155. No fabricated native facts or bypassed Pending policy.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(root.relative_to(repo)),['PROGRESS Native202 combined known-preview/Unknown-window-command/whole-host Restart campaign prepared. Original199 min/lost receipt/no replay/durable historical Unknown/actual pixels/keyboard/normal helper/cohort gates retained, same current GUI143/core16/plugin19/AQ155. Actual native source/companion/pointer/pure-renderer capture plus held original GIO reader must block Native close until monotonic revocation/probe/release after real shared renderer death; strict original policy/physical/journal/ticket/confirmation empty custody before GTK Restart. Fresh host native preview must use new native owner on same compositor/source clock, and close while preserving historical Unknown. Original deadlines. Protected QA-only supervisor options, no production/installed/foreign changes; full release remains open.'],'progress',[str((root/'qa/preflight.json').relative_to(repo)),str((root/'ANCESTRY.json').relative_to(repo))]))
