"""Prepare bounded actual pure-renderer pixels publication over PUBLIC92."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v93/publication';assert not out.exists();out.mkdir(parents=True)
base='76e246bc803755b2a0c15bfac249c147dba5a9fa';local='c1ef4a20a938a62bf771070e49cbd42747005f56';previous='2caa20036f23d3da9960a2771764a8d5560b5233'
components=[('warlock-preview-provider-v126',True),('warlock-client-provider-native-v136',True)];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report126.json').read_text());assert held['passed'] and held['actualCapturedPixelsQualified'] and held['nativeChecks']==21 and held['normalOwnedExits']==10 and not held['physicalRevealQualified'] and not held['nativeAcceptance']
prior=r/'docs/warlock-repository/v92/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='2117a5147b7170ddc9b7cc0d6fe430f8a2698d4f'","BASE='"+base+"'").replace('41abd7627988bf0f98dd692a0a69c82b09a40257..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v92/publication/','docs/warlock-repository/v93/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report126.json').read_text());assert qualification['passed'] and qualification['actualControlledAdmissionAndDrainQualified'] and qualification['normalControlledHostClosureQualified'] and qualification['actualCapturedPixelsQualified'] and qualification['actualScopedURIImageLoadObserved'] and qualification['nativeChecks']==21 and qualification['normalOwnedExits']==10 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and qualification['compiledPageAssetClosureQualified'] and not qualification['actualStaleSnapshotCallbackQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Qualify pure WebKit preview pixels through the original native URI\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-report125.json','component-report126.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v126',['PROGRESS PUBLIC93 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI126/Native136 actual pure WebKit renderer/native scoped URI/320x240 Core client image at160x120 and original independent pixel oracle19200red/zero green and blue with mapped unrelated green peer. Original16 admission/drain checks retained;21checks10normalexits/privatecleanup/full119/originaldeadline6/core16/plugin19/AQ155. Native-current snapshot request and callback guards implemented; actual stale-callback fault qualification remains open. Original Elm policy/native issuer/physical/journal/independent confirmation/strict close unchanged. Physical curtain stays closed; frame/concealment/reveal/workload/RSS/pressure/reload/uncertain recovery/full S09 preview13 and release gates open. Next actual frame/physical concealment and stale async snapshot qualification. Legacy2518/278, failed integrations and125/135 preserved; installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-report126.json','implementation/warlock-preview-provider-v126/component-manifest.json','implementation/warlock-client-provider-native-v136/component-manifest.json','docs/warlock-repository/v93/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('2117a5147b7170ddc9b7cc0d6fe430f8a2698d4f',base).replace('Record public controlled native host qualification','Record public pure renderer pixel qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit125.py').read_text().replace('03a2f8559c538267d227518b71db90cbf27e4abf',local).replace('warlock-repository/v92/publication','warlock-repository/v93/publication').replace('Connect the controlled native Elm policy and qualify strict host teardown','Qualify pure WebKit preview pixels through the original native URI')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
p=r/'docs/warlock-preview/v93/commit126.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
