"""Publish actual known current-failure drain repair and original regressions."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v102/publication';assert not out.exists()
base='608fa06d684f1c2d94a6dec92f937c93ff6c63d0';local='8ddf0df605073f483776585b9cbbd121c9c46102';previous='295769b0c62a30ba124e229a7f54e7040dfae348';oldbase='5ad30ad20254454a534adfa7ae0fee3eb7a3733c'
components=[('warlock-preview-provider-v139',True),*[(f'warlock-client-provider-native-v{v}',True) for v in range(169,175)]];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report-gui139-current-drain.json').read_text());assert held['passed'] and held['gracefulCurrentFailureDrainQualified'] and held['currentFailureNativeControls']==22 and held['fullBuildCommands']==119
out.mkdir(parents=True);prior=r/'docs/warlock-repository/v101/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('dd836cb2b40daf793b41a5a6cd9f76253c69c911..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v101/publication/','docs/warlock-repository/v102/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report-gui139-current-drain.json').read_text());assert qualification['passed'] and qualification['actualCurrentMatchingErrorNativeQualified'] and qualification['actualCurrentFailureNativeCustodyDrained'] and qualification['gracefulCurrentFailureDrainQualified'] and qualification['currentFailureNativeControls']==22 and qualification['currentFailureExpectedExitCode']==1 and qualification['currentFailureOtherNormalOwnedExits']==7 and not qualification['currentFailureGLibCriticalsObserved'] and qualification['actualCancelledOldResultQualified'] and qualification['cancelledOldResultNativeChecks']==36 and qualification['cancelledOldResultNormalOwnedExits']==13 and qualification['successfulOldResultNativeChecks']==35 and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['rapidPendingReaderNativeChecks']==51 and qualification['rapidPendingReaderNormalOwnedExits']==17 and qualification['delayedResultNativeChecks']==18 and qualification['delayedResultNormalOwnedExits']==8 and qualification['currentFailureDrainQuintScenarios']==8 and qualification['currentFailureDrainInvariantSamples']==200 and qualification['currentFailureDrainCoupledStages']==5 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['uncertainCurrentFailureDrainQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Drain original native duties before exiting a failed renderer\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text();a=s.index('report=json.loads(');b=s.index('\nsys.path.insert',a);s=s[:a]+"report=json.loads((r/'docs/warlock-preview/v93/component-report-gui139-current-drain.json').read_text());assert report['passed'] and report['gracefulCurrentFailureDrainQualified'] and not report['uncertainCurrentFailureDrainQualified']"+s[b:]
s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v139',['PROGRESS PUBLIC102 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. '+report['scope']+' Next real uncertain/process/reload recovery and original-clock pressure/expiry, ongoing physical frame/reveal/full release gates; goal remains active.'],'progress',['docs/warlock-preview/v93/component-report-gui139-current-drain.json','implementation/warlock-preview-provider-v139/component-manifest.json','implementation/warlock-client-provider-native-v169/component-manifest.json','docs/warlock-repository/v102/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record current failure and native drain counterexample publication','Record public current renderer native drain repair');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui138_current_failure.py').read_text().replace('f7cc7be0173f8f6ef3fb07c3e3be6fddc966d518',local).replace('Qualify current snapshot failure and retain native drain counterexample','Drain original native duties before exiting a failed renderer')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v102/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui139_current_failure_drain.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
