"""Prepare owned reservation/admission/controlled cleanup publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v69/publication';assert not out.exists();out.mkdir(parents=True)
base='3a185885ae0ef3c1f3d45cc6c7508e77441f30d1';local='0d26d7bf63411aed795ab434b45376868b2e2e23'
proof=json.loads((r/'docs/warlock-preview/v93/component-report99.json').read_text());assert proof['passed'] and proof['compiledElmNativeQuotaControls']==69 and proof['unchangedLegacyDecoderControls']==44
minimum=sum(len(json.loads((r/('implementation/warlock-preview-provider-v'+str(n))/'component-manifest.json').read_text())['files']) for n in [97,98,99])
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(r/'docs/warlock-repository/v68/publication/publish.py').read_text().replace("BASE='f6b9ef964d1551178fb3c21693da957feb44d0d7'","BASE='"+base+"'").replace('579a0fdd3d8c7d71518dc31c6ccece83c36d0d37..','1a54b79945a5be37a1096aecd1bddecc0e4f2457..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v68/publication/','docs/warlock-repository/v69/publication/','implementation/warlock-preview-provider-v97/','implementation/warlock-preview-provider-v98/','implementation/warlock-preview-provider-v99/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Reserve original native cleanup credits before job issuance\n\nAdd inactive native reservation/ticket bookkeeping, original receiver enrollment before subjects, and guarded original Coordinator/Broker issuance. Exact retries keep native-assigned ordinals; capacity/exhaustion protects reserved cleanup, and post-issuance exceptions retain Unknown obligations. GUI97 passes11 selected Quint scenarios/23 compiled traces/397 comparisons/four compiled variants and64 adversarial controls. GUI98 admission passes13/21/189/four variants while its separately held actual Elm/native/URI counterexample exposes late Offer Release rejection by the legacy decoder. GUI99 adds a separate retained-path validator against actual native readiness and exact original job/token; original strict decoder and44 fixed regression controls remain unchanged. Its14 selected scenarios/22 compiled traces/174 comparisons/four variants and69 actual optimized Elm/native Broker/real URI/control bank controls pass late Offer cleanup, two terminal proofs and25 repeated ACKs without another ordinal/effect. Synthetic observation and fixture bytes do not establish capture, WebKit, actual actor retirement or host close. Actor/reconciliation credits remain retained. Helpers remain inactive pending actual controlled provider admission/ticket/physical-barrier/reconciliation/renderer integration and WebKit activation. Full qualified GUI92/native128/core16/plugin18 and all original release gates remain unchanged.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report99.json').read_text());assert qualification['passed'] and qualification['retainedDecoderScenarios']==14 and qualification['retainedDecoderTraces']==22 and qualification['retainedDecoderStates']==174 and qualification['unsafeCompiledNativeVariantsDetected']==4 and qualification['compiledElmNativeQuotaControls']==69 and qualification['unchangedLegacyDecoderControls']==44 and qualification['inheritedAdmissionGuardPassed'] and qualification['legacyDecoderAndRegressionSourceUnchanged'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:];put('publish.py',s)
s=(r/'docs/warlock-repository/v68/publication/record_delivery.py').read_text().replace('warlock-repository/v68','warlock-repository/v69').replace('component-report96.json','component-report99.json').replace("d['ownedFiles']>=833","d['ownedFiles']>="+str(minimum))
start=s.index('e=loop.write_checkpoint(');s=s[:start]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v99',['PROGRESS PUBLIC69 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held97 native reservations11/23/397/four +64controls; held98 admission13/21/189/four and retainedlateOffer counterexample; held99 controlled decoder14/22/174/four +44unchangedlegacycontrols +69compiledElm/NativeBroker/realURI/Nativebank controls,25ACKretries no neweffect. Syntheticfacts/fixturebytes only; no WebKit/capture/actor-hostclose/native-release claim. Next actualcontrolledprovider admission/tickets/physical release/reconciliation/outbox integration. FullqualifiedGUI92/native128 originalgatesunchanged.'],'progress',['docs/warlock-preview/v93/component-report99.json','implementation/warlock-preview-provider-v99/component-manifest.json','docs/warlock-repository/v69/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(r/'docs/warlock-repository/v68/publication/commit_receipt.py').read_text().replace('f6b9ef964d1551178fb3c21693da957feb44d0d7',base).replace('Record public frontend receipt confirmation qualification','Record public native cleanup reservation and controlled decoder qualification').replace("d['ownedFiles']>=833","d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit96.py').read_text().replace('9c6804a5c2b462dda63d2fa6d0844afced3d2acd',local).replace("[('warlock-preview-provider-v96',True)]","[('warlock-preview-provider-v97',True),('warlock-preview-provider-v98',False),('warlock-preview-provider-v99',True)]").replace('warlock-repository/v68/publication','warlock-repository/v69/publication').replace('Preserve native transport until original frontend receipt confirmation','Reserve native cleanup capacity before original job issuance');ast.parse(s);(r/'docs/warlock-preview/v93/commit99.py').write_text(s)
print(out)
