"""Prepare exact owned original capture-intent and resource-reconciliation publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v72/publication';assert not out.exists();out.mkdir(parents=True)
base='359f68251029daf00f15fa2a927614ff5bc5401e';local='c6c8be67921938947fe106ced58d6b8bf0f8ba8f';previous='f2ffafa0b0514d7542541d1aa11d54113d56a169'
proof=json.loads((r/'docs/warlock-preview/v93/component-report105.json').read_text());assert proof['passed'] and proof['resourceCChecks']==477 and proof['resourceCCompiledVariants']==4 and proof['resourceStates']==349 and proof['fullBuildCommands']==95
names=['warlock-preview-provider-v104','warlock-preview-provider-v105','warlock-family-style-crop-capture-v19']
minimum=sum(len(json.loads((r/'implementation'/n/'component-manifest.json').read_text())['files']) for n in names)
prior=r/'docs/warlock-repository/v71/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='dd58cba2cb3d908d87fd5e7cbbc115f58fb59b27'","BASE='"+base+"'").replace('3115c879300ec66f8a1ffb8ceda2217b5eaccca6..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v71/publication/','docs/warlock-repository/v72/publication/',*[('implementation/'+n+'/') for n in names],'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
message='Retain original capture intent and reconcile scoped native resources\n\nPreserve original native request/context/binding/command/deadline and mapping custody across adoption exceptions. Scoped native resource observation and idempotent export/producer cleanup retain lock barriers and recover lost replies without acquisition replay or erasing another capture. Complete native response allocation precedes mutation. Family reconciliation shares one native-issued reserved binding ticket, dispatched only under the actual receiver and borrowed receipt Endpoint; fair polling quarantines new admission and re-observes original resources. Backend zero remains independent of local FD/mapping/readers, terminal proofs, incarnation facts, final processing and control confirmation. CPU evidence:477 C/socket checks in six cases,35 decoder checks,four compiled variants;21 resource-engine checks/two sealed export descriptors/three variants;14 resource scenarios/22 compiled traces/349 states/three variants;original capture14/66/816/three and controlled C10190/260 metadata actors/1041 native tickets;95 full-host commands. Plugin19 compiles on exact core16 ABI and symbol closure. Preserve failures and parent evidence. Actual Core registry/capture pixels/scoped FD/adopted mapping reconciliation, live-window binding detachment, renderer native tickets, WebKit and full release remain open. Qualified runtime GUI92/native128/core16/plugin18 is unchanged.\n'
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report105.json').read_text());assert qualification['passed'] and qualification['resourceCChecks']==477 and qualification['resourceCases']==6 and qualification['resourceDecoderChecks']==35 and qualification['resourceCCompiledVariants']==4 and qualification['resourceScenarios']==14 and qualification['resourceTraces']==22 and qualification['resourceStates']==349 and qualification['resourceCompiledVariants']==3 and qualification['captureTraces']==66 and qualification['captureStates']==816 and qualification['controlledCChecks']==10190 and qualification['fullBuildCommands']==95 and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v71','warlock-repository/v72').replace('component-report103.json','component-report105.json').replace("d['ownedFiles']>=17064","d['ownedFiles']>="+str(minimum))
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v105',['PROGRESS PUBLIC72 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held104 capture intent/adoption and held105/plugin19 scoped resource/C recovery477+35/four variants,14/22/349/three resource model,original capture14/66/816/three,controlled C10190/260/1041,95 full host and core16/plugin19 compile. Actual adopted-FD/readers reconciliation, native Core registry/capture, live-window binding detachment and renderer native tickets/WebKit remain open. RuntimeGUI92/native128/core16/plugin18 and original gates unchanged.'],'progress',['docs/warlock-preview/v93/component-report105.json','implementation/warlock-preview-provider-v105/component-manifest.json','docs/warlock-repository/v72/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('dd58cba2cb3d908d87fd5e7cbbc115f58fb59b27',base).replace('Record public actor quota and controlled native C qualification','Record public original capture resource reconciliation').replace("d['ownedFiles']>=17064","d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit103.py').read_text().replace('81812346adeadf464aae26259a8ae1bf413741c9',local)
s=s.replace("[('warlock-preview-provider-v102',True),('warlock-preview-provider-v103',True)]","[('warlock-preview-provider-v104',True),('warlock-preview-provider-v105',True),('warlock-family-style-crop-capture-v19',True)]").replace('warlock-repository/v71/publication','warlock-repository/v72/publication').replace('Guard actor quotas and expose original native control tickets through C','Retain original capture intent and reconcile scoped native resources')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit105.py';assert not p.exists();p.write_text(s)
print(out)
