"""Prepare owned publication of actual known reload fix and all retained failures."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v103/publication';assert not out.exists()
base='377cfb985322ab82eab1f3192803cbec540ec093';local='0114c381540c5c9909080d90aa62fbdf647bb9b7';previous='1c052f9948a9602155fd50ca0540a352ebbbbfbe';oldbase='608fa06d684f1c2d94a6dec92f937c93ff6c63d0'
components=[('warlock-preview-provider-v140',False),('warlock-client-provider-native-v175',True),('warlock-client-provider-native-v176',False),('warlock-preview-provider-v141',True),('warlock-client-provider-native-v177',False),*[(f'warlock-client-provider-native-v{v}',True) for v in range(178,185)]]
minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report-gui141-known-reload.json').read_text());assert held['passed'] and held['actualKnownRendererReloadQualified'] and held['reloadNativeChecks']==34 and held['reloadNormalOwnedExits']==12 and held['fullBuildCommands']==119
out.mkdir(parents=True);prior=r/'docs/warlock-repository/v102/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('295769b0c62a30ba124e229a7f54e7040dfae348..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v102/publication/','docs/warlock-repository/v103/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report-gui141-known-reload.json').read_text());assert qualification['passed'] and qualification['actualKnownRendererReloadQualified'] and qualification['actualSamePopupLeaseAcrossReloadQualified'] and qualification['actualSamePolicyRetained'] and qualification['actualOriginalNativeBindingRetained'] and qualification['reloadNativeChecks']==34 and qualification['reloadNormalOwnedExits']==12 and qualification['reloadQuintScenarios']==9 and qualification['reloadQuintInvariantSamples']==200 and qualification['reloadCoupledStages']==7 and qualification['currentFailureNativeControls']==22 and qualification['currentFailureExpectedExitCode']==1 and qualification['normalRouteNativeChecks']==29 and qualification['cancelledOldResultNativeChecks']==36 and qualification['rapidPendingReaderNativeChecks']==51 and qualification['delayedResultNativeChecks']==18 and qualification['successfulOldResultNativeChecks']==35 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and qualification['navigationResets']==0 and qualification['snapshotOrdinalResets']==0 and not qualification['reloadRecoveryQualified'] and not qualification['uncertainRecoveryQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Recover known renderer reload after strict native retirement\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text();a=s.index('report=json.loads(');b=s.index('\nsys.path.insert',a);s=s[:a]+"report=json.loads((r/'docs/warlock-preview/v93/component-report-gui141-known-reload.json').read_text());assert report['passed'] and report['actualKnownRendererReloadQualified'] and not report['reloadRecoveryQualified']"+s[b:]
s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v141',['PROGRESS PUBLIC103 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. '+report['scope']+' Next actual uncertain/process/repeated renderer recovery, original-clock pressure/expiry/physical/full-release gates; goal remains active.'],'progress',['docs/warlock-preview/v93/component-report-gui141-known-reload.json','implementation/warlock-preview-provider-v141/component-manifest.json','implementation/warlock-client-provider-native-v184/component-manifest.json','docs/warlock-repository/v103/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record public current renderer native drain repair','Record public known renderer reload recovery');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui139_current_failure_drain.py').read_text().replace('8ddf0df605073f483776585b9cbbd121c9c46102',local).replace('Drain original native duties before exiting a failed renderer','Recover known renderer reload after strict native retirement')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v103/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui141_known_renderer_reload.py';assert not p.exists();ast.parse(s);p.write_text(s);print(json.dumps({'publication':str(out),'minimumOwnedFiles':minimum}))
