"""Prepare owned actual process-drain repair publication with original failure."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v104/publication';assert not out.exists()
base='0ddc454b739f0a8dce50530d661a8b2e86551ca7';local='0549a14782f04c155beda4191068dbaf1910730c';previous='3a25f38c155bcf60fd27110a9a0190a3be418d65';oldbase='377cfb985322ab82eab1f3192803cbec540ec093'
components=[('warlock-preview-provider-v142',False),('warlock-client-provider-native-v185',True),('warlock-client-provider-native-v186',False),('warlock-preview-provider-v143',True),*[(f'warlock-client-provider-native-v{v}',True) for v in range(187,195)]]
minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report-gui143-shared-process-drain.json').read_text());assert held['passed'] and held['actualKnownSharedProcessNativeDrainQualified'] and held['processFailureNativeControls']==21 and held['fullBuildCommands']==119
out.mkdir(parents=True);prior=r/'docs/warlock-repository/v103/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('1c052f9948a9602155fd50ca0540a352ebbbbfbe..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v103/publication/','docs/warlock-repository/v104/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report-gui143-shared-process-drain.json').read_text());assert qualification['passed'] and qualification['actualKnownSharedProcessNativeDrainQualified'] and qualification['actualGTKRecoveryAfterStrictDrainQualified'] and qualification['processFailureNativeControls']==21 and qualification['processFailureExpectedHostExitCode']==1 and qualification['processFailureOtherNormalOwnedExits']==7 and not qualification['processFailureGLibCriticalsObserved'] and qualification['processDrainQuintScenarios']==9 and qualification['processDrainQuintInvariantSamples']==200 and qualification['processDrainCoupledStages']==6 and qualification['reloadNativeChecks']==34 and qualification['reloadNormalOwnedExits']==12 and qualification['currentFailureNativeControls']==22 and qualification['normalRouteNativeChecks']==29 and qualification['cancelledOldResultNativeChecks']==36 and qualification['rapidPendingReaderNativeChecks']==51 and qualification['delayedResultNativeChecks']==18 and qualification['successfulOldResultNativeChecks']==35 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and qualification['navigationResets']==0 and qualification['snapshotOrdinalResets']==0 and not qualification['wholeHostRestartQualified'] and not qualification['durableUnknownRecoveryQualified'] and not qualification['uncertainProcessDrainQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Drain native custody before shared renderer recovery\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text();a=s.index('report=json.loads(');b=s.index('\nsys.path.insert',a);s=s[:a]+"report=json.loads((r/'docs/warlock-preview/v93/component-report-gui143-shared-process-drain.json').read_text());assert report['passed'] and report['actualKnownSharedProcessNativeDrainQualified'] and not report['wholeHostRestartQualified']"+s[b:]
s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v143',['PROGRESS PUBLIC104 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. '+report['scope']+' Next actual native uncertainty, durable Unknown/window-command/whole-host restart, original-clock pressure/expiry/physical/full-release gates; goal remains active.'],'progress',['docs/warlock-preview/v93/component-report-gui143-shared-process-drain.json','implementation/warlock-preview-provider-v143/component-manifest.json','implementation/warlock-client-provider-native-v187/component-manifest.json','docs/warlock-repository/v104/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record public known renderer reload recovery','Record public shared renderer native drain repair');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui141_known_renderer_reload.py').read_text().replace('0114c381540c5c9909080d90aa62fbdf647bb9b7',local).replace('Recover known renderer reload after strict native retirement','Drain native custody before shared renderer recovery')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v104/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui143_shared_process_drain.py';assert not p.exists();ast.parse(s);p.write_text(s);print(json.dumps({'publication':str(out),'minimumOwnedFiles':minimum}))
