"""Prepare exact owned publication of ordered visual custody and its bounded gates."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v88/publication';assert not out.exists();out.mkdir(parents=True)
base='8bc0b5dd33e97f06e37284d0ca518db4d8e829fb';local='8399dd6e5f7eef07ae6acaa02b142bafc908fe80';previous='e17f3e5dcb66a3a3cc083e83dcfc6951580e5234'
proof=json.loads((r/'docs/warlock-preview/v93/component-report119.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['orderedVisualCustodyCPUQualified']
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v119/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v87/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='99c357235f940af304314501ce76efe76cbd91c5'","BASE='"+base+"'").replace('356ebb9de9a5c203f67c4fd40b614ecd22d39c76..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v87/publication/','docs/warlock-repository/v88/publication/','implementation/warlock-preview-provider-v119/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
expected={k:proof[k] for k in ['sourceHeld','passed','singlePreviewPolicy','parentElmPolicyUnchanged','parentNativeIssuerAndPhysicalProductUnchanged','parentAssetsAndAdaptersUnchanged','nativeOwnedJavaScriptCore','persistentPolicyContexts','nativeElmOutboxChecks','additiveVisualProjectionChecks','readonlyProjectionChecks','visualChannelChecks','visualChannelBoundaryChecks','pureRendererInstances','rendererWindowPolicies','visualChannelScenarios','visualChannelTraces','visualChannelObservableStates','visualChannelSamples','visualChannelCompiledNativeVariantsDetected','compiledSeededCounterBoundaries','orderedVisualCustodyCPUQualified','nativeControlOrdinalsUnchanged','fullBuildCommands','originalBuildCommands','realHostPolicyActivated','actualRendererProjectionActivated','actualDOMQualified','actualWebKitContextAuthenticationQualified','physicalConcealmentQualified','ongoingProjectionFreshnessQualified','realHostInputBackpressureQualified','nativeDelayedProposalLivenessQualified','uncertainLiveWorkerRecoveryQualified','fullElmRecoveryQualified','typedHostRoutingActivated','webKitActivated','nativeAcceptance','fullReleaseAccepted']}
assert expected['visualChannelChecks']==67 and expected['visualChannelBoundaryChecks']==33 and expected['fullBuildCommands']==115 and expected['originalBuildCommands']==112 and not expected['nativeAcceptance'] and not expected['fullReleaseAccepted']
a=s.index(' qualification=');b=s.index('\n published=',a);q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report119.json').read_text());expected="+repr(expected)+";assert all(qualification.get(k)==v for k,v in expected.items());assert len(qualification['heldFailedReports'])==1"
s=s[:a]+q+'\n message='+repr('Retain ordered visual snapshots in native context custody\n\n'+proof['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v87','warlock-repository/v88').replace('component-report118.json','component-report119.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v119',['PROGRESS PUBLIC88 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI119 native context/lease/separate visual sequence custody and pure receiver: actual C/JSC/Elm67/boundaries33/Quint14/26 C+JSC traces/451 observable states/200 samples/four compiled guards/two seeded exhaustion boundaries; original native207+90+74 unchanged grant/normal; full115 retains112. One header compile failure held. Parent policy/issuer/effects/physical/assets/adapters unchanged. Context strong refs until detach; native floors survive renderer replacement, exact pending retry/current-cache comparison, pure renderer ordering and malformed/conflicting concealment latch. No actual WebKit callback/DOM/frame/physical concealment/ongoing freshness/URI proof or host input/ticket custody activation. Next Native131 coherent current legacy source requalification and actual controlled host/renderer barriers with durable original input/ticket custody/retry. Native130 remains actual bounded baseline2518/278; uncertain worker/delayed proposal/full release gates remain open, installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/component-report119.json','implementation/warlock-preview-provider-v119/component-manifest.json','docs/warlock-repository/v88/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('99c357235f940af304314501ce76efe76cbd91c5',base).replace('Record public readonly visual custody qualification','Record public ordered visual custody qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit118.py').read_text().replace('c226d97a29289e6edccbe784ab9591eee02bd31f',local).replace("[('warlock-preview-provider-v118',True)]","[('warlock-preview-provider-v119',True)]").replace('warlock-repository/v87/publication','warlock-repository/v88/publication').replace('Copy committed visual data from the native-owned Elm policy','Retain ordered visual snapshots in native context custody');s=s.replace('exact held GUI118 readonly visual custody','exact held GUI119 ordered visual custody')
p=r/'docs/warlock-preview/v93/commit119.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
