"""Prepare exact inactive reliable transport primitive publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=repo/'docs/warlock-repository/v67/publication';assert not out.exists();out.mkdir(parents=True)
base='d67896fdde83540561f5097b22c59f19010e39f8'
proof=json.loads((repo/'docs/warlock-preview/v93/component-report95.json').read_text());assert proof['passed'] and proof['outboxNativeControls']==64 and proof['outboxStates']==389
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(repo/'docs/warlock-repository/v66/publication/publish.py').read_text().replace("BASE='d0372d2fe8a19048e404e364d2ca0c9f94b248b1'","BASE='"+base+"'").replace('b659e487649c867a0c36bac6bcd860d3961317ba..','20bd7a8d5229d26afaaa56f190e94967017b4a65..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v66/publication/','docs/warlock-repository/v67/publication/','implementation/warlock-preview-provider-v95/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Qualify bounded exact outgoing control retries without effect replay\n\nHeld GUI95 adds inactive native original-grant exact-wire control delivery receipts and an immutable bounded frontend outbox. Actual C12 selected Quint scenarios/20 coupled traces/190 states and three compiled native mutations qualify loss/retry, changed bytes, foreign grants, reentrancy, reload refusal and exhaustion. Actual JS10 selected scenarios/22 coupled traces/389 states and three syntax-checked mutations qualify queue/prefix/order/retry/failed-post preservation. Actual compiled native metadata/JS roundtrip64 controls passes normal cleanup, lost transmission/receipt, exact bytes/ordinals, Unknown outcome, backpressure, UTF8 bound and foreign/old grants. Production modules stay byte-identical to GUI94; these primitives are not loaded or routed in WebKit, and no new host/native runtime qualification is claimed. Add EARS/OpenSpec outgoing-control contract including final receipt confirmation before native close. Next native frontend confirmation barrier, cleanup capacity/ordinal reservations before admission, receiver reconciliation and actual WebKit outgoing/retirement activation. Fully qualified runtime remains GUI92/native128/core16/plugin18; all original GUI release gates remain open.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report95.json').read_text());assert qualification['passed'] and qualification['nativeControlScenarios']==12 and qualification['nativeControlTraces']==20 and qualification['nativeControlStates']==190 and qualification['unsafeCompiledNativeVariantsDetected']==3 and qualification['outboxScenarios']==10 and qualification['outboxTraces']==22 and qualification['outboxStates']==389 and qualification['unsafeActualJSVariantsDetected']==3 and qualification['outboxNativeControls']==64 and qualification['unchangedProductionModulesVerified'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:]
put('publish.py',s)
s=(repo/'docs/warlock-repository/v66/publication/record_delivery.py').read_text().replace('warlock-repository/v66','warlock-repository/v67').replace('component-report94.json','component-report95.json')
start=s.index('e=loop.write_checkpoint(')
s=s[:start]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v95',['PROGRESS PUBLIC67 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI95 inactive native control12selected/20traces/190states/3compiled mutants, JS10selected/22traces/389states/3JSvariants and64nativeMetadata+JS loss/retry/Unknown/order/backpressure/normalcleanup controls. Productionmodules unchanged; fullyqualifiedGUI92/native128 unchanged. Next receipt confirmation before native close, cleanup reservations before native admission, receiver reconciliation and actual WebKit activation. All original release gates remain.'],'progress',['docs/warlock-preview/v93/component-report95.json','implementation/warlock-preview-provider-v95/component-manifest.json','docs/warlock-repository/v67/publication/delivery.json']);print(e)\n"
put('record_delivery.py',s)
s=(repo/'docs/warlock-repository/v66/publication/commit_receipt.py').read_text().replace('d0372d2fe8a19048e404e364d2ca0c9f94b248b1',base).replace('Record public bounded fair retirement polling qualification','Record public bounded outgoing control primitive qualification')
put('commit_receipt.py',s)
s=(repo/'docs/warlock-preview/v93/commit94.py').read_text().replace('c7584a62e5e2dbf270079092a7ea49d74cbb6f0f','a324243c1bcf2b8dfec2c780270905e41d23ae09').replace("[('warlock-preview-provider-v94',True)]","[('warlock-preview-provider-v95',True)]").replace('warlock-repository/v66/publication','warlock-repository/v67/publication')
s=s.replace('Bound and rotate native retirement polling while preserving ownership barriers','Qualify bounded outgoing control retry primitives without effect replay')
ast.parse(s);(repo/'docs/warlock-preview/v93/commit95.py').write_text(s);print(out)
