"""Prepare exact held GUI121 output custody publication over PUBLIC90."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v91/publication';assert not out.exists();out.mkdir(parents=True)
base='78170391db233cbfd6b43d6361622bf742cb79dd';local='f269ef107f669e8d453136009d7fb3564f943301';previous='43498757f42a4fa785d2ff7d04a35e8de8f6ffd7'
root=r/'implementation/warlock-preview-provider-v121';held=json.loads((root/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed'] and held['normalOutputReservationUnderHeldProducerContractQualified'] and held['fullBuildCommands']==116
minimum=len(held['files']);prior=r/'docs/warlock-repository/v90/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='520fdcc920b48de72672c7864ba291d5fb2442bf'","BASE='"+base+"'").replace('88f77a78184a5676ae666052c7766a9d84b2e0d4..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v90/publication/','docs/warlock-repository/v91/publication/','implementation/warlock-preview-provider-v121/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report121.json').read_text());assert qualification['passed'] and qualification['positiveChecks']==2261 and qualification['lateQuarantinedOutputChecks']==2269 and qualification['pressureChecks']==2270 and qualification['preGrantFaultChecks']==9 and qualification['fullBuildCommands']==116 and qualification['originalBuildCommands']==116 and qualification['driverScenarios']==8 and qualification['driverSamples']==200 and qualification['coupledTraces']==8 and qualification['observableStatesCompared']==48 and qualification['compiledNativeVariantsDetected']==2 and qualification['normalOutputReservationUnderHeldProducerContractQualified'] and not qualification['nativeOutputQueueResourceBoundQualified'] and not qualification['realHostPolicyActivated'] and not qualification['actualRendererProjectionActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Reserve retained native output before effects and prioritize admitted events\n\n'+held['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-report120.json','component-report121.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v121',['PROGRESS PUBLIC91 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI121 normal native output reservation8192/batches3195/bytes26173440 under held original producer contract, serializer20/max1544bytes, positive synthetic FD2261/late quarantine2269/stricter compiled pressure2270; no native grant reset, normal accepted exits. Explicit Quint first-ticket8/200/eight actual C/JSC traces/48states/two compiled guards/full116 retains116. Two failed attempts retained. Actual output exhaustion/full-workload progress/RSS remain unqualified; actual legacy Native131GUI119/core16/plugin19/AQ1552518/278 unchanged. Next actual controlled host/pure renderer GTK admission/native grant/poll pausing/WebKit identity/async DOM/frame/physical concealment/URI. Uncertain live/process recovery, delayed never-issued proposals and all full release gates remain open. No installed/draft/foreign changes.'],'progress',['docs/warlock-preview/v93/component-report121.json','implementation/warlock-preview-provider-v121/component-manifest.json','docs/warlock-repository/v91/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('520fdcc920b48de72672c7864ba291d5fb2442bf',base).replace('Record public native policy driver qualification','Record public native output custody qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit120.py').read_text().replace('84498f01c814f6a3ff411df965aa508dc167e5b0',local).replace('warlock-preview-provider-v120','warlock-preview-provider-v121').replace('warlock-repository/v90/publication','warlock-repository/v91/publication').replace('Retain original native inputs and issued tickets in the policy driver','Reserve retained native output before effects and prioritize admitted events')
p=r/'docs/warlock-preview/v93/commit121.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
