"""Prepare exact held native-issued renderer transport publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v81/publication';assert not out.exists();out.mkdir(parents=True)
base='620566103509a1469c6d75401f753dc32a4bcb3c';local='d029415cf596ad30892b1fe3e8ed851fa3bf89d7';previous='d8a51e4141fe3d7d7eb033002fdf37594f23060c'
proof=json.loads((r/'docs/warlock-preview/v93/component-report112.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeRecoveryChecks']==129 and proof['recoveryStates']==498
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v112/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v80/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='48451e88124dd0ae9aa8e69f25e25c7ba8e82e05'","BASE='"+base+"'").replace('0ac8ba2f19859b7b1429dc106b6c36e74ee2bce2..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v80/publication/','docs/warlock-repository/v81/publication/','implementation/warlock-preview-provider-v112/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report112.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['nativeRecoveryChecks']==129 and qualification['recoveryScenarios']==24 and qualification['recoveryTraces']==36 and qualification['recoveryStates']==498 and qualification['unsafeActualJSVariantsDetected']==9 and qualification['unsafeCompiledNativeVariantsDetected']==3 and qualification['fullBuildCommands']==98 and qualification['currentScopedRegressionSuites']==4 and len(qualification['heldFailedReports'])==3 and not qualification['actualWebKitContextReloadQualified'] and not qualification['fullElmRecoveryQualified'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Recover original native preview tickets after renderer context loss\n\n'+proof['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v80','warlock-repository/v81').replace('component-report111.json','component-report112.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v112',['PROGRESS PUBLIC81 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI112 inactive readonly native realm recovery C129/two recreated JS contexts/two Active-subject epochs/unchanged Native grant/model24/36 actualJS traces/498 states/200 samples/nine JS and three native variants/full98 retains97/current four resource and four scoped regressions. Three failures retained. Native130 current110 legacy2518/278/full cleanup remains bounded baseline. Next typed realm/retained Elm recovery and actual WebKit callback/context/Core activation. Original full release gates open; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report112.json','implementation/warlock-preview-provider-v112/component-manifest.json','docs/warlock-repository/v81/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('48451e88124dd0ae9aa8e69f25e25c7ba8e82e05',base).replace('Record public native-issued renderer transport qualification','Record public native realm recovery qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit111.py').read_text().replace('f7b7039ef613ff455491f7ee516eb68c90aaea27',local).replace("[('warlock-preview-provider-v111',True)]","[('warlock-preview-provider-v112',True)]").replace('warlock-repository/v80/publication','warlock-repository/v81/publication').replace('Retain native-issued renderer tickets and independent confirmation','Recover original native preview tickets after renderer context loss')
p=r/'docs/warlock-preview/v93/commit112.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
