"""Prepare held native-owned Elm policy publication under existing authorization."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v85/publication';assert not out.exists();out.mkdir(parents=True)
base='1d89276d5d6b8d7dbd24d79e20073608589da795';local='060a36829fdb934ab03a6f21d9a7df6b1697c07c';previous='9825a9d59f35bb3a7eb6bc637291c7f2b60ed24f'
proof=json.loads((r/'docs/warlock-preview/v93/component-report116.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeElmOutboxChecks']==207 and proof['lifetimeStates']==405
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v116/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v84/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='16d4f7dc97ddb9934341bb60eac1decd74b895e4'","BASE='"+base+"'").replace('8776582022f14f9c633d6219211a6f434d3e1eae..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v84/publication/','docs/warlock-repository/v85/publication/','implementation/warlock-preview-provider-v116/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report116.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['singlePreviewPolicy'] and qualification['nativeOwnedJavaScriptCore'] and qualification['persistentPolicyContexts']==1 and qualification['rendererElmInstancesInCoupling']==0 and qualification['nativeElmOutboxChecks']==207 and qualification['lifetimeBoundaryChecks']==37 and qualification['constructorFaults']==13 and qualification['backpressureChecks']==48 and qualification['lifetimeScenarios']==8 and qualification['lifetimeTraces']==20 and qualification['lifetimeStates']==405 and qualification['lifetimeCompiledNativeVariantsDetected']==3 and qualification['fullBuildCommands']==110 and qualification['originalBuildCommands']==108 and len(qualification['heldFailedReports'])==5 and qualification['persistentPolicyCPUQualified'] and not qualification['realHostPolicyActivated'] and not qualification['realHostInputBackpressureQualified'] and not qualification['nativeDelayedProposalLivenessQualified'] and not qualification['uncertainLiveWorkerRecoveryQualified'] and not qualification['fullElmRecoveryQualified'] and not qualification['typedHostRoutingActivated'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Own the retained Elm policy in a persistent native JavaScriptCore worker\n\n'+proof['scope'];s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v84','warlock-repository/v85').replace('component-report115.json','component-report116.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v116',['PROGRESS PUBLIC85 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI116 persistent native-owned optimized JSC Elm policy; original single window policy unchanged. Actual C/JSC/native synthetic peer207/two epochs/unchanged Native grant/two fresh transport contexts/one policy/normal exits. Lifetime37/13 pre-grant faults/backpressure48/Quint8 selected/20 actual traces/405 states/three compiled guards/full110 retains108; five failed attempts held. Host library links but creates no worker or controlled route. Next typed renderer projection without another window policy, durable input custody/native sender channel/original ticket custody/retry and actual WebKit/Core activation. Uncertain live JSC/process recovery, delayed proposal expiry/revocation outcomes and all original release gates remain. Native130 legacy2518/278 remains actual baseline; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report116.json','implementation/warlock-preview-provider-v116/component-manifest.json','docs/warlock-repository/v85/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('16d4f7dc97ddb9934341bb60eac1decd74b895e4',base).replace('Record public retained Elm proposal qualification','Record public persistent native Elm policy qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit115.py').read_text().replace('3527bb5dca16bfa997b3e2d1007baade1cae85bf',local).replace("[('warlock-preview-provider-v115',True)]","[('warlock-preview-provider-v116',True)]").replace('warlock-repository/v84/publication','warlock-repository/v85/publication').replace('Retain original Elm proposals and revoke quarantined demand during backpressure','Own the retained Elm policy in a persistent native JavaScriptCore worker')
p=r/'docs/warlock-preview/v93/commit116.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
