"""Prepare safe actual delayed-result qualification over PUBLIC94."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v95/publication';assert not out.exists();out.mkdir(parents=True)
base='fc3c916778d144785c6fc3e64617c310e5f80e5d';local='99f4be9d2868d47d998a4f65f13731fb1a075be0';previous='d9e69b01f644a664208f24e4bb8120d2e8acc716'
components=[('warlock-preview-provider-v129',True),('warlock-client-provider-native-v140',True),('warlock-client-provider-native-v141',True)];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report129.json').read_text());assert held['passed'] and held['actualStaleSnapshotCallbackQualified'] and held['normalRouteNativeChecks']==29 and held['normalRouteNormalOwnedExits']==13 and held['delayedResultNativeChecks']==18 and held['delayedResultNormalOwnedExits']==8 and not held['physicalRevealQualified'] and not held['nativeAcceptance']
prior=r/'docs/warlock-repository/v94/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='6723ef8d72aea0ead4b3434f5fdff1825db93144'","BASE='"+base+"'").replace('a32af78b824c79f6e77214739dfcc1594a45c04d..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v94/publication/','docs/warlock-repository/v95/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report129.json').read_text());assert qualification['passed'] and qualification['actualStaleSnapshotCallbackQualified'] and qualification['actualRetainedResultConsumedOnce'] and qualification['actualStaleSnapshotArtifactRejected'] and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['delayedResultNativeChecks']==18 and qualification['delayedResultNormalOwnedExits']==8 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['physicalConcealmentQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Reject a real delayed WebKit snapshot after native popup closure\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-curtain-control-report.json','component-report129.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v129',['PROGRESS PUBLIC95 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. SAFEGUI129 normalNative14029checks13normalexits and separate actual delayed-resultNative14118checks8normalexits; original16 admission/drain retained. One actual original WebKit result/view/scope held without early finish, real closure invalidates projection, same result finished once/rejected/no stale artifact, original policy/native input/ticket/physical/journal/confirmation duties drain through strict close. Both cleanups/full119/deadline6/core16/plugin19/AQ155 pass, opacity0/single policy/original native issuer/physical product/no grant reset unchanged. Bounded after-close snapshot callback qualified; broader stale callbacks/normal realm reopen/reload/process/uncertain recovery/physical frame/reveal/pressure/workload/RSS/full preview/release remain open. Next safe original native realm lifecycle and actual ongoing frame/reveal qualification, retaining all accepted/failed/unsafe evidence. Installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-report129.json','implementation/warlock-preview-provider-v129/component-manifest.json','implementation/warlock-client-provider-native-v140/component-manifest.json','implementation/warlock-client-provider-native-v141/component-manifest.json','docs/warlock-repository/v95/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('6723ef8d72aea0ead4b3434f5fdff1825db93144',base).replace('Record public native curtain detector qualification','Record public delayed snapshot qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit127.py').read_text().replace('2e567bce2a3458bef1782e308ab19c1888b0071b',local).replace('warlock-repository/v94/publication','warlock-repository/v95/publication').replace('Bind native popup paint observations and verify the closed curtain detector','Reject a real delayed WebKit snapshot after native popup closure')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
p=r/'docs/warlock-preview/v93/commit129.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
