"""Prepare exact held counterexample and stale-error guard fix publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v100/publication';assert not out.exists()
base='2873c6289af212c6b64002cd42dad9a21e0eca68';local='2f3def1c88547c67499336de276e23f2b9002e3d';previous='506e513b61961a46dbca3e9a21e3957c61276d70';oldbase='999882f42faba9ba1e008d273dc9f14ea984473a'
components=[('warlock-preview-provider-v136',False),('warlock-client-provider-native-v158',True),('warlock-client-provider-native-v159',False),('warlock-preview-provider-v137',True),*[(f'warlock-client-provider-native-v{v}',True) for v in range(160,165)]];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report-gui137-stale-error.json').read_text());assert held['passed'] and held['actualCancelledOldResultQualified'] and held['cancelledReopenedSnapshotNativeChecks']==36 and held['asyncErrorScopeQuintScenarios']==10 and held['fullBuildCommands']==119 and not held['currentMatchingErrorNativeQualified']
out.mkdir(parents=True);prior=r/'docs/warlock-repository/v99/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('5317904baf6303f73fc7c48574453a0e27a460a9..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v99/publication/','docs/warlock-repository/v100/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report-gui137-stale-error.json').read_text());assert qualification['passed'] and qualification['actualCancelledOldResultQualified'] and qualification['actualNewRealmCapturedPixelsQualified'] and not qualification['actualOldSnapshotPixelsAccepted'] and qualification['cancelledReopenedSnapshotNativeChecks']==36 and qualification['cancelledReopenedSnapshotNormalOwnedExits']==13 and qualification['successfulReopenedSnapshotNativeChecks']==35 and qualification['asyncErrorScopeQuintScenarios']==10 and qualification['asyncErrorScopeInvariantSamples']==200 and qualification['asyncErrorScopeCoupledCases']==4 and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['delayedResultNativeChecks']==18 and qualification['delayedResultNormalOwnedExits']==8 and qualification['rapidPendingReaderNativeChecks']==51 and qualification['rapidPendingReaderNormalOwnedExits']==17 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['currentMatchingErrorNativeQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Reject retired WebKit errors before current GUI failure handling\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text();a=s.index('report=json.loads(');b=s.index('\nsys.path.insert',a);s=s[:a]+"report=json.loads((r/'docs/warlock-preview/v93/component-report-gui137-stale-error.json').read_text());assert report['passed'] and report['actualCancelledOldResultQualified'] and not report['currentMatchingErrorNativeQualified']"+s[b:]
s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v137',['PROGRESS PUBLIC100 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. '+report['scope']+' Next actual current matching error native control then remaining async/physical/recovery gates; full release remains active.'],'progress',['docs/warlock-preview/v93/component-report-gui137-stale-error.json','implementation/warlock-preview-provider-v137/component-manifest.json','implementation/warlock-client-provider-native-v161/component-manifest.json','docs/warlock-repository/v100/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record public rapid popup retirement repair qualification','Record public retired WebKit error guard qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui135_reopened_snapshot.py').read_text().replace('41af33e38dc5f991671ed5afdb18af81b542daa7',local).replace('Reject an old WebKit result after native realm reopening','Reject retired WebKit errors before current GUI failure handling')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v100/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui137_stale_snapshot_error_guard.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
