"""Prepare exact owned one-policy realm reuse publication over PUBLIC95."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v96/publication';assert not out.exists();out.mkdir(parents=True)
base='c59722eb3c501552914859d58f8c5c70bdd8c21c';local='5e59bb47962d5716b0fbc46271eebe3ec3fd03b4';previous='6be2b7fce8c20cc5fcb577f50959e3039c4cc1de'
components=[('warlock-preview-provider-v130',True),('warlock-client-provider-native-v142',True),('warlock-client-provider-native-v143',True)]
minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report130.json').read_text())
assert held['passed'] and held['cpuCPolicyRealmReuseQualified'] and not held['actualGUIRealmReopenQualified'] and held['realmReuseCChecks']==143 and held['realmReuseQuintScenarios']==8 and held['fullBuildCommands']==119
prior=r/'docs/warlock-repository/v95/publication-v2'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace('fc3c916778d144785c6fc3e64617c310e5f80e5d',base).replace('d9e69b01f644a664208f24e4bb8120d2e8acc716..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v95/publication-v2/','docs/warlock-repository/v96/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report130.json').read_text());assert qualification['passed'] and qualification['cpuCPolicyRealmReuseQualified'] and qualification['realmReuseCChecks']==143 and qualification['originalDriverChecks']==2261 and qualification['preGrantConstructorChecks']==9 and qualification['realmReuseQuintScenarios']==8 and qualification['realmReuseInvariantSamples']==200 and qualification['realmReuseConcreteObservedStates']==11 and qualification['realmReuseCoupledQuintChecks']==6 and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['delayedResultNativeChecks']==18 and qualification['delayedResultNormalOwnedExits']==8 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['actualGUIRealmReopenQualified'] and not qualification['nativeRealmRebindingActivated'] and not qualification['directPermanentRetirementQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Preserve one Elm policy across normally retired native preview realms\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-report129.json','component-report130.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v130',['PROGRESS PUBLIC96 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI130 same persistent Elm policy C/JSC realm reuse143 checks/two sealed-FD captures/same binding and policy pointer/permanent retired21 replay rejection/new Active22 capture/strict final close. Original2261+9/current full119/Quint8named200samples/six stages coupled to11 concrete observations pass. Actual Native142 unchanged29checks13normalexits and delayedNative14318checks8normalexits/private cleanups pass. Native original grants/issuer/policy/physical product/deadlines unchanged/no grant reset; popup quarantine precedes permanent retirement. Direct-retirement failed fixture retained/unqualified. Actual GUI rebind/fixed-grant context replacement and normal reopen not yet wired; physical reveal/ongoing conceal/hardware/pressure/workload/RSS/reload/process/uncertain recovery/full preview/release open. Next fresh native host lifecycle integration; installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-report130.json','implementation/warlock-preview-provider-v130/component-manifest.json','implementation/warlock-client-provider-native-v142/component-manifest.json','implementation/warlock-client-provider-native-v143/component-manifest.json','docs/warlock-repository/v96/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('fc3c916778d144785c6fc3e64617c310e5f80e5d',base).replace('Record public delayed snapshot qualification','Record public persistent policy realm reuse qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui129_controlled.py').read_text().replace('99f4be9d2868d47d998a4f65f13731fb1a075be0',local).replace('Reject a real delayed WebKit snapshot after native popup closure','Preserve one Elm policy across normally retired native preview realms')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v96/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui130_policy_reuse.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
