"""Prepare exact held GUI109 scoped live-application preview detachment delivery."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v77/publication';assert not out.exists();out.mkdir(parents=True)
base='2d8f3fd9503e673afa0b1274de15d344e3891cc9';local='0fb366e1ce71f48fd47d32498a4ef40e7b2f039b';previous='3a3bc903159bba35a46f5c1ef99a976083af37ef'
proof=json.loads((r/'docs/warlock-preview/v93/component-report109.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['detachmentCChecks']==77 and proof['detachmentCohortChecks']==66 and proof['detachmentStates']==715
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v109/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v76/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='c1f44a4fd9b68aa669a08a6231e9477dc5174399'","BASE='"+base+"'").replace('e8ff9b88cce51ddf86850df830802d708e874829..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v76/publication/','docs/warlock-repository/v77/publication/','implementation/warlock-preview-provider-v109/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report109.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['detachmentCChecks']==77 and qualification['detachmentReaderChecks']==60 and qualification['detachmentLostProducerResponseChecks']==64 and qualification['detachmentPostTransferChecks']==51 and qualification['detachmentCohortChecks']==66 and qualification['detachmentScenarios']==21 and qualification['detachmentTraces']==33 and qualification['detachmentStates']==715 and qualification['detachmentModelCompiledVariants']==5 and qualification['fullBuildCommands']==95 and len(qualification['heldFailedReports'])==4 and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Detach scoped preview ownership while the native application stays Active\n\n'+proof['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v76','warlock-repository/v77').replace('component-report108.json','component-report109.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v109',['PROGRESS PUBLIC77 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held109 scoped detachment C77/resource60+64+51/cohort66/model21/33/715/five variants/current full95/original four regressions; four failures retained. Synthetic Native applications stay Active, original barriers unchanged. Inactive controlled path; actual Native129 GUI92/core16/plugin19 remains2517/278. Next fresh110 safe URI callback lifetime/routing and typed frontend realm wrapper/native renderer outbox before actual controlled Core/WebKit; original full release/deployment gates remain open. No installed changes.'],'progress',['docs/warlock-preview/v93/component-report109.json','implementation/warlock-preview-provider-v109/component-manifest.json','docs/warlock-repository/v77/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('c1f44a4fd9b68aa669a08a6231e9477dc5174399',base).replace('Record public Bootstrap receipt lifetime qualification','Record public scoped preview detachment qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit108.py').read_text().replace('800184195e3c86704676192df38a327ac22c6dad',local).replace("[('warlock-preview-provider-v108',True)]","[('warlock-preview-provider-v109',True)]").replace('warlock-repository/v76/publication','warlock-repository/v77/publication').replace('Close native Bootstrap receipt ownership before preview Endpoint destruction','Detach scoped preview ownership while the native application stays Active')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit109.py';assert not p.exists();p.write_text(s);print(out)
