"""Prepare exact owned native driver publication over PUBLIC89."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v90/publication';assert not out.exists();out.mkdir(parents=True)
base='520fdcc920b48de72672c7864ba291d5fb2442bf';local='84498f01c814f6a3ff411df965aa508dc167e5b0';previous='88f77a78184a5676ae666052c7766a9d84b2e0d4'
root=r/'implementation/warlock-preview-provider-v120';proof=json.loads((r/'docs/warlock-preview/v93/component-report120.json').read_text());held=json.loads((root/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed'] and proof['passed'] and held['driverChecks']==2250 and held['fullBuildCommands']==116
minimum=len(held['files']);prior=r/'docs/warlock-repository/v89/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='2b6f8fb433eccb956449be3a6d4c0508d2dfb743'","BASE='"+base+"'").replace('73e6fb1bee3133084da6ae4871d9a9ef9664195b..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v89/publication/','docs/warlock-repository/v90/publication/','implementation/warlock-preview-provider-v120/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report120.json').read_text());assert qualification['passed'] and qualification['driverChecks']==2250 and qualification['preGrantFaultChecks']==9 and qualification['fullBuildCommands']==116 and qualification['originalBuildCommands']==115 and qualification['driverScenarios']==14 and qualification['driverSamples']==200 and qualification['compiledNativeVariantsDetected']==4 and qualification['nativeTicketCustodyCPUQualified'] and qualification['independentNativeConfirmationCPUQualified'] and not qualification['nativeOutputQueueResourceBoundQualified'] and not qualification['realHostPolicyActivated'] and not qualification['actualRendererProjectionActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Retain original native inputs and issued tickets in the policy driver\n\n'+held['scope']+'\n\nBounded Native/C/JSC component2250 + constructor faults9; explicit custody Quint14/200 samples/six concrete ordered witnesses/four compiled guards; full116 retains115. Original parent policy/native issuance/effects/physical/assets/adapters unchanged. Output resource bound, actual host/pure renderer/WebKit/Core/URI and full release gates remain open; no installed changes.'
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v89','warlock-repository/v90').replace('native-report131.json','component-report120.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v120',['PROGRESS PUBLIC90 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI120 native driver atomic input1065/16MiB, original source epoch, ticket before issuance notification/dispatch, deferred callbacks and separate confirmation. Original Native/C/Bootstrap/Broker/journal/scoped closure with synthetic peer2250/constructor faults9/normal exits/no grant reset; Quint custody14/200/six concrete witnesses/four compiled guards; full116 retains115. Parent policy/issuer/effects/physical/assets/adapters unchanged, three failed attempts retained. Driver links but remains inactive in actual legacy host; Native131 actualGUI119 legacy2518/278 baseline remains. Next bounded retained native outputs and paused producer scheduling before actual controlled host/pure renderer WebKit identity/async frame/physical concealment/URI. In-process memory is not a loss journal; uncertain worker/process recovery, delayed never-issued proposal outcome/order and all full release gates remain open. No installed/foreign changes.'],'progress',['docs/warlock-preview/v93/component-report120.json','implementation/warlock-preview-provider-v120/component-manifest.json','docs/warlock-repository/v90/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('2b6f8fb433eccb956449be3a6d4c0508d2dfb743',base).replace('Record public current native legacy qualification','Record public native policy driver qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit119.py').read_text().replace('8399dd6e5f7eef07ae6acaa02b142bafc908fe80',local).replace("[('warlock-preview-provider-v119',True)]","[('warlock-preview-provider-v120',True)]").replace('warlock-repository/v88/publication','warlock-repository/v90/publication').replace('Retain ordered visual snapshots in native context custody','Retain original native inputs and issued tickets in the policy driver')
p=r/'docs/warlock-preview/v93/commit120.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
