"""Prepare held GUI108 exact Bootstrap receipt lifetime qualification delivery."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v76/publication';assert not out.exists();out.mkdir(parents=True)
base='c1f44a4fd9b68aa669a08a6231e9477dc5174399';local='800184195e3c86704676192df38a327ac22c6dad';previous='e8ff9b88cce51ddf86850df830802d708e874829'
proof=json.loads((r/'docs/warlock-preview/v93/component-report108.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['bootstrapCChecks']==97 and proof['bootstrapCoreDeathChecks']==47 and proof['bootstrapStates']==719
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v108/component-manifest.json').read_text())['files'])
prior=r/'docs/warlock-repository/v75/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='806c609195d742d2a97e5d845c4c9cad1d45b2c7'","BASE='"+base+"'").replace('3f40039fbec11bbacf5bafb33a17427cc13c3d68..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v75/publication/','docs/warlock-repository/v76/publication/','implementation/warlock-preview-provider-v108/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
message='Close native Bootstrap receipt ownership before preview Endpoint destruction\n\nPreserve original strict C physical/proof/actor/final-processing/independent-confirmation cleanup and validate the exact owning Bootstrap, Native transport, Endpoint, receiver epoch, creator thread and empty receipt membership. Complete the original native claim, release borrowed delivery, then destroy the Endpoint. Refused or foreign Bootstrap close retains the original owner/channel. Lookup and polling refuse safely after close; the next actual owner attaches a new channel on the unchanged Native binding. C97 live replacement and47 actual synthetic native-peer-death close controls,17 selected Quint/29 coupled actual C traces/719 states, precise compiled variants, current full95 and original resource/capture/ticket/SCM_RIGHTS/GIO/allocation regressions pass. The first count-premise failure remains with its actual97 passing C assertions. Elm/assets remain byte-identical to held107/106 and prior evidence retains its source. GUI108 is inactive CPU qualification; actual native GUI92/native129/core16/plugin19 remains2517 checks/278 normal exits/full cleanup. Distinct live-window binding detachment, typed frontend realm delivery, renderer native outbox/current controlled Core/WebKit and all original release/deployment gates remain open. No installed changes.\n'
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report108.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['bootstrapCChecks']==97 and qualification['bootstrapCoreDeathChecks']==47 and qualification['bootstrapScenarios']==17 and qualification['bootstrapTraces']==29 and qualification['bootstrapStates']==719 and qualification['fullBuildCommands']==95 and len(qualification['heldFailedReports'])==1 and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v75','warlock-repository/v76').replace('component-report107.json','component-report108.json')
import re
s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v108',['PROGRESS PUBLIC76 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI108 inactive CPU exact Bootstrap-aware strict C close/borrowed receipt release/reattachment:97 replacement+47 synthetic native-peer-death controls,17 selected Quint/29 actual C traces/719 states/current full95/original resource/capture/ticket/FD regressions; count-premise failure retained. Native129/public74 GUI92/core16/plugin19 remains2517/278/full cleanup. Next freshGUI109 distinct live-window binding detach/typed scoped proof/readiness/final processing/confirmation/frontend realm freshness/current controlled Core/renderer native outbox/WebKit. Original full release/deployment gates remain open; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report108.json','implementation/warlock-preview-provider-v108/component-manifest.json','docs/warlock-repository/v76/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('806c609195d742d2a97e5d845c4c9cad1d45b2c7',base).replace('Record public preview realm ownership qualification','Record public Bootstrap receipt lifetime qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit107.py').read_text().replace('67d8b7e46e719509f8afbe635c1f082530d7a8ae',local).replace("[('warlock-preview-provider-v107',True)]","[('warlock-preview-provider-v108',True)]").replace('warlock-repository/v75/publication','warlock-repository/v76/publication').replace('Preserve native preview realm identity across settled owner replacement','Close native Bootstrap receipt ownership before preview Endpoint destruction')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit108.py';assert not p.exists();p.write_text(s)
print(out)
