"""Prepare exact owned actor/quota retirement and controlled C publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v71/publication';assert not out.exists();out.mkdir(parents=True)
base='dd58cba2cb3d908d87fd5e7cbbc115f58fb59b27';local='81812346adeadf464aae26259a8ae1bf413741c9';previous_source='3115c879300ec66f8a1ffb8ceda2217b5eaccca6'
proof=json.loads((r/'docs/warlock-preview/v93/component-report103.json').read_text());assert proof['passed'] and proof['controlledCChecks']==10190 and proof['controlledCCompiledVariants']==5 and proof['originalRegressionSuites']==12 and proof['fullBuildCommands']==95
minimum=sum(len(json.loads((r/('implementation/warlock-preview-provider-v'+str(n))/'component-manifest.json').read_text())['files']) for n in [102,103])
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(r/'docs/warlock-repository/v70/publication/publish.py').read_text()
assert s.count("BASE='0e60cf3adefd85be3407503351315d4472a10c9b'")==1
s=s.replace("BASE='0e60cf3adefd85be3407503351315d4472a10c9b'","BASE='"+base+"'").replace('601b6d42830da1aa0b4a27d5f61f0c67a209f342..',previous_source+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v70/publication/','docs/warlock-repository/v71/publication/','implementation/warlock-preview-provider-v102/','implementation/warlock-preview-provider-v103/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
message='Guard actor cleanup and expose original native control tickets through C\n\nPreserve independent original physical/proof/receiver retirement barriers and frontend control confirmations. GUI102 passes7809 authenticated synthetic socket controls across260 metadata actors and1040 uninterrupted native tickets; actual final processing and frontend confirmation precede actor credit release. GUI103 exposes an opt-in C factory that claims one native preview namespace, refuses raw legacy controls and invokes only original purpose-issued immutable tickets under the actual creator thread, receiver, binding, epoch and borrowed receipt Endpoint.10190 actual C controls across260 actors and1041 uninterrupted tickets pass, including retained failed-handler receipts, confirmed predecessor suppression, final ACK after subject erasure, and cached latest receipt/confirmation after synthetic core exit. Polling preserves exact original readiness bytes, including whitespace. Five unsafe C variants compile and fail original socket assertions; the original fixture-server failure is preserved and not counted. Actor15 selected scenarios/23 native traces/316 states/four compiled variants,job15/23/299/four,reservation11/23/397/four+64 controls,admission15/23/191/six and69 optimized Elm/native Broker/real URI controls pass. The full changed host passes95 build/check commands and all12 original regression suites. Preserve failed whitespace, aggregate-initializer, quota-count, allocator-arithmetic and mutation-compile/server evidence. This qualifies metadata/socket/native C components only: no real capture, WebKit activation, live-window binding detachment or full GUI release. Native reconciliation/capture Unknown settlement/native-assigned renderer outbox and all original native release gates remain open. Qualified runtime GUI92/native128/core16/plugin18 is unchanged.\n'
qualification=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report103.json').read_text());assert qualification['passed'] and qualification['controlledCChecks']==10190 and qualification['controlledCMetadataActors']==260 and qualification['controlledCNativeIssuedPrefix']==1041 and qualification['controlledCCompiledVariants']==5 and qualification['nativeActorScenarios']==15 and qualification['nativeActorTraces']==23 and qualification['nativeActorStates']==316 and qualification['nativeActorCompiledVariants']==4 and qualification['compiledElmNativeQuotaControls']==69 and qualification['originalRegressionSuites']==12 and qualification['originalRegressionSuitesRerunHere'] and qualification['fullBuildCommands']==95 and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+qualification+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(r/'docs/warlock-repository/v70/publication/record_delivery.py').read_text().replace('warlock-repository/v70','warlock-repository/v71').replace('component-report101.json','component-report103.json').replace("d['ownedFiles']>=11485","d['ownedFiles']>="+str(minimum))
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v103',['PROGRESS PUBLIC71 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held102 actor quota7809/260/1040;held103 controlled C10190/260/1041, exact readiness bytes and five compiled unsafe C witnesses,actor15/23/316/four,job/bank/admission/69Elm-nativeURI requalified,95 full host commands and12 original suites rerun. Failed evidence retained, noWebKit/capture/live-binding detach/native fullrelease claim. Next actual live-window binding detachment, native reconciliation/capture Unknown settlement and native-assigned renderer outbox. QualifiedGUI92/native128/core16/plugin18 and alloriginalgates unchanged.'],'progress',['docs/warlock-preview/v93/component-report103.json','implementation/warlock-preview-provider-v103/component-manifest.json','docs/warlock-repository/v71/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(r/'docs/warlock-repository/v70/publication/commit_receipt.py').read_text().replace('0e60cf3adefd85be3407503351315d4472a10c9b',base).replace('Record public guarded admission and native ticket issuer qualification','Record public actor quota and controlled native C qualification').replace("d['ownedFiles']>=11485","d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit101-v2.py').read_text().replace('fcfe28956f8dfd71642e7632b84d8e3b22c7cb4d',local).replace("[('warlock-preview-provider-v100',True),('warlock-preview-provider-v101',True)]","[('warlock-preview-provider-v102',True),('warlock-preview-provider-v103',True)]").replace('warlock-repository/v70/publication','warlock-repository/v71/publication').replace('Guard native admission and issue immutable purpose-validated control tickets','Guard actor quotas and expose original native control tickets through C')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit103.py';assert not p.exists();p.write_text(s)
print(out)
