"""Prepare exact held native-issued renderer transport publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v80/publication';assert not out.exists();out.mkdir(parents=True)
base='48451e88124dd0ae9aa8e69f25e25c7ba8e82e05';local='f7b7039ef613ff455491f7ee516eb68c90aaea27';previous='0ac8ba2f19859b7b1429dc106b6c36e74ee2bce2'
proof=json.loads((r/'docs/warlock-preview/v93/component-report111.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeTicketRoundtripChecks']==93 and proof['nativeOutboxStates']==463
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v111/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v79/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='4ffd7371e6f172b3f5fe19abc6345ddd55abc8c1'","BASE='"+base+"'").replace('cf347c314d8856fbea327a79f5ef862d618c4840..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v79/publication/','docs/warlock-repository/v80/publication/','implementation/warlock-preview-provider-v111/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report111.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['nativeTicketRoundtripChecks']==93 and qualification['protocolChecks']==47 and qualification['nativeOutboxScenarios']==14 and qualification['nativeOutboxTraces']==26 and qualification['nativeOutboxStates']==463 and qualification['unsafeActualJSVariantsDetected']==6 and qualification['fullBuildCommands']==97 and len(qualification['heldFailedReports'])==3 and not qualification['rendererReloadRecoveryQualified'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Retain native-issued renderer tickets and independent confirmation\n\n'+proof['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v79','warlock-repository/v80').replace('native-report130.json','component-report111.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v111',['PROGRESS PUBLIC80 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI111 inactive native-issued renderer outbox C93/protocol47/Quint14/26 actualJS traces/463 states/200 samples/six variants/full97 retains original96. Two Active subject realms share Native grant and strict native barriers. Three fixture failures retained. Parent110 product byte-identical. Native130 current110 legacy2518/278/full cleanup remains bounded baseline. Next native ticket/prefix reload recovery and typed realm/actual WebKit/Core activation. Original full release gates open; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report111.json','implementation/warlock-preview-provider-v111/component-manifest.json','docs/warlock-repository/v80/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('4ffd7371e6f172b3f5fe19abc6345ddd55abc8c1',base).replace('Record public current-host native qualification','Record public native-issued renderer transport qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit110.py').read_text().replace('435d99e329de62444bdb22a6413d0cc0b0391d36',local).replace("[('warlock-preview-provider-v110',True)]","[('warlock-preview-provider-v111',True)]").replace('warlock-repository/v78/publication','warlock-repository/v80/publication').replace('Guard native URI callbacks with exact Endpoint lifetime and receiver epoch','Retain native-issued renderer tickets and independent confirmation')
p=r/'docs/warlock-preview/v93/commit111.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
