"""Prepare exact owned actual normal GUI close/reopen publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v97/publication';assert not out.exists();out.mkdir(parents=True)
base='455421e67ebb431a32669e5dab23578a350dc99b';local='24497b0bd5480a9c7441f28d7114d77b1a63b2fa';previous='5f9ed867f5bbb8ef19377051486a682ccb55be8f';oldbase='c59722eb3c501552914859d58f8c5c70bdd8c21c'
components=[('warlock-preview-provider-v131',False),('warlock-preview-provider-v132',True),('warlock-client-provider-native-v144',True),('warlock-client-provider-native-v145',True),('warlock-client-provider-native-v146',True)];minimum=0
for name,passed in components:
 held=json.loads((r/'implementation'/name/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed']==passed;minimum+=len(held['files'])
held=json.loads((r/'docs/warlock-preview/v93/component-report132.json').read_text());assert held['passed'] and held['actualGUIRealmReopenQualified'] and held['normalReopenNativeChecks']==46 and held['hostLifecycleQuintScenarios']==9 and held['fullBuildCommands']==119
prior=r/'docs/warlock-repository/v96/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace(oldbase,base).replace('6be2b7fce8c20cc5fcb577f50959e3039c4cc1de..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v96/publication/','docs/warlock-repository/v97/publication/',*(f'implementation/{name}/' for name,_ in components),'openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report132.json').read_text());assert qualification['passed'] and qualification['actualGUIRealmReopenQualified'] and qualification['nativeRealmRebindingActivated'] and qualification['normalReopenNativeChecks']==46 and qualification['normalReopenNormalOwnedExits']==18 and qualification['hostLifecycleQuintScenarios']==9 and qualification['hostLifecycleInvariantSamples']==200 and qualification['hostLifecycleCoupledStages']==6 and qualification['normalRouteNativeChecks']==29 and qualification['normalRouteNormalOwnedExits']==13 and qualification['delayedResultNativeChecks']==18 and qualification['delayedResultNormalOwnedExits']==8 and qualification['fullBuildCommands']==119 and qualification['nativeGrantResets']==0 and not qualification['actualPendingIntentReopenQualified'] and not qualification['physicalRevealQualified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr('Reopen the native GUI with one persistent Elm policy\n\n'+held['scope'])+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('component-report130.json','component-report132.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v132',['PROGRESS PUBLIC97 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI132 actual normal GUI close/reopen two pointer cycles/same policy/native binding/fresh fixed-grant pure renderer/strict C Bootstrap closes/epoch navigation lease request1->2/current source URI red19200 each/opacity0 closed output. Native14546checks18normalexits retains original29; Native14429/13 and delayed14618/8 unchanged regressions/private cleanups pass. Full119, Quint9named200samples and six stages coupled to actual observations; failed131 held. Native issuer/policy/physical product/deadlines unchanged/no resets; pending-intent code/model only not actual qualified, broader async/process/reload/Unknown/physical ongoing conceal reveal hardware/pressure workload RSS/full preview/release open. Next fresh actual pending-intent and old-context qualification; installed/drafts/foreign preserved.'],'progress',['docs/warlock-preview/v93/component-report132.json','implementation/warlock-preview-provider-v132/component-manifest.json','implementation/warlock-client-provider-native-v145/component-manifest.json','docs/warlock-repository/v97/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace(oldbase,base).replace('Record public persistent policy realm reuse qualification','Record public normal GUI close and reopen qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit_gui130_policy_reuse.py').read_text().replace('5e59bb47962d5716b0fbc46271eebe3ec3fd03b4',local).replace('Preserve one Elm policy across normally retired native preview realms','Reopen the native GUI with one persistent Elm policy')
a=s.index('for name,passed in ');b=s.index(':\n root=',a);s=s[:a]+'for name,passed in '+repr(components)+s[b:]
a=s.index('for base in [');b=s.index(':\n for p in',a);s=s[:a]+"for base in [r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v97/publication']"+s[b:]
p=r/'docs/warlock-preview/v93/commit_gui132_normal_reopen.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
