"""Prepare held native129/Core19 qualification publication over verified public73."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v74/publication';assert not out.exists();out.mkdir(parents=True)
base='daed06a2a125f729eb5e9ec3ddf585d160031247';local='448b229ee11a4bb2299e7099e7306c45e5865108';previous='9a47a8668676458f6eaf01116a654a690c910806'
proof=json.loads((r/'docs/warlock-preview/v93/native-report129.json').read_text());assert proof['passed'] and proof['nativeChecks']==2517 and proof['normalOwnedExits']==278 and proof['captureResourceControls']==49 and proof['prior128FixedOrderedControls']==2459
minimum=len(json.loads((r/'implementation/warlock-client-provider-native-v129/component-manifest.json').read_text())['files'])
prior=r/'docs/warlock-repository/v73/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='b4a72a5ce672dd05647c256ab5ef4b60aad5eddb'","BASE='"+base+"'").replace('1387ee79b973310c060e68e20b6e2ec2ac0d9aa8..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v73/publication/','docs/warlock-repository/v74/publication/','implementation/warlock-client-provider-native-v129/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
message='Qualify scoped native capture resource recovery on the owning Core pair\n\nRetain the complete GUI92/native128 campaign on exact core16/plugin19 and add real kernel-authenticated scoped capture/export/producer observations and cleanup. Actual private session lock preserves owned producer retirement, fresh original-target observation repairs application-dropped acknowledgements, and imported sealed SCM_RIGHTS descriptors remain independent from backend zero until explicit local close. Old capture targets cannot erase a different current capture; foreign bindings, subjects and transfers refuse without resource/sequence mutation. Native2517 checks/278 normal exits/full cleanup retain2459 original128 and2458 original126 fixed controls plus actual allocator attempts within original expiry. New resource phase49 controls/11 snapshots/two imported descriptors closed. Held106 control/reader/adoption/compiled Elm fixes remain separately CPU-qualified and inactive; this campaign retains the legacy GUI92 runtime and does not establish new controlled factory/WebKit integration. Preserve all source/ABI hashes, pixel oracles, deadlines and teardown. Ordinary eligible capture, live-window binding detachment, renderer native tickets, real-window turnover and full release gates remain open; no installed changes.\n'
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/native-report129.json').read_text());assert qualification['passed'] and qualification['nativeChecks']==2517 and qualification['normalOwnedExits']==278 and qualification['prior128FixedOrderedControls']==2459 and qualification['prior126FixedOrderedControls']==2458 and qualification['captureResourceControls']==49 and qualification['captureResourceSnapshots']==11 and qualification['actualImportedDescriptorsClosed']==2 and qualification['captureResourceEvidence']['actualCoreRegistryAndResources'] and qualification['captureResourceEvidence']['actualSessionLock'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v73','warlock-repository/v74').replace('component-report106.json','native-report129.json')
old="d['ownedFiles']>=6464";assert s.count(old)==1;s=s.replace(old,"d['ownedFiles']>="+str(minimum))
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v129',['PROGRESS PUBLIC74 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldNative129 on exactcore16/plugin19,retainedGUI92 legacy runtime:2517 checks/278 normal exits/full cleanup,2459 original128 and2458 original126 fixed controls plus original allocator/expiry;actual49 resource/registry/capture/lock/SCM_RIGHTS controls,11 snapshots/two local FD closures. Held106 local C/GIO/adoption/Elm/full95 inactive CPU source remains public73. Next distinct live-window preview-binding detachment/native receiver freshness, current controlled path/renderer native outbox/WebKit integration. All original full-release gates remain open; no installed changes.'],'progress',['docs/warlock-preview/v93/native-report129.json','implementation/warlock-client-provider-native-v129/component-manifest.json','docs/warlock-repository/v74/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('b4a72a5ce672dd05647c256ab5ef4b60aad5eddb',base).replace('Record public imported storage and read reconciliation','Record public Core capture resource qualification');assert s.count(old)==1;s=s.replace(old,"d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit106-v2.py').read_text().replace('972f7a1f0c44da9fd6f28b1e0cfeb17f91cf2101',local).replace("[('warlock-preview-provider-v106',True)]","[('warlock-client-provider-native-v129',True)]").replace('warlock-repository/v73/publication','warlock-repository/v74/publication').replace('Revoke reconciled preview reads and retain adopted storage through cleanup','Qualify scoped native capture resource recovery on the owning Core pair')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit129.py';assert not p.exists();p.write_text(s)
print(out)
