"""Prepare exact Native130 current-host native qualification publication."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v79/publication';assert not out.exists();out.mkdir(parents=True)
base='4ffd7371e6f172b3f5fe19abc6345ddd55abc8c1';local='302730c0059575b5b29f79ebc290233c8f9f7e4f';previous='cf347c314d8856fbea327a79f5ef862d618c4840'
proof=json.loads((r/'docs/warlock-preview/v93/native-report130.json').read_text());assert proof['passed'] and proof['nativeChecks']==2518 and proof['normalOwnedExits']==278 and proof['currentGUI110LegacyRuntimeQualified']
minimum=len(json.loads((r/'implementation/warlock-client-provider-native-v130/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v78/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='33f0afa16104467c36dc8aea9a75d028a0d55aef'","BASE='"+base+"'").replace('25efdc897243360a0e4878036b1768418902f2b6..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v78/publication/','docs/warlock-repository/v79/publication/','implementation/warlock-client-provider-native-v130/'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/native-report130.json').read_text());assert qualification['passed'] and qualification['nativeChecks']==2518 and qualification['normalOwnedExits']==278 and qualification['currentGUI110LegacyRuntimeQualified'] and qualification['prior129FixedOrderedControls']==2509 and qualification['prior128FixedOrderedControls']==2459 and qualification['prior126FixedOrderedControls']==2458 and not qualification['newURIRouterActivated'] and not qualification['newControlledFactoryActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Qualify current GUI110 legacy runtime on the owning compositor pair\n\n'+proof['scope']+'\n\n2518 checks and 278 normal owned process exits with full cleanup. Retained original129/128/126 fixed controls, actual allocator attempts and original expiry/deadlines. Actual scoped Core resource/FD/private-lock witnesses remain. New controlled factory, URI router and scoped detachment are inactive. Full release gates remain open.'
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v78','warlock-repository/v79').replace('component-report110.json','native-report130.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v130',['PROGRESS PUBLIC79 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Native130 current GUI110 compiled legacy runtime/core16/plugin19/AQ155 passes2518 checks/278 normal owned exits/full cleanup,2509 prior129/2459 prior128/2458 prior126 fixed controls with actual allocator/original expiry.49 Core resource witnesses/11 snapshots/two independent FD closes. New URI router/controlled/scoped path inactive; historical GUI92 probes retain original identity. Next typed realm/native-issued renderer outbox and actual WebKit/Core activation, all original release gates open. No installed changes.'],'progress',['docs/warlock-preview/v93/native-report130.json','implementation/warlock-client-provider-native-v130/component-manifest.json','docs/warlock-repository/v79/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('4ffd7371e6f172b3f5fe19abc6345ddd55abc8c1',base).replace('33f0afa16104467c36dc8aea9a75d028a0d55aef',base).replace('Record public native URI callback lifetime qualification','Record public current-host native qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit110.py').read_text().replace('435d99e329de62444bdb22a6413d0cc0b0391d36',local).replace("[('warlock-preview-provider-v110',True)]","[('warlock-client-provider-native-v130',True)]").replace('warlock-repository/v78/publication','warlock-repository/v79/publication').replace('Guard native URI callbacks with exact Endpoint lifetime and receiver epoch','Qualify current GUI110 legacy runtime on the owning compositor pair')
a=s.index('ownedTracked=');b=s.index('\nforeign=',a);s=s[:a]+"ownedTracked={'docs/warlock-preview/v93/HANDOFF.md'}"+s[b:]
ast.parse(s);p=r/'docs/warlock-preview/v93/commit130.py';assert not p.exists();p.write_text(s);print(out)
