"""Prepare exact owned admission and native purpose-issuer publication."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v70/publication';assert not out.exists();out.mkdir(parents=True)
base='0e60cf3adefd85be3407503351315d4472a10c9b';local='fcfe28956f8dfd71642e7632b84d8e3b22c7cb4d';previous_source='601b6d42830da1aa0b4a27d5f61f0c67a209f342'
proof=json.loads((r/'docs/warlock-preview/v93/component-report101.json').read_text());assert proof['passed'] and proof['nativePurposeSocketControls']==70 and proof['nativePurposeStates']==299 and proof['fullBuildCommands']==95
minimum=sum(len(json.loads((r/('implementation/warlock-preview-provider-v'+str(n))/'component-manifest.json').read_text())['files']) for n in [100,101])
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(r/'docs/warlock-repository/v69/publication/publish.py').read_text().replace("BASE='3a185885ae0ef3c1f3d45cc6c7508e77441f30d1'","BASE='"+base+"'").replace('1a54b79945a5be37a1096aecd1bddecc0e4f2457..',previous_source+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v69/publication/','docs/warlock-repository/v70/publication/','implementation/warlock-preview-provider-v100/','implementation/warlock-preview-provider-v101/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Guard native admission and issue original purpose-validated control tickets\n\nIntegrate opt-in cleanup credit guards with actual ImportedClients start/resume. Native receiver and owning Broker are established before admission; old physical/proof barriers and frontend confirmation precede resume queries and new intent/job mutation. GUI100 passes40 authenticated synthetic socket controls,15 selected Quint scenarios/23 native traces/191 comparisons/six compiled variants,95 full-host build commands and all12 unchanged original regression suites. GUI101 validates actual original jobs, packets and terminal proofs before native purpose-slot/ordinal assignment. Exact post-effect ACK retries retain their original ticket after Broker record removal. Confirmed job quota release retains one bounded predecessor per actual actor, exposing only already-delivered identity without a live invocation ticket.70 socket controls and15 selected scenarios/23 actual native traces/299 comparisons/four compiled variants pass. Changed reservation and admission models are requalified;69 actual optimized Elm/native Broker/real URI cleanup controls still pass with25 repeated ACKs. GUI101 full95-command build passes; GUI100 twelve suites are retained with unchanged scripts, Elm/assets and default C factory/shared-host flow, not claimed rerun101. Failed fixture compile remains preserved. No capture, WebKit activation, real actor/host close or full GUI acceptance. Controlled C provider/routing, physical and actor quota release, original receiver reconciliation and native-assigned renderer outbox remain open. Qualified runtime GUI92/native128/core16/plugin18 and all original deadlines/release gates remain unchanged.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report101.json').read_text());assert qualification['passed'] and qualification['nativePurposeSocketControls']==70 and qualification['nativePurposeScenarios']==15 and qualification['nativePurposeTraces']==23 and qualification['nativePurposeStates']==299 and qualification['nativePurposeCompiledVariants']==4 and qualification['compiledElmNativeQuotaControls']==69 and qualification['fullBuildCommands']==95 and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:];put('publish.py',s)
s=(r/'docs/warlock-repository/v69/publication/record_delivery.py').read_text().replace('warlock-repository/v69','warlock-repository/v70').replace('component-report99.json','component-report101.json').replace("d['ownedFiles']>=4638","d['ownedFiles']>="+str(minimum))
start=s.index('e=loop.write_checkpoint(');s=s[:start]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v101',['PROGRESS PUBLIC70 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held100 actual admission40 socket controls,15/23/191/six,95build,12 original suites. Held101 native purpose issuer70socket controls,15/23/299/four variants,bounded confirmed predecessor; reservation/admission requalified;69compiledElm/nativeURI controls;95build. GUI10012suites retained unchanged,notrerun101. Failed fixture compile retained. NoWebKit/capture/realactor-hostclose/fullGUI claim. Next actualphysical/actor quota release,Cprovider/routing,reconciliation,native-assigned renderer outbox. QualifiedGUI92/native128/core16/plugin18 and alloriginalgates unchanged.'],'progress',['docs/warlock-preview/v93/component-report101.json','implementation/warlock-preview-provider-v101/component-manifest.json','docs/warlock-repository/v70/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(r/'docs/warlock-repository/v69/publication/commit_receipt.py').read_text().replace('3a185885ae0ef3c1f3d45cc6c7508e77441f30d1',base).replace('Record public native cleanup reservation and controlled decoder qualification','Record public guarded admission and native ticket issuer qualification').replace("d['ownedFiles']>=4638","d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit99.py').read_text().replace('0d26d7bf63411aed795ab434b45376868b2e2e23',local).replace("[('warlock-preview-provider-v97',True),('warlock-preview-provider-v98',False),('warlock-preview-provider-v99',True)]","[('warlock-preview-provider-v100',True),('warlock-preview-provider-v101',True)]").replace('warlock-repository/v69/publication','warlock-repository/v70/publication').replace('Reserve native cleanup capacity before original job issuance','Guard native admission and issue immutable purpose-validated control tickets');ast.parse(s);(r/'docs/warlock-preview/v93/commit101.py').write_text(s)
print(out)
