"""Retain current-failure oracle separately; demand actual ordered native drain."""
import ast,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
docs=pathlib.Path(__file__).parent;p=docs/'native168_current_failure_drain_runner.py';assert not p.exists();s=(docs/'native166_current_failure_runner.py').read_text()
s=s.replace('"""Actual matching-current WebKit cancellation, expected failure without settlement."""','"""Actual current failure must drain original native custody before failure exit."""')
needle="   check('controlledCurrentFailureRetainsOriginalNativeCustody',last is not None and not last['privatePolicy']['realm']['closed'] and bool(last['privatePolicy']['models']) and 'Controlled native teardown incomplete: Original policy/input/ticket/physical/journal/confirmation custody prevents realm retirement' in text,state=last)";assert s.count(needle)==1
s=s.replace(needle,"   check('controlledCurrentFailureNativeCustodyDrainedBeforeFailureExit',last is not None and last['privatePolicy']['realm']['closed'] and not last['privatePolicy']['models'] and not last['retainedInputs'] and not last['postedTickets'] and not last['confirmations'] and not last['returnedEventBatches'] and last['transport']['pending']==0 and 'controlled-native-realm-retired: epoch=1 ' in text and 'Controlled native teardown incomplete:' not in text,state=last)")
needle="'controlled-native-reopened:' not in text and 'controlled-native-realm-retired:' not in text and 'controlled-native-snapshot-held:' not in text";assert s.count(needle)==1;s=s.replace(needle,"'controlled-native-reopened:' not in text and 'controlled-native-snapshot-held:' not in text")
s=s.replace('actualCurrentFailureNativeCustodyRetained=True','actualCurrentFailureNativeCustodyDrained=True').replace('gracefulCurrentFailureDrainQualified=False','gracefulCurrentFailureDrainQualified=True');ast.parse(s);p.write_text(s)
s=(docs/'prepare_native166_current_snapshot_failure.py').read_text();needle="root=repo/'implementation/warlock-client-provider-native-v166';provider=repo/'implementation/warlock-preview-provider-v138'";assert s.count(needle)==1;s=s.replace(needle,"root=repo/'implementation/warlock-client-provider-native-v168';provider=repo/'implementation/warlock-preview-provider-v138'").replace("'native166_current_failure_runner.py'","'native168_current_failure_drain_runner.py'").replace('ownNative166','ownNative168')
a=s.index(";pre.update(popupCurtainOracle=");b=s.index('\nassert all',a)
scope='Distinct actual current WebKit cancellation with original admission/current-scope/real canceled-result/finish-once/failure1/no-artifact checks retained from Native166. Additional mandatory original native drain oracle requires last retained policy realm closed/no models/input/tickets/confirmation/batches/pending transport, original actual strict native realm retirement and no incomplete teardown BEFORE original expected failure exit1, under unchanged observer six seconds/core16/plugin19/AQ155. Native166 original strict-refusal negative control remains separately held; this probe may fail and must not be reclassified as accepted drain. Does not qualify current error as success/normal-exit, fabricate settlement or extend deadlines; no renderer/Native authority or physical/full-release changes.'
s=s[:a]+";pre.update(popupCurtainOracle=str(oracleReport.parent/'popup-curtain-oracle'),popupCurtainOracleBuild=str(oracleReport),scope="+repr(scope)+')'+s[b:]
q=docs/'prepare_native168_current_failure_drain_package.py';assert not q.exists();ast.parse(s);q.write_text(s);print(p);print(q)
