"""Prepare exact held single Elm realm policy publication under existing authorization."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v83/publication';assert not out.exists();out.mkdir(parents=True)
base='0670a4500e3b668285b43e163adda958d1996f82';local='a470c667232b0e4a6b9044e79bf3a4647e003e42';previous='d7ff0259f7a6bf3783ee44d45d48966ce604e0ba'
proof=json.loads((r/'docs/warlock-preview/v93/component-report114.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['nativeElmOutboxChecks']==192 and proof['ingressStates']==300
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v114/component-manifest.json').read_text())['files']);prior=r/'docs/warlock-repository/v82/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='a03d4953d8ed1ab2f500ababc1dbdc5a0c367ce8'","BASE='"+base+"'").replace('0da2d5bf6c4565345cd150c30d7225f6065dab11..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v82/publication/','docs/warlock-repository/v83/publication/','implementation/warlock-preview-provider-v114/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report114.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['singlePreviewPolicy'] and qualification['nativeElmOutboxChecks']==192 and qualification['packetizerChecks']==43 and qualification['ingressScenarios']==12 and qualification['ingressTraces']==22 and qualification['ingressStates']==300 and qualification['unsafeCompiledNativeVariantsDetected']==5 and qualification['fullBuildCommands']==104 and qualification['originalBuildCommands']==103 and qualification['resourceRegressionSuites']==4 and qualification['scopedRegressionSuites']==4 and len(qualification['heldFailedReports'])==1 and not qualification['proposalRetentionQualified'] and not qualification['popupTypedPortsWebKitExecuted'] and not qualification['fullElmRecoveryQualified'] and not qualification['typedHostRoutingActivated'] and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Validate native proposal ingress and compile typed Popup realm ports\n\n'+proof['scope']
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v82','warlock-repository/v83').replace('component-report113.json','component-report114.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v114',['PROGRESS PUBLIC83 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI114 native proposal ingress/C+Elm+outbox192/two epochs/unchanged Native grant/normal exits; pure packetization43; Quint12/22 actualC traces/300 states/200 samples/five compiled variants; full104 retains103; current resource4+scoped4. Failed runner/freezer attempts retained. Popup typed ports compiled only, actual WebKit execution and host activation unqualified. Next GUI115 retain original Elm proposals before native ticket issuance; full Elm recovery/actual WebKit/Core/window and original release gates remain. Native130 legacy2518/278/full cleanup remains actual baseline; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report114.json','implementation/warlock-preview-provider-v114/component-manifest.json','docs/warlock-repository/v83/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('a03d4953d8ed1ab2f500ababc1dbdc5a0c367ce8',base).replace('Record public single Elm preview realm qualification','Record public native proposal ingress qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit113.py').read_text().replace('5ca2631493281c0adcc21e07b798ac4506a00bac',local).replace("[('warlock-preview-provider-v113',True)]","[('warlock-preview-provider-v114',True)]").replace('warlock-repository/v82/publication','warlock-repository/v83/publication').replace('Integrate native preview realms and scoped detachment in the single Elm policy','Validate native proposal ingress and compile typed Popup realm ports')
p=r/'docs/warlock-preview/v93/commit114.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
