"""Publish current native legacy coherence with all original source/control custody."""
import ast,json,pathlib,re,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v89/publication';assert not out.exists();out.mkdir(parents=True)
base='2b6f8fb433eccb956449be3a6d4c0508d2dfb743';local='a9994a5ebca127298d7b450b18dcf745eaa00402';previous='73e6fb1bee3133084da6ae4871d9a9ef9664195b'
root=r/'implementation/warlock-client-provider-native-v131';proof=json.loads((r/'docs/warlock-preview/v93/native-report131.json').read_text());held=json.loads((root/'component-manifest.json').read_text());assert held['sourceHeld'] and held['passed'] and proof['passed'] and held['nativeChecks']==2518 and held['normalOwnedExits']==278 and held['currentGUI119LegacyRuntimeQualified']
minimum=len(held['files']);prior=r/'docs/warlock-repository/v88/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='8bc0b5dd33e97f06e37284d0ca518db4d8e829fb'","BASE='"+base+"'").replace('e17f3e5dcb66a3a3cc083e83dcfc6951580e5234..',previous+'..')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(('docs/warlock-preview/v93/','docs/warlock-repository/v88/publication/','docs/warlock-repository/v89/publication/','implementation/warlock-client-provider-native-v131/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md'))+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/native-report131.json').read_text());assert qualification['passed'] and qualification['nativeChecks']==2518 and qualification['normalOwnedExits']==278 and qualification['currentGUI119LegacyRuntimeQualified'] and qualification['prior130FixedOrderedControls']==2510 and qualification['captureResourceControls']==49 and qualification['captureResourceSnapshots']==11 and qualification['actualImportedDescriptorsClosed']==2 and not qualification['nativePersistentPolicyActivated'] and not qualification['nativeVisualChannelActivated'] and not qualification['pureRendererActivated'] and not qualification['newURIRouterActivated'] and not qualification['newControlledFactoryActivated'] and not qualification['ordinaryEligibleCaptureAccepted'] and not qualification['actorTurnoverAccepted'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
message='Qualify the current legacy provider on its owning native tuple\n\n'+held['scope']+'\n\nActual2518 checks/278 normal exits/full cleanup retain all2510 original130 fixed ordered controls and actual allocator trials/original expiry/deadlines/pixels/receipts/teardown. Resource49/scoped snapshots11/independent FD closures2 remain. New JSC policy/channel/pure renderer/controlled URI route stays inactive. Fresh count audit retains optional polling evidence: five actual polling rows versus six in130, no changed campaign or oracle. All full release gates remain open; no installed changes.'
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v88','warlock-repository/v89').replace('component-report119.json','native-report131.json');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1
a=s.index('e=loop.write_checkpoint(');s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v131',['PROGRESS PUBLIC89 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Native131 current GUI119 legacy host/assets/backend on core16/plugin19/AQ155: actual2518 checks/278 normal owned exits/full cleanup, all2510 original130 fixed controls plus actual allocator/original expiry/deadlines/pixels/receipts/teardown retained. Resource49/snapshots11/independent FD closures2. Shared visual helper refactor qualifies current actual legacy DOM/host only. Native JSC policy/channel/pure renderer/controlled URI route remains inactive. Failed nominal count freezer preserved; v2 audits original optional readonly polling counts without changing any campaign/oracle/deadline. Next actual controlled host durable input/native-ticket custody/retry and WebKit callback/lease/async frame/physical concealment/URI barriers. GUI119 CPU channel/pure renderer/full115 remains separate. Uncertain worker/revoked delayed proposals/>256 actual native windows/full release gates stay open; installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/native-report131.json','implementation/warlock-client-provider-native-v131/component-manifest.json','docs/warlock-repository/v89/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('8bc0b5dd33e97f06e37284d0ca518db4d8e829fb',base).replace('Record public ordered visual custody qualification','Record public current native legacy qualification');s,n=re.subn(r"d\['ownedFiles'\]>=\d+","d['ownedFiles']>="+str(minimum),s);assert n==1;put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit119.py').read_text().replace('8399dd6e5f7eef07ae6acaa02b142bafc908fe80',local).replace("[('warlock-preview-provider-v119',True)]","[('warlock-client-provider-native-v131',True)]").replace('warlock-repository/v88/publication','warlock-repository/v89/publication').replace('Retain ordered visual snapshots in native context custody','Qualify the current legacy provider on its owning native tuple')
p=r/'docs/warlock-preview/v93/commit_native131.py';assert not p.exists();ast.parse(s);p.write_text(s);print(out)
