"""Prepare exact owned GUI106 publication over verified public72."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=r/'docs/warlock-repository/v73/publication';assert not out.exists();out.mkdir(parents=True)
base='b4a72a5ce672dd05647c256ab5ef4b60aad5eddb';local='972f7a1f0c44da9fd6f28b1e0cfeb17f91cf2101';previous='1387ee79b973310c060e68e20b6e2ec2ac0d9aa8'
proof=json.loads((r/'docs/warlock-preview/v93/component-report106.json').read_text());assert proof['sourceHeld'] and proof['passed'] and proof['importedResourceStates']==373 and proof['importedElmChecks']==24 and proof['fullBuildCommands']==95
minimum=len(json.loads((r/'implementation/warlock-preview-provider-v106/component-manifest.json').read_text())['files'])
prior=r/'docs/warlock-repository/v72/publication'
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(prior/'publish.py').read_text().replace("BASE='359f68251029daf00f15fa2a927614ff5bc5401e'","BASE='"+base+"'").replace('f2ffafa0b0514d7542541d1aa11d54113d56a169..',previous+'..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v72/publication/','docs/warlock-repository/v73/publication/','implementation/warlock-preview-provider-v106/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
a=s.index('allowed=');b=s.index('\nassert all',a);s=s[:a]+'allowed='+repr(allowed)+s[b:]
a=s.index(' qualification=');b=s.index('\n published=',a)
message='Revoke reconciled preview reads and retain adopted storage through cleanup\n\nShare one actual Native binding quarantine with existing and new URI authorization, while readers retain original storage until physical drain. Preserve actual mapping custody after Broker adoption commits and result allocation throws; scoped backend, producer, reader and local FD barriers yield Released/Cancelled before final ACK. Confirmed binding reconciliation reproposals retain the same native ticket/ordinal and suppress stale dispatch after later controls. CPU scope:49 mapped-reader and40 post-transfer allocator controls/two compiled unsafe variants;24 optimized Elm and actual mapped-native final ACK controls/two normal exits;14 selected local Quint scenarios/22 compiled C/GIO traces/373 states/three variants. Current resource477 C/six cases+35 decoder/four variants,resource14/22/349/three,original capture14/66/816/three,controlled C10190/260 metadata actors/1041 tickets and full95 host commands pass. Exact held core16/plugin19. Preserve failed attempts, original deadlines and source inventory. Actual Core registry/resource capture pixels, live-window binding detachment, renderer native tickets/WebKit and full release remain open. Qualified bounded GUI92/native128/core16/plugin18 is unchanged; no installed desktop changes.\n'
q=" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report106.json').read_text());assert qualification['sourceHeld'] and qualification['passed'] and qualification['actualReaderChecks']==49 and qualification['actualPostTransferChecks']==40 and qualification['fdCompiledVariants']==2 and qualification['importedElmChecks']==24 and qualification['importedResourceScenarios']==14 and qualification['importedResourceTraces']==22 and qualification['importedResourceStates']==373 and qualification['importedResourceCompiledVariants']==3 and qualification['resourceCChecks']==477 and qualification['resourceDecoderChecks']==35 and qualification['resourceCCompiledVariants']==4 and qualification['captureTraces']==66 and qualification['captureStates']==816 and qualification['controlledCChecks']==10190 and qualification['fullBuildCommands']==95 and not qualification['webKitActivated'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']"
s=s[:a]+q+'\n message='+repr(message)+'\n'+s[b:];put('publish.py',s)
s=(prior/'record_delivery.py').read_text().replace('warlock-repository/v72','warlock-repository/v73').replace('component-report105.json','component-report106.json').replace("d['ownedFiles']>=10076","d['ownedFiles']>="+str(minimum))
a=s.index('e=loop.write_checkpoint(')
s=s[:a]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v106',['PROGRESS PUBLIC73 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held GUI106 actual FD/GIO49+allocator40/two variants,compiled Elm/native ACK24/two normal exits,local14/22/373/three variants;current resource477+35/four,resource14/22/349/three,capture14/66/816/three,C10190/260/1041 and full95. Next real Core19 capture-resource protocol/native qualification, live-window binding detachment and renderer native tickets/WebKit. QualifiedGUI92/native128/core16/plugin18 and original full-release gates unchanged; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report106.json','implementation/warlock-preview-provider-v106/component-manifest.json','docs/warlock-repository/v73/publication/delivery.json']);print(e)\n";put('record_delivery.py',s)
s=(prior/'commit_receipt.py').read_text().replace('359f68251029daf00f15fa2a927614ff5bc5401e',base).replace('Record public original capture resource reconciliation','Record public imported storage and read reconciliation').replace("d['ownedFiles']>=10076","d['ownedFiles']>="+str(minimum));put('commit_receipt.py',s)
s=(r/'docs/warlock-preview/v93/commit105.py').read_text().replace('c6c8be67921938947fe106ced58d6b8bf0f8ba8f',local).replace("[('warlock-preview-provider-v104',True),('warlock-preview-provider-v105',True),('warlock-family-style-crop-capture-v19',True)]","[('warlock-preview-provider-v106',True)]").replace('warlock-repository/v72/publication','warlock-repository/v73/publication').replace('Retain original capture intent and reconcile scoped native resources','Revoke reconciled preview reads and retain adopted storage through cleanup')
ast.parse(s);p=r/'docs/warlock-preview/v93/commit106.py';assert not p.exists();p.write_text(s)
print(out)
