"""Prepare exact bounded polling publication and raw-byte owned commit."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');out=repo/'docs/warlock-repository/v66/publication';assert not out.exists();out.mkdir(parents=True)
base='d0372d2fe8a19048e404e364d2ca0c9f94b248b1'
proof=json.loads((repo/'docs/warlock-preview/v93/component-report94.json').read_text());assert proof['passed'] and proof['fairPollingControls']==50 and proof['fairPollingStates']==427
def put(name,s):ast.parse(s);(out/name).write_text(s)
s=(repo/'docs/warlock-repository/v65/publication/publish.py').read_text().replace("BASE='3cd4db6f232d185d8655de3b76106b2229da7272'","BASE='"+base+"'").replace('b0fbf91cc20661423c9f3b29784686f1b5e3c518..','b659e487649c867a0c36bac6bcd860d3961317ba..')
allowed=('docs/warlock-preview/v93/','docs/warlock-repository/v65/publication/','docs/warlock-repository/v66/publication/','implementation/warlock-preview-provider-v94/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Bound and rotate native retirement polling without weakening ownership barriers\n\nHeld GUI94 selects at most one accepted readiness candidate per call and rotates through pending rows. Original physical, producer, backend, terminal-proof and other-receiver barriers precede a fresh exact native Retired query. Full95 and byte-identical Elm assets pass45 processing controls. Actual C/native/Elm54 loss/ACK/receiver controls and50 C/socket exact-query-count, blocked-first/eligible-neighbor, terminal-proof, original actor floor, final retry and normal-close controls pass. Ten selected Quint scenarios/200 bounded samples match22 actual compiled native traces/427 states; three compiled mutations fail exact witnesses. Original9068 aggregate and14467 retained-channel controls retain280 synthetic subjects. Preserve failed model syntax fixture. This is a structural bound, not measured latency acceptance. Fully qualified runtime remains GUI92/native128/core16/plugin18. Actual WebKit routing, reliable outgoing control delivery/retry/ACK and native cleanup reservation before admission, receiver reload, captured retirement, real continuing windows and all original GUI release gates remain open.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report94.json').read_text());assert qualification['passed'] and qualification['buildCommands']==95 and qualification['fairPollingControls']==50 and qualification['fairPollingScenarios']==10 and qualification['fairPollingTraces']==22 and qualification['fairPollingStates']==427 and qualification['unsafeCompiledNativeMutantsDetected']==3 and qualification['aggregateRetirementControls']==9068 and qualification['retainedChannelControls']==14467 and qualification['unchangedElmAssetIdentityVerified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:]
put('publish.py',s)
s=(repo/'docs/warlock-repository/v65/publication/record_delivery.py').read_text().replace('warlock-repository/v65','warlock-repository/v66').replace('component-report.json','component-report94.json')
start=s.index('e=loop.write_checkpoint(')
s=s[:start]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v94',['PROGRESS PUBLIC66 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI94 fairpoll full95/identicalElm/45 controls/nativeElm54/Csocket50/Q10selected/22actualC++traces/427states/3compiledMutants and original9068aggregate/14467channel/280synthetic. FullyqualifiedGUI92/native128 stays unchanged. Next fresh bounded reliable outgoing control/retry/ACK/nativecleanupreservation/reload contract before actual WebKit activation. All original release gates remain.'],'progress',['docs/warlock-preview/v93/component-report94.json','implementation/warlock-preview-provider-v94/component-manifest.json','docs/warlock-repository/v66/publication/delivery.json']);print(e)\n"
put('record_delivery.py',s)
s=(repo/'docs/warlock-repository/v65/publication/commit_receipt.py').read_text().replace('3cd4db6f232d185d8655de3b76106b2229da7272',base).replace('Record public retained native readiness qualification','Record public bounded fair retirement polling qualification')
put('commit_receipt.py',s)
s=(repo/'docs/warlock-preview/v93/commit_owned.py').read_text().replace('be920333162ceabea225bde044f1b1457fa250a0','c7584a62e5e2dbf270079092a7ea49d74cbb6f0f').replace("[('warlock-preview-provider-v93',True)]","[('warlock-preview-provider-v94',True)]")
s=s.replace("[r/'docs/warlock-preview/v91',r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v65/publication']","[r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v66/publication']").replace('Retain exact Elm readiness until native receiver barriers clear','Bound and rotate native retirement polling while preserving ownership barriers')
ast.parse(s);(repo/'docs/warlock-preview/v93/commit94.py').write_text(s);print(out)
