"""Own the actual native policy/transport driver before controlled WebKit activation."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v119';root=repo/'implementation/warlock-preview-provider-v120';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=parent/'component-manifest.json';d=json.loads(m.read_text());assert d['sourceHeld'] and d['passed'] and d['fullBuildCommands']==115 and d['orderedVisualCustodyCPUQualified'] and not root.exists()
for rel,row in d['files'].items():assert sha(parent/rel)==row['sha256'],rel
native=repo/'implementation/warlock-client-provider-native-v131/component-manifest.json';n=json.loads(native.read_text());assert n['sourceHeld'] and n['passed'] and n['currentGUI119LegacyRuntimeQualified'] and n['nativeChecks']==2518 and n['normalOwnedExits']==278
for rel,row in n['files'].items():assert sha(native.parent/rel)==row['sha256'],rel
def ignore(path,names):
 if pathlib.Path(path)==parent:return [n for n in names if n in {'component-manifest.json','ANCESTRY.json','__pycache__'}]
 if pathlib.Path(path)==parent/'qa':return [n for n in names if (pathlib.Path(path)/n).is_dir() and n!='toolchain']
 return [n for n in names if n in {'__pycache__','elm-stuff'}]
shutil.copytree(parent,root,ignore=ignore)
(root/'ANCESTRY.json').write_text(json.dumps({'owner':d['owner'],'parent':str(parent),'parentManifestSHA256':sha(m),'nativeBaselineManifest':str(native),'nativeBaselineManifestSHA256':sha(native),'purpose':'Integrate original persistent Elm policy and native-issued outbox into a creator-owned native host driver with original domain stamping before JS, exact input retention/backpressure, ticket custody before issued notification or dispatch, deferred native callbacks and independent receipt confirmation. Preserve every original native effect/physical/deadline gate; actual pure WebKit host activation/reload/DOM/concealment/URI remains explicit.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
print(loop.write_checkpoint(repo,d['owner'],str(root.relative_to(repo)),['PROGRESS ownGUI120 actual native host policy/transport driver. Parent119 native lease/ordered visual custody/pure receiver and full115 held/PUBLIC88; current actual native131 GUI119 legacy2518/278 all original1302510 fixed controls preserved/PUBLIC89. Driver integrates the original JSC Elm worker and unchanged native-issued outbox; stamp original native domain before JS, retain ordinary input on WOULD_BLOCK, keep urgent quarantine available, retain exact ticket before issued notification/dispatch, drain deferred callback outputs only after JS returns, preserve independent data receipt confirmation. First actual Native/C/JSC qualification, then controlled host WebKit projection/lease/frame/concealment/URI and input scheduling activation. No alternate window policy, Native grant reset, changed deadlines/oracles, installed changes or foreign paths. Full release remains open.'],'progress',[str(m.relative_to(repo)),str(native.relative_to(repo)),str((root/'ANCESTRY.json').relative_to(repo))]))
