"""Publish held native readiness component separately from runtime acceptance."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');proof=json.loads((repo/'docs/warlock-preview/v93/component-report.json').read_text())
assert proof['passed'] and proof['buildCommands']==95 and proof['readinessNativeElmControls']==54 and proof['readinessStates']==384
out=repo/'docs/warlock-repository/v65/publication';assert not out.exists();out.mkdir(parents=True)
def put(name,s):ast.parse(s);(out/name).write_text(s)
base='3cd4db6f232d185d8655de3b76106b2229da7272'
s=(repo/'docs/warlock-repository/v64/publication/publish.py').read_text().replace("BASE='bc6dfc11c5efcf9447fb325d678a2e4b7aed4afa'", "BASE='"+base+"'").replace('50d42b2b6bdd0f11c19d071e2847f5fce46cb3bf..','b0fbf91cc20661423c9f3b29784686f1b5e3c518..')
allowed=('docs/warlock-preview/v91/','docs/warlock-preview/v93/','docs/warlock-repository/v64/publication/','docs/warlock-repository/v65/publication/','implementation/warlock-preview-provider-v93/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Retain exact Elm readiness until native receiver barriers clear\n\nHeld GUI93 retains validated readiness in its existing bounded native journal row, preserving original receiver epoch/binding and all physical/proof/receiver barriers. Native polling retries the retained input without another Elm effect or replay of capture/release/terminal ACK. Current full95 build and byte-identical Elm assets pass45 processing-prefix controls. Actual C/socket/native/compiled Elm54 controls validate a real second receiver barrier, completion after it clears without another readiness effect, lost final delivery and processing ACK, original neighbor/counter and normal confirmed close. Eight explicitly selected Quint scenarios/200 sampled30-step runs match20 actual C++ journal traces/384 states, and three separately compiled native mutations fail exact witnesses. Preserve reserved-name Quint and fake-clock fixture failures. This journal is transport metadata; trusted commit is not a physical proof or a second Elm policy. The fully qualified runtime remains GUI92/native128/core16/plugin18 with2466 checks/277 normal exits and all original gates. GUI93 readiness API is not yet wired through WebKit. Bounded outgoing control delivery/retry/ACK, cleanup reservation, reload/namespace/fairness/budgets, actual host retirement routing, captured resources, >256 real windows and all original GUI release gates remain open.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v93/component-report.json').read_text());assert qualification['passed'] and qualification['buildCommands']==95 and qualification['readinessNativeElmControls']==54 and qualification['readinessScenarios']==8 and qualification['readinessTraces']==20 and qualification['readinessStates']==384 and qualification['unsafeCompiledNativeMutantsDetected']==3 and qualification['unchangedElmAssetIdentityVerified'] and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:]
put('publish.py',s)
s=(repo/'docs/warlock-repository/v64/publication/record_delivery.py').read_text().replace('warlock-repository/v64','warlock-repository/v65')
start=s.index("report=json.loads(");end=s.index('\nsys.path.insert',start);s=s[:start]+"report=json.loads((r/'docs/warlock-preview/v93/component-report.json').read_text())"+s[end:]
start=s.index("e=loop.write_checkpoint(");s=s[:start]+"e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v93',['PROGRESS PUBLIC65 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI93 full95/identicalElm/45controls and native readiness8selected/20actualC++traces/384states/3compiled mutants plus54CnativeElm receiver/loss/ACK/neighbor/close/normalexit controls. Qualified runtime staysGUI92/native128/core16/plugin18 PASS2466/277normal/all2458prior126fixed. No actual GUI/QA process is continuing; verify again on resume. Next own fresh host/transport derivative: freeze bounded retry/ACK/cleanup-reservation and epoch/reload contract, implement actual dispatcher/channel/observations/readiness/final retry without effect replay. Actual captured retirement, >256realwindows and all original release gates remain.'],'progress',['docs/warlock-preview/v93/component-report.json','implementation/warlock-preview-provider-v93/component-manifest.json','docs/warlock-repository/v65/publication/delivery.json']);print(e)\n"
put('record_delivery.py',s)
s=(repo/'docs/warlock-repository/v64/publication/commit_receipt.py').read_text().replace('bc6dfc11c5efcf9447fb325d678a2e4b7aed4afa',base).replace('Record public retained Elm completion qualification','Record public retained native readiness qualification')
put('commit_receipt.py',s)
s=(repo/'docs/warlock-preview/v91/commit_owned.py').read_text().replace('7e50cf82d6de4169eb25ada61c28be64220ba804','be920333162ceabea225bde044f1b1457fa250a0')
old="[('warlock-preview-provider-v91',True),('warlock-preview-provider-v92',True),('warlock-client-provider-native-v127',False),('warlock-client-provider-native-v128',True)]";assert s.count(old)==1;s=s.replace(old,"[('warlock-preview-provider-v93',True)]")
s=s.replace("[r/'docs/warlock-preview/v91',r/'docs/warlock-repository/v64/publication']","[r/'docs/warlock-preview/v91',r/'docs/warlock-preview/v93',r/'docs/warlock-repository/v65/publication']")
s=s.replace("assert set(git(['diff','--cached','--name-only'],text=True).splitlines())==paths","staged=set(git(['diff','--cached','--name-only'],text=True).splitlines());assert staged and staged<=paths")
s=s.replace('Qualify retained native completion processing in immutable Elm','Retain exact Elm readiness until native receiver barriers clear')
ast.parse(s);(repo/'docs/warlock-preview/v93/commit_owned.py').write_text(s)
print(out)
