import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=3859
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-curtain-control-report.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v127',['PROGRESS PUBLIC94 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. PositiveGUI127/Native13829checks13normalexits/native GTK paint/current geometry/private output region248976opaque samples no previewcolors, pure source reference19200red. Actual intentional unsafeGUI128/Native139 opacity1 exposes19200 previewpixels and byte-identical original native oracle rejects; host1/strict close refusal/privatecleanup/other normal exits retained. Full119/deadline6/core16/plugin19/AQ155 unchanged. Bounded region detector qualified; GTK phase is not compositor/hardware proof and ongoing transition concealment/reveal/stale callbacks/pressure/workload/RSS/recovery/full S09 preview13/release stay open. Next resume safe positiveGUI127 lineage for actual stale async callbacks and physical frame/reveal qualifications. Native13726/12 output observation preserved. Unsafe variant never installed/default accepted; installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-curtain-control-report.json','implementation/warlock-preview-provider-v127/component-manifest.json','implementation/warlock-client-provider-native-v138/component-manifest.json','implementation/warlock-preview-provider-v128/component-manifest.json','implementation/warlock-client-provider-native-v139/component-manifest.json','docs/warlock-repository/v94/publication/delivery.json']);print(e)
