import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=6009
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report115.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v115',['PROGRESS PUBLIC84 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI115 immutable retained intents/single unchanged window policy/urgent quarantine under blocked input: boundaries98/native C+Elm206/two epochs/unchanged Native grant/normal exits; ingress Quint16/28/468/six compiled variants; urgent6/18/406/two variants; cold256/3608 retains original1549 with synthetic ticket facts; wrapper legacy45/native20+C34; full108 retains104 and earlier106. Six failed attempts and original phase evidence held. Native/assets/adapters unchanged114; Popup typed ports compiled only. Next actual host input backpressure/issued facts/ticket custody/retry/persistent Elm policy lifetime and WebKit/Core activation, with delayed expiry/revocation outcome/order liveness qualification. All original release gates remain; Native130 legacy2518/278/full cleanup remains actual baseline; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report115.json','implementation/warlock-preview-provider-v115/component-manifest.json','docs/warlock-repository/v84/publication/delivery.json']);print(e)
