const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(__dirname+'/GlobalRoute.js','utf8').replace(/^\.pragma library\s*/,'');
const sandbox={module:{exports:{}},console};vm.runInNewContext(source,sandbox);const {GlobalRoute}=sandbox.module.exports;
const full={x:80,y:20,width:80,height:60},icon={x:180,y:0,width:10,height:10},identity=['0x10','abc',123],nativeRect={x:82,y:48,width:76,height:30};
function route(){return new GlobalRoute({identity,atlasIdentity:identity,completeAtlas:true,digest:'gold-red',full,icon,current:{x:130,y:10,width:45,height:35},nativeRect,outputs:['left','right'],destination:'right',topology:1,token:'session-1',operation:'minimize'})}
function reserve(r,operation='restore',token='session-2'){return r.reserve({identity,previousToken:r.token,token,operation})}
function proof(r){return {identity,token:r.token,nativeRect,digest:'gold-red',topology:1,familyValidated:true}}
let count=0;function test(name,f){f();count++;console.log('PASS '+name)}
test('immediate reversal moves pixels while validation is blocked',()=>{const r=route(),before=JSON.stringify(r.current);assert(reserve(r));assert.equal(JSON.stringify(r.current),before);r.tick(16);assert.notEqual(JSON.stringify(r.current),before);assert.equal(r.events.length,0);assert.equal(r.digest,'gold-red')});
test('unvalidated endpoint has no native authority',()=>{const r=route();reserve(r);r.tick(400);for(const o of r.outputs)r.present(o,r.token,1,r.current,400);assert.equal(r.events.length,0);assert.equal(r.phase,'provisional')});
test('promotion retains exact current rect texture and route progress',()=>{const r=route();reserve(r);r.tick(64);const at=JSON.stringify(r.current),p=r.progress;assert(r.promote(proof(r)));assert.equal(JSON.stringify(r.current),at);assert.equal(r.progress,p);assert.equal(r.digest,'gold-red')});
test('third request during blocked second keeps current visual origin',()=>{const r=route();reserve(r);r.tick(90);const at=JSON.stringify(r.current);assert(reserve(r,'minimize','session-3'));assert.equal(JSON.stringify(r.from),at);r.tick(16);assert.notEqual(JSON.stringify(r.current),at);assert.equal(r.digest,'gold-red')});
test('stale validation and replacement identity cannot promote',()=>{const r=route();reserve(r);const old=proof(r);reserve(r,'minimize','session-3');assert(!r.promote(old));assert(!r.promote({...proof(r),identity:['0x10','new',123]}));assert(!r.promote({...proof(r),familyValidated:false}));assert(!r.promote({...proof(r),nativeRect:{...nativeRect,width:77}}));assert.equal(r.events.length,0)});
test('all output presentation acknowledgements gate native ready',()=>{const r=route();reserve(r);r.promote(proof(r));r.present('left',r.token,1,r.current,16);assert.equal(r.events.length,0);r.present('right',r.token,1,r.current,17);assert.equal(r.events[0].kind,'ready')});
test('endpoint needs actual final frame from each output',()=>{const r=route();reserve(r);r.promote(proof(r));r.tick(16);for(const o of r.outputs)r.present(o,r.token,1,r.current,16);r.tick(400);r.present('left',r.token,1,r.current,400);assert.equal(r.events.length,1);r.present('right',r.token,1,r.current,401);assert.equal(r.events[1].kind,'done');assert.equal(r.phase,'idle')});
test('rejection uses prior fresh authority and current visual rectangle',()=>{const r=route();reserve(r);r.tick(80);const at=JSON.stringify(r.current);assert(!r.reject({identity,token:r.token}));assert(r.reject({identity,token:r.token,priorIntentFreshlyValidated:true}));assert.equal(JSON.stringify(r.from),at);r.tick(400);for(const o of r.outputs)r.present(o,r.token,1,r.current,400);assert.equal(r.events[1].kind,'rollbackDone');assert.equal(r.events[1].operation,'minimize')});
test('destination/output removal requires fresh service settlement',()=>{const r=route();reserve(r);r.removeOutput('right');r.tick(400);assert.equal(r.phase,'cancelled');assert.equal(r.events[0].kind,'needsFreshSettlement');assert(!r.promote(proof(r)))});
test('closed/reused route rejects old authority',()=>{const r=route();reserve(r);r.close();assert(!r.promote(proof(r)));assert.equal(r.digest,'');assert.equal(r.events.length,0)});
test('frame diagnostic retention is bounded',()=>{const r=route();reserve(r);for(let i=0;i<700;i++)r.present('left',r.token,1,r.current,i);assert.equal(r.frames.length,512);assert.equal(r.frames[0].time,188)});
console.log(count+' provisional route scenarios PASS');
