import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=2499
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report119.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v119',['PROGRESS PUBLIC88 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI119 native context/lease/separate visual sequence custody and pure receiver: actual C/JSC/Elm67/boundaries33/Quint14/26 C+JSC traces/451 observable states/200 samples/four compiled guards/two seeded exhaustion boundaries; original native207+90+74 unchanged grant/normal; full115 retains112. One header compile failure held. Parent policy/issuer/effects/physical/assets/adapters unchanged. Context strong refs until detach; native floors survive renderer replacement, exact pending retry/current-cache comparison, pure renderer ordering and malformed/conflicting concealment latch. No actual WebKit callback/DOM/frame/physical concealment/ongoing freshness/URI proof or host input/ticket custody activation. Next Native131 coherent current legacy source requalification and actual controlled host/renderer barriers with durable original input/ticket custody/retry. Native130 remains actual bounded baseline2518/278; uncertain worker/delayed proposal/full release gates remain open, installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/component-report119.json','implementation/warlock-preview-provider-v119/component-manifest.json','docs/warlock-repository/v88/publication/delivery.json']);print(e)
