#include "imported_clients.hpp"
#include "imported-clients.h"
#include "preview-provider-bootstrap.h"
#include <fstream>
#include <iostream>
using namespace preview;using namespace preview::bridge;
int main(int argc,char** argv){try{
 require(argc==6,"Own config, three actual native subjects, private PNG prefix");unsigned checks=0;
 auto check=[&](bool ok,const char* reason){require(ok,reason);++checks;};GError* error=nullptr;
 auto owner=warlock_preview_bootstrap_open(argv[1],&error);check(owner && !error,"Actual own native bootstrap");auto native=static_cast<Native*>(warlock_preview_bootstrap_native_transport(owner,&error));check(native && !error,"Borrowed exact own native grant");
 std::array<uint64_t,3> subjects{decimal(argv[2]),decimal(argv[3]),decimal(argv[4])};check(std::set<uint64_t>(subjects.begin(),subjects.end()).size()==3,"Three actual distinct native window incarnations");
 constexpr uint64_t receiver=77;auto popup=reinterpret_cast<gpointer>(receiver);char* initial=nullptr;void* raw=nullptr;auto cowner=warlock_imported_clients_open_dynamic(native,popup,subjects[0],1,1,&initial,&raw,&error);check(cowner && initial && raw && !error,"Actual dynamic C first native enrollment");const std::string firstEvents(initial);g_free(initial);auto& endpoint=*static_cast<uri::Endpoint*>(raw);std::array<GInputStream*,3> held{};std::array<Job,3> jobs;std::array<Packet,3> packets;std::array<uint64_t,3> sequences{};

 const auto job=[&](uint64_t entry){return endpoint.native([&](auto& b){for(const auto& row:b.inspect())if(row.entry==entry)return row.job;throw std::runtime_error("Actual retained C imported job");});};
 const auto actualPacket=[&](uint64_t entry){return endpoint.native([&](auto& b)->std::optional<Packet>{for(const auto& row:b.inspect())if(row.entry==entry)return row.packet;return {};});};
 const auto ownershipStatus=[&](uint64_t entry){char* result=nullptr;check(warlock_imported_clients_status(cowner,&result,&error) && result && !error,"Actual C native ownership status");Json root("{\"entries\":"+std::string(result)+"}");g_free(result);auto rows=json_object_get_array_member(root.object(),"entries");require(rows && entry<=json_array_get_length(rows),"Exact own C status row");auto bytes=json_to_string(json_array_get_element(rows,entry-1),FALSE);std::string text(bytes);g_free(bytes);return text;};
 const auto command=[&](uint64_t entry,const std::string& identity,const std::string& text){(void)entry;char* result=nullptr;check(warlock_imported_clients_command(cowner,identity.c_str(),text.c_str(),&result,&error) && result && !error,"Actual C native command");std::string events(result);g_free(result);return events;};
 const auto retire=[&](uint64_t entry){char* events=nullptr;auto identity="family:"+std::to_string(subjects[entry-1]);check(warlock_imported_clients_poll(cowner,identity.c_str(),&events,&error) && events && !error,"Actual C poll for physical retirement");g_free(events);Json current(ownershipStatus(entry));return Json::boolean(current.object(),"mappedFDClosed") && Json::boolean(current.object(),"producerRetired") && Json::boolean(current.object(),"exportReleased");};
 const auto enroll=[&](uint64_t subject,WarlockImportedAdmission expected){char* events=nullptr;WarlockImportedAdmission result=WARLOCK_IMPORTED_INVALID;check(warlock_imported_clients_enroll(cowner,popup,subject,1,1,&result,&events,&error) && !error && events && result==expected,"Actual typed dynamic C enrollment outcome");std::string text(events);g_free(events);return text;};
 const auto acquire=[&](uint64_t entry){auto& j=jobs[entry-1];Wire w;auto wire=w.text("kind","acquire").begin("job").job(j).end().finish();auto events=command(entry,"family:"+std::to_string(subjects[entry-1]),wire);auto packet=actualPacket(entry);check(packet && packet->job==j && packet->signaled,"Actual own imported FD/mapping becomes signaled packet");packets[entry-1]=*packet;return events;};
 const auto keepReader=[&](uint64_t entry,const std::string& suffix=""){gsize length=0;held[entry-1]=endpoint.open(receiver,uri::encode(packets[entry-1].token),&length,&error);check(held[entry-1] && !error && length>8,"Actual retained own native GIO reader");std::array<uint8_t,4> head{};check(g_input_stream_read(held[entry-1],head.data(),4,nullptr,&error)==4 && !error && head==std::array<uint8_t,4>{137,80,78,71},"Retained real client PNG header");
  auto stream=endpoint.open(receiver,uri::encode(packets[entry-1].token),&length,&error);check(stream && !error,"Actual independent specimen reader");std::vector<uint8_t> bytes(length);gsize read=0;check(g_input_stream_read_all(stream,bytes.data(),bytes.size(),&read,nullptr,&error) && !error && read==length,"Actual complete native PNG specimen");check(g_input_stream_close(stream,nullptr,&error) && !error,"Specimen reader closes normally");g_object_unref(stream);std::ofstream file(std::string(argv[5])+"."+std::to_string(entry)+suffix+".png",std::ios::binary);file.write(reinterpret_cast<const char*>(bytes.data()),bytes.size());file.close();check(bool(file),"Native specimen written before resource retirement");};
 const auto pending=[&](){char* wire=nullptr;check(warlock_preview_bootstrap_pending(owner,popup,&wire,&error) && wire && !error,"Actual C retained terminal projection");std::string result(wire);g_free(wire);return result;};
 const auto finalSequence=[&](uint64_t entry){auto& retained=sequences[entry-1];if(!retained)retained=endpoint.native([&](auto& b){for(const auto& r:b.inspect())if(r.entry==entry){require(r.terminal && !r.proofs.empty(),"Actual exact final native proof");return r.proofs.back().sequence.value;}throw std::runtime_error("Retained original record");});return retained;};
 const auto acknowledge=[&](uint64_t entry){Wire w;const auto wire=w.text("kind","acknowledge").begin("job").job(jobs[entry-1]).end().counter("sequence",finalSequence(entry)).finish();auto identity="family:"+std::to_string(subjects[entry-1]);auto ok=warlock_preview_bootstrap_acknowledge(owner,popup,identity.c_str(),wire.c_str(),&error);check(!error,"Actual own C ACK result");return bool(ok);};
 const auto release=[&](uint64_t entry){Wire w;const auto wire=w.text("kind","release").begin("frame").begin("job").job(jobs[entry-1]).end().text("handle",uri::encode(packets[entry-1].token).substr(20)).boolean("owned",true).boolean("signaled",packets[entry-1].signaled).text("fidelity","client").array("coverage").element("client").endArray().counter("expires",packets[entry-1].expires).end().finish();check(command(entry,"family:"+std::to_string(subjects[entry-1]),wire)=="[]","Original exact imported Release");};
 const auto drain=[&](uint64_t entry){check(g_input_stream_close(held[entry-1],nullptr,&error) && !error,"Actual held reader closes normally");g_object_unref(held[entry-1]);held[entry-1]=nullptr;check(retire(entry),"Actual consumer, backend, mapping, FD and Broker retirement");Json status(ownershipStatus(entry));check(Json::boolean(status.object(),"mappedFDClosed") && Json::boolean(status.object(),"producerRetired") && Json::boolean(status.object(),"exportReleased"),"Actual native import retirement facts");};
 jobs[0]=job(1);acquire(1);check(endpoint.registeredView(receiver)->entries==std::set<uint64_t>{1},"Original one-subject C native receiver");const auto epoch=endpoint.registeredView(receiver)->epoch;
 check(warlock_preview_bootstrap_attach_delivery(owner,&endpoint,popup,&error) && !error,"One original C journal enrollment");keepReader(1);const auto oldJob=jobs[0];const auto oldPacket=packets[0];
 auto secondEvents=enroll(subjects[1],WARLOCK_IMPORTED_STARTED);jobs[1]=job(2);check(endpoint.registeredView(receiver)->entries==std::set<uint64_t>{1,2},"Actual second C native member extends original receiver");acquire(2);keepReader(2);
 check(endpoint.readers()==2 && endpoint.native([](auto& b){return b.activeItems()==2 && b.recordCount()==2;}),"Two actual retained physical mappings share one pool");
 std::array<uint8_t,4> continuation{};check(g_input_stream_read(held[0],continuation.data(),4,nullptr,&error)==4 && !error && continuation==std::array<uint8_t,4>{13,10,26,10},"Original actual reader continues after second native capture");
 auto thirdScope=native->clientScope({subjects[2]});check(thirdScope.kind==SourceObservation::Kind::UnqualifiedClientMain && !thirdScope.previewEligible && thirdScope.scope.binding==native->binding(),"Third actual own source remains explicitly unqualified");
 auto waitingEvents=enroll(subjects[2],WARLOCK_IMPORTED_CAPACITY);check(waitingEvents=="[]" && endpoint.native([](auto& b){return b.activeItems()==2 && b.recordCount()==2 && b.requestFloor(3)==0;}),"Actual C third capture waits without fake job receipt eviction or request floor");Json waitingStatus(ownershipStatus(3));const auto originalDeadline=waitingStatus.counter("originalDeadline");
 const auto chargedBefore=endpoint.native([](auto& b){return b.charge();});const auto heldState=ownershipStatus(1);
 release(2);check(!retire(2) && pending()=="[]" && endpoint.native([](auto& b){return b.charge();})==chargedBefore,"Second held reader blocks physical retirement and early receipt");
 drain(2);check(pending()=="[]" && !acknowledge(2),"Actual view growth alone cannot deliver or ACK new terminal subject");
 const auto secondPhysical=ownershipStatus(2);check(endpoint.native([](auto& b){return b.recordCount()==2 && b.activeItems()==1 && b.charge()>0;}),"New terminal journal retained while original mapping stays charged");
 check(warlock_preview_bootstrap_extend_delivery(owner,popup,&error) && !error,"Actual explicit C native journal extension");const auto secondReceipts=pending();check(secondReceipts!="[]" && pending()==secondReceipts,"Actual new native terminal proof repeats without consumption");
 check(endpoint.registeredView(receiver)->epoch==epoch && job(1)==oldJob && actualPacket(1)->token==oldPacket.token && actualPacket(1)->expires==oldPacket.expires,"Native receipt growth preserves original epoch, job, token and expiry");
 uint8_t byte=0;check(g_input_stream_read(held[0],&byte,1,nullptr,&error)==1 && !error,"Original own reader survives actual C journal growth");
 check(acknowledge(2) && !acknowledge(2),"New exact final ACK drains only original new journal and duplicate is refused");
 auto thirdEvents=enroll(subjects[2],WARLOCK_IMPORTED_STARTED);jobs[2]=job(3);check(jobs[2].deadline==originalDeadline && jobs[2].request.value==1 && jobs[2].binding==oldJob.binding && jobs[2].clock==oldJob.clock,"Actual third new job retains independent original request domain and native clock");
 check(endpoint.registeredView(receiver)->entries==std::set<uint64_t>{1,2,3} && warlock_preview_bootstrap_extend_delivery(owner,popup,&error) && !error,"Third native actor joins same receiver and retained journal");acquire(3);keepReader(3);
 check(endpoint.registeredView(receiver)->epoch==epoch && job(1)==oldJob && endpoint.native([](auto& b){return b.activeItems()==2 && b.recordCount()==2 && b.requestFloor(1)==1 && b.requestFloor(2)==1 && b.requestFloor(3)==1;}),"Third allocation follows actual capacity without erasing old floors or replacing original job");
 check(enroll(subjects[2],WARLOCK_IMPORTED_RETAINED)=="[]" && job(3)==jobs[2],"Duplicate C enrollment does not replay original capture or deadline");
 char* resumeEvents=nullptr;WarlockImportedAdmission resumeAdmission=WARLOCK_IMPORTED_INVALID;const auto secondIdentity="family:"+std::to_string(subjects[1]);const auto priorSecond=jobs[1];
 check(warlock_imported_clients_resume_at(cowner,secondIdentity.c_str(),2,2,&resumeAdmission,&resumeEvents,&error) && !error && resumeEvents && resumeAdmission==WARLOCK_IMPORTED_CAPACITY && std::string_view(resumeEvents)=="[]","Actual native resume capacity without fake job or proof");g_free(resumeEvents);resumeEvents=nullptr;
 Json resumeStatus(ownershipStatus(2));const auto resumeDeadline=resumeStatus.counter("resumeDeadline");check(resumeDeadline && endpoint.native([](auto& b){return b.activeItems()==2 && b.recordCount()==2 && b.requestFloor(2)==1;}),"Actual native waiting resume retains original floor and other physical jobs");
 release(1);check(g_input_stream_read(held[0],&byte,1,nullptr,&error)==-1 && error,"Original native revocation still denies held reader after growth");g_clear_error(&error);drain(1);check(acknowledge(1),"Original exact terminal ACK after actual physical drain");
 check(warlock_imported_clients_resume_at(cowner,secondIdentity.c_str(),2,2,&resumeAdmission,&resumeEvents,&error) && !error && resumeEvents && resumeAdmission==WARLOCK_IMPORTED_STARTED && std::string_view(resumeEvents)!="[]","Actual native resume after exact original physical drain and ACK");g_free(resumeEvents);resumeEvents=nullptr;
 jobs[1]=job(2);sequences[1]=0;check(jobs[1].deadline==resumeDeadline && jobs[1].request.value==2 && jobs[1].origin.value==2 && jobs[1].binding==priorSecond.binding && jobs[1].clock==priorSecond.clock,"Actual native resumed job keeps original waiting cutoff and identity domain");
 acquire(2);keepReader(2,".resume");check(endpoint.native([](auto& b){return b.activeItems()==2 && b.recordCount()==2 && b.requestFloor(2)==2 && b.requestFloor(3)==1;}),"Actual resumed FD mapping shares unchanged pool and third original job");
 release(2);drain(2);check(acknowledge(2) && !acknowledge(2),"Actual resumed physical/backend/FD/GIO drain precedes exact new final ACK");
 release(3);drain(3);const auto thirdReceipts=pending();check(thirdReceipts!="[]" && acknowledge(3),"Third original terminal proof follows retained C delivery and ACK");check(warlock_imported_clients_empty(cowner),"All actual native mappings, FDs, readers, charges and journal records drained");
 auto originalView=*endpoint.registeredView(receiver);endpoint.unregisterView(receiver);check(endpoint.registerView(receiver,originalView.binding,originalView.entries),"Explicit actual native receiver replacement");const auto beforeResumeRefusal=native->clientScope({subjects[1]});
 check(!warlock_imported_clients_resume_at(cowner,secondIdentity.c_str(),3,3,&resumeAdmission,&resumeEvents,&error) && error && !resumeEvents,"Actual replaced receiver refuses typed native resume");g_clear_error(&error);
 check(!warlock_imported_clients_resume(cowner,secondIdentity.c_str(),3,3,&resumeEvents,&error) && error && !resumeEvents,"Actual replaced receiver refuses legacy native resume");g_clear_error(&error);
 const auto afterResumeRefusal=native->clientScope({subjects[1]});check(afterResumeRefusal.request==beforeResumeRefusal.request+1,"Both actual receiver refusals happen before native scope queries");check(endpoint.native([](auto& b){return b.recordCount()==0 && b.charge()==0 && b.requestFloor(1)==1 && b.requestFloor(2)==2 && b.requestFloor(3)==1;}),"Actual native resume cleanup preserves all independent request floors");
 check(warlock_imported_clients_close(cowner,&error) && !error,"C owner closes after every original physical and journal obligation");warlock_preview_bootstrap_free(owner);
 std::cout<<"{\"passed\":true,\"checks\":"<<checks<<",\"resumeDeadlineRetained\":true,\"receiverResumeGuard\":true,\"providerPID\":"<<getpid()<<",\"previewEligible\":false,\"sameReceiverEpoch\":true,\"capacityWithoutJob\":true,\"dynamicCEnrollment\":true,\"originalDeadlineRetained\":true,\"originalHeldStatus\":"<<heldState<<",\"newPhysicalStatus\":"<<secondPhysical<<",\"firstEvents\":"<<firstEvents<<",\"secondEvents\":"<<secondEvents<<",\"thirdEvents\":"<<thirdEvents<<",\"secondTerminal\":"<<secondReceipts<<",\"thirdTerminal\":"<<thirdReceipts<<",\"empty\":true,\"hardwarePresentation\":false}\n";return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<'\n';return 1;}}
