import ast,difflib,json,hashlib
from pathlib import Path
B=Path(__file__).resolve().parent;O=B/'proposed';s=(B/'retained-a3/run_native.py').read_text()
s=s.replace('from native_cases import NativeCases,PRODUCT,QA', 'sys.path.append(str(Path(__file__).resolve().parent.parent))\nfrom native_cases import NativeCases,PRODUCT,QA')
s=s.replace('import private_output_host,output_readiness','import private_output_host,output_readiness,pair_binding')
s=s.replace("B=Path(__file__).resolve().parent\n","B=Path(__file__).resolve().parent.parent\n")
s=s.replace("HOST=QA/'private-weston-aq-bootstrap-host-v5'","HOST=B/'proposed'")
s=s.replace("PLUGIN=PRODUCT/'native-candidate/hyprbars-v25-pin-stacking-candidate.so'","PLUGIN=pair_binding.PLUGIN")
s=s.replace("PROBE=QA/'browser-files-flow-v20/native-keyboard-probe/libqt-modal-probe.so'","PROBE=B/'readonly-probe/libqt-modal-probe.so'")
s=s.replace("scope=require_qa_scope();main_env=", "pair=pair_binding.read_pair(B/'PAIR_READY.json')\n scope=require_qa_scope();main_env=")
s=s.replace("nativePinAccepted=False,taskbarFrontendAccepted", "bindingChecks=[],nativePinAccepted=False,taskbarFrontendAccepted")
s=s.replace("module('_pin_exact_private_host',HOST/'weston_host.py')", "module('_pin_exact_private_host',HOST/'candidate_host.py')")
s=s.replace("  with host as session:\n",'''  def binding_gate(session,phase,loaded=()):
   verify();current_pair=pair_binding.read_pair(B/'PAIR_READY.json')
   raw=pair_binding.attest(session,current_pair,phase,loaded)
   report['bindingChecks'].append(raw);persist(output/'report.json',report)
   if raw['passed'] is not True:raise AssertionError('Exact completed core/plugin/probe binding: '+phase)
  with host as session:
   binding_gate(session,'before-legacy-clients')
''')
s=s.replace("    loaded=True\n", "    loaded=True\n    binding_gate(session,'candidate-loaded',(str(PLUGIN),))\n")
s=s.replace("    cases.run()\n", "    binding_gate(session,'before-genuine-original14',(str(PLUGIN),str(PROBE)))\n    cases.run()\n")
s=s.replace("len(report['hostChecks'])==10 and", "len(report['bindingChecks'])==3 and all(r['passed'] is True for r in report['bindingChecks']) and len(report['hostChecks'])==10 and")
s=s.replace('Exact frozen V25 native candidate load refused','Exact completed matching native candidate load refused').replace('Exact V25 candidate privately mapped after genuine legacy creation','Exact matching candidate privately mapped after genuine legacy creation').replace('Exact immutable B20 readonly core/Seat/hit probe mapped','Exact rebuilt byte-identical B20 readonly core/Seat/hit probe mapped')
s=s.replace("  report['hostEvidence']=host.evidence\n  gate('Exact normal", "  report['hostEvidence']=host.evidence\n  closure=host.evidence.get('ownedNormalClosure',{})\n  report['normalHostClosure']=closure;persist(output/'report.json',report)\n  if closure.get('normal') is not True:raise AssertionError('Actual normal owned host closure required')\n  gate('Exact normal")
s=s.replace("len(report['bindingChecks'])==3 and", "report.get('normalHostClosure',{}).get('normal') is True and len(report['bindingChecks'])==3 and")
s=s.replace(" return packet\ndef observer", " for name,mode in packet.get('directoryModes',{}).items():\n  d=Path(name)\n  if type(mode)is not int or d.is_symlink()or not d.is_dir()or stat.S_IMODE(d.stat().st_mode)!=mode:raise RuntimeError('Exact declared directory mode changed: '+name)\n return packet\ndef observer")
s=s.replace("B/'source-ready-inputs.json' if a.source_check", "B/'source-ready-inputs-final-v1.json' if a.source_check")
ast.parse(s);(O/'run_native.py').write_text(s)
original=(B/'retained-a3/run_native.py').read_text()
(B/'runner-selector-binding.diff').write_text(''.join(difflib.unified_diff(original.splitlines(True),s.splitlines(True),fromfile='original-A3/run_native.py',tofile='proposed/run_native.py')))
# Existing OutputWestonHost adapter remains otherwise exact.
a=(B/'retained-a3/private_output_host.py').read_text().replace('QA=Path(__file__).resolve().parent.parent',"QA=Path('/home/hoskinson/window-integration-qa')")
(O/'private_output_host.py').write_text(a)
(B/'output-adapter-path.diff').write_text(''.join(difflib.unified_diff((B/'retained-a3/private_output_host.py').read_text().splitlines(True),a.splitlines(True),fromfile='original-A3/private_output_host.py',tofile='proposed/private_output_host.py')))
print('proposed runner parsed; original14 body remains selected immutable A3')
