import hashlib,json,pathlib,re,subprocess
ROOT=pathlib.Path(__file__).resolve().parents[1];OUT=ROOT/'qa';rows=[]
def run(name,args,expected=0):
 p=subprocess.run(['quint',*args],cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,timeout=90);(OUT/(name+'.log')).write_text(p.stdout);rows.append({'name':name,'command':['quint',*args],'exit':p.returncode,'expected':expected,'ok':p.returncode==expected,'outputSHA256':hashlib.sha256(p.stdout.encode()).hexdigest()});return p
run('version',['--version']);run('typecheck',['typecheck',str(ROOT/'tests.qnt')]);names=re.findall(r'run (\w+) =',(ROOT/'tests.qnt').read_text());p=run('named',['test',str(ROOT/'tests.qnt'),'--main=tests','--match=^('+'|'.join(names)+')$','--seed=60501','--max-samples=1','--backend=typescript','--out-itf='+str(OUT/'accepted_{test}_{seq}.itf.json')]);executed=re.findall(r'ok (\w+) passed 1 test\(s\)',p.stdout)
run('traces',['run',str(ROOT/'release.qnt'),'--main=release','--invariant=allProps','--seed=60502','--max-samples=2000','--max-steps=80','--backend=typescript'])
mutants=[('skip-restart-prepared-root-barrier','s.rootReady and s.stage==1 and s.proofDurable','s.visibleStage==1 and s.proofDurable','visiblePreparedRestartNeedsRootSyncTest'),('skip-restart-released-root-barrier','| Ack => if (s.rootReady and releaseReady(s))','| Ack => if (s.visibleStage==2 and not(s.durableFile))','visibleReleasedRestartNeedsRootSyncTest'),('durable-release-skips-restart-barrier','| Ack => if (s.rootReady and releaseReady(s))','| Ack => if (releaseReady(s))','durableReleasedRestartNeedsBarrierTest'),('prepare-rename-implies-durability','{...s,visibleStage:1} else s','{...s,visibleStage:1,stage:1} else s','visiblePreparedRestartNeedsRootSyncTest'),('released-rename-implies-durability','{...s,visibleStage:2} else s','{...s,visibleStage:2,stage:2} else s','visibleReleasedRestartNeedsRootSyncTest'),('powerloss-keeps-unsynced-rename','visibleStage:s.stage,rootReady:false','visibleStage:s.visibleStage,rootReady:false','preparedRenameLostOnPowerLossTest'),('registered-proof','s.nativeRetired and p.kind==1 and p.key==1 and p.epoch==1 and p.barrier==1','p.key==1 and p.epoch==1 and p.barrier==1','registeredProofRefusedTest'),('old-intent-replay','and key==2 and not(s.history.contains(key))','and key>=1','historyUnknownNotCommitTest'),('stage-regression','if (s.stage==0 and s.visibleStage==1 and s.recordSynced and observations(s) and s.proofDurable)','if (s.recordSynced and observations(s) and s.proofDurable)','releasedStageCannotRegressTest')]
for label,old,new,name in mutants:
 d=OUT/'mutants'/label;d.mkdir(parents=True,exist_ok=True);s=(ROOT/'release.qnt').read_text();assert s.count(old)==1,(label,s.count(old));(d/'release.qnt').write_text(s.replace(old,new));(d/'tests.qnt').write_bytes((ROOT/'tests.qnt').read_bytes());run(label+'-typecheck',['typecheck',str(d/'tests.qnt')]);p=run(label+'-counterexample',['test',str(d/'tests.qnt'),'--main=tests','--match=^'+name+'$','--seed=60503','--max-samples=1','--backend=typescript'],1);rows[-1]['actualAssertionFailure']='Assertion failed' in p.stdout
r={'passed':executed==names and all(row['ok'] and row.get('actualAssertionFailure',True) for row in rows),'scope':'CPU process-restart/power-loss abstract rename/fsync model only; actual filesystem/native semantics unproven','namedCount':len(names),'selectedNames':names,'executedNames':executed,'traces':2000,'maxTransitions':80,'typedMutants':len(mutants),'commands':rows,'sourceHashes':{str(f.relative_to(ROOT)):hashlib.sha256(f.read_bytes()).hexdigest() for f in [ROOT/'release.qnt',ROOT/'tests.qnt',pathlib.Path(__file__)]},'nativeActions':False};(OUT/'report.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'passed':r['passed'],'named':len(executed),'expected':len(names),'mutants':len(mutants)}));raise SystemExit(not r['passed'])
