import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=4466
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report134.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v134',['PROGRESS PUBLIC98 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI134 fixes actual rapid149 original6s closing-subject deadlock with two sticky old-realm producer gates; original failure/source/host1/private cleanup retained. Current same byte-identical rapid15251/17 normal exits, slower15151/18, unchanged normal15029/13 and delayed15318/8 cleanups/full119 pass. Real original GIO reader/owned Retiring job across later GTK popup, held/fresh read denial/one actual close then independent strict Native retirement, same popup lease/new fixed renderer/same policy binding and current source URI/red19200 both epochs/monotonic chronology/opacity0 output. Reader Quint6/200/8coupled and producer8/200/4failure-fix cases; scope actual fixture schedules not all timings. Native issuer/policy/physical gates/deadlines unchanged/no resets. Next old-context actual delayed result across reopened epoch; ongoing physical conceal/reveal/hardware/pressure/workload/RSS/process/reload/Unknown/full preview/release open. Installed/drafts/foreign preserved.'],'progress',['docs/warlock-preview/v93/component-report134.json','implementation/warlock-preview-provider-v134/component-manifest.json','implementation/warlock-client-provider-native-v149/component-manifest.json','implementation/warlock-client-provider-native-v152/component-manifest.json','docs/warlock-repository/v98/publication/delivery.json']);print(e)
