import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=17064
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report103.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v103',['PROGRESS PUBLIC71 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held102 actor quota7809/260/1040;held103 controlled C10190/260/1041, exact readiness bytes and five compiled unsafe C witnesses,actor15/23/316/four,job/bank/admission/69Elm-nativeURI requalified,95 full host commands and12 original suites rerun. Failed evidence retained, noWebKit/capture/live-binding detach/native fullrelease claim. Next actual live-window binding detachment, native reconciliation/capture Unknown settlement and native-assigned renderer outbox. QualifiedGUI92/native128/core16/plugin18 and alloriginalgates unchanged.'],'progress',['docs/warlock-preview/v93/component-report103.json','implementation/warlock-preview-provider-v103/component-manifest.json','docs/warlock-repository/v71/publication/delivery.json']);print(e)
