'use strict';
const fs=require('fs'),assert=require('assert/strict'),cp=require('child_process'),path=require('path');
const app=require(process.argv[2]).Elm.BatchReplay.init({flags:null}),evidence=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));
const probe=process.argv[4],out=process.argv[5],copy=x=>JSON.parse(JSON.stringify(x)),native=frame=>({kind:'native',frame}),scope={id:'1',generation:'1'},checks=[];
const timer=setTimeout(()=>{throw Error('bounded CPU disposition replay timed out')},30000);
function replay(events){return new Promise(resolve=>{const cb=rows=>{app.ports.outgoing.unsubscribe(cb);resolve(rows)};app.ports.outgoing.subscribe(cb);app.ports.incoming.send(events)})}
const last=async events=>(await replay(events)).at(-1),check=(name,test)=>{test();checks.push(name)};
function certificate(row,gate){
 const p=path.join(path.dirname(out),'probe-input.json');fs.writeFileSync(p,JSON.stringify({original:JSON.stringify(row.submitted),binding:evidence.geometry52.binding,gate}));
 const text=cp.execFileSync(probe,[p],{encoding:'utf8'});return JSON.parse(text.trim().split('\n').at(-1));
}
const disposition=frame=>({kind:'disposition',frame});
(async()=>{
 const p=copy(evidence.projection51),g=copy(evidence.geometry52),a=copy(evidence.geometryAttach);p.requestId='1';a.requestId='2';g.requestId='3';
 const baseline=[{kind:'topology',frame:{viewProtocol:1,kind:'view-topology',revision:'1',views:[scope]}},native(evidence.attached),native(p),native({protocolVersion:3,kind:'host-geometry-negotiate'}),native(a),native(g)];
 const ready=await last(baseline);assert(ready.shell.available);
 const open={kind:'action',action:{viewProtocol:1,kind:'view-action',scope,action:{surfaceProtocol:2,kind:'surface-context',surface:'bar',publication:ready.frame.publication,lease:ready.frame.lease,id:'bar:group:application:elm-maximize-probe',trigger:'pointer',x:227,y:21}}};
 const opened=[...baseline,open],menu=await last(opened),notification=native({protocolVersion:3,kind:'host-refresh'}),pendingEvents=[...opened,notification],pending=await last(pendingEvents);
 assert.equal(pending.frame.mode,'menu');assert.equal(pending.requests.length,2);
 const cert=certificate(pending,{publication:menu.frame.publication,lease:menu.frame.lease,closed:menu.frame.lease});
 const dismissal={kind:'dismiss',frame:{scope,lease:menu.frame.lease}},lost=[...pendingEvents,dismissal,notification],stranded=await last(lost);
 check('actual recorded retirement ordering strands both unsent correlations without disposition',()=>{assert.equal(stranded.requests.length,0);assert.deepEqual(stranded.correlation,(awaitValue=>awaitValue)(pending.correlation));assert.equal(stranded.shell.available,false)});
 const recovered=await last([...lost,disposition(cert)]);
 check('actual C preflight-unsent exact original string recovers shared Main registration after popup owner cleared',()=>{assert.equal(recovered.frame.mode,'closed');assert.equal(recovered.requests.length,2);assert.notEqual(recovered.correlation.legacy,pending.correlation.legacy);assert.notEqual(recovered.correlation.geometry,pending.correlation.geometry);assert.equal(recovered.registry,0);assert.equal(recovered.outstanding,0)});
 check('fresh observation IDs strictly exceed rejected originals; no effect replay',()=>{assert(recovered.requests.every(r=>BigInt(r.requestId)>BigInt(pending.requests[1].requestId)));assert.equal(recovered.shell.effects.request,'0')});
 const duplicate=await last([...lost,disposition(cert),disposition(cert)]);
 check('exact duplicate is consumed once',()=>{assert.equal(duplicate.requests.length,0);assert.deepEqual(duplicate.correlation,recovered.correlation)});
 const hp=copy(p),hg=copy(g);hp.requestId=pending.requests[0].requestId;hg.requestId=pending.requests[1].requestId;
 const stale=await last([...lost,disposition(cert),native(hp),native(hg)]);
 check('late rejected request IDs cannot satisfy fresh expected slots',()=>{assert.deepEqual(stale.correlation,recovered.correlation);assert.equal(stale.shell.available,false)});
 const freshP=copy(p),freshG=copy(g);freshP.requestId=recovered.correlation.legacy;freshP.scene.windows=[];freshP.scene.focused=null;freshP.scene.revision=freshP.context.revision=String(BigInt(p.scene.revision)+1n);freshG.requestId=recovered.correlation.geometry;freshG.sequence=String(BigInt(g.sequence)+1n);freshG.revision=String(BigInt(g.revision)+1n);freshG.facts.windows=[];freshG.facts.focused=null;
 const retired=await last([...lost,disposition(cert),native(freshP),native(freshG)]);
 check('CPU synthetic retirement control admits fresh correlated facts and removes target',()=>{assert(retired.shell.available);assert.equal(retired.geometry.windows.length,0)});
 const bads=[['wrong kind',c=>c.kind='wrong'],['wrong protocol',c=>c.viewProtocol=2],['wrong disposition',c=>c.disposition='refused'],['wrong scope',c=>c.scope.id='2'],['wrong generation',c=>c.scope.generation='2'],['zero scope',c=>c.scope.id='0'],['wrong topology revision',c=>c.revision='2'],['wrong publication',c=>c.publication=String(BigInt(c.publication)+1n)],['wrong lease',c=>c.lease='999'],['wrong binding',c=>c.binding.frontend='2'],['noncanonical counter',c=>c.publication='01'],['extra field',c=>c.extra=true],['missing binding',c=>delete c.binding],['batch object instead of literal string',c=>c.batch=JSON.parse(c.batch)],['altered request order',c=>{const b=JSON.parse(c.batch);b.requests.reverse();c.batch=JSON.stringify(b)}],['altered request ID',c=>{const b=JSON.parse(c.batch);b.requests[0].requestId='999';c.batch=JSON.stringify(b)}],['altered request binding',c=>{const b=JSON.parse(c.batch);b.requests[0].binding.frontend='999';c.batch=JSON.stringify(b)}],['batch over byte bound',c=>c.batch='😀'.repeat(40000)]];
 for(const [name,change]of bads){const bad=copy(cert);change(bad);const result=await last([...lost,disposition(bad)]);check(name+' cannot consume or clear observations',()=>{assert.deepEqual(result.correlation,stranded.correlation);assert.equal(result.requests.length,0);assert.equal(result.batchCount,stranded.batchCount)})}
 for(const state of ['admitted','uncertain']){const other=copy(cert);other.disposition=state;const r=await last([...lost,disposition(other)]);check(state+' never proves unsent observations',()=>{assert.deepEqual(r.correlation,stranded.correlation);assert.equal(r.requests.length,0);assert.equal(r.batchCount,stranded.batchCount-1)})}
 const replacement={kind:'topology',frame:{viewProtocol:1,kind:'view-topology',revision:'2',views:[{id:'1',generation:'2'}]}};
 const replaced=await last([...lost,replacement,disposition(cert)]);
 check('retired/replaced scope cannot reauthorize old batch; old records retire without erasing intent ledger',()=>{assert.equal(replaced.batchCount,1);assert.notDeepEqual(replaced.correlation,stranded.correlation);assert.equal(replaced.shell.effects.request,'0');assert.equal(replaced.requests.length,0)});
 // Invoke the actual typed native operation through the QA-only input route.
 for(const operation of ['minimize','restore-geometry'])for(const mixed of [false,true]){
  const effectEvents=[...baseline,{kind:'direct-native-begin',operation,incarnation:'1',mixed}],effect=await last(effectEvents);
  assert(effect.requests.some(r=>r.kind==='window-effect'));
  const gate={publication:effect.frame.publication,lease:effect.frame.lease,closed:effect.frame.lease},ec=certificate(effect,gate);
  const er=await last([...effectEvents,disposition(ec)]);
  check(operation+' '+(mixed?'mixed':'operation-only')+' exact unsent certificate preserves actual Pending intent/full issued key; no retry',()=>{assert.deepEqual(er.unresolved,effect.unresolved);assert.deepEqual(er.unresolvedFull,effect.unresolvedFull);assert.deepEqual(er.issued,effect.issued);assert.deepEqual(er.shell.effects.transaction,effect.shell.effects.transaction);assert.equal(er.shell.effects.request,effect.shell.effects.request);assert(!er.requests.some(r=>r.kind==='window-effect'))});
  const command=effect.requests.find(r=>r.kind==='window-effect'),unknown={protocolVersion:3,kind:'effect-outcome',binding:command.binding,effectProtocol:command.effectProtocol,intent:command.intent,status:'Unknown',reason:'held-test',revision:command.intent.context.revision,outputGeneration:command.intent.context.output};
  const unknownBefore=await last([...effectEvents,native(unknown)]);assert(unknownBefore.unresolved.some(r=>r.status==='Unknown'));const unknownAfter=await last([...effectEvents,native(unknown),disposition(ec)]);
  check(operation+' '+(mixed?'mixed':'operation-only')+' exact original-key Unknown survives late unsent disposition',()=>{assert.deepEqual(unknownAfter.unresolved,unknownBefore.unresolved);assert.deepEqual(unknownAfter.unresolvedFull,unknownBefore.unresolvedFull);assert.deepEqual(unknownAfter.issued,unknownBefore.issued);assert.equal(unknownAfter.shell.effects.request,unknownBefore.shell.effects.request);assert(!unknownAfter.requests.some(r=>r.kind==='window-effect'))});
 }
 // A real menu-origin actor B Unknown ledger precedes unrelated actor A recovery.
 const twoP=copy(p),twoG=copy(g),peerP=copy(p.scene.windows[0]),peerG=copy(g.facts.windows[0]);peerP.incarnation='20';peerP.application='actor-b';peerP.label='Actor B';peerG.incarnation='20';twoP.scene.windows.push(peerP);twoG.facts.windows.push(peerG);
 const twoBase=baseline.map((e,i)=>i===2?native(twoP):i===5?native(twoG):e),twoReady=await last(twoBase),bOpen=copy(open);bOpen.action.action.publication=twoReady.frame.publication;bOpen.action.action.lease=twoReady.frame.lease;bOpen.action.action.id='bar:group:application:actor-b';
 const bOpened=[...twoBase,bOpen],bMenu=await last(bOpened),bRow=bMenu.frame.popup.find(r=>r.label==='Restore'&&r.enabled);assert(bRow);
 const bSelect={kind:'action',action:{viewProtocol:1,kind:'view-action',scope,action:{surfaceProtocol:2,kind:'surface-action',surface:'popup',publication:bMenu.frame.publication,lease:bMenu.frame.lease,id:bRow.id}}};
 const bPrepared=[...bOpened,bSelect],bSlot=await last(bPrepared);assert(bSlot.prepared);assert.equal(bSlot.registry,0);
 const bLegacy=copy(twoP),bGeometry=copy(twoG);bLegacy.requestId=bSlot.correlation.legacy;bGeometry.requestId=bSlot.correlation.geometry;
 const bSent=[...bPrepared,native(bLegacy),native(bGeometry)],bDispatch=await last(bSent),bCommand=bDispatch.requests.find(r=>r.kind==='window-effect');assert(bCommand);assert.equal(bCommand.intent.incarnation,'20');assert.equal(bDispatch.registry,1);assert.equal(bDispatch.outstanding,1);
 const bPendingReadTrace=[...bSent,{kind:'geometry-refresh'}],bPendingRead=await last(bPendingReadTrace);assert.equal(bPendingRead.requests.length,1);assert.equal(bPendingRead.requests[0].kind,'geometry-facts-request');
 const bPendingCert=certificate(bPendingRead,{publication:bPendingRead.frame.publication,lease:bPendingRead.frame.lease,closed:bPendingRead.frame.lease});
 const bPendingRecovered=await last([...bPendingReadTrace,disposition(bPendingCert)]);
 check('actual Menu receipt-router actor B Pending full-key/outstanding registry survives exact unsent observation retirement',()=>{assert.equal(bPendingRecovered.registry,1);assert.equal(bPendingRecovered.outstanding,1);assert.deepEqual(bPendingRecovered.unresolvedFull,bDispatch.unresolvedFull);assert.deepEqual(bPendingRecovered.issued,bDispatch.issued);assert.equal(bPendingRecovered.requests.length,0);assert.equal(bPendingRecovered.correlation.geometry,null);assert.equal(bPendingRecovered.shell.notificationQueued,true)});
 const bOutcome={protocolVersion:3,kind:'effect-outcome',binding:bCommand.binding,effectProtocol:bCommand.effectProtocol,intent:bCommand.intent,status:'Unknown',reason:'held-B',revision:bCommand.intent.context.revision,outputGeneration:bCommand.intent.context.output};
 const bUnknown=[...bSent,native(bOutcome)],bRefreshing=await last(bUnknown);assert(bRefreshing.unresolvedFull.some(r=>r.status==='Unknown'));
 const bFreshLegacy=copy(twoP),bFreshGeometry=copy(twoG);bFreshLegacy.requestId=bRefreshing.correlation.legacy;bFreshGeometry.requestId=bRefreshing.correlation.geometry;
 const bReadyTrace=[...bUnknown,native(bFreshLegacy),native(bFreshGeometry)],bReady=await last(bReadyTrace);assert(bReady.shell.available);assert.equal(bReady.registry,1);assert.equal(bReady.outstanding,1);
 const aOpen=copy(open);aOpen.action.action.publication=bReady.frame.publication;aOpen.action.action.lease=bReady.frame.lease;
 const aOpened=[...bReadyTrace,aOpen],aMenu=await last(aOpened),aPendingTrace=[...aOpened,notification],aPending=await last(aPendingTrace),aCert=certificate(aPending,{publication:aMenu.frame.publication,lease:aMenu.frame.lease,closed:aMenu.frame.lease});
 const aRecovered=await last([...aPendingTrace,{kind:'dismiss',frame:{scope,lease:aMenu.frame.lease}},disposition(aCert)]);
 check('actual Menu receipt-router actor B Unknown full-key/outstanding registry survives unrelated actor A unsent recovery',()=>{assert.equal(aRecovered.registry,1);assert.equal(aRecovered.outstanding,1);assert.deepEqual(aRecovered.unresolvedFull,bReady.unresolvedFull);assert.deepEqual(aRecovered.issued,bReady.issued);assert.equal(aRecovered.requests.length,2);assert(!aRecovered.requests.some(r=>r.kind==='window-effect'))});
 const aRecoveredTrace=[...aPendingTrace,{kind:'dismiss',frame:{scope,lease:aMenu.frame.lease}},disposition(aCert)];
 const wrongB=copy(bOutcome);wrongB.intent.request=String(BigInt(wrongB.intent.request)+100n);wrongB.status='Committed';
 const wrongBResult=await last([...aRecoveredTrace,native(wrongB)]);
 check('wrong original actor B receipt identity cannot clear preserved router mapping',()=>{assert.equal(wrongBResult.registry,1);assert.equal(wrongBResult.outstanding,1)});
 const definitiveB=copy(bOutcome);definitiveB.status='Committed';definitiveB.reason='CPU-correlated-final';
 const finalB=await last([...aRecoveredTrace,native(definitiveB)]);
 check('exact original actor B full-key definitive receipt still routes after unrelated recovery',()=>{assert.equal(finalB.registry,0);assert.equal(finalB.outstanding,0);assert.equal(finalB.unresolvedFull.length,0);assert.equal(finalB.issued.length,0);assert(!finalB.requests.some(r=>r.kind==='window-effect'))});
 const noOwner=await last([native(evidence.attached)]);
 check('absent live scope refuses authority transport before send without fictitious request forwarding',()=>{assert.equal(noOwner.submitted,null);assert.equal(noOwner.requests.length,0);assert.equal(noOwner.batchCount,0);assert.equal(noOwner.attemptedRequests.length,1);assert.equal(noOwner.attemptedRequests[0].kind,'projection-request')});
 let capacity=[...baseline],capRow=await last(capacity);
 for(let i=0;i<20;i++){
  capacity.push(notification);capRow=await last(capacity);
  if(capRow.submitted===null)break;
  const cp=copy(p),cg=copy(g);cp.requestId=capRow.correlation.legacy;cg.requestId=capRow.correlation.geometry;capacity.push(native(cp),native(cg));
 }
 check('sixteen unacknowledged records bounded; capacity refuses actual transport without evicting batch',()=>{assert.equal(capRow.batchCount,16);assert.equal(capRow.submitted,null);assert.equal(capRow.requests.length,0);assert(capRow.attemptedRequests.length>0)});
 const topologyRetired=await last([...capacity,replacement]);
 check('topology retirement replaces obsolete transport inventory and supersedes reads under fresh IDs without effect replay',()=>{assert.equal(topologyRetired.batchCount,1);assert.equal(topologyRetired.requests.length,2);assert.equal(topologyRetired.shell.effects.request,'0');assert.notDeepEqual(topologyRetired.correlation,capRow.correlation);assert(BigInt(topologyRetired.correlation.legacy)>BigInt(capRow.correlation.geometry))});
 const ownerAcquired=await last([native(evidence.attached),{kind:'topology',frame:{viewProtocol:1,kind:'view-topology',revision:'1',views:[scope]}}]);
 check('authoritative live topology recovers conservative ownerless exhaustion with fresh read ID',()=>{assert(ownerAcquired.submitted);assert.equal(ownerAcquired.requests.length,1);assert.equal(ownerAcquired.requests[0].kind,'projection-request');assert(BigInt(ownerAcquired.requests[0].requestId)>1n)});
 const lateCapP=copy(p),lateCapG=copy(g);lateCapP.requestId=capRow.correlation.legacy;lateCapG.requestId=capRow.correlation.geometry;
 const lateCap=await last([...capacity,replacement,native(lateCapP),native(lateCapG)]);
 check('late old topology read responses cannot satisfy superseding correlations',()=>{assert.deepEqual(lateCap.correlation,topologyRetired.correlation);assert.equal(lateCap.shell.available,false)});
 const zero={kind:'topology',frame:{viewProtocol:1,kind:'view-topology',revision:'2',views:[]}},newScope={id:'2',generation:'1'},reacquire={kind:'topology',frame:{viewProtocol:1,kind:'view-topology',revision:'3',views:[newScope]}};
 const zeroRow=await last([...aRecoveredTrace,zero]);
 check('zero outputs retires all read IDs without forwarding or losing actor B Unknown registry',()=>{assert.equal(zeroRow.correlation.legacy,null);assert.equal(zeroRow.correlation.geometry,null);assert.equal(zeroRow.correlation.attach,null);assert.equal(zeroRow.requests.length,0);assert.equal(zeroRow.batchCount,0);assert.equal(zeroRow.shell.available,false);assert.equal(zeroRow.registry,1);assert.equal(zeroRow.outstanding,1);assert.deepEqual(zeroRow.unresolvedFull,bReady.unresolvedFull);assert.deepEqual(zeroRow.issued,bReady.issued)});
 const reacquired=await last([...aRecoveredTrace,zero,reacquire]);
 check('new native-issued scope after zero outputs allocates fresh paired observations only',()=>{assert.equal(reacquired.requests.length,2);assert(BigInt(reacquired.correlation.legacy)>BigInt(aRecovered.correlation.geometry));assert.deepEqual(reacquired.outputs.focusOwner,newScope);assert.equal(reacquired.registry,1);assert.equal(reacquired.outstanding,1);assert.deepEqual(reacquired.issued,bReady.issued)});
 const lateZeroP=copy(twoP),lateZeroG=copy(twoG);lateZeroP.requestId=aRecovered.correlation.legacy;lateZeroG.requestId=aRecovered.correlation.geometry;
 const lateZero=await last([...aRecoveredTrace,zero,reacquire,native(lateZeroP),native(lateZeroG),disposition(aCert)]);
 check('retired-view certificate and late superseded reads are ignored after scope reacquisition',()=>{assert.deepEqual(lateZero.correlation,reacquired.correlation);assert.equal(lateZero.registry,1);assert.equal(lateZero.outstanding,1);assert.equal(lateZero.requests.length,0)});
 const newP=copy(twoP),newG=copy(twoG);newP.requestId=reacquired.correlation.legacy;newG.requestId=reacquired.correlation.geometry;
 const recoveredOwnerTrace=[...aRecoveredTrace,zero,reacquire,native(newP),native(newG)],newReady=await last(recoveredOwnerTrace);assert(newReady.shell.available);
 const originalBReceipt=await last([...recoveredOwnerTrace,native(definitiveB)]);
 check('exact actor B original-key receipt still routes after topology retirement and new owner acquisition',()=>{assert.equal(originalBReceipt.registry,0);assert.equal(originalBReceipt.outstanding,0);assert.equal(originalBReceipt.issued.length,0);assert.equal(originalBReceipt.unresolvedFull.length,0);assert(!originalBReceipt.requests.some(r=>r.kind==='window-effect'))});
 const bPendingTopology=await last([...bSent,replacement]);
 check('topology supersedes reads while preserving real Menu actor B Pending full keys and no mutation replay',()=>{assert.equal(bPendingTopology.registry,1);assert.equal(bPendingTopology.outstanding,1);assert.deepEqual(bPendingTopology.issued,bDispatch.issued);assert.deepEqual(bPendingTopology.unresolvedFull,bDispatch.unresolvedFull);assert.equal(bPendingTopology.requests.length,2);assert(!bPendingTopology.requests.some(r=>r.kind==='window-effect'))});
 const aMenuBeforeSelection=await last(aOpened),aEnabled=aMenuBeforeSelection.frame.popup.find(r=>r.label==='Restore'&&r.enabled);assert(aEnabled);
 const aStage={kind:'action',action:{viewProtocol:1,kind:'view-action',scope,action:{surfaceProtocol:2,kind:'surface-action',surface:'popup',publication:aMenuBeforeSelection.frame.publication,lease:aMenuBeforeSelection.frame.lease,id:aEnabled.id}}};
 const aStageTrace=[...aOpened,aStage],aPrepared=await last(aStageTrace);assert(aPrepared.preparedToken);assert.equal(aPrepared.outstanding,2);
 const aCancelled=await last([...aStageTrace,replacement]);
 check('authoritative topology cancels only prepared unsent selection, preserves unrelated Unknown router and refreshes reads',()=>{assert.equal(aCancelled.preparedToken,null);assert.equal(aCancelled.outstanding,1);assert.equal(aCancelled.registry,1);assert.deepEqual(aCancelled.unresolvedFull,bReady.unresolvedFull);assert.deepEqual(aCancelled.issued,bReady.issued);assert.equal(aCancelled.requests.length,2);assert(!aCancelled.requests.some(r=>r.kind==='window-effect'))});
 const oldPreparedP=copy(twoP),oldPreparedG=copy(twoG);oldPreparedP.requestId=aPrepared.correlation.legacy;oldPreparedG.requestId=aPrepared.correlation.geometry;
 const oldPrepared=await last([...aStageTrace,replacement,native(oldPreparedP),native(oldPreparedG)]);
 check('superseded prepared-selection reads cannot resurrect or dispatch the cancelled action',()=>{assert.equal(oldPrepared.preparedToken,null);assert.equal(oldPrepared.registry,1);assert.equal(oldPrepared.shell.effects.request,bReady.shell.effects.request);assert.deepEqual(oldPrepared.correlation,aCancelled.correlation);assert.equal(oldPrepared.requests.length,0)});
 const negotiating=baseline.slice(0,4),negotiatingRow=await last(negotiating);assert.equal(negotiatingRow.correlation.attach,'2');
 const supersededAttach=await last([...negotiating,replacement]);
 check('topology supersedes active geometry attachment using fresh correlated ID',()=>{assert.equal(supersededAttach.requests.length,2);assert.equal(supersededAttach.requests[1].kind,'geometry-attach');assert(BigInt(supersededAttach.correlation.attach)>2n)});
 const lateAttach=await last([...negotiating,replacement,native(a),native(p)]);
 check('late old attach and legacy responses cannot satisfy refreshed topology requests',()=>{assert.deepEqual(lateAttach.correlation,supersededAttach.correlation);assert.equal(lateAttach.requests.length,0)});
 const attachZero=await last([...negotiating,zero]);assert.equal(attachZero.correlation.attach,null);
 const attachReacquired=await last([...negotiating,zero,reacquire]);
 check('geometry attachment requirement survives zero outputs and reacquires with fresh attach ID',()=>{assert.equal(attachReacquired.requests.length,2);assert.equal(attachReacquired.requests[1].kind,'geometry-attach');assert(BigInt(attachReacquired.correlation.attach)>2n)});
 const unicodeP=copy(p);unicodeP.scene.windows[0].label='É / quote " slash \\ 😀 \u2028';
 const unicodeBase=baseline.map(e=>e===baseline[2]?native(unicodeP):e),unicodeReady=await last(unicodeBase),unicodeOpen=copy(open);unicodeOpen.action.action.publication=unicodeReady.frame.publication;unicodeOpen.action.action.lease=unicodeReady.frame.lease;
 const unicodeEvents=[...unicodeBase,unicodeOpen],unicodeMenu=await last(unicodeEvents),unicodePending=await last([...unicodeEvents,notification]);
 const unicodeCert=certificate(unicodePending,{publication:unicodeMenu.frame.publication,lease:unicodeMenu.frame.lease,closed:unicodeMenu.frame.lease});
 const unicodeRecovered=await last([...unicodeEvents,notification,disposition(unicodeCert)]);
 check('literal original JSON bridge wire including quotes/slashes/astral Unicode roundtrips C certificate and Elm exact match',()=>{assert.equal(unicodeCert.batch,JSON.stringify(unicodePending.submitted));assert.equal(unicodeRecovered.requests.length,2)});
 fs.writeFileSync(out,JSON.stringify({passed:true,checks,scope:'Actual compiled shared registration/Controller and actual C preflight/certificate; exact recorded producer fields, CPU-only synthetic retirement control; operation terminal/recovery incomplete',nativeAcceptance:false,cert,pending,stranded,recovered,retired},null,2)+'\n');clearTimeout(timer);
})().catch(e=>{fs.writeFileSync(out,JSON.stringify({passed:false,checks,error:String(e)},null,2)+'\n');clearTimeout(timer);console.error(e.stack);process.exitCode=1});
