import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=3469
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report120.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v120',['PROGRESS PUBLIC90 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI120 native driver atomic input1065/16MiB, original source epoch, ticket before issuance notification/dispatch, deferred callbacks and separate confirmation. Original Native/C/Bootstrap/Broker/journal/scoped closure with synthetic peer2250/constructor faults9/normal exits/no grant reset; Quint custody14/200/six concrete witnesses/four compiled guards; full116 retains115. Parent policy/issuer/effects/physical/assets/adapters unchanged, three failed attempts retained. Driver links but remains inactive in actual legacy host; Native131 actualGUI119 legacy2518/278 baseline remains. Next bounded retained native outputs and paused producer scheduling before actual controlled host/pure renderer WebKit identity/async frame/physical concealment/URI. In-process memory is not a loss journal; uncertain worker/process recovery, delayed never-issued proposal outcome/order and all full release gates remain open. No installed/foreign changes.'],'progress',['docs/warlock-preview/v93/component-report120.json','implementation/warlock-preview-provider-v120/component-manifest.json','docs/warlock-repository/v90/publication/delivery.json']);print(e)
