import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=585
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/native-report130.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v130',['PROGRESS PUBLIC79 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Native130 current GUI110 compiled legacy runtime/core16/plugin19/AQ155 passes2518 checks/278 normal owned exits/full cleanup,2509 prior129/2459 prior128/2458 prior126 fixed controls with actual allocator/original expiry.49 Core resource witnesses/11 snapshots/two independent FD closes. New URI router/controlled/scoped path inactive; historical GUI92 probes retain original identity. Next typed realm/native-issued renderer outbox and actual WebKit/Core activation, all original release gates open. No installed changes.'],'progress',['docs/warlock-preview/v93/native-report130.json','implementation/warlock-client-provider-native-v130/component-manifest.json','docs/warlock-repository/v79/publication/delivery.json']);print(e)
