import hashlib,json,resource,shutil,subprocess,sys,time
from pathlib import Path
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1];SOURCE=REPO/'implementation/elm-pending-observation-join-v567';OUT=ROOT/'qa'/('replay-'+str(time.time_ns()));OUT.mkdir();log=REPO/'implementation/elm-pending-observation-recovery-trace-v573/qa/native-1791143276230101221/native-evidence/elm-webview.log'
frames=[json.loads(line.split(': ',1)[1]) for line in log.read_text().splitlines() if line.startswith('backend-frame: ')]
uncertain=next(f for f in frames if f['kind']=='host-uncertain');projection=[f for f in frames if f['kind']=='action-projection'][-1];assert uncertain['binding']==projection['binding']
flags={'intent':uncertain['intent'],'projection':projection};(OUT/'frames.json').write_text(json.dumps(flags,indent=2)+'\n')
inputs=OUT/'inputs';shutil.copytree(SOURCE/'src',inputs/'src');shutil.copy2(SOURCE/'elm.json',inputs/'elm.json');shutil.copy2(ROOT/'qa/Probe.elm',inputs/'src/Probe.elm')
p=subprocess.run(['npm','exec','--yes','--package=elm@0.19.2-0','--','elm','make','src/Probe.elm','--output='+str(OUT/'worker.js')],cwd=inputs,capture_output=True,timeout=180);(OUT/'compile.stdout').write_bytes(p.stdout);(OUT/'compile.stderr').write_bytes(p.stderr);assert p.returncode==0,p.stderr.decode()[-1800:]
(OUT/'probe.cjs').write_text("const a=require(process.argv[2]).Elm.Probe.init({flags:null});a.ports.outgoing.subscribe(x=>{console.log(JSON.stringify(x));process.exit(0)});a.ports.incoming.send(JSON.parse(require('fs').readFileSync(process.argv[3],'utf8')));setTimeout(()=>process.exit(2),3000);")
p=subprocess.run(['node',str(OUT/'probe.cjs'),str(OUT/'worker.js'),str(OUT/'frames.json')],capture_output=True,text=True,timeout=10);(OUT/'result.stdout').write_text(p.stdout);(OUT/'result.stderr').write_text(p.stderr);assert p.returncode==0,p.stderr;w=json.loads(p.stdout);assert w=={'recoverError':None,'snapshotError':None,'blocked':True,'connected':True,'unresolved':1,'request':'12','emitted':False,'refusal':'Unresolved native operation'},w
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();report={'passed':True,'nativeAcceptance':False,'scope':'Actual compiled Effects public recovery and snapshot APIs with unmodified573 Unknown intent/current projection: target still reserved, no new effect or counter consumed','witness':w,'capturedLogSHA256':sha(log),'artifacts':{str(p.relative_to(OUT)):sha(p) for p in OUT.rglob('*') if p.is_file() and 'elm-stuff' not in p.parts}};(OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'passed':True,'report':str(OUT/'report.json'),'witness':w}))
