import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=4983
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report108.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v108',['PROGRESS PUBLIC76 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. HeldGUI108 inactive CPU exact Bootstrap-aware strict C close/borrowed receipt release/reattachment:97 replacement+47 synthetic native-peer-death controls,17 selected Quint/29 actual C traces/719 states/current full95/original resource/capture/ticket/FD regressions; count-premise failure retained. Native129/public74 GUI92/core16/plugin19 remains2517/278/full cleanup. Next freshGUI109 distinct live-window binding detach/typed scoped proof/readiness/final processing/confirmation/frontend realm freshness/current controlled Core/renderer native outbox/WebKit. Original full release/deployment gates remain open; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report108.json','implementation/warlock-preview-provider-v108/component-manifest.json','docs/warlock-repository/v76/publication/delivery.json']);print(e)
