from pathlib import Path
import ast,json,hashlib,difflib
B=Path(__file__).resolve().parent;P=B/'proposed';V=Path('/home/hoskinson/window-behavior-spec/qml-process-provider-v9-source-boundary-fixture');O=Path('/home/hoskinson/window-behavior-spec/qml-process-provider-v8-terminal-retire')
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
old=(V/'cpu_retire_product_disconnect.cpp').read_text();s=(P/'cpu_terminal_required_routes.cpp').read_text();reconstructed=s
for line in ['#include <limits>\n','#include "cpu_typed_retire_adapter.hpp"\n','#include "cpu_durable_route_evidence.hpp"\n']:reconstructed=reconstructed.replace(line,'')
reconstructed=reconstructed.replace('auto receiptFor=[&](QString input){return [&,input](const QByteArray&out,const QByteArray&err,const KernelWitness&w,int code){','spec.receiptGuard=[&](const QByteArray&out,const QByteArray&err,const KernelWitness&w,int code){').replace(' };};spec.receiptGuard=receiptFor(input);',' };')
reconstructed=reconstructed.replace('int helperStartedSignals=0;','').replace('++helperStartedSignals;','').replace('pendingCase=="pending-retire"||(pendingCase=="cancelled-changed-command"&&helperStartedSignals==1)','pendingCase=="pending-retire"')
reconstructed=reconstructed.replace('(state["complete"].toBool()||(pendingCase=="cancelled-changed-command"&&!state["current"].toBool()&&!state["kernelBound"].toBool()&&state["historicalKernelProof"].toBool()&&state["workerJoined"].toBool()&&state["receiptVerified"].toBool()))','state["complete"].toBool()')
a=reconstructed.index(' if(scenario=="normal-changed-command"');z=reconstructed.index(' }else if(scenario=="fault-after-disconnect-source-boundary")',a);reconstructed=reconstructed[:a]+' if(scenario=="fault-after-disconnect-source-boundary")'+reconstructed[z+len(' }else if(scenario=="fault-after-disconnect-source-boundary")'):]
parser=(B/'exact-production-lease-parser.inc').read_text();primitive=(B/'exact-production-final-admission.inc').read_text();native=(O/'NativeProcess.cpp').read_text();registry=(O/'ProcessRegistry.cpp').read_text();driver=(P/'terminal_product_once.py').read_text();adapter=(P/'cpu_typed_retire_adapter.hpp').read_text()
checks={'wholeOriginalCpuSourceReconstructed':reconstructed==old,'actualProductionParserExact':parser in native and parser in adapter,'actualFinalAdmissionExact':primitive in registry and primitive in(P/'cpu_final_admission_primitive.cpp').read_text(),'originalProcessFixtureExact':(P/'retire_process_fixture.cpp').read_bytes()==(V/'retire_process_fixture.cpp').read_bytes(),'perInvocationReceiptInputOwned':'return [&,input]'in s,'cancelOnlyFirstActualStarted':'pendingCase=="cancelled-changed-command"&&helperStartedSignals==1'in s,'sourceRetireBeforeCommandChange':s.index('const auto secondInput=')>s.index('"Actual typed retirement seals'),'secondFreshProofRequired':'Second invocation has no first actor kernel EOF receipt proof'in s,'sameCommandImplicitRoutePreserved':'if(scenario!="same-command-reuse")'in s,'noHelperRetryDelay':"actor.communicate("in driver and 'timeout=8'in driver and 'actor.wait(timeout=5)'in driver,'primitiveScopeExplicit':'not actual Qt notification'in(P/'cpu_final_admission_primitive.cpp').read_text(),'publicProviderNotOverridden':'loader.instance()'in(P/'cpu_public_provider_retire_refusal.cpp').read_text()and 'source()'not in(P/'cpu_public_provider_retire_refusal.cpp').read_text(),'durableFirstAndFreshArm':'persistRouteEvidence(config['in s and 'before-second-helper.json'in s}
for f in P.glob('*.py'):ast.parse(f.read_text())
checks['pythonSourcesAST']=True
D=B/'diffs';D.mkdir(exist_ok=True)
for oldpath,newpath in [(V/'cpu_retire_product_disconnect.cpp',P/'cpu_terminal_required_routes.cpp'),(V/'terminal_product_once.py',P/'terminal_product_once.py')]:
 (D/(newpath.name+'.diff')).write_text(''.join(difflib.unified_diff(oldpath.read_text().splitlines(True),newpath.read_text().splitlines(True),fromfile=str(oldpath),tofile=str(newpath))))
row={'result':'pass'if all(checks.values())else'fail','checks':checks,'inverseOriginalSHA256':sha(V/'cpu_retire_product_disconnect.cpp'),'reconstructedSHA256':hashlib.sha256(reconstructed.encode()).hexdigest(),'productionParserSourceSHA256':sha(O/'NativeProcess.cpp'),'productionFinalSourceSHA256':sha(O/'ProcessRegistry.cpp'),'checksAreSourceOnly':True,'buildExecuted':False,'CPUExecuted':False,'GUI':False};(B/'source-review.json').write_text(json.dumps(row,indent=2)+'\n');print(json.dumps(row));raise SystemExit(int(row['result']!='pass'))
