"""Materialize concrete matrix obligations; no fixture/native processes execute."""
from pathlib import Path
import hashlib,json
B=Path(__file__).resolve().parent;Q=B.parent
cases=[]
for kind,mode,button in [('move',0,272),('resize',1,273)]:
 for end in ['escape','reload','unload-reload','minimize-preview','close-reopen']:
  cases.append({'name':kind+'-'+end,'kind':kind,'nativeMode':mode,'button':button,'end':end,'before':['exposed-native-allocation','float-cursor-readiness','real-button-press','first-motion-exact-core-target','actual-target-geometry-change','exact-WM-peer-focus-intervention-observed'],'afterRetirement':['exact-controller-retired','actual-groups-unchanged','independent-native-focus-preserved','no-peer-or-new-lifetime-callback-leak','genuine-button-release-quiescent','actual-toolkit-callback-after-release'],'geometryAuthority':'current freshly requeried geometry' if end=='minimize-preview' else 'old captured lifetime gone; new lifetime default' if end=='close-reopen' else 'exact press geometry','afterPublicRestoreOrOpen':['actual deepest-modal focus and per-member geometry/pins exact'] if end=='minimize-preview' else ['new observed exact native lifetime; intended public toolkit create/focus'] if end=='close-reopen' else [],'requiresServiceV12':end=='minimize-preview'})
cases+=[{'name':'genuine-group-release-positive','kind':'move','nativeMode':0,'button':272,'before':['fresh-disposable-source-lifetime','real-target-group-and-public-drop-region','exposed-native-allocation','real-press-motion-exact-target'],'after':['actual-genuine-release','same-real-group-source-and-peer-members','native-target-and-held-signals-clear','actual-original-toolkit-callbacks']},{'name':'pending-caption-escape','kind':'pending','nativeMode':-1,'button':272,'before':['real-caption-press-without-motion','no-core-target','actual-button-signal-down'],'after':['genuine-native-Escape','pending-intent-cleared','same-group-and-peer-focus','swallowed-real-release-without-drop','actual-callbacks-work']},{'name':'pending-caption-reload','kind':'pending','nativeMode':-1,'button':272,'before':['real-caption-press-without-motion','no-core-target','actual-button-signal-down'],'after':['genuine-private-config-reload','pending-intent-cleared','same-group-and-peer-focus','swallowed-real-release-without-drop','actual-callbacks-work']}]
variants=[{'name':'qt-wayland','toolkit':'QtWidgets','backend':'wayland','fixture':str(Q/'qt-modal-private-v9/build-v7/qt-window-modal-fixture'),'actualAuthority':['QGuiApplication.platformName=wayland','frozen-actual-Qt-Wayland-plugin','xwayland-false'],'host':'private-weston-aq-host-v4'}, {'name':'qt-xcb','toolkit':'QtWidgets','backend':'xcb','fixture':str(Q/'qt-modal-private-x11-v2/build-v7/qt-window-modal-fixture'),'actualAuthority':['QGuiApplication.platformName=xcb','frozen-actual-Qt-XCB-plugin','actual-owned-X-server','no-cookie-refused/fresh-cookie-accepted','xwayland-true'],'host':'private-weston-x11-host-v2'}, {'name':'gtk-wayland','toolkit':'GTK4','backend':'wayland','fixture':str(B/'fixtures/gtk_family.py'),'actualAuthority':['actual-GdkWaylandDisplay','actual-GdkWayland-surface','frozen-actual-GDK-modules','xwayland-false'],'host':'private-weston-aq-host-v4'}, {'name':'gtk-x11','toolkit':'GTK4','backend':'x11','fixture':str(B/'fixtures/gtk_family.py'),'actualAuthority':['actual-GdkX11Display','actual-GdkX11-surface','frozen-actual-GDK-modules','actual-owned-X-server','no-cookie-refused/fresh-cookie-accepted','xwayland-true'],'host':'private-weston-x11-host-v2'}]
record={'nativeExecuted':False,'runnerFrozen':False,'nativeBlocked':'Fresh V21/frontend exact source pair and held52 wrapper staged; root review/freeze and native command pending; no native grant','candidate':str(Q/'toolkit-interruption-v5/native-candidate/hyprbars-v21-interruption-candidate.so'),'candidateSHA256':'bdd8bab3b3cea6f2dd2e49b317f133691cc920700f9743d21438c0e3338a0dc7','pairedSnap':str(Q/'toolkit-interruption-v5/native-candidate/installed-snap.lua'),'pairedCloseHelper':str(Q/'snap-close-identity-v1/hypr-snap-groups'),'probe':str(B/'native-probe/libtoolkit-held-probe.so'),'variants':variants,'casesPerVariant':cases,'totalVariantCases':len(variants)*len(cases),'mainWrites':False,'remaining':['root review/freeze exact full source closure and serial native command','root exclusive actual held52 GUI observations'],'keyboardFocusBindingCannotRetainCoreTarget':True,'privateCoreHeldIdsExposed':False,'signalDownIdsAndPublicCoreHeldBoolSeparate':True}
(B/'matrix.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'nativeExecuted':False,'variants':len(variants),'casesPerVariant':len(cases),'totalCases':len(variants)*len(cases)}))
if __name__=='__main__':pass
