import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=3854
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report116.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v116',['PROGRESS PUBLIC85 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI116 persistent native-owned optimized JSC Elm policy; original single window policy unchanged. Actual C/JSC/native synthetic peer207/two epochs/unchanged Native grant/two fresh transport contexts/one policy/normal exits. Lifetime37/13 pre-grant faults/backpressure48/Quint8 selected/20 actual traces/405 states/three compiled guards/full110 retains108; five failed attempts held. Host library links but creates no worker or controlled route. Next typed renderer projection without another window policy, durable input custody/native sender channel/original ticket custody/retry and actual WebKit/Core activation. Uncertain live JSC/process recovery, delayed proposal expiry/revocation outcomes and all original release gates remain. Native130 legacy2518/278 remains actual baseline; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report116.json','implementation/warlock-preview-provider-v116/component-manifest.json','docs/warlock-repository/v85/publication/delivery.json']);print(e)
