"""Handwritten adapters count as source; bundles and old records retain their meaning."""
import json
import unittest

import test_warlock as fixtures


class AdapterProgressTests(unittest.TestCase):
    def setUp(self):
        self.fixture = fixtures.ContributionPolicyTests('test_fresh_start_status_check_record')
        self.fixture.setUp()
        self.addCleanup(self.fixture.doCleanups)
        self.repo, self.cli = self.fixture.repo, self.fixture.cli

    def select(self, paths):
        for name in paths:
            self.fixture.write('implementation/warlock/' + name, 'original bytes\n')
        self.fixture.run_git('add', '.')
        self.fixture.run_git('commit', '-qm', 'adapter fixtures')
        self.fixture.write('.warlock-contributor/adapter-plan.json', dict(self.fixture.slice, paths=paths))
        self.cli('start', '--owner', 'adapter-contributor', '--slice-file', '.warlock-contributor/adapter-plan.json')

    def record(self):
        self.cli('record', '--outcome', 'production-fix', '--summary', 'Source change; behavior verification remains pending')
        return json.loads((self.repo / '.warlock-contributor/slice.json').read_text())

    def test_handwritten_keyboard_and_transport_changes_are_recorded_progress(self):
        names = ['assets/bar-adapter.js', 'assets/popup-adapter.js', 'assets/context.js',
                 'assets/activation.js', 'assets/native-preview-proposals.js']
        self.select(names)
        for name in names:
            self.fixture.write('implementation/warlock/' + name, 'changed ' + name + '\n')
            record = self.record()
            self.assertTrue(record['iterations'][-1]['meaningfulProgress'])
            self.assertEqual(record['iterations'][-1]['progressPolicy'], 4)
            self.cli('check')
        # Re-recording identical adapter bytes cannot conceal a stalled investigation.
        self.assertFalse(self.record()['iterations'][-1]['meaningfulProgress'])
        self.assertFalse(self.record()['iterations'][-1]['meaningfulProgress'])
        packet = json.loads(self.cli('check').stdout)
        self.assertIn('two-iterations-without-progress', packet['progress']['reasons'])

    def test_generated_bundles_unknown_js_and_qa_never_count_as_implementation(self):
        names = ['assets/elm.js', 'assets/bar.js', 'assets/popup.js',
                 'assets/unknown-generated.js', 'qa/bar-adapter.js', 'src/bar-adapter.js']
        self.select(names)
        for name in names:
            self.fixture.write('implementation/warlock/' + name, 'new artifact bytes\n')
            self.assertFalse(self.record()['iterations'][-1]['meaningfulProgress'], name)
        self.cli('check')

    def test_policy_one_and_two_adapter_records_remain_valid_and_nonprogress(self):
        self.select(['assets/popup-adapter.js'])
        self.fixture.write('implementation/warlock/assets/popup-adapter.js', 'changed adapter\n')
        record = self.record()
        path = '.warlock-contributor/slice.json'
        for policy in (1, 2):
            record['iterations'][-1].update(progressPolicy=policy, meaningfulProgress=False)
            self.fixture.write(path, record)
            self.cli('check')
        record['iterations'][-1].pop('progressPolicy')
        self.fixture.write(path, record)
        self.cli('check')
        # A new record uses the current policy without treating old bytes as a new fix.
        self.assertFalse(self.record()['iterations'][-1]['meaningfulProgress'])
        self.fixture.write('implementation/warlock/assets/popup-adapter.js', 'second changed adapter\n')
        self.assertTrue(self.record()['iterations'][-1]['meaningfulProgress'])

    def test_fabricated_progress_or_unknown_policy_is_rejected(self):
        self.select(['assets/elm.js'])
        self.fixture.write('implementation/warlock/assets/elm.js', 'changed generated bytes\n')
        record = self.record()
        record['iterations'][-1]['meaningfulProgress'] = True
        self.fixture.write('.warlock-contributor/slice.json', record)
        self.cli('check', ok=False)
        record['iterations'][-1].update(meaningfulProgress=False, progressPolicy=99)
        self.fixture.write('.warlock-contributor/slice.json', record)
        self.cli('check', ok=False)


if __name__ == '__main__':
    unittest.main()
