#define _POSIX_C_SOURCE 200809L
#define _XOPEN_SOURCE 700
#include <gtk/gtk.h>
#include <gdk/wayland/gdkwayland.h>
#include <json-glib/json-glib.h>
#include <wayland-client.h>
#include <glib-unix.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "commands.h"

typedef struct { char name; GtkWidget *widget, *entry, *landmark; GtkEventController *controllers[3]; GdkSurface *surface; uint64_t instance, generation; } Role;
static Role roles[5];
static GtkWindowGroup *family, *independent;
static GMainLoop *loop;
static uint64_t event_sequence, request_sequence, next_instance;
static int exit_code;
static uint64_t process_started;
static gboolean stopping, default_group;
static uint32_t surface_id(GdkSurface *s) { if (!s || !GDK_IS_WAYLAND_SURFACE(s)) return 0; struct wl_surface *w=gdk_wayland_surface_get_wl_surface(s); return w ? wl_proxy_get_id((struct wl_proxy *)w):0; }
static void integer(JsonBuilder *b,const char *key,gint64 n) { json_builder_set_member_name(b,key);json_builder_add_int_value(b,n); }
static void boolean(JsonBuilder *b,const char *key,gboolean n) { json_builder_set_member_name(b,key);json_builder_add_boolean_value(b,n); }
static void string(JsonBuilder *b,const char *key,const char *s) { json_builder_set_member_name(b,key);json_builder_add_string_value(b,s); }
static void number(JsonBuilder *b,const char *key,double n) { if(isfinite(n)){json_builder_set_member_name(b,key);json_builder_add_double_value(b,n);} }
static JsonBuilder *record(const char *event,Role *r) {
 JsonBuilder *b=json_builder_new();json_builder_begin_object(b);integer(b,"schema",1);integer(b,"sequence",++event_sequence);integer(b,"pid",getpid());integer(b,"processStarted",process_started);integer(b,"monotonicUs",g_get_monotonic_time());integer(b,"requestSequence",request_sequence);string(b,"event",event);string(b,"profile",default_group?"default-group":"independent-groups");
 if(r){char name[2]={r->name,0};string(b,"role",name);integer(b,"instance",r->instance);integer(b,"mapGeneration",r->generation);integer(b,"surfaceId",surface_id(r->surface));boolean(b,"mapped",r->widget && gtk_widget_get_mapped(r->widget));string(b,"surfaceClass",r->surface ? G_OBJECT_TYPE_NAME(r->surface):"unavailable");
 if(r->surface && GDK_IS_TOPLEVEL(r->surface)){GdkToplevelState state=gdk_toplevel_get_state(GDK_TOPLEVEL(r->surface));integer(b,"observedState",state);boolean(b,"observedMaximized",state&GDK_TOPLEVEL_STATE_MAXIMIZED);boolean(b,"observedFullscreen",state&GDK_TOPLEVEL_STATE_FULLSCREEN);boolean(b,"observedMinimized",state&GDK_TOPLEVEL_STATE_MINIMIZED);}
 if(r->widget){integer(b,"allocatedWidth",gtk_widget_get_width(r->widget));integer(b,"allocatedHeight",gtk_widget_get_height(r->widget));}if(r->surface){integer(b,"surfaceWidth",gdk_surface_get_width(r->surface));integer(b,"surfaceHeight",gdk_surface_get_height(r->surface));integer(b,"surfaceScale",gdk_surface_get_scale_factor(r->surface));}if(r->entry){const char *draft=gtk_editable_get_text(GTK_EDITABLE(r->entry));string(b,"draftUTF8",draft);integer(b,"draftBytes",strlen(draft));}
 if(r->landmark && r->widget){GtkNative*n=gtk_widget_get_native(r->landmark);graphene_rect_t bounds;gboolean valid=n&&gtk_widget_compute_bounds(r->landmark,GTK_WIDGET(n),&bounds);boolean(b,"landmarkBoundsAvailable",valid);if(valid){number(b,"landmarkNativeX",bounds.origin.x);number(b,"landmarkNativeY",bounds.origin.y);number(b,"landmarkWidth",bounds.size.width);number(b,"landmarkHeight",bounds.size.height);double x,y;gtk_native_get_surface_transform(n,&x,&y);number(b,"nativeSurfaceTransformX",x);number(b,"nativeSurfaceTransformY",y);}}
 if(r->widget && GTK_IS_WINDOW(r->widget)){GtkWindowGroup *group=gtk_window_get_group(GTK_WINDOW(r->widget));string(b,"observedWindowGroup",group==family?"family":group==independent?"independent":"default");boolean(b,"hasExplicitWindowGroup",gtk_window_has_group(GTK_WINDOW(r->widget)));boolean(b,"requestedModal",gtk_window_get_modal(GTK_WINDOW(r->widget)));GtkWindow *parent=gtk_window_get_transient_for(GTK_WINDOW(r->widget));integer(b,"transientSurfaceId",parent ? surface_id(gtk_native_get_surface(GTK_NATIVE(parent))):0);}
 }
 return b;
}
static void emit(JsonBuilder *b){json_builder_end_object(b);JsonNode *node=json_builder_get_root(b);JsonGenerator *g=json_generator_new();json_generator_set_root(g,node);char *text=json_generator_to_data(g,NULL);puts(text);fflush(stdout);g_free(text);json_node_free(node);g_object_unref(g);g_object_unref(b);}
static void state_changed(GObject *object,GParamSpec *spec,gpointer data){(void)spec;Role*r=data;if(object!=G_OBJECT(r->surface)||!r->widget)return;emit(record("surface-state",r));}
static void mapped(GtkWidget *w,gpointer data){Role *r=data;if(w!=r->widget)return;if(r->surface){g_signal_handlers_disconnect_by_data(r->surface,r);g_clear_object(&r->surface);}GtkNative *native=gtk_widget_get_native(w);GdkSurface *s=native?gtk_native_get_surface(native):NULL;if(s){r->surface=g_object_ref(s);if(GDK_IS_TOPLEVEL(s))g_signal_connect(s,"notify::state",G_CALLBACK(state_changed),r);}r->generation++;emit(record("map",r));}
static void unmapped(GtkWidget *w,gpointer data){Role*r=data;if(w!=r->widget)return;emit(record("unmap",r));}
static JsonBuilder *input_record(const char *event,Role *r,GtkEventController *c){JsonBuilder *b=record(event,r);GdkEvent *e=gtk_event_controller_get_current_event(c);boolean(b,"rawEventAvailable",e!=NULL);integer(b,"sourceSurfaceId",e?surface_id(gdk_event_get_surface(e)):0);if(e){GdkEventType type=gdk_event_get_event_type(e);integer(b,"rawEventType",type);integer(b,"rawEventTime",gdk_event_get_time(e));integer(b,"rawModifiers",gdk_event_get_modifier_state(e));if(type==GDK_BUTTON_PRESS||type==GDK_BUTTON_RELEASE)integer(b,"rawButton",gdk_button_event_get_button(e));if(type==GDK_KEY_PRESS||type==GDK_KEY_RELEASE){integer(b,"rawKeyval",gdk_key_event_get_keyval(e));integer(b,"rawKeycode",gdk_key_event_get_keycode(e));}}double x,y;gboolean has=e && gdk_event_get_position(e,&x,&y);boolean(b,"hasSurfacePosition",has);if(has){number(b,"surfaceX",x);number(b,"surfaceY",y);}if(r->widget){GtkNative *n=gtk_widget_get_native(r->widget);if(n){gtk_native_get_surface_transform(n,&x,&y);number(b,"nativeTransformX",x);number(b,"nativeTransformY",y);}}return b;}
static gboolean current_controller(Role*r,GtkEventController*c){return r->widget && gtk_event_controller_get_widget(c)==r->widget;}
static void pressed(GtkGestureClick *c,int count,double x,double y,gpointer data){if(!current_controller(data,GTK_EVENT_CONTROLLER(c)))return;JsonBuilder*b=input_record("button-press",data,GTK_EVENT_CONTROLLER(c));integer(b,"button",gtk_gesture_single_get_current_button(GTK_GESTURE_SINGLE(c)));integer(b,"clickCount",count);number(b,"widgetX",x);number(b,"widgetY",y);emit(b);}
static void released(GtkGestureClick*c,int count,double x,double y,gpointer data){if(!current_controller(data,GTK_EVENT_CONTROLLER(c)))return;JsonBuilder*b=input_record("button-release",data,GTK_EVENT_CONTROLLER(c));integer(b,"button",gtk_gesture_single_get_current_button(GTK_GESTURE_SINGLE(c)));integer(b,"clickCount",count);number(b,"widgetX",x);number(b,"widgetY",y);emit(b);}
static gboolean key_pressed(GtkEventControllerKey*c,guint key,guint code,GdkModifierType state,gpointer data){if(!current_controller(data,GTK_EVENT_CONTROLLER(c)))return FALSE;JsonBuilder*b=input_record("key-press",data,GTK_EVENT_CONTROLLER(c));integer(b,"keyval",key);integer(b,"keycode",code);integer(b,"modifiers",state);emit(b);return FALSE;}
static void key_released(GtkEventControllerKey*c,guint key,guint code,GdkModifierType state,gpointer data){if(!current_controller(data,GTK_EVENT_CONTROLLER(c)))return;JsonBuilder*b=input_record("key-release",data,GTK_EVENT_CONTROLLER(c));integer(b,"keyval",key);integer(b,"keycode",code);integer(b,"modifiers",state);emit(b);}
static void motion(GtkEventControllerMotion*c,double x,double y,gpointer data){if(!current_controller(data,GTK_EVENT_CONTROLLER(c)))return;JsonBuilder*b=input_record("motion",data,GTK_EVENT_CONTROLLER(c));number(b,"widgetX",x);number(b,"widgetY",y);emit(b);}
static void attach(Role*r){g_signal_connect(r->widget,"map",G_CALLBACK(mapped),r);g_signal_connect(r->widget,"unmap",G_CALLBACK(unmapped),r);GtkGesture*c=gtk_gesture_click_new();gtk_gesture_single_set_button(GTK_GESTURE_SINGLE(c),0);gtk_event_controller_set_propagation_phase(GTK_EVENT_CONTROLLER(c),GTK_PHASE_CAPTURE);g_signal_connect(c,"pressed",G_CALLBACK(pressed),r);g_signal_connect(c,"released",G_CALLBACK(released),r);r->controllers[0]=g_object_ref(GTK_EVENT_CONTROLLER(c));gtk_widget_add_controller(r->widget,GTK_EVENT_CONTROLLER(c));GtkEventController*k=gtk_event_controller_key_new();gtk_event_controller_set_propagation_phase(k,GTK_PHASE_CAPTURE);g_signal_connect(k,"key-pressed",G_CALLBACK(key_pressed),r);g_signal_connect(k,"key-released",G_CALLBACK(key_released),r);r->controllers[1]=g_object_ref(k);gtk_widget_add_controller(r->widget,k);GtkEventController*m=gtk_event_controller_motion_new();g_signal_connect(m,"motion",G_CALLBACK(motion),r);r->controllers[2]=g_object_ref(m);gtk_widget_add_controller(r->widget,m);}
static void close_role(Role*r){if(!r->widget)return;emit(record("destroy-request",r));for(int i=0;i<3;i++){if(r->controllers[i]){g_signal_handlers_disconnect_by_data(r->controllers[i],r);g_clear_object(&r->controllers[i]);}}r->entry=NULL;r->landmark=NULL;if(r->surface){g_signal_handlers_disconnect_by_data(r->surface,r);g_clear_object(&r->surface);}g_signal_handlers_disconnect_by_data(r->widget,r);if(GTK_IS_WINDOW(r->widget))gtk_window_destroy(GTK_WINDOW(r->widget));else{gtk_popover_popdown(GTK_POPOVER(r->widget));gtk_widget_unparent(r->widget);}g_clear_object(&r->widget);emit(record("local-destroy",r));}
static void finish(int code){if(stopping)return;stopping=TRUE;exit_code=code;close_role(&roles[4]);close_role(&roles[3]);close_role(&roles[1]);close_role(&roles[0]);close_role(&roles[2]);emit(record(code?"failed-exit":"normalexit",NULL));g_main_loop_quit(loop);}
static void retire_role(Role*r){if(r==&roles[0]){close_role(&roles[4]);close_role(&roles[3]);close_role(&roles[1]);}else if(r==&roles[1])close_role(&roles[3]);close_role(r);}
static gboolean close_requested(GtkWindow*w,gpointer data){Role*r=data;if(GTK_WIDGET(w)!=r->widget)return TRUE;retire_role(r);return TRUE;}
static void popover_clicked(GtkButton*button,gpointer data){Role*r=data;if(r->widget && gtk_widget_get_ancestor(GTK_WIDGET(button),GTK_TYPE_POPOVER)==r->widget){emit(record("popover-button-clicked",r));close_role(r);}}
static void draw(GtkDrawingArea*area,cairo_t*cr,int width,int height,gpointer data){Role*r=data;if(!r->widget||gtk_widget_get_ancestor(GTK_WIDGET(area),GTK_TYPE_WINDOW)!=r->widget)return;cairo_set_source_rgb(cr,r->name=='A'?0.8:0.2,r->name=='C'?0.8:0.2,r->name=='B'?0.8:0.2);cairo_paint(cr);cairo_set_source_rgb(cr,1,1,0);cairo_rectangle(cr,4,4,8,8);cairo_fill(cr);JsonBuilder*b=record("draw-queued",r);integer(b,"drawWidth",width);integer(b,"drawHeight",height);emit(b);}
static void window_new(int index,char name,GtkWindow*parent,gboolean modal){Role*r=&roles[index];r->name=name;r->instance=++next_instance;r->generation=0;r->widget=g_object_ref_sink(gtk_window_new());char title[64];snprintf(title,sizeof title,"ELM-GTK4-%c-%d",name,getpid());gtk_window_set_title(GTK_WINDOW(r->widget),title);gtk_window_set_default_size(GTK_WINDOW(r->widget),320,180);if(parent)gtk_window_set_transient_for(GTK_WINDOW(r->widget),parent);gtk_window_set_modal(GTK_WINDOW(r->widget),modal);if(!default_group)gtk_window_group_add_window(index==2?independent:family,GTK_WINDOW(r->widget));GtkWidget*box=gtk_box_new(GTK_ORIENTATION_VERTICAL,8);GtkWidget*label=gtk_label_new(title);GtkWidget*entry=gtk_entry_new();r->entry=entry;gtk_entry_set_max_length(GTK_ENTRY(entry),256);GtkWidget*area=gtk_drawing_area_new();r->landmark=area;gtk_widget_set_size_request(area,100,60);gtk_drawing_area_set_draw_func(GTK_DRAWING_AREA(area),draw,r,NULL);gtk_box_append(GTK_BOX(box),area);gtk_editable_set_text(GTK_EDITABLE(entry),"ELM-ROLE-DRAFT");gtk_box_append(GTK_BOX(box),label);gtk_box_append(GTK_BOX(box),entry);gtk_window_set_child(GTK_WINDOW(r->widget),box);attach(r);g_signal_connect(r->widget,"close-request",G_CALLBACK(close_requested),r);emit(record("create",r));gtk_window_present(GTK_WINDOW(r->widget));}
static gboolean execute(struct command*c){if(c->sequence<=request_sequence)return FALSE;request_sequence=c->sequence;JsonBuilder*b=record("request",NULL);string(b,"command",c->operation);if(c->role){char name[2]={c->role,0};string(b,"requestedRole",name);}emit(b);
 if(!strcmp(c->operation,"quit")){finish(0);return TRUE;}
 if(!strcmp(c->operation,"inspect")){for(int i=0;i<5;i++)if(roles[i].widget)emit(record("inspect",&roles[i]));return TRUE;}
 if(!strcmp(c->operation,"create-family")||!strcmp(c->operation,"create-owners")){if(roles[0].widget||roles[2].widget)return FALSE;window_new(0,'A',NULL,FALSE);window_new(2,'C',NULL,FALSE);if(!strcmp(c->operation,"create-family"))window_new(1,'B',GTK_WINDOW(roles[0].widget),TRUE);return TRUE;}
 if(!roles[0].widget && !c->role)return FALSE;
 if(!strcmp(c->operation,"open-modal")){if(roles[1].widget)return FALSE;window_new(1,'B',GTK_WINDOW(roles[0].widget),TRUE);return TRUE;}
 if(!strcmp(c->operation,"close-modal")){if(!roles[1].widget)return FALSE;retire_role(&roles[1]);return TRUE;}
 if(!strcmp(c->operation,"close-owner")){retire_role(&roles[0]);return TRUE;}
 if(!strcmp(c->operation,"open-nested")){if(roles[3].widget||!roles[1].widget)return FALSE;window_new(3,'D',GTK_WINDOW(roles[1].widget),TRUE);return TRUE;}
 if(!strcmp(c->operation,"close-nested")){if(!roles[3].widget)return FALSE;close_role(&roles[3]);return TRUE;}
 if(!strcmp(c->operation,"open-popover")){if(roles[4].widget)return FALSE;Role*r=&roles[4];r->name='P';r->instance=++next_instance;r->generation=0;r->widget=g_object_ref_sink(gtk_popover_new());GtkWidget*owner=gtk_window_get_child(GTK_WINDOW(roles[0].widget));gtk_widget_set_parent(r->widget,owner);GdkRectangle rect={20,20,16,16};gtk_popover_set_pointing_to(GTK_POPOVER(r->widget),&rect);GtkWidget*button=gtk_button_new_with_label("ELM-POPOVER");r->landmark=button;g_signal_connect(button,"clicked",G_CALLBACK(popover_clicked),r);gtk_popover_set_child(GTK_POPOVER(r->widget),button);attach(r);emit(record("create",r));gtk_popover_popup(GTK_POPOVER(r->widget));return TRUE;}
 if(!strcmp(c->operation,"close-popover")){if(!roles[4].widget)return FALSE;close_role(&roles[4]);return TRUE;}
 Role*r=c->role=='A'?&roles[0]:&roles[2];if(!r->widget)return FALSE;GtkWindow*w=GTK_WINDOW(r->widget);if(!strcmp(c->operation,"minimize"))gtk_window_minimize(w);else if(!strcmp(c->operation,"restore"))gtk_window_unminimize(w);else if(!strcmp(c->operation,"maximize"))gtk_window_maximize(w);else if(!strcmp(c->operation,"unmaximize"))gtk_window_unmaximize(w);else return FALSE;emit(record("requested-state",r));return TRUE;
}
static gboolean stdin_ready(gint fd,GIOCondition condition,gpointer data){(void)data;static char line[512];static size_t used;char bytes[256];ssize_t n=read(fd,bytes,sizeof bytes);if(n<0 && (errno==EAGAIN||errno==EINTR))return G_SOURCE_CONTINUE;if(n<=0){if(used){emit(record("refusal",NULL));finish(6);}else finish(0);return G_SOURCE_REMOVE;}for(ssize_t i=0;i<n;i++){if(bytes[i]=='\n'){line[used]=0;struct command c;if(!parse_command(line,&c)||!execute(&c)){emit(record("refusal",NULL));finish(6);return G_SOURCE_REMOVE;}used=0;if(stopping)return G_SOURCE_REMOVE;}else if(bytes[i]==0||used>=511){emit(record("refusal",NULL));finish(6);return G_SOURCE_REMOVE;}else line[used++]=bytes[i];}(void)condition;return G_SOURCE_CONTINUE;}
static uint64_t own_start(void){char text[4096];FILE*f=fopen("/proc/self/stat","r");if(!f)return 0;char*read=fgets(text,sizeof text,f);fclose(f);if(!read)return 0;char*tail=strrchr(text,')');if(!tail)return 0;char*save=NULL;char*field=strtok_r(tail+1," ",&save);for(int index=3;field;index++,field=strtok_r(NULL," ",&save))if(index==22){errno=0;char*end;unsigned long long value=strtoull(field,&end,10);return !errno&&!(*end)&&value&&value<=INT64_MAX?value:0;}return 0;}
static gboolean protected_scope(void){char*text=NULL;if(!g_file_get_contents("/proc/self/cgroup",&text,NULL,NULL))return FALSE;gboolean match=g_regex_match_simple("/qa-harness\\.slice/qa-harness-[A-Za-z0-9_-]+\\.scope(\\n|$)",text,0,0);g_free(text);struct rlimit limit;if(getrlimit(RLIMIT_CORE,&limit))return FALSE;rlim_t expected=!g_strcmp0(getenv("WINDOW_QA_BACKTRACE"),"1")?RLIM_INFINITY:1;return match&&limit.rlim_cur==expected&&limit.rlim_max==expected;}
static gboolean canonical_runtime(const char *runtime) {
 char *resolved=realpath(runtime,NULL);
 gboolean valid=resolved && !strcmp(resolved,runtime);
 free(resolved);
 return valid;
}
static gboolean private_environment(void){const char*runtime=getenv("XDG_RUNTIME_DIR"),*display=getenv("WAYLAND_DISPLAY");struct stat st;char base[128];snprintf(base,sizeof base,"/run/user/%u/wqa/",(unsigned)getuid());if(!protected_scope()||!runtime||strncmp(runtime,base,strlen(base))||!runtime[strlen(base)]||strchr(runtime+strlen(base),'/')||!strcmp(runtime+strlen(base),".")||!strcmp(runtime+strlen(base),"..")||!canonical_runtime(runtime)||!display||!*display||strchr(display,'/'))return FALSE;if(lstat(runtime,&st)||!S_ISDIR(st.st_mode)||st.st_uid!=getuid()||(st.st_mode&0777)!=0700)return FALSE;char*path=g_build_filename(runtime,display,NULL);gboolean valid=!lstat(path,&st)&&S_ISSOCK(st.st_mode)&&st.st_uid==getuid();g_free(path);return valid && !g_strcmp0(getenv("ELM_GTK_ROLE_QA"),"1") && !g_strcmp0(getenv("GDK_BACKEND"),"wayland") && !g_strcmp0(getenv("WAYLAND_DEBUG"),"client");}
int main(int argc,char**argv){if(argc==2&&!strcmp(argv[1],"--describe")){puts("{\"schema\":1,\"toolkit\":\"GTK4\",\"nativeQualification\":false,\"commands\":\"SEQ command [A|C]\"}");return 0;}if(argc==3&&!strcmp(argv[1],"--validate-command")){struct command c;return parse_command(argv[2],&c)?0:6;}if(argc!=2||(strcmp(argv[1],"--run")&&strcmp(argv[1],"--run-default-group"))||!private_environment()){fputs("private Wayland QA environment required\n",stderr);return 2;}default_group=!strcmp(argv[1],"--run-default-group");process_started=own_start();if(!process_started)return 2;gtk_init();family=gtk_window_group_new();independent=gtk_window_group_new();loop=g_main_loop_new(NULL,FALSE);int flags=fcntl(STDIN_FILENO,F_GETFL);if(flags<0||fcntl(STDIN_FILENO,F_SETFL,flags|O_NONBLOCK)<0)return 2;g_unix_fd_add(STDIN_FILENO,G_IO_IN|G_IO_HUP|G_IO_ERR,stdin_ready,NULL);emit(record("ready",NULL));g_main_loop_run(loop);g_main_loop_unref(loop);g_object_unref(family);g_object_unref(independent);return exit_code;}
