#include "MappingWitness.hpp"
#include "ProcessRegistry.hpp"
#include <QFileInfo>
#include <QCryptographicHash>
#include <QRegularExpression>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <sys/sysmacros.h>
#include <unistd.h>
#include <cerrno>
#include <filesystem>
#include <memory>
#include <vector>
namespace Lifetime {
namespace {
void need(bool yes,const char*reason){checkKernelBudget();if(!yes)throw Refused(reason);}
QString link(const QString&name){return QString::fromStdString(std::filesystem::read_symlink(name.toStdString()).string());}
QVariantMap stamp(const struct stat&s){return {{"device",qulonglong(s.st_dev)},{"major",qulonglong(major(s.st_dev))},{"minor",qulonglong(minor(s.st_dev))},{"inode",qulonglong(s.st_ino)},{"mode",qulonglong(s.st_mode)},{"uid",qulonglong(s.st_uid)},{"gid",qulonglong(s.st_gid)},{"nlink",qulonglong(s.st_nlink)},{"size",qlonglong(s.st_size)},{"mtimeSeconds",qlonglong(s.st_mtim.tv_sec)},{"mtimeNanoseconds",qlonglong(s.st_mtim.tv_nsec)}};}
QVariantMap named(const QString&name){struct stat s{};need(QFileInfo(name).canonicalFilePath()==name,"Mapped canonical source path differs");need(lstat(name.toUtf8().constData(),&s)==0&&S_ISREG(s.st_mode),"Mapped named regular source unavailable");return stamp(s);}
QVariantMap fdSnapshot(int fd){struct stat s{};need(fstat(fd,&s)==0,"Mapped source FD fstat unavailable");struct statfs fs{};need(fstatfs(fd,&fs)==0,"Mapped source FD filesystem unavailable");const int flags=fcntl(fd,F_GETFL),fdflags=fcntl(fd,F_GETFD);need(flags>=0&&fdflags>=0,"Mapped FD flags unavailable");QVariantMap x;struct statx sx{};if(statx(fd,"",AT_EMPTY_PATH,STATX_BASIC_STATS|STATX_MNT_ID|STATX_SUBVOL,&sx))x={{"errno",errno}};else x={{"errno",0},{"mask",qulonglong(sx.stx_mask)},{"major",qulonglong(sx.stx_dev_major)},{"minor",qulonglong(sx.stx_dev_minor)},{"inode",qulonglong(sx.stx_ino)},{"mode",qulonglong(sx.stx_mode)},{"uid",qulonglong(sx.stx_uid)},{"gid",qulonglong(sx.stx_gid)},{"nlink",qulonglong(sx.stx_nlink)},{"size",qulonglong(sx.stx_size)},{"mountID",qulonglong(sx.stx_mnt_id)},{"subvolumeID",qulonglong(sx.stx_subvol)},{"mtimeSeconds",qlonglong(sx.stx_mtime.tv_sec)},{"mtimeNanoseconds",qulonglong(sx.stx_mtime.tv_nsec)}};return {{"stat",stamp(s)},{"statx",x},{"filesystemType",qulonglong(fs.f_type)},{"descriptorFlags",flags},{"descriptorFDFlags",fdflags},{"fdTarget",link(QString("/proc/self/fd/%1").arg(fd))},{"rawFDInfo",QString::fromLatin1(boundedFile(QString("/proc/self/fdinfo/%1").arg(fd)))}};}
QVariantMap identity(int pid){const auto root=QString("/proc/%1/").arg(pid);const auto status=boundedFile(root+"status");bool goodUID=false;for(const auto&line:status.split('\n'))if(line.startsWith("Uid:")){const auto parts=line.mid(4).simplified().split(' ');goodUID=parts.size()==4;for(const auto&part:parts)goodUID=goodUID&&part==QByteArray::number(getuid());}need(goodUID,"Actual mapping child all UID fields differ");const auto stat=boundedFile(root+"stat");const auto tail=stat.mid(stat.lastIndexOf(')')+2).simplified().split(' ');need(stat.lastIndexOf(')')>0&&tail.size()>=20&&tail[1]==QByteArray::number(getpid())&&tail[2]==QByteArray::number(getpgrp()),"Actual mapping child parent/group/stat differs");QVariantMap ns;for(const auto*name:{"user","mnt","net","pid","ipc","uts","cgroup"})ns[QString::fromLatin1(name)]=link(root+"ns/"+name);return {{"pid",pid},{"uid",qulonglong(getuid())},{"start",QString::fromLatin1(tail[19])},{"parent",QString::fromLatin1(tail[1])},{"group",QString::fromLatin1(tail[2])},{"executable",link(root+"exe")},{"argvSHA256",QString::fromLatin1(digest(boundedFile(root+"cmdline")))},{"cgroupSHA256",QString::fromLatin1(digest(boundedFile(root+"cgroup")))},{"namespaces",ns}};}
QString selectedMount(const QByteArray&raw,qulonglong id){QString found;int count=0;for(const auto&line:raw.split('\n'))if(line.startsWith(QByteArray::number(id)+' ')){++count;found=QString::fromLatin1(line);}need(count==1,"Actual source mount selection missing/ambiguous");return found;}
struct Source{int fd=-1;QString path;QVariantMap before,after,namedBefore,namedAfter;QByteArray sha;qulonglong mount=0;QString observerMountBefore,consumerMountBefore,observerMountAfter,consumerMountAfter;~Source(){if(fd>=0)close(fd);}};
struct VMA{QByteArray raw;QString path,range;QVariantMap before,after;};
QVariantMap mapLink(int pid,const QString&range){QVariantMap r;const auto path=QString("/proc/%1/map_files/%2").arg(pid).arg(range);try{r["link"]=link(path);}catch(const std::filesystem::filesystem_error&e){r["errno"]=e.code().value();r["error"]=QString::fromLocal8Bit(e.what());}catch(const std::exception&e){r["error"]=QString::fromLocal8Bit(e.what());}return r;}
QByteArray sourceHash(int fd){QCryptographicHash h(QCryptographicHash::Sha256);char buffer[65536];off_t offset=0;for(;;){checkKernelBudget();const auto n=pread(fd,buffer,sizeof(buffer),offset);if(n<0&&errno==EINTR)continue;need(n>=0,"Bounded mapped source pread failed");if(!n)break;offset+=n;need(offset<=128*1024*1024,"Mapped source hash byte bound");h.addData(QByteArrayView(buffer,n));}return h.result().toHex();}
}
void verifyOwnedMappings(int pid,const QByteArray&maps,const std::map<QString,std::pair<QByteArray,uint32_t>>&code,const SourceAliases&aliases,QVariantMap*evidence){
 const auto batchStartedAt=std::chrono::steady_clock::now();QVariantMap batch{{"schema","owned-map-device-batch-v2-current"},{"cacheScope","one-readKernel-call"},{"directMappedTargetFDClaimed",false},{"mappingMemoryBytesClaimed",false}};std::map<QString,std::unique_ptr<Source>>sources;std::vector<VMA>rows;QByteArray fresh;std::map<QString,QString>aliasBefore,aliasAfter;
 auto persist=[&]{QVariantList values;for(const auto&v:rows)values<<QVariantMap{{"rawLine",QString::fromLatin1(v.raw)},{"path",v.path},{"range",v.range},{"before",v.before},{"after",v.after}};QVariantMap files;for(const auto&[name,s]:sources)files[name]=QVariantMap{{"fdBefore",s->before},{"fdAfter",s->after},{"namedBefore",s->namedBefore},{"namedAfter",s->namedAfter},{"hash",QString::fromLatin1(s->sha)},{"observerMountBefore",s->observerMountBefore},{"consumerMountBefore",s->consumerMountBefore},{"observerMountAfter",s->observerMountAfter},{"consumerMountAfter",s->consumerMountAfter}};QVariantMap aliasesBefore,aliasesAfter;for(const auto&[n,t]:aliasBefore)aliasesBefore[n]=t;for(const auto&[n,t]:aliasAfter)aliasesAfter[n]=t;batch["aliasesBefore"]=aliasesBefore;batch["aliasesAfter"]=aliasesAfter;batch["declaredFrozenAliasCount"]=qulonglong(aliases.declaredCount());batch["currentAliasScope"]="expanded initial and fresh selected images plus launch references";batch["elapsedMicrosecondsAtPersistence"]=qlonglong(std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now()-batchStartedAt).count());batch["vmas"]=values;batch["sources"]=files;if(evidence)evidence->insert("ownedMappingBatch",batch);};
 try{
  batch["identityBefore"]=identity(pid);batch["mapsBeforeSHA256"]=QString::fromLatin1(digest(maps));const auto observerMounts=boundedFile("/proc/self/mountinfo",2*1024*1024),consumerMounts=boundedFile(QString("/proc/%1/mountinfo").arg(pid),2*1024*1024);batch["observerMountsBeforeSHA256"]=QString::fromLatin1(digest(observerMounts));batch["consumerMountsBeforeSHA256"]=QString::fromLatin1(digest(consumerMounts));const auto ns=link("/proc/self/ns/mnt");need(batch["identityBefore"].toMap()["namespaces"].toMap()["mnt"].toString()==ns,"Actual child/observer mount namespace differs");
  const auto syntax=QRegularExpression("^([0-9a-f]+)-([0-9a-f]+) ([r-][w-][x-][ps]) ([0-9a-f]+) ([0-9a-f]+):([0-9a-f]+) ([1-9][0-9]*) +(/[^\\n\\r]+)$");
  auto parsedRows=[&](const QByteArray&raw){std::vector<VMA>out;for(const auto&line:raw.split('\n')){if(line.isEmpty())continue;const auto parts=line.simplified().split(' ');need(parts.size()>=5,"Actual maps complete syntax required");const bool executable=parts[1].contains('x');const auto match=syntax.match(QString::fromLatin1(line));if(match.hasMatch()){const auto path=match.captured(8);need(code.contains(path)&&!path.endsWith(" (deleted)"),"Mapped source absent/deleted");out.push_back(VMA{line,path,match.captured(1)+'-'+match.captured(2),{}, {}});}else{const auto path=parts.size()>5?parts[5]:QByteArray();need(!path.startsWith('/'),"Disk VMA syntax refused");need(!executable||path=="[vdso]"||path=="[vsyscall]","Fresh anonymous/unknown executable mapping refused");}}return out;};
  auto proveAliasesBefore=[&](const std::vector<VMA>&selected){std::set<QString>images;for(const auto&v:selected)images.insert(v.path);for(const auto&name:aliases.select(images))if(!aliasBefore.contains(name)){const auto actual=link(name);aliasBefore[name]=actual;need(actual==aliases.target(name),"Relevant frozen alias differs before source proof");}};
  rows=parsedRows(maps);proveAliasesBefore(rows);need(!rows.empty(),"Actual disk mapping batch empty");for(auto&v:rows)v.before=mapLink(pid,v.range);
  auto openSources=[&](const std::vector<VMA>&selected){for(const auto&v:selected)if(!sources.contains(v.path)){auto s=std::make_unique<Source>();s->path=v.path;s->namedBefore=named(v.path);const auto encoded=v.path.toUtf8();s->fd=open(encoded.constData(),O_RDONLY|O_NOFOLLOW|O_CLOEXEC);if(s->fd<0){batch["sourceOpenErrno"]=errno;sources[v.path]=std::move(s);throw Refused("Actual frozen source FD unavailable");}auto*retained=s.get();sources[v.path]=std::move(s);auto&saved=*retained;saved.before=fdSnapshot(saved.fd);const auto sx=saved.before.value("statx").toMap();need(sx.contains("errno")&&sx.value("errno").toInt()==0&&(sx.value("mask").toULongLong()&STATX_MNT_ID),"Exact mapped FD statx mount required");saved.mount=sx.value("mountID").toULongLong();saved.observerMountBefore=selectedMount(observerMounts,saved.mount);saved.consumerMountBefore=selectedMount(consumerMounts,saved.mount);const auto hashBegin=std::chrono::steady_clock::now();saved.sha=sourceHash(saved.fd);batch["lastHashMicroseconds"]=qlonglong(std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now()-hashBegin).count());batch["lastHashedPath"]=v.path;}};
  openSources(rows);fresh=boundedFile(QString("/proc/%1/maps").arg(pid),2*1024*1024);batch["rawMapsAfter"]=QString::fromLatin1(fresh);auto freshRows=parsedRows(fresh);proveAliasesBefore(freshRows);openSources(freshRows);
  const auto observerAfter=boundedFile("/proc/self/mountinfo",2*1024*1024),consumerAfter=boundedFile(QString("/proc/%1/mountinfo").arg(pid),2*1024*1024);batch["mapsAfterSHA256"]=QString::fromLatin1(digest(fresh));batch["observerMountsAfterSHA256"]=QString::fromLatin1(digest(observerAfter));batch["consumerMountsAfterSHA256"]=QString::fromLatin1(digest(consumerAfter));
  for(auto&[_,s]:sources){s->after=fdSnapshot(s->fd);s->namedAfter=named(s->path);s->observerMountAfter=selectedMount(observerAfter,s->mount);s->consumerMountAfter=selectedMount(consumerAfter,s->mount);}
  for(const auto&[name,before]:aliasBefore){const auto actual=link(name);aliasAfter[name]=actual;need(actual==before&&actual==aliases.target(name),"Relevant frozen alias changed after source proof");}
  for(auto&v:rows)v.after=mapLink(pid,v.range);batch["identityAfter"]=identity(pid);need(batch["identityBefore"]==batch["identityAfter"],"Actual mapped child identity changed");need(link("/proc/self/ns/mnt")==ns,"Observer mount namespace changed");
  auto facts=[&](const VMA&v){const auto&s=*sources.at(v.path);return QVariantMap{{"diagnosticCompleted",true},{"identityUnchanged",batch["identityBefore"]==batch["identityAfter"]},{"identityBefore",batch["identityBefore"]},{"identityAfter",batch["identityAfter"]},{"sourceFDUnchanged",s.before==s.after},{"fdBefore",s.before},{"fdAfter",s.after},{"namedUnchanged",s.namedBefore==s.namedAfter},{"namedBefore",s.namedBefore},{"namedAfter",s.namedAfter},{"mapFilesUnchanged",v.before==v.after},{"mapFilesBefore",v.before},{"mapFilesAfter",v.after},{"selectedMountUnchanged",s.observerMountBefore==s.observerMountAfter&&s.consumerMountBefore==s.consumerMountAfter},{"observerSelectedMount",s.observerMountBefore},{"childSelectedMount",s.consumerMountBefore},{"observerSelectedMountAfter",s.observerMountAfter},{"childSelectedMountAfter",s.consumerMountAfter},{"observerMountNamespace",ns},{"childMountNamespace",ns},{"selectedRowBeforePresent",maps.split('\n').contains(v.raw)},{"selectedRowAfterPresent",fresh.split('\n').contains(v.raw)},{"rawLine",QString::fromLatin1(v.raw)},{"path",v.path},{"selectedBackingSHA256",QString::fromLatin1(s.sha)}};};
  // All original and independently fresh implicated images must pass frozen
  // source/FD/mount/device guards BEFORE a MappingChanged can leave this call.
  for(const auto&v:rows)verifyFrozenMappingSource(facts(v),code.at(v.path).first,code.at(v.path).second);for(const auto&v:freshRows)verifyFrozenMappingSource(facts(v),code.at(v.path).first,code.at(v.path).second);
  bool changed=false;QVariantList changes;
  for(const auto&v:rows){const bool present=fresh.split('\n').contains(v.raw);if(!present){changed=true;changes<<QVariantMap{{"originalRawRow",QString::fromLatin1(v.raw)},{"freshRowAbsent",true},{"before",v.before},{"after",v.after}};}else{need(v.before.contains("link")&&v.before["link"].toString()==v.path&&v.after.contains("link")&&v.after["link"].toString()==v.path,"Unexplained current VMA backing name differs/unavailable");}for(const auto&point:{v.before,v.after})if(point.contains("errno"))need(point["errno"].toInt()==ENOENT&&!present,"VMA map_files error not explained by fresh disappearance");}
  for(const auto&v:freshRows)if(!maps.split('\n').contains(v.raw)){changed=true;changes<<QVariantMap{{"newRawRow",QString::fromLatin1(v.raw)},{"knownFrozenSourceFDVerified",true}};}
  if(changed){batch["explainedChanges"]=changes;batch["typedMappingChanged"]=true;batch["accepted"]=false;persist();throw MappingChanged("Wholly fresh known frozen loader VMA set differs");}
  for(const auto&v:rows){const auto r=facts(v);if(evidence)evidence->insert("lastOwnedMappingWitness",r);verifyCapturedMapping(r,code.at(v.path).first,code.at(v.path).second);}
  batch["accepted"]=true;batch["uniqueImagesHashed"]=qulonglong(sources.size());batch["exactVMARowsChecked"]=qulonglong(rows.size());persist();
 }catch(const std::exception&e){batch["accepted"]=false;batch["failure"]=QString::fromLocal8Bit(e.what());persist();throw;}
}
}
