import hashlib,json,pathlib,resource,sys,time,subprocess,shlex,traceback
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
ROOT=pathlib.Path(__file__).resolve().parents[1];REPO=ROOT.parents[1];OUT=ROOT/'qa'/('prepare-'+str(time.time_ns()));OUT.mkdir()
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
r={'passed':False,'nativeLaunched':False,'nativeAcceptance':False,'fullReleaseAccepted':False}
try:
 parent=REPO/'implementation/warlock-client-provider-native-v34';old=parent/'qa/preflight.json';pre=json.loads(old.read_text());assert pre['passed']
 inputs=dict(pre['inputs'])
 for p,h in inputs.items():assert sha(p)==h,p
 inputs[str(old)]=sha(old)
 baseline=parent/'qa/native-1791257839724867928/report.json';accepted=json.loads(baseline.read_text());assert accepted['passed'] and accepted['cleanupPassed'] and len(accepted['checks'])==1351 and all(row['passed'] for row in accepted['checks']) and len(accepted['ownedExitCodes'])==125 and all(row['exitCode']==0 for row in accepted['ownedExitCodes'])
 for rel,h in accepted['artifacts'].items():assert sha(baseline.parent/rel)==h,rel
 inputs[str(baseline)]=sha(baseline);pre['retainedFamilyObserverReport']=str(baseline)
 owner=REPO/'implementation/warlock-family-style-crop-capture-v16';descriptor=owner/'native-build-report.json';pair=json.loads(descriptor.read_text());assert pair['result']=='pass' and sha(ROOT/'native-build-report.json')==sha(descriptor) and sha(pair['binary'])==pair['sha256'] and sha(pair['plugin']['path'])==pair['plugin']['sha256']
 build=pathlib.Path(pair['pluginBuildReport']);assert sha(build)==pair['pluginBuildReportSHA256'];compiled=json.loads(build.read_text());assert compiled['passed'] and not compiled['missingSymbols']
 coreReport=pathlib.Path(pair['buildReport']);assert sha(coreReport)==pair['buildReportSHA256'];coreBuilt=json.loads(coreReport.read_text());assert coreBuilt['passed'] and pathlib.Path(coreBuilt['ancestor']['report']).parent/'Hyprland'==REPO/'implementation/warlock-core-family-crop-v5/build-1791276470213981301/Hyprland'
 coreManifest=pathlib.Path(pair['coreComponentManifest']);assert sha(coreManifest)==pair['coreComponentManifestSHA256'];held=json.loads(coreManifest.read_text())
 for rel,row in held['files'].items():assert sha(coreManifest.parent/rel)==row['sha256'],rel
 for proof in [compiled,coreBuilt]:
  for key in ['dependencies','linkDependencies','linkedLibraries','tools']:
   for p,h in proof.get(key,{}).items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in compiled['inputs'].items():assert sha(owner/rel)==h,rel;inputs[str(owner/rel)]=h
 closure=pathlib.Path(pair['linkClosureReport']);assert sha(closure)==pair['linkClosureReportSHA256'] and not json.loads(closure.read_text())['missingSymbols']
 for p in [descriptor,build,closure,coreReport,coreManifest,pathlib.Path(pair['binary']),pathlib.Path(pair['plugin']['path']),*ROOT.glob('*'),*ROOT.joinpath('qa').glob('*.py')]:
  if p.is_file():inputs[str(p)]=sha(p)
 familyFD=REPO/'implementation/warlock-family-fd-qualification-v1/qa/test-report.json';pointer=json.loads(familyFD.read_text());familyFDReport=pathlib.Path(pointer['path']);assert sha(familyFDReport)==pointer['sha256'];proof=json.loads(familyFDReport.read_text());assert proof['passed'] and proof['evidence']['physicalFDClosed'] and proof['evidence']['physicalMappingClosed']
 for p,h in proof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in proof['artifacts'].items():assert sha(familyFDReport.parent/rel)==h,rel;inputs[str(familyFDReport.parent/rel)]=h
 inputs[str(familyFD)]=sha(familyFD);inputs[str(familyFDReport)]=sha(familyFDReport);pre['familyFDReport']=str(familyFDReport)
 cropFD=REPO/'implementation/warlock-family-crop-fd-qualification-v2/qa/test-report.json';pointer=json.loads(cropFD.read_text());cropReport=pathlib.Path(pointer['path']);assert sha(cropReport)==pointer['sha256'];cropProof=json.loads(cropReport.read_text());assert cropProof['passed'] and cropProof['evidence']['legacy']['checks']==150
 for p,h in cropProof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in cropProof['artifacts'].items():assert sha(cropReport.parent/rel)==h,rel;inputs[str(cropReport.parent/rel)]=h
 inputs[str(cropFD)]=sha(cropFD);inputs[str(cropReport)]=sha(cropReport);pre['cropFDReport']=str(cropReport)
 oldCombined=REPO/'implementation/warlock-client-provider-native-v37/qa/native-1791259128393147111/report.json';oldNative=json.loads(oldCombined.read_text());assert oldNative['passed'] and oldNative['cleanupPassed'] and len(oldNative['checks'])==1524
 inputs[str(oldCombined)]=sha(oldCombined);pre['retainedCombinedFamilyReport']=str(oldCombined)
 oldCrop=REPO/'implementation/warlock-client-provider-native-v38/qa/native-1791260728575460795/report.json';oldCropNative=json.loads(oldCrop.read_text());assert oldCropNative['passed'] and oldCropNative['cleanupPassed'] and len(oldCropNative['checks'])==1612
 inputs[str(oldCrop)]=sha(oldCrop);pre['retainedNativeCropReport']=str(oldCrop)
 styleModel=REPO/'implementation/warlock-family-style-revisions-v2/qa/model-report.json';pointer=json.loads(styleModel.read_text());styleReport=pathlib.Path(pointer['path']);assert sha(styleReport)==pointer['sha256'];styleProof=json.loads(styleReport.read_text());assert styleProof['passed'] and len(styleProof['selectedNames'])==9 and styleProof['states']==29
 for p,h in styleProof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in styleProof['artifacts'].items():assert sha(styleReport.parent/rel)==h,rel;inputs[str(styleReport.parent/rel)]=h
 inputs[str(styleReport)]=sha(styleReport);inputs[str(styleModel)]=sha(styleModel);pre['styleModelReport']=str(styleReport)
 retainedStyle=REPO/'implementation/warlock-client-provider-native-v41/qa/native-1791261901860161292/report.json';retained=json.loads(retainedStyle.read_text());assert retained['passed'] and retained['cleanupPassed'] and len(retained['checks'])==1636 and len(retained['ownedExitCodes'])==150 and all(row['exitCode']==0 for row in retained['ownedExitCodes'])
 for rel,h in retained['artifacts'].items():assert sha(retainedStyle.parent/rel)==h,rel
 inputs[str(retainedStyle)]=sha(retainedStyle);pre['retainedNativeStyleReport']=str(retainedStyle)
 styleCropFD=REPO/'implementation/warlock-family-style-crop-fd-qualification-v1/qa/test-report.json';pointer=json.loads(styleCropFD.read_text());styleCropReport=pathlib.Path(pointer['path']);assert sha(styleCropReport)==pointer['sha256'];styleCropProof=json.loads(styleCropReport.read_text());assert styleCropProof['passed'] and styleCropProof['evidence']['legacy']['checks']==150 and styleCropProof['evidence']['qualify']['checks']==295
 for p,h in styleCropProof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in styleCropProof['artifacts'].items():assert sha(styleCropReport.parent/rel)==h,rel;inputs[str(styleCropReport.parent/rel)]=h
 inputs[str(styleCropFD)]=sha(styleCropFD);inputs[str(styleCropReport)]=sha(styleCropReport);pre['styleCropFDReport']=str(styleCropReport)
 failed42=REPO/'implementation/warlock-client-provider-native-v42/qa/native-1791262614875927452/report.json';failure=json.loads(failed42.read_text());assert not failure['passed'] and any(row['name']=='stoppedNewLeaseRetainsOriginalNativeJob' and not row['passed'] for row in failure['checks']);inputs[str(failed42)]=sha(failed42);pre['retainedFailedStyleCropReport']=str(failed42)
 failed44=REPO/'implementation/warlock-client-provider-native-v44/qa/native-1791264636216724357/report.json';failed44Proof=json.loads(failed44.read_text());assert not failed44Proof['passed'] and failed44Proof['cleanupPassed'] and any(row['name']=='familyWebCanonicalFamilyCoverage' and not row['passed'] for row in failed44Proof['checks']);inputs[str(failed44)]=sha(failed44);pre['retainedFailedFamilyWebReport']=str(failed44)
 failed46=REPO/'implementation/warlock-client-provider-native-v46/qa/native-1791265271172342426/report.json';failed46Proof=json.loads(failed46.read_text());assert not failed46Proof['passed'] and failed46Proof['cleanupPassed'] and any(row['name']=='familyHistoricalMinimizeExactCommittedNativeEffect' and not row['passed'] and row['outcome']['reason']=='seat-grab' for row in failed46Proof['checks']);inputs[str(failed46)]=sha(failed46);pre['retainedFailedFamilyHistoricalReport']=str(failed46)
 failed48=REPO/'implementation/warlock-client-provider-native-v48/qa/native-1791265464350990212/report.json';failed48Proof=json.loads(failed48.read_text());assert not failed48Proof['passed'] and failed48Proof['cleanupPassed'] and any(row['name']=='familyHistoricalMinimizeExactCommittedNativeEffect' and not row['passed'] and row['outcome']['reason']=='seat-grab' for row in failed48Proof['checks']);inputs[str(failed48)]=sha(failed48);pre['retainedFailedFamilyGTKGrabReport']=str(failed48)
 failed49=REPO/'implementation/warlock-client-provider-native-v49/qa/native-1791265648045047174/report.json';failed49Proof=json.loads(failed49.read_text());assert not failed49Proof['passed'] and failed49Proof['cleanupPassed'] and not any(not row['passed'] for row in failed49Proof['checks']) and 'missing-popup' in failed49Proof['traceback'] and 'familyHistoricalEvidence' in failed49Proof;inputs[str(failed49)]=sha(failed49);pre['retainedFailedHistoricalCleanupReport']=str(failed49)
 failed51=REPO/'implementation/warlock-client-provider-native-v51/qa/native-1791266300446781817/report.json';failed51Proof=json.loads(failed51.read_text());assert not failed51Proof['passed'] and failed51Proof['cleanupPassed'] and 'JSONDecodeError' in failed51Proof['error'] and all(row['exitCode']==0 for row in failed51Proof['ownedExitCodes']);inputs[str(failed51)]=sha(failed51);pre['retainedFailedPartialLogReport']=str(failed51)
 failed52=REPO/'implementation/warlock-client-provider-native-v52/qa/native-1791266452818753324/report.json';failed52Proof=json.loads(failed52.read_text());assert not failed52Proof['passed'] and failed52Proof['cleanupPassed'] and any(row['name']=='config-shadow-power-oneTypedNativeCropCapture' and not row['passed'] for row in failed52Proof['checks']) and all(row['exitCode']==0 for row in failed52Proof['ownedExitCodes']);inputs[str(failed52)]=sha(failed52);pre['retainedFailedConfigBoundsReport']=str(failed52)
 failed53=REPO/'implementation/warlock-client-provider-native-v53/qa/native-1791266958319056482/report.json';failed53Proof=json.loads(failed53.read_text());assert not failed53Proof['passed'] and failed53Proof['cleanupPassed'] and failed53Proof['renderConfigurationEvidence']['bytesChanged'] and not failed53Proof['renderConfigurationEvidence']['styleEpochChanged'] and all(row['exitCode']==0 for row in failed53Proof['ownedExitCodes']);inputs[str(failed53)]=sha(failed53);pre['retainedNativeConfigCounterexample']=str(failed53)
 failed54=REPO/'implementation/warlock-client-provider-native-v54/qa/native-1791267146852469629/report.json';failed54Proof=json.loads(failed54.read_text());assert not failed54Proof['passed'] and failed54Proof['cleanupPassed'] and failed54Proof['renderConfigurationEvidence']['bytesChanged'] and not failed54Proof['renderConfigurationEvidence']['styleEpochChanged'] and all(row['exitCode']==0 for row in failed54Proof['ownedExitCodes']) and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in failed54Proof['checks']) and any(row['name']=='configStyleChangedNativePixelsRequireNewStyleEpoch' and not row['passed'] for row in failed54Proof['checks']);inputs[str(failed54)]=sha(failed54);pre['retainedFinalNativeConfigurationCounterexample']=str(failed54)
 configRoot=REPO/'implementation/warlock-family-style-revisions-v11';assert sha(owner/'native/style_revision.hpp')==sha(configRoot/'native/style_revision.hpp')
 for pointerName in ['model-report.json','test-report.json']:
  pointerPath=configRoot/'qa'/pointerName;pointer=json.loads(pointerPath.read_text());proofPath=pathlib.Path(pointer['path']);assert sha(proofPath)==pointer['sha256'];proof=json.loads(proofPath.read_text());assert proof['passed']
  if pointerName=='model-report.json':assert len(proof['selectedNames'])==41 and proof['states']==160
  else:assert proof['evidence']['checks']==425
  for p,h in proof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
  for rel,h in proof['artifacts'].items():assert sha(proofPath.parent/rel)==h,rel;inputs[str(proofPath.parent/rel)]=h
  inputs[str(pointerPath)]=sha(pointerPath);inputs[str(proofPath)]=sha(proofPath);pre['configuration'+pointerName]=str(proofPath)
 retained55=REPO/'implementation/warlock-client-provider-native-v55/qa/native-1791267298767196849/report.json';retained55Proof=json.loads(retained55.read_text());assert retained55Proof['passed'] and retained55Proof['cleanupPassed'] and len(retained55Proof['checks'])==1853 and len(retained55Proof['ownedExitCodes'])==172 and all(row['exitCode']==0 for row in retained55Proof['ownedExitCodes']);inputs[str(retained55)]=sha(retained55);pre['retainedNativeConfigurationFreshnessReport']=str(retained55)
 failed56=REPO/'implementation/warlock-client-provider-native-v56/qa/native-1791267724171862557/report.json';failed56Proof=json.loads(failed56.read_text());assert not failed56Proof['passed'] and failed56Proof['cleanupPassed'] and 'familyConfigurationHistoricalEvidence' in failed56Proof and any(row['name']=='allOriginal1739OrderedAssertionsRetained' and not row['passed'] for row in failed56Proof['checks']) and all(row['exitCode']==0 for row in failed56Proof['ownedExitCodes']);inputs[str(failed56)]=sha(failed56);pre['retainedFailedConfigGUIFixtureReport']=str(failed56)
 retained57=REPO/'implementation/warlock-client-provider-native-v57/qa/native-1791267929432150447/report.json';retained57Proof=json.loads(retained57.read_text());assert retained57Proof['passed'] and retained57Proof['cleanupPassed'] and len(retained57Proof['checks'])==1880 and len(retained57Proof['ownedExitCodes'])==176 and all(row['exitCode']==0 for row in retained57Proof['ownedExitCodes']);inputs[str(retained57)]=sha(retained57);pre['retainedNativeLiveSourceHistoricalReport']=str(retained57)
 failed58=REPO/'implementation/warlock-client-provider-native-v58/qa/native-1791268407705509382/report.json';failed58Proof=json.loads(failed58.read_text());assert not failed58Proof['passed'] and failed58Proof['cleanupPassed'] and all(row['exitCode']==0 for row in failed58Proof['ownedExitCodes']) and any(row['name']=='config-glow-power-oneTypedNativeCropCapture' and not row['passed'] and row['reply']['reason']=='preview-probe-context-stale' for row in failed58Proof['checks']);inputs[str(failed58)]=sha(failed58);pre['retainedFailedGlowApplicationReport']=str(failed58)
 failed59=REPO/'implementation/warlock-client-provider-native-v59/qa/native-1791268662250358453/report.json';failed59Proof=json.loads(failed59.read_text());assert not failed59Proof['passed'] and failed59Proof['cleanupPassed'] and any(row['name']=='glowIndependentDecoderNormalExit' and not row['passed'] for row in failed59Proof['checks']);delta=pathlib.Path(failed59).parent/'private-evidence/pixels-glow-delta.log';pixels=json.loads(delta.read_text());assert pixels['changedFamilyPixels']==pixels['changedOutputPixels']==8696 and pixels['mismatchedBefore']==pixels['mismatchedAfter']==0 and pixels['changedCenterPixels']==12;inputs[str(failed59)]=sha(failed59);inputs[str(delta)]=sha(delta);pre['retainedFailedGlowContourOracleReport']=str(failed59)
 retained60=REPO/'implementation/warlock-client-provider-native-v60/qa/native-1791268932752885842/report.json';retained60Proof=json.loads(retained60.read_text());assert retained60Proof['passed'] and retained60Proof['cleanupPassed'] and all(row['exitCode']==0 for row in retained60Proof['ownedExitCodes']) and retained60Proof['glowConfigurationEvidence']['pixels']['passed'];inputs[str(retained60)]=sha(retained60);pre['retainedNativeGlowFidelityReport']=str(retained60)
 failed61=REPO/'implementation/warlock-client-provider-native-v61/qa/native-1791269093940842620/report.json';failed61Proof=json.loads(failed61.read_text());assert not failed61Proof['passed'] and failed61Proof['cleanupPassed'] and all(row['exitCode']==0 for row in failed61Proof['ownedExitCodes']) and any(row['name']=='config-opacity-halfIndependentNativeCompositedRoot' and not row['passed'] for row in failed61Proof['checks']) and 'opacityConfigurationEvidence' not in failed61Proof;inputs[str(failed61)]=sha(failed61);pre['retainedFailedOpacityFixtureBackgroundReport']=str(failed61)
 failed62=REPO/'implementation/warlock-client-provider-native-v62/qa/native-1791269530323836731/report.json';failed62Proof=json.loads(failed62.read_text());assert not failed62Proof['passed'] and failed62Proof['cleanupPassed'] and all(row['exitCode']==0 for row in failed62Proof['ownedExitCodes']) and len(failed62Proof['ownedExitCodes'])==193 and failed62Proof['opacityConfigurationEvidence']['bytesChanged'] and not failed62Proof['opacityConfigurationEvidence']['styleEpochChanged'] and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in failed62Proof['checks']) and any(row['name']=='opacityChangedNativePixelsRequireNewStyleEpoch' and not row['passed'] for row in failed62Proof['checks']);inputs[str(failed62)]=sha(failed62);pre['retainedNativeOpaqueRuleCounterexample']=str(failed62)
 retained63=REPO/'implementation/warlock-client-provider-native-v63/qa/native-1791269735621565040/report.json';retained63Proof=json.loads(retained63.read_text());assert retained63Proof['passed'] and retained63Proof['cleanupPassed'] and len(retained63Proof['checks'])==2057 and len(retained63Proof['ownedExitCodes'])==201 and all(row['exitCode']==0 for row in retained63Proof['ownedExitCodes']);inputs[str(retained63)]=sha(retained63);pre['retainedNativeOpaqueAndSamplingFactReport']=str(retained63)
 failed65=REPO/'implementation/warlock-client-provider-native-v65/qa/native-1791271084435994222/report.json';failed65Proof=json.loads(failed65.read_text());assert not failed65Proof['passed'] and failed65Proof['cleanupPassed'] and len(failed65Proof['checks'])==2086 and len(failed65Proof['ownedExitCodes'])==202 and all(row['exitCode']==0 for row in failed65Proof['ownedExitCodes']) and not failed65Proof['backgroundEffectEvidence']['creationEpochAdvanced'] and any(row['name']=='backgroundCreationBeforeCommitRequiresNewEpoch' and not row['passed'] for row in failed65Proof['checks']) and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in failed65Proof['checks']);inputs[str(failed65)]=sha(failed65);pre['retainedNativeBackgroundInputCounterexample']=str(failed65)
 retained66=REPO/'implementation/warlock-client-provider-native-v66/qa/native-1791271302348322684/report.json';retained66Proof=json.loads(retained66.read_text());assert retained66Proof['passed'] and retained66Proof['cleanupPassed'] and len(retained66Proof['checks'])==2088 and len(retained66Proof['ownedExitCodes'])==202 and all(row['exitCode']==0 for row in retained66Proof['ownedExitCodes']);inputs[str(retained66)]=sha(retained66);pre['retainedNativeRootBackgroundFactReport']=str(retained66)
 failed67=REPO/'implementation/warlock-client-provider-native-v67/qa/native-1791273038897678392/report.json';failed67Proof=json.loads(failed67.read_text());assert not failed67Proof['passed'] and failed67Proof['cleanupPassed'] and len(failed67Proof['checks'])==2053 and len(failed67Proof['ownedExitCodes'])==198 and 'control-shape' in failed67Proof['error'] and [row['name'] for row in failed67Proof['ownedExitCodes'] if row['exitCode']]==['child'] and next(row for row in failed67Proof['ownedExitCodes'] if row['name']=='child')['exitCode']==1;inputs[str(failed67)]=sha(failed67);pre['retainedFailedNestedProtocolCommandLengthReport']=str(failed67)
 retained68=REPO/'implementation/warlock-client-provider-native-v68/qa/native-1791273599848012391/report.json';retained68Proof=json.loads(retained68.read_text());assert retained68Proof['passed'] and retained68Proof['cleanupPassed'] and len(retained68Proof['checks'])==2136 and len(retained68Proof['ownedExitCodes'])==202 and all(row['exitCode']==0 for row in retained68Proof['ownedExitCodes']);inputs[str(retained68)]=sha(retained68);pre['retainedNativeNestedBackgroundFacts']=str(retained68)
 failed69=REPO/'implementation/warlock-client-provider-native-v69/qa/native-1791274804392885567/report.json';failed69Proof=json.loads(failed69.read_text());assert not failed69Proof['passed'] and failed69Proof['cleanupPassed'] and len(failed69Proof['checks'])==2130 and len(failed69Proof['ownedExitCodes'])==205 and all(row['exitCode']==0 for row in failed69Proof['ownedExitCodes']) and failed69Proof['appliedShaderEvidence']['actualAppliedShaderFactsQualified'] and 'Original six-second fixture observation deadline' in failed69Proof['error'];inputs[str(failed69)]=sha(failed69);pre['retainedFailedShaderFixtureLayoutCleanup']=str(failed69)
 failed70=REPO/'implementation/warlock-client-provider-native-v70/qa/native-1791275066933375312/report.json';failed70Proof=json.loads(failed70.read_text());assert not failed70Proof['passed'] and failed70Proof['cleanupPassed'] and len(failed70Proof['checks'])==2158 and len(failed70Proof['ownedExitCodes'])==206 and all(row['exitCode']==0 for row in failed70Proof['ownedExitCodes']) and [row['name'] for row in failed70Proof['checks'] if not row['passed']]==['allOriginal1636OrderedAssertionsRetained'];inputs[str(failed70)]=sha(failed70);pre['retainedFailedShaderOriginalPollingIdentity']=str(failed70)
 failed71=REPO/'implementation/warlock-client-provider-native-v71/qa/native-1791275305628597524/report.json';failed71Proof=json.loads(failed71.read_text());assert not failed71Proof['passed'] and failed71Proof['cleanupPassed'] and len(failed71Proof['checks'])==2161 and len(failed71Proof['ownedExitCodes'])==206 and all(row['exitCode']==0 for row in failed71Proof['ownedExitCodes']) and [row['name'] for row in failed71Proof['checks'] if not row['passed']]==['allOriginal1636OrderedAssertionsRetained'];inputs[str(failed71)]=sha(failed71);pre['retainedFailedShaderOriginalDimObservationCount']=str(failed71)
 shader72Reports=list((REPO/'implementation/warlock-client-provider-native-v72').glob('qa/native-*/report.json'));assert len(shader72Reports)==1;shader72=shader72Reports[0];shader72Proof=json.loads(shader72.read_text());assert shader72Proof['passed'] and shader72Proof['cleanupPassed'] and all(row['exitCode']==0 for row in shader72Proof['ownedExitCodes']) and shader72Proof['appliedShaderEvidence']['actualAppliedShaderFactsQualified'] and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in shader72Proof['checks']);inputs[str(shader72)]=sha(shader72);pre['retainedNativeAppliedShaderFacts']=str(shader72)
 shader73=REPO/'implementation/warlock-client-provider-native-v73/qa/native-1791276008379195044/report.json';shader73Proof=json.loads(shader73.read_text());assert not shader73Proof['passed'] and shader73Proof['cleanupPassed'] and len(shader73Proof['checks'])==2197 and len(shader73Proof['ownedExitCodes'])==212 and all(row['exitCode']==0 for row in shader73Proof['ownedExitCodes']) and [row['name'] for row in shader73Proof['checks'] if not row['passed']]==['shaderActualNativeTintRequiresMatchingFamilyPixels'] and shader73Proof['shaderPixelSamples'][1]['familyPixels']['rootRGBA']==[255,0,0,255] and shader73Proof['shaderPixelSamples'][1]['nativePixels']['rootRGBA']==[204,0,0,255] and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in shader73Proof['checks']);inputs[str(shader73)]=sha(shader73);pre['retainedNativeOmittedScreenShaderCounterexample']=str(shader73)
 old50=REPO/'implementation/warlock-client-provider-native-v50/qa/native-1791265841870106110/report.json';old50Proof=json.loads(old50.read_text());assert old50Proof['passed'] and old50Proof['cleanupPassed'] and len(old50Proof['checks'])==1783 and all(row['exitCode']==0 for row in old50Proof['ownedExitCodes']);inputs[str(old50)]=sha(old50);pre['retainedNativeHistoricalFamilyReport']=str(old50)
 old45=REPO/'implementation/warlock-client-provider-native-v45/qa/native-1791264757369168051/report.json';old45Proof=json.loads(old45.read_text());assert old45Proof['passed'] and old45Proof['cleanupPassed'] and len(old45Proof['checks'])==1756 and all(row['exitCode']==0 for row in old45Proof['ownedExitCodes']);inputs[str(old45)]=sha(old45);pre['retainedNativeFamilyWebReport']=str(old45)
 old43=REPO/'implementation/warlock-client-provider-native-v43/qa/native-1791262717179444040/report.json';old43Proof=json.loads(old43.read_text());assert old43Proof['passed'] and old43Proof['cleanupPassed'] and len(old43Proof['checks'])==1739 and len(old43Proof['ownedExitCodes'])==159 and all(row['exitCode']==0 for row in old43Proof['ownedExitCodes']);inputs[str(old43)]=sha(old43);pre['retainedNativeStyleCropReport']=str(old43)
 provider=REPO/'implementation/warlock-preview-provider-v34';builds=list((provider/'qa').glob('build-*/report.json'));assert len(builds)==1;providerBuild=builds[0];providerProof=json.loads(providerBuild.read_text());assert providerProof['passed'] and all(row['exitCode']==0 for row in providerProof['commands'])
 for rel,h in providerProof['inputs'].items():assert sha(provider/rel)==h,rel;inputs[str(provider/rel)]=h
 for section in ['compilerDependencies','linkedLibraries','tools']:
  for path,row in providerProof[section].items():assert sha(path)==row['sha256'],path;inputs[path]=row['sha256']
 for rel,h in providerProof['artifacts'].items():assert sha(providerBuild.parent/rel)==h,rel;inputs[str(providerBuild.parent/rel)]=h
 binary=providerBuild.parent/'elm-host';assert sha(binary)==providerProof['binarySHA256'];inputs[str(binary)]=sha(binary);inputs[str(providerBuild)]=sha(providerBuild)
 pre['fullHostBinary']=str(binary);pre['fullHostAssets']=str(providerBuild.parent/'inputs/assets');pre['fullHostBackend']=str(providerBuild.parent/'inputs/adapter/daemon.py');pre['familyProviderBuild']=str(providerBuild)
 fixtureReport=REPO/'implementation/warlock-family-modal-fixture-v5/qa/client-build-1791273460581769282/report.json';fixtureProof=json.loads(fixtureReport.read_text());assert fixtureProof['passed'] and all(row['exitCode']==0 for row in fixtureProof['commands'])
 for key in ['inputs','dependencies','linkedLibraries','tools']:
  for p,h in fixtureProof[key].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in fixtureProof['artifacts'].items():assert sha(fixtureReport.parent/rel)==h,rel;inputs[str(fixtureReport.parent/rel)]=h
 assert sha(fixtureProof['client'])==fixtureProof['clientSHA256'];pre['fixtureClient']=fixtureProof['client'];inputs[str(fixtureReport)]=sha(fixtureReport);pre['backgroundEffectFixtureBuild']=str(fixtureReport)
 inputs['/usr/bin/grim']=sha('/usr/bin/grim')
 for line in subprocess.check_output(['ldd','/usr/bin/grim'],text=True).splitlines():
  assert 'not found' not in line
  for word in line.split():
   if word.startswith('/') and pathlib.Path(word).is_file():path=str(pathlib.Path(word).resolve());inputs[path]=sha(path)
 flags=shlex.split(subprocess.check_output(['pkg-config','--cflags','--libs','libpng'],text=True))
 for name,key in [('modal-pixels','modalPixelOracle'),('family-pixels','familyPixelOracle'),('crop-pixels','cropPixelOracle'),('family-web-pixels','familyWebPixelOracle'),('glow-pixels','glowPixelOracle'),('opacity-pixels','opacityPixelOracle'),('shader-pixels','shaderPixelOracle'),('coordinate-pixels','coordinatePixelOracle'),('composited-crop-pixels','compositedCropPixelOracle'),('shader-half-body-pixels','shaderHalfBodyPixelOracle'),('blur-body-deltas','blurBodyDeltaOracle')]:
  argv=['g++','-std=c++20','-O2','-Wall','-Wextra','-Werror',str(ROOT/(name+'.cpp')),*flags,'-o',str(OUT/name)];p=subprocess.run(argv,capture_output=True,text=True,timeout=180);(OUT/(name+'.stdout')).write_text(p.stdout);(OUT/(name+'.stderr')).write_text(p.stderr);assert p.returncode==0,p.stderr;inputs[str(OUT/name)]=sha(OUT/name);pre[key]=str(OUT/name)
 retained75=REPO/'implementation/warlock-client-provider-native-v75/qa/native-1791277277997740781/report.json';proof75=json.loads(retained75.read_text());assert proof75['passed'] and proof75['cleanupPassed'] and proof75['shaderWholeRootPixels']['passed'] and len(proof75['checks'])==2199 and len(proof75['ownedExitCodes'])==213 and all(row['exitCode']==0 for row in proof75['ownedExitCodes']);inputs[str(retained75)]=sha(retained75);pre['retainedNativeShaderOpaqueRootPixels']=str(retained75)
 retained76=REPO/'implementation/warlock-client-provider-native-v76/qa/native-1791277798549957384/report.json';proof76=json.loads(retained76.read_text());assert not proof76['passed'] and proof76['cleanupPassed'] and len(proof76['checks'])==2216 and len(proof76['ownedExitCodes'])==216 and all(row['exitCode']==0 for row in proof76['ownedExitCodes']) and [row['name'] for row in proof76['checks'] if not row['passed']]==['shaderActualGlobalCoordinatesMatchIndependentNativeOutput'] and proof76['shaderCoordinatePixels']['familyPixels']['rootRGBA']==[21,28,0,255] and proof76['shaderCoordinatePixels']['nativePixels']['rootRGBA']==[32,43,0,255] and proof76['shaderWholeRootPixels']['passed'];inputs[str(retained76)]=sha(retained76);pre['retainedNativeCropLocalCoordinateCounterexample']=str(retained76)
 retainedShaderOracle=[]
 for version,stamp,expected in [(74,'1791276866539509774',True),(73,'1791276008379195044',False)]:
  nativeReport=REPO/('implementation/warlock-client-provider-native-v'+str(version))/('qa/native-'+stamp+'/report.json');proof=json.loads(nativeReport.read_text());images=nativeReport.parent/'private-evidence';sample=proof['shaderPixelSamples'][0];crop=sample['source']['crop'];geometry=sample['source']['members'][0]['geometry']
  paths=[images/name for name in ['shader-identity-pixels.png','shader-tint-pixels.png','shader-identity-pixels-native-output.png','shader-tint-pixels-native-output.png']]
  for path in paths:assert sha(path)==proof['artifacts'][str(path.relative_to(nativeReport.parent))];inputs[str(path)]=sha(path)
  inputs[str(nativeReport)]=sha(nativeReport)
  argv=[pre['shaderPixelOracle'],*[str(path) for path in paths],crop['pixelX'],crop['pixelY'],*[str(int(v)) for v in geometry[:4]]];p=subprocess.run(argv,capture_output=True,text=True,timeout=5);(OUT/('retained-shader-'+str(version)+'.stdout')).write_text(p.stdout);(OUT/('retained-shader-'+str(version)+'.stderr')).write_text(p.stderr);pixels=json.loads(p.stdout)
  assert p.returncode==(0 if expected else 2) and pixels['passed']==expected and pixels['comparedRootPixels']==76800 and pixels['changedOutputPixels']==73728 and pixels['mismatchedBefore']==0
  assert (pixels['mismatchedAfter'],pixels['changedFamilyPixels'])==((0,73728) if expected else (73728,0))
  retainedShaderOracle.append({'version':version,'argv':argv,'exitCode':p.returncode,'pixels':pixels})
 r['retainedShaderWholeRootOracle']=retainedShaderOracle
 coordinateReports=[]
 for version,expected in [(76,False),(77,True)]:
  reports=list((REPO/('implementation/warlock-client-provider-native-v'+str(version))).glob('qa/native-*/report.json'));assert len(reports)==1;report=reports[0];proof=json.loads(report.read_text());assert proof['passed']==expected and proof['cleanupPassed'] and all(row['exitCode']==0 for row in proof['ownedExitCodes']);sample=proof['shaderCoordinatePixels'];crop=sample['source']['crop'];geometry=sample['source']['members'][0]['geometry'];paths=[report.parent/'private-evidence'/name for name in ['shader-coordinate-pixels.png','shader-coordinate-pixels-native-output.png']]
  for path in paths:assert sha(path)==proof['artifacts'][str(path.relative_to(report.parent))];inputs[str(path)]=sha(path)
  inputs[str(report)]=sha(report);argv=[pre['coordinatePixelOracle'],*[str(p) for p in paths],crop['pixelX'],crop['pixelY'],*[str(int(v)) for v in geometry[:4]]];p=subprocess.run(argv,capture_output=True,text=True,timeout=5);(OUT/('retained-coordinate-'+str(version)+'.stdout')).write_text(p.stdout);(OUT/('retained-coordinate-'+str(version)+'.stderr')).write_text(p.stderr);pixels=json.loads(p.stdout);assert p.returncode==(0 if expected else 2) and pixels['passed']==expected and pixels['comparedRootPixels']==76800 and (pixels['mismatchedRootPixels']==0 if expected else pixels['mismatchedRootPixels']>0);coordinateReports.append({'version':version,'argv':argv,'exitCode':p.returncode,'pixels':pixels})
 r['retainedWholeRootCoordinates']=coordinateReports
 retained79=REPO/'implementation/warlock-client-provider-native-v79/qa/native-1791279763519516140/report.json';proof79=json.loads(retained79.read_text());assert not proof79['passed'] and proof79['cleanupPassed'] and len(proof79['checks'])==2189 and len(proof79['ownedExitCodes'])==219 and [row['name'] for row in proof79['checks'] if not row['passed']]==['allOwnedProcessesNormalExit'] and sum(row['exitCode']==2 for row in proof79['ownedExitCodes'])==2 and all(row['exitCode'] in [0,2] for row in proof79['ownedExitCodes']) and all(sample['pixels']['mismatchedCompositedPixels']==6912 for sample in proof79['shaderCompositedCropPixels']);inputs[str(retained79)]=sha(retained79);pre['retainedWholeCropFixtureBackgroundFailure']=str(retained79)
 compositedReport=REPO/'implementation/warlock-client-provider-native-v78/qa/native-1791278994447344491/report.json';compositedProof=json.loads(compositedReport.read_text());assert compositedProof['passed'] and compositedProof['cleanupPassed'] and compositedProof['shaderWholeCoordinatePixels']['passed'];compositedSamples=[]
 for sample in compositedProof['shaderPixelSamples']:
  name=sample['name'];crop=sample['source']['crop'];paths=[compositedReport.parent/'private-evidence'/(name+suffix) for suffix in ['.png','-native-output.png']]
  for path in paths:assert sha(path)==compositedProof['artifacts'][str(path.relative_to(compositedReport.parent))];inputs[str(path)]=sha(path)
  argv=[pre['compositedCropPixelOracle'],*[str(path) for path in paths],crop['pixelX'],crop['pixelY']];p=subprocess.run(argv,capture_output=True,text=True,timeout=5);(OUT/(name+'-retained-composite.stdout')).write_text(p.stdout);(OUT/(name+'-retained-composite.stderr')).write_text(p.stderr);assert p.returncode==0,p.stderr;compositedSamples.append({'name':name,'argv':argv,'exitCode':p.returncode,'pixels':json.loads(p.stdout)})
 inputs[str(compositedReport)]=sha(compositedReport);r['retainedCompositedCropProbe']=compositedSamples
 retained80=REPO/'implementation/warlock-client-provider-native-v80/qa/native-1791280152652471078/report.json';proof80=json.loads(retained80.read_text());assert proof80['passed'] and proof80['cleanupPassed'] and len(proof80['checks'])==2224 and len(proof80['ownedExitCodes'])==221 and all(row['exitCode']==0 for row in proof80['ownedExitCodes']) and proof80['nativeShaderWholeCropOverBlackQualified'];sample=next(row for row in proof80['shaderPixelSamples'] if row['name']=='shader-tint-pixels');crop=sample['source']['crop'];geometry=sample['source']['members'][0]['geometry'];paths=[retained80.parent/'private-evidence'/name for name in ['shader-tint-pixels.png','shader-tint-pixels-native-output.png']]
 for path in paths:assert sha(path)==proof80['artifacts'][str(path.relative_to(retained80.parent))];inputs[str(path)]=sha(path)
 argv=[pre['shaderHalfBodyPixelOracle'],*[str(path) for path in paths],crop['pixelX'],crop['pixelY'],*[str(int(v)) for v in geometry[:4]]];p=subprocess.run(argv,capture_output=True,text=True,timeout=5);(OUT/'opaque-is-not-half-alpha.stdout').write_text(p.stdout);(OUT/'opaque-is-not-half-alpha.stderr').write_text(p.stderr);pixels=json.loads(p.stdout);assert p.returncode==0 and not pixels['passed'] and pixels['comparedRootPixels']==76800 and pixels['mismatchedCompositedPixels']==0 and pixels['unexpectedBodyPixels']==76800;r['retainedOpaqueDoesNotQualifyHalfAlpha']=pixels;inputs[str(retained80)]=sha(retained80);pre['retainedNativeWholeCropAlphaComposition']=str(retained80)
 retained81=REPO/'implementation/warlock-client-provider-native-v81/qa/native-1791281075067620039/report.json';proof81=json.loads(retained81.read_text());assert not proof81['passed'] and proof81['cleanupPassed'] and all(row['exitCode']==0 for row in proof81['ownedExitCodes']) and [row['name'] for row in proof81['checks'] if not row['passed']]==['shaderHalfBodyMatchesDeclaredAlphaAndIndependentNativeOutput'] and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in proof81['checks']);sample=proof81['shaderHalfBodyPixels'];crop=sample['source']['crop'];geometry=next(row['geometry'] for row in sample['source']['members'] if row['incarnation']==sample['source']['scope']['context']['incarnation']);paths=[retained81.parent/'private-evidence'/name for name in ['shader-half-body-pixels.png','shader-half-body-pixels-native-output.png']]
 for path in paths:assert sha(path)==proof81['artifacts'][str(path.relative_to(retained81.parent))];inputs[str(path)]=sha(path)
 argv=[pre['shaderHalfBodyPixelOracle'],*[str(path) for path in paths],crop['pixelX'],crop['pixelY'],*[str(int(v)) for v in geometry[:4]]];p=subprocess.run(argv,capture_output=True,text=True,timeout=5);(OUT/'retained-81-half-alpha.stdout').write_text(p.stdout);(OUT/'retained-81-half-alpha.stderr').write_text(p.stderr);pixels=json.loads(p.stdout);assert p.returncode==0 and pixels==proof81['shaderHalfBodyComparison'] and pixels['mismatchedCompositedPixels']==pixels['unexpectedBodyPixels']==253 and not pixels['passed'];r['retainedHalfAlphaCursorCounterexample']=pixels;inputs[str(retained81)]=sha(retained81);pre['retainedHalfAlphaCursorCounterexample']=str(retained81)
 importFailure=REPO/'implementation/warlock-client-provider-native-v82/qa/native-import-failure.json';failure=json.loads(importFailure.read_text());assert not failure['nativeLaunched'] and failure['protectedLauncherExitCode']==1;inputs[str(importFailure)]=sha(importFailure)
 for helper in ['isolation.py','session_bus.py','system_isolation.py']:assert sha(ROOT/'qa'/helper)==sha(REPO/'implementation/warlock-client-provider-native-v81/qa'/helper)
 retained83=REPO/'implementation/warlock-client-provider-native-v83/qa/native-1791281764693182620/report.json';proof83=json.loads(retained83.read_text());assert proof83['passed'] and proof83['cleanupPassed'] and proof83['nativeShaderHalfBodyOverBlackNoBlurQualified'] and len(proof83['checks'])==2257 and len(proof83['ownedExitCodes'])==227;inputs[str(retained83)]=sha(retained83);pre['retainedNativeHalfAlphaTintNoBlur']=str(retained83)
 for own in [*ROOT.glob('*.py'),*ROOT.glob('*.cpp'),ROOT/'SPEC.md',*ROOT.glob('qa/*.py')]:inputs[str(own.resolve())]=sha(own)
 pre['pair']['core']={'path':pair['binary'],'sha256':pair['sha256']};pre['pair']['plugin']=pair['plugin'];pre['inputs']=inputs
 assert all(sha(p)==h for p,h in inputs.items());(ROOT/'qa/preflight.json').write_text(json.dumps(pre,indent=2)+'\n');r.update(passed=True,inputs=inputs,pair=pre['pair'])
except Exception as e:r['error']=repr(e);r['traceback']=traceback.format_exc()
(OUT/'report.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'passed':r['passed'],'report':str(OUT/'report.json'),'error':r.get('error')}));raise SystemExit(not r['passed'])
