import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=9299
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report125.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v125',['PROGRESS PUBLIC92 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI125/Native135 bounded actual controlled GTK/single native Elm policy/one-time pure WebKit renderer/current DOM receipt/original journal and independent confirmation/strict normal teardown16checks8exits. Full119/page asset closure pass; original deadline6/core16/plugin19/AQ155 unchanged. Failed122/132,123/133,124/134 held. Physical curtain remains closed; actual pixels/physical frame/reveal/pressure/workload/RSS/reload/uncertain recovery/full S09 preview13 and release gates remain open. Next actual captured-image pure renderer/WebKit URI and physical frame qualification. Legacy Native1312518/278 remains separate. Installed/drafts/foreign preserved.'],'progress',['docs/warlock-preview/v93/component-report125.json','implementation/warlock-preview-provider-v125/component-manifest.json','implementation/warlock-client-provider-native-v135/component-manifest.json','docs/warlock-repository/v92/publication/delivery.json']);print(e)
