import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>1000
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v86/report.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v124',['PROGRESS PUBLIC exactowner publication61 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. Exact core16/plugin18/GUI85/native124 passed2463/277normal/orderedcleanup, all2455 prior122 fixed controls retained. Full95/original12/C96/decoder13-25-439states-3mutants. Failed123 and actual unchanged strict C lock guard race preserved; stable-inode parent publisher corrected. Next mutableGUI86 aggregate native retirement, Elm settlement and control barrier, actual >256window turnover then ordinary capture and all original release gates. Main desktop/drafts/five foreign tracked changes preserved.'],'progress',['docs/warlock-preview/v86/report.json','implementation/warlock-preview-provider-v85/component-manifest.json','implementation/warlock-client-provider-native-v124/component-manifest.json','docs/warlock-repository/v61/publication/delivery.json']);print(e)
