#include "capture-intent-source-fixture.hpp"
using namespace preview;
static std::string take(char*& text){require(text,"Actual cohort C output");std::string result(text);g_free(text);text=nullptr;return result;}
static JsonObject* row(Json& wrapper){auto rows=json_object_get_array_member(wrapper.object(),"rows");require(rows && json_array_get_length(rows)==1,"One actual cohort completion row");return json_array_get_object_element(rows,0);}
int main(){try{
 Server server;GError* error=nullptr;auto bootstrap=warlock_preview_bootstrap_open(server.config().c_str(),&error);
 check(bootstrap && !error,"Cohort original authenticated Bootstrap");auto transport=warlock_preview_bootstrap_native_transport(bootstrap,&error);auto& native=*static_cast<Native*>(transport);const auto binding=native.binding();auto popup=reinterpret_cast<gpointer>(uintptr_t(77));
 char* text=nullptr;char* grantText=nullptr;void* raw=nullptr;
 auto owner=warlock_imported_clients_open_controlled(transport,popup,21,1,1,&text,&grantText,&raw,&error);check(owner && text && grantText && raw && !error,"Cohort actual controlled owner");take(text);Json grant(take(grantText));const auto epoch=grant.counter("receiverEpoch");auto& endpoint=*static_cast<uri::Endpoint*>(raw);
 check(warlock_preview_bootstrap_attach_delivery(bootstrap,raw,popup,&error) && !error,"Cohort original receiver attachment");auto delivery=warlock_preview_bootstrap_delivery(bootstrap,popup,&error);check(delivery && !error,"Cohort actual borrowed receipt capability");
 for(uint64_t subject:{23,24}){WarlockImportedAdmission admission=WARLOCK_IMPORTED_INVALID;check(warlock_imported_clients_enroll(owner,popup,subject,1,1,&admission,&text,&error) && !error,"Cohort actual extra actor admission");take(text);check(admission==(subject==23?WARLOCK_IMPORTED_STARTED:WARLOCK_IMPORTED_CAPACITY),"Original physical capacity retains third unissued actor");check(warlock_preview_bootstrap_extend_delivery(bootstrap,popup,&error) && !error,"Cohort exact original receipt membership extension");}
 struct Ticket{uint64_t ordinal;std::string wire;};
 auto propose=[&](uint64_t subject,const std::string& command){auto identity="family:"+std::to_string(subject);check(warlock_imported_clients_propose_control_at_epoch(owner,delivery,popup,epoch,identity.c_str(),command.c_str(),&text,&error) && !error,"Cohort native purpose proposal");Json proposal(take(text));return Ticket{proposal.counter("controlOrdinal"),Json::text(proposal.object(),"wire")};};
 auto dispatch=[&](const Ticket& ticket){char* receipt=nullptr;check(warlock_imported_clients_dispatch_control(owner,delivery,popup,ticket.wire.c_str(),&text,&receipt,&error) && !error && text && receipt,"Cohort actual native dispatch");take(text);take(receipt);};
 auto confirm=[&](uint64_t ordinal){auto wire=Wire().integer("previewProtocol",3).text("kind","preview-control-confirmed").begin("binding").binding(binding).end().counter("receiverEpoch",epoch).counter("controlOrdinal",ordinal).finish();check(warlock_imported_clients_confirm_control(owner,popup,wire.c_str(),&text,&error) && !error,"Cohort original independent confirmation");take(text);};
 auto control=[&](uint64_t subject,const std::string& command){auto ticket=propose(subject,command);dispatch(ticket);confirm(ticket.ordinal);};
 auto pending=[&](bool scoped){check((scoped?warlock_imported_clients_detachment_pending(owner,delivery,popup,&text,&error):warlock_imported_clients_retirement_pending(owner,delivery,popup,&text,&error)) && !error,"Cohort exact typed pending query");return take(text);};
 auto detachedReady=[&](uint64_t subject){auto identity="family:"+std::to_string(subject);check(warlock_imported_clients_detachment_inventory(owner,popup,identity.c_str(),&text,&error) && !error,"Cohort scoped native inventory");Json seed(take(text));if(subject==24)check(std::string_view(Json::text(seed.object(),"requestFloor"))=="0","Unissued cold actor retains original zero request floor");control(subject,Wire().text("kind","detach-ready").begin("binding").binding(binding).end().counter("receiverEpoch",epoch).counter("subject",subject).text("entry",Json::text(seed.object(),"entry")).text("entryIssuedThrough",Json::text(seed.object(),"entryIssuedThrough")).text("requestFloor",Json::text(seed.object(),"requestFloor")).finish());};
 auto ackActor=[&](uint64_t subject,bool scoped){Json completion("{\"rows\":"+pending(scoped)+"}");auto fact=row(completion);auto wire=Wire().text("kind",scoped?"detach-delivery-ack":"retire-delivery-ack").begin("binding").binding(binding).end();if(scoped)wire.counter("receiverEpoch",epoch);control(subject,wire.text("deliveryOrdinal",Json::text(fact,"deliveryOrdinal")).finish());};
 control(21,Wire().text("kind","reconcile").begin("binding").binding(binding).end().finish());
 detachedReady(24);check(endpoint.native([](auto& broker){return broker.actorCount()==2 && broker.recordCount()==2;}),"Cold detachment preserves both neighboring actual jobs");ackActor(24,true);
 detachedReady(23);
 std::ofstream(server.root/"retired-through")<<21;
 check(warlock_imported_clients_retirement_observe(owner,popup,"family:21",&text,&error) && !error,"Cohort original permanent incarnation observation");Json observations("{\"rows\":"+take(text)+"}");auto observation=row(observations);
 control(21,Wire().text("kind","retire-ready").begin("binding").binding(binding).end().counter("subject",21).text("observationRequest",Json::text(observation,"request")).text("observationSequence",Json::text(observation,"sequence")).finish());
 auto poll=[&]{check(warlock_imported_clients_retirement_poll(owner,delivery,popup,&text,&error) && !error,"Cohort mixed bounded native poll");return take(text);};
 poll();check(pending(true)=="[]" && pending(false)=="[]" && endpoint.native([](auto& broker){auto records=broker.inspect();return broker.actorCount()==2 && records.size()==2 && records[0].terminal && records[1].terminal;}),"Neither scoped nor permanent readiness bypasses final neighboring job ACK");
 for(const auto& record:endpoint.native([](auto& broker){return broker.inspect();}))control(record.job.context.incarnation.value,Wire().text("kind","acknowledge").begin("job").job(record.job).end().counter("sequence",record.proofs.back().sequence.value).finish());
 poll();check(endpoint.native([](auto& broker){return broker.actorCount()==1 && broker.recordCount()==0;}),"Mixed poll examines at most one ready candidate across both domains");
 poll();check(endpoint.native([](auto& broker){return broker.actorCount()==0 && broker.recordCount()==0 && broker.charge()==0;}),"Mixed readiness fairness completes both domains within two polls");
 check(pending(true)!="[]" && pending(false)!="[]" && !warlock_imported_clients_empty(owner),"Both distinct typed completions retain their final processing obligations");ackActor(23,true);check(pending(false)!="[]" && !warlock_imported_clients_empty(owner),"Scoped final processing cannot consume permanent completion");ackActor(21,false);
 RetirementCursor cursor;check(observeIncarnationRetirement(native,{23},cursor).state==IncarnationState::Active,"Scoped cohort neighbor remains native Active");check(observeIncarnationRetirement(native,{24},cursor).state==IncarnationState::Active,"Cold scoped actor remains native Active");
 check(warlock_imported_clients_empty(owner) && warlock_imported_clients_close_bootstrap(owner,bootstrap,&error) && !error,"Mixed original physical and distinct final processing close");check(native.binding()==binding,"Mixed closure preserves original Native grant");warlock_preview_bootstrap_free(bootstrap);server.finish();
 std::cout<<"{\"passed\":true,\"checks\":"<<passed<<",\"actualColdZeroFloor\":true,\"actualMixedDomains\":true,\"oneCandidatePerPoll\":true,\"normalOwnedExit\":true,\"nativeAcceptance\":false}\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
