"""Prepare scoped publication scripts from the prior verified workflow."""
import pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');old=repo/'docs/warlock-repository/v52/publication';out=repo/'docs/warlock-repository/v53/publication';assert not out.exists();out.mkdir(parents=True)
def replace(text,old,new):assert text.count(old)==1,(old,text.count(old));return text.replace(old,new,1)
text=(old/'commit_owned.py').read_text();text=replace(text,'07acaedc54c61fcab0bcdb61223fe796679e213b','0b9b4be5d26bd13e06b0c6af091ab7340b97eeef');text=replace(text,'docs/warlock-preview/v70/report.json','docs/warlock-preview/v71/report.json');text=replace(text,"['docs/warlock-preview/v69','docs/warlock-preview/v70','docs/warlock-repository/v52/publication']","['docs/warlock-preview/v71','docs/warlock-repository/v53/publication']");text=replace(text,'Preserve native preview readers while receiver membership grows','Extend native preview receipt subjects without replacing original ownership');(out/'commit_owned.py').write_text(text)
text=(old/'publish.py').read_text();text=replace(text,'654f2e32fc16a4aa1d3f52cf137c72271f56713e','e88c72b8c17e960daebb5c70f806e1314113aa1d');text=replace(text,'07acaedc54c61fcab0bcdb61223fe796679e213b','0b9b4be5d26bd13e06b0c6af091ab7340b97eeef')
begin=text.index('allowed=(');end=text.index('\nassert all(',begin);text=text[:begin]+"allowed=('docs/warlock-preview/v71/', 'docs/warlock-repository/v52/publication/', 'docs/warlock-repository/v53/publication/', 'implementation/warlock-preview-provider-v57/', 'implementation/warlock-preview-provider-v58/', 'implementation/warlock-preview-provider-v59/', 'implementation/warlock-preview-provider-v60/', 'implementation/warlock-client-provider-native-v102/', 'implementation/warlock-client-provider-native-v103/', 'implementation/warlock-client-provider-native-v104/', 'implementation/warlock-client-provider-native-v105/', 'openspec/changes/warlock-preview-receipt-membership/')"+text[end:]
text=replace(text,'docs/warlock-preview/v70/report.json','docs/warlock-preview/v71/report.json');begin=text.index(' message=');end=text.index('\n published=',begin)
message='Extend native preview receipt subjects without replacing original ownership\n\nReceiptDelivery explicitly admits actual own native view membership under one atomic receiver/broker critical section. Preserve old receiver epoch, immutable entry/incarnation correlations and the original broker terminal journal; refuse partial foreign admission or reused receivers. Actual C extension checks own Native process, and new subjects cannot deliver/ACK from pixel membership alone. Full optimized GUI60 build90/GIO49 and original receiver40/catalog60/decoder26/metadata82/GIO74 pass. Six selected Quint/150 samples/16 actual GIO+journal traces compare388 states and detect2 unsafe mutants, retaining original catalog8/metadata8/demand10. Exact owning native105 retains all original1783 and stable priornative101 checks with clean normal exits. Three actual native windows share one bounded two-item physical pool: held old stream survives growth, third capacity has no fake job/receipt, new original receipts require explicit C admission and all actual imports/backend/mappings/FDs drain before exact final ACK. Dedicated third blue-child stimulus fixes preserved native104 pixel failure without changing original oracles/deadlines. Failed model parser/mutation compiler and CPU-only descriptor/review attempts retained. Three additive EARS/OpenSpec contracts preserve242/417/originalS09 thirteen; ordinary eligible product capture, full S09/hardware/coherent release remain open. Main desktop and concurrent workers preserved.\n'
text=text[:begin]+' message='+repr(message)+text[end:];(out/'publish.py').write_text(text)
text=(old/'commit_receipt.py').read_text();text=text.replace('implementation/warlock-preview-provider-v56','implementation/warlock-client-provider-native-v105');text=replace(text,'Record public receiver growth component qualification','Record public native receiver and receipt growth qualification');(out/'commit_receipt.py').write_text(text)
print(out)
