import hashlib,json,re,shutil,subprocess,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'qa'/('model-'+str(time.time_ns()));OUT.mkdir();shutil.copy2(ROOT/'spec/accepted.qnt',OUT/'accepted.qnt');rows=[]
def run(name,args,expected=0):
 p=subprocess.run(['quint',*args],cwd=OUT,capture_output=True,text=True,timeout=90);(OUT/(name+'.log')).write_text(p.stdout+p.stderr);rows.append({'name':name,'command':['quint',*args],'exitCode':p.returncode,'expected':expected,'passed':p.returncode==expected,'outputSHA256':hashlib.sha256((p.stdout+p.stderr).encode()).hexdigest()});return p
run('version',['--version']);run('typecheck',['typecheck',str(OUT/'accepted.qnt')]);source=(OUT/'accepted.qnt').read_text();names=re.findall(r'run (\w+) =',source)
p=run('named',['test',str(OUT/'accepted.qnt'),'--main=accepted','--match=^('+'|'.join(names)+')$','--seed=61901','--max-samples=1','--backend=typescript','--out-itf='+str(OUT/'accepted_{test}_{seq}.itf.json')]);executed=re.findall(r'ok (\w+) passed 1 test\(s\)',p.stdout)
run('traces',['run',str(OUT/'accepted.qnt'),'--main=accepted','--invariant=safety','--seed=61902','--max-samples=500','--max-steps=25','--backend=typescript'])
mutants=[('request-erases-acceptance','{...state,requestedA:state.requestedA+1','{...state,acceptedA:0,requestedA:state.requestedA+1','finalGeometryDrainTest'),('phase-hides-valid-release','state.proof and state.reserved and a>0','state.phase=="Ready" and state.proof and state.reserved and a>0','finalActionDrainTest'),('obsolete-release-accepted','a==state.acceptedA and g==state.acceptedG','true','acceptedNewActionTest'),('history-invented-committed','{...state,reserved:false,releaseA:a','{...state,history:"Committed",reserved:false,releaseA:a','completedPairTest')]
for name,old,new,test in mutants:
 assert source.count(old)==1;d=OUT/name;d.mkdir();(d/'accepted.qnt').write_text(source.replace(old,new));run(name+'-typecheck',['typecheck',str(d/'accepted.qnt')]);p=run(name+'-counterexample',['test',str(d/'accepted.qnt'),'--main=accepted','--match=^'+test+'$','--seed=61903','--max-samples=1','--backend=typescript','--out-itf='+str(d/'counterexample_{test}_{seq}.itf.json')],1);rows[-1]['assertionFailure']='Assertion failed' in p.stdout+p.stderr
report={'passed':executed==names and all(row['passed'] and row.get('assertionFailure',True) for row in rows),'named':len(names),'executed':executed,'sampledTraces':500,'maxSteps':25,'mutants':len(mutants),'commands':rows,'sourceSHA256':hashlib.sha256(source.encode()).hexdigest(),'scope':'Abstract immutable frontend accepted-read reducer only; no native binding/authentication/transport/storage or effect replay proof'}
(OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n');shutil.copy2(ROOT/'qa/model.py',OUT/'model-source.py');print(json.dumps({'passed':report['passed'],'named':len(names),'mutants':len(mutants),'report':str(OUT/'report.json')}));raise SystemExit(not report['passed'])
