import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=7172
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report110.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v110',['PROGRESS PUBLIC78 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Held110 lifetime-safe URI C66/four real sealed mapped FDs/three compiled variants/model16/24/320/200 samples/full96 preserving original95/current four resource and four scoped-detachment regressions; two model fixture failures retained. Current scoped detachment regressions retain synthetic Native Active facts and original barriers. Inactive controlled path; actual Native129 GUI92/core16/plugin19 remains2517/278. Next Native130 current GUI110 legacy route requalification on core16/plugin19 preserving every original129/128/126 control, then actual WebKit callback registration/typed realm/native outbox/controlled Core; original full release/deployment gates remain open. No installed changes.'],'progress',['docs/warlock-preview/v93/component-report110.json','implementation/warlock-preview-provider-v110/component-manifest.json','docs/warlock-repository/v78/publication/delivery.json']);print(e)
