import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>1000
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v89/report.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v126',['PROGRESS PUBLIC exactowner publication63 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. CurrentGUI89/native126 exactcore16/plugin18 PASS2465/277normalclean/all2457prior125fixed; full95/original12 and all original retirement regressions. Async10selected/30actualElmtraces/641state-command comparisons and3model+3compiledElm mutants. Heldfailed90 unconfirmed-completion owner-close counterexample retained. MutableGUI91 close barrier and C/native unissued/turnover/receipt journal work excluded. Next actual immutable Elm processing-prefix/ACK wrappers, native/host routing and retained completion delivery, >256real native/Elm turnover and all original release gates. Main desktop/drafts/five foreign tracked changes preserved.'],'progress',['docs/warlock-preview/v89/report.json','implementation/warlock-preview-provider-v89/component-manifest.json','implementation/warlock-client-provider-native-v126/component-manifest.json','docs/warlock-repository/v63/publication/delivery.json']);print(e)
