"""Reconcile initial proposals into an exact, versioned consensus ballot."""
from pathlib import Path
import collections,hashlib,json,re
ROOT=Path(__file__).resolve().parent
raw={};reports={}
for p in sorted((ROOT/'research').glob('sol*.candidates.json')):
 reviewer=p.name.removesuffix('.candidates.json')
 for row in json.loads(p.read_text()):raw[row['id']]={**row,'reviewer':reviewer}
assert len(raw)==25
# Immutable first ballot: corrected interpretations are explicit, not silent source rewrites.
rows=[]
def add(local,cap,ears=None,notes='',extra=()):
 item=raw[local];n=len(rows)+1
 rows.append({'id':f'ELM-ADOPT-{n:03d}','title':item['title'],'capability':cap,'ears':ears or item['ears'],'classification':item['classification'],'status':'draft-for-consensus','priority':item.get('priority','P1'),'baselineIds':item['baselineIds'],'workItems':item['workItems'],'sourceProposals':[local,*extra],'sources':item['sources'],'scenarios':item['scenarios'],'tradeoffs':item.get('tradeoffs',''),'guardrails':notes,'ownerRole':{'elm-verification':'Verification lead','elm-native-bridge':'Native authority lead','elm-delivery':'Release integration lead','elm-accessibility':'Accessibility lead','elm-performance':'Performance qualification lead','elm-capture-motion':'Graphics lead','elm-shell-experience':'Desktop experience lead'}[cap],'verifierRole':'Independent acceptance reviewer'})
add('IMM-01','elm-verification','WHEN a reducer replay is evaluated, the verifier SHALL reproduce state and ordered effect descriptions from versioned initial state and complete recorded inputs, reject invalid input explicitly, report selected and processed coverage, and execute no native mutations.','Sanitized replay needs an explicit semantics-preserving mapping. Refused dummy events are counted explicitly; a nonempty selected corpus cannot pass by processing zero inputs.',('OPUS01-IMM-2','OPUS01-IMM-4'))
add('IMM-02','elm-native-bridge',notes='No age-based deletion of Unknown, cleanup, issuance/revocation authority or replay floors. A presentation close/restart is not proof-safe reclamation.',extra=('OPUS01-IMM-3',))
add('IMM-03','elm-delivery',notes='Use existing durable ledger. Interrupted migration/write/fsync and storage-full are qualifying faults; coherent checkpoint is not proof that a window action completed.')
add('IMM-04','elm-performance',notes='Caching/indexing is an implementation option after profiling. Cache keys include native dependency/output/publication revisions; stale cached data grants no authority.')
add('IMM-05','elm-verification',notes='Explicit partial-observation/stuttering abstraction; compare actual commands and resources as well as model state. Bounded sampling/trace validation is not an exhaustive proof.',extra=('OPUS01-IMM-1',))
add('TE-01','elm-native-bridge',notes='Narrow module-owned typed events, effects and identity domains; native authenticates context. Do not mandate a new language, framework, giant event type or incompatible wire change.',extra=('OPUS02-TE-01','OPUS02-TE-03'))
add('TE-02','elm-native-bridge',notes='Register every implied native request; preserve child effects. Cmd.batch does not sequence dependent results. Independent actions need not wait for unrelated dependencies.')
add('TE-03','elm-native-bridge','WHEN an authenticated protocol event is admitted, each participant SHALL follow the declared actor-specific legal transitions and outcome reachability for that protocol version, preserving exact correlation and stable proof identities.','Share semantic outcome classes but keep operation/protocol-specific transitions. Window Committed is not preview Released/fenced/presented. Model transitions/typestate are implementation choices, not a claim of static session typing.',('OPUS02-TE-02','OPUS02-TE-05'))
add('TE-04','elm-native-bridge','WHILE a resource or reservation is owned, the native broker SHALL account for its admission, transfer and cleanup until matching native completion permits retirement; cancellation or release intent alone SHALL NOT erase ownership, charge or cleanup obligations.','Conservation includes newly admitted resources and ownership transfers. Cancel/Release emission is not physical retirement; producer refusal is valid only after trusted failure before image adoption. Native producer/consumer completion and reader drain remain distinct.',('OPUS02-TE-06',))
add('TE-05','elm-native-bridge',notes='Original absolute native deadlines/start events survive queue/recovery. Causality/order counters, presentation clock, input clock and epoch are distinct. Late receipts may reconcile knowledge without becoming timely success.',extra=('SOL-FLUID-03',))
add('ERR-01','elm-shell-experience',notes='Stable bounded outcome/reason catalog and actionable localized text. Unknown remains perceivable. Unknown reason within a validated Refused class may use generic refusal text; unknown schema/outcome cannot fabricate Refused.',extra=('OPUS03-ER-01',))
add('ERR-02','elm-accessibility',notes='One announcement owner; deduplicate repeated outcomes, not distinct later state changes. Native speech/braille/focus transcript required; ARIA alone is insufficient.',extra=('OPUS03-ER-02',))
add('ERR-03','elm-delivery',notes='Allowlist excludes secrets, draft content, pixels, raw port bodies, titles/arguments/paths by default. Bounded lost-record counters. Diagnostics saturation cannot block native control/cleanup or compact durable authority.',extra=('OPUS03-ER-03','OPUS01-IMM-5'))
add('ERR-04','elm-delivery',notes='Recovery action must preserve durable Unknown, replay floors, held resources and original clocks. Generic restart guidance is not acceptance. Compositor replacement is not an incidental recovery action.',extra=('OPUS03-ER-05',))
add('ERR-05','elm-delivery','WHERE local diagnostic export is selected, WHEN the user requests an export, the shell SHALL produce an inspectable local bundle of validated export-allowed evidence and declared omissions, preserving recovery authority and sending nothing externally.','Conditional/deferrable feature; not a new mandatory release blocker. No default cores, screenshots, environment, unrestricted journals or uploads. Explicit local user request; cancellation/disk-full has truthful partial-artifact outcome.',('OPUS03-ER-04',))
rows[-1]['classification']='conditional-new';rows[-1]['priority']='deferred'
add('SOL04-01','elm-shell-experience',notes='Publication/lease/incarnation captured at press remains authoritative at release. Preserve a surviving focus identity across unrelated changes; explicit eligible fallback only on removal. Keyed DOM is an implementation choice.')
add('SOL04-02','elm-accessibility','WHEN a shell projection changes, the shell SHALL expose coherent native names, roles, states, relationships and actions for the current control identities, keeping preview imagery inert and keyboard focus distinct from selection.','Control semantics plus actual native bridge required. Announcement ownership is separately ELM-ADOPT-012; multiple read-only status regions do not establish a single AT announcement.')
add('SOL04-03','elm-accessibility',notes='Native field/composition epoch binds commits; consumed keys cannot trigger shell shortcuts. Native candidate/preedit and actual input target evidence required.')
add('SOL04-04','elm-accessibility',notes='Freeze measurable contrast/target/text/reflow budgets and test constrained outputs, long labels, scaling and non-color cues. Do not assume CSS tokens or screenshots establish native reachability.')
add('SOL04-05','elm-shell-experience','WHEN a shell action is unavailable or its outcome is unresolved, the shell SHALL expose the correlated reason and safe next step, retain eligible focus and independent controls, and avoid queuing or automatically replaying a rejected or Unknown action.','Unrelated refresh must not collapse a valid picker or disable unrelated actions. Repeated clicks during pending have truthful outcome under the interruption policy; no announcement storm.',('FI-03',))
add('SOL-FLUID-01','elm-performance',notes='Input, commit, rendering, presentation and retirement are separate stages. Record clock mappings, feedback flags and missing/discarded events. Frame callback/image-load/screenshot request is not hardware presentation.',extra=('FI-01',))
add('SOL-FLUID-02','elm-native-bridge',notes='Coalesce only explicitly replaceable observations in the exact identity/dependency domain. Preserve reliable ordered effect/cleanup/control events, original deadlines and reserved progress capacity; no universal lossy stream.')
add('SOL-FLUID-04','elm-capture-motion',notes='Native last-presented geometry/velocity and approved reversal profile. Reduced motion is a live native preference, with no velocity continuation/decorative motion under the selected reduced profile. Presentation timestamps, original38/34/52 cases remain required.',extra=('FI-06',))
add('SOL-FLUID-05','elm-performance','WHEN host selection or release evaluation is prepared, the performance owner SHALL freeze same-machine workload budgets that separately measure input feedback, useful native presentation, whole-process resource closure and observer overhead, declaring missing stages.','No numeric limit invented from papers. Record latency distributions, missed frames, hardware/refresh/output metadata, CPU/memory/wakeups/idle-power and resource soak; QA observers disabled for product measurements.')
# Additional substantive Opus proposals, kept separate from their mechanism choices.
def extra(title,cap,ears,local,base,work,scenarios,notes,priority='P1'):
 rows.append({'id':f'ELM-ADOPT-{len(rows)+1:03d}','title':title,'capability':cap,'ears':ears,'classification':'refinement','status':'draft-for-consensus','priority':priority,'baselineIds':base,'workItems':work,'sourceProposals':local,'sources':[],'scenarios':scenarios,'tradeoffs':'Additional protocol/evidence complexity must meet the frozen workload/resource budget. Reuse current modules and incrementally qualify changed paths.','guardrails':notes,'ownerRole':'Native authority lead' if cap=='elm-native-bridge' else ('Graphics lead' if cap=='elm-capture-motion' else 'Performance qualification lead'),'verifierRole':'Independent acceptance reviewer'})
extra('Control delivery continuity distinct from proof identity','elm-native-bridge','WHEN authenticated control receipts are delivered, the bridge SHALL preserve their required per-channel causal order, detect gaps or regressions under the declared transport contract, reconcile uncertainty and keep repeated proofs idempotent without acknowledging unseen cleanup.', ['OPUS02-TE-04'],['ELM-ARC-010','ELM-REV-008','ELM-REV-009','ELM-REV-010'],['W03','W10'],[{'name':'reordered-cleanup','given':'Released and racing Cancelled proofs for a still-held job','when':'the later control event overtakes its prerequisite','then':'no unseen proof is acknowledged and no ownership is forgotten; the declared gap/reconciliation policy preserves cleanup'},{'name':'cross-entry-proof-and-retry','given':'global proof IDs interleave across entries and a valid final Ack is lost','when':'a stable proof repeats on the authenticated delivery stream','then':'it does not create a false gap or duplicate physical cleanup; the declared idempotent acknowledgement/reconciliation policy can finish retirement'}],'Use a separate delivery ordinal or independently qualified continuity mechanism. Proof IDs are not stream ordinals. Duplicate Acks may be retried idempotently when required; do not mandate withholding known-safe Ack retries. No global total order.','P0')
extra('Capture must not starve native presentation','elm-performance','IF a preview capture or export route exceeds its frozen presentation-impact budget on an active output, THEN the release verifier SHALL reject that route and retain a qualified alternative or explicit unavailable-preview state.', ['FI-02'],['ELM-REV-022','ELM-REN-012','ELM-QA-023','ELM-UI-017'],['W06','W08'],[{'name':'cross-output-capture-impact','given':'restore motion on one output and capture demand on another','when':'the capture route runs on the measured hardware tuple','then':'presentation gaps and latency are measured on every active output against the same workload without capture'},{'name':'over-budget-route','given':'measured route impact exceeds the frozen budget','when':'release admission evaluates it','then':'the route is rejected and the documented unavailable fallback is truthful; no stale or unqualified route substitutes for required capture acceptance'}],'Synchronous compositor readback/encode is a concern, not a measured regression. Async readback/cropping/off-thread encoding need their own safety, fence, eligibility and ABI qualification. Unavailable fallback does not close mandatory source-stop/family gates.','P0')
extra('Persistent demand converges to latest authorized source content','elm-capture-motion','WHILE preview demand remains authorized, WHEN a newer content revision arrives during outstanding capture, the provider SHALL retain bounded latest-content demand and service it after eligible capacity returns, without admitting work after demand closes or authority revokes.', ['FI-04'],['ELM-ARC-015','ELM-REN-012','ELM-UI-017','ELM-TEA-004'],['W03','W06'],[{'name':'final-content-while-busy','given':'one admitted capture and multiple newer same-source revisions while visible demand persists','when':'the first job terminates and capacity returns','then':'bounded demand selects the latest valid revision without losing the final update or extending the first job deadline'},{'name':'close-or-lock-before-followup','given':'a pending latest-content update','when':'demand closes, lock/revocation occurs or source identity changes before admission','then':'no unauthorized follow-up capture is admitted; existing jobs and cleanup obligations remain accounted'}],'No forced allocation while backpressured/exhausted. Follow-up is a genuine new native-scoped request with its own original issued clock, not renewal of expired work. Control/retirement events are lossless.')
extra('Source liveness and frame freshness are separate facts','elm-capture-motion','WHEN an authorized preview is displayed, the shell SHALL distinguish source liveness, captured content revision and frame age, and SHALL NOT describe historical or stale pixels as current content.', ['FI-05'],['ELM-REN-004','ELM-REN-014','ELM-UI-016','ELM-UX-006','ELM-UX-007'],['W03','W06'],[{'name':'live-source-with-old-frame','given':'a live source advances after its authorized frame was captured','when':'the old frame remains valid while a replacement is pending','then':'source liveness and frame age/freshness are distinguished; no false current-content claim or target substitution is made'},{'name':'revocation-or-minimize','given':'a displayed frame and native source-state/lease update','when':'the source minimizes or lease revokes','then':'the existing historical/unavailable policy and native revocation govern display before replacement; no revoked pixels remain eligible'}],'Refine labels only after reviewing the frozen historical/live/unavailable policy; do not relabel stale pixels as current-live or alter original13 S09 assertions.')
extra('Native keyboard entry and exit for the taskbar','elm-shell-experience','WHEN the declared taskbar-focus binding is admitted, the native host SHALL enter a bounded keyboard scope on the current output and retain the prior eligible application identity for the frozen exit/fallback policy, keeping the binding inert while locked.', ['UXA-02'],['ELM-UX-023','ELM-UX-024','ELM-UI-011','ELM-UI-019'],['W07'],[{'name':'enter-and-escape','given':'an eligible application has focus and the taskbar is idle','when':'the declared conflict-resolved taskbar focus binding is invoked and then Escape ends the scope','then':'native keyboard and AT focus enter the bar and return under the frozen policy, with no unintended activation-history change'},{'name':'retired-source-output-or-lock','given':'a bar keyboard scope whose prior application or output retires','when':'the scope exits or the session locks','then':'no replacement incarnation or removed output receives stale focus; the frozen eligible fallback/lock policy applies and idle bar does not intercept application input'}],'This is native keyboard scope qualification, not a mandated permanent EXCLUSIVE mode or a new default shortcut. Declare which history changes are focus-only versus real accepted activation; do not override existing MRU policy.','P0')
rows[-1]['ownerRole']='Desktop experience lead'
extra('Versioned disabled-action navigation policy','elm-shell-experience','WHEN a supported shell action becomes disabled, the shell SHALL retain its declared position, expose its reason and disabled state, and follow the frozen per-surface navigation policy without dispatching it through pointer, keyboard or accessibility activation.', ['UXA-05'],['ELM-UI-011','ELM-UX-024','ELM-UX-025'],['W07','W08'],[{'name':'supported-disabled-action','given':'a state change disables a supported menu action','when':'the user navigates with the declared per-surface policy','then':'the action position remains stable, native AT exposes unavailable state and reason, and attempted activation dispatches no effect'},{'name':'all-disabled-and-focus-retirement','given':'all menu actions are disabled or the focused action becomes disabled','when':'navigation, Enter/Space or Escape occurs','then':'the frozen policy keeps focus and dismissal reachable without invoking a disabled action or trapping focus'}],'GTK and Windows/APG differ. Freeze the chosen per-surface policy; no universal requirement to focus every disabled control. Preserve existing right-click24 amendment and unsupported-action semantics.')
rows[-1]['ownerRole']='Desktop experience lead'
uxmap={16:['UXA-01'],17:['UXA-03'],12:['UXA-04'],18:['UXA-06']}
for num,ids in uxmap.items():rows[num-1]['sourceProposals']+=ids
rows[11]['guardrails']+=' The semantic owner is the controller; delivery must reach a qualified AT-active document or declared native/fallback route, including when application focus remains outside shell.'
rows[16]['guardrails']+=' Keep the visible stable control label as the accessible name; expose transient state and action descriptions separately, within the frozen per-control naming policy.'
rows[15]['guardrails']+=' Admitted keyboard activation must equal the native AT-exposed focused identity, not merely a selected row.'
assert len(rows)==30
# Complete exact provenance of original drafts, including all Opus report sections.
for reviewer in json.loads((ROOT/'request.json').read_text())['reviewers']:
 p=ROOT/'research'/(reviewer['id']+'.md');assert p.exists(),str(p)
 text=p.read_text();reports[reviewer['id']]={'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'words':len(text.split()),'sourceURLs':sorted(set(re.findall(r'https?://[^\s)>\]\"]+',text)))}
opus_sources={}
for reviewer,row in reports.items():
 if reviewer.startswith('opus'):
  text=(ROOT/row['path']).read_text();heads=re.findall(r'^### (.+)$',text,re.M)
  opus_sources[reviewer]=heads
# Cross-source citation pool is documented, not claimed as independently verified by coordinator.
for c in rows:
 for r,report in reports.items():
  if r.startswith('opus') and any(re.search(re.escape(local)+r'\b',(ROOT/report['path']).read_text()) for local in c['sourceProposals']):
   c['sources']=sorted(set(c['sources']+report['sourceURLs']))
 if not c['sources']:c['sources']=reports['opus-05-fluid-interaction']['sourceURLs']
 c['priority']=str(c['priority'])
 if len(c['ears'])>500:raise AssertionError(c['id'])
 c['scenarioIDs']=[c['id']+' '+s['name'] for s in c['scenarios']]
for c in rows:
 if c['ears'].startswith('WHERE ') or c['ears'].startswith('WHILE ') and ' WHEN ' in c['ears']:c['pattern']='complex' if ' WHEN ' in c['ears'] else 'optional'
 elif c['ears'].startswith('WHEN '):c['pattern']='event-driven'
 elif c['ears'].startswith('WHILE '):c['pattern']='state-driven'
 elif c['ears'].startswith('IF '):c['pattern']='unwanted'
 else:c['pattern']='ubiquitous'
proposals=[]
for reviewer,report in reports.items():
 if reviewer.startswith('sol'):
  ids=[v['id'] for v in raw.values() if v['reviewer']==reviewer]
 else:
  ids=re.findall(r'^### ((?:OPUS\d+-[A-Z]+-\d+|FI-\d+|UXA-\d+))', (ROOT/report['path']).read_text(),re.M)
 for local in ids:
  mapped=[c['id'] for c in rows if local in c['sourceProposals']]
  assert mapped,(reviewer,local)
  proposals.append({'reviewer':reviewer,'localId':local,'report':report['path'],'candidates':mapped,'disposition':'reconciled draft; initial advice retained unchanged'})
assert len(proposals)==53,len(proposals)
registry={'schema':1,'round':'candidate-v1','status':'draft awaiting explicit ten-reviewer votes','preserve':{'baselineRequirements':242,'baselineScenarios':417,'nativePreviewScenarios':13,'restoreBaseline':38,'restoreRecovery':34,'originalDeadlines':True,'nativeAuthority':True,'noUnknownReplay':True,'compositorConditional':True,'noNamedAppRepairTargets':True},'requirements':rows,'originalSolCandidates':list(raw.values()),'proposalDispositions':proposals,'opusProposalHeadings':opus_sources,'reports':reports,'coordinatorCorrections':['Ownership conservation must include admission and transfer; Cancel/Release emission cannot discharge physical ownership.','Outcome semantics are shared but legal transition reachability remains protocol-specific.','Proof identity differs from transport ordinal; known-safe idempotent Ack retry must remain possible.','Latest-content followup does not reset the first job deadline or allocate while backpressured.','Source liveness is distinct from captured-frame freshness; stale pixels cannot be called current content.','Diagnostic export is conditional and deferrable.']}
path=ROOT/'candidates-v1.json';assert not path.exists();path.write_text(json.dumps(registry,indent=2)+'\n')
md=['# Consensus candidate v1','','This is the exact first ballot, not an accepted implementation. All30 candidates are draft refinements except conditional export015. Existing242/417 and current acceptance levels remain unchanged.','',f'Ballot SHA256: {hashlib.sha256(path.read_bytes()).hexdigest()}','','## Common constraints','','- Preserve native authority, exact identities, original clocks/deadlines, ordered retirement, and no automatic replay of Unknown.','- Typed state does not grant linear ownership. Cancel/Release commands do not prove physical retirement.','- Model/CPU/replay/native/hardware/AT evidence remains distinct. No comparator superiority or performance claim from source review.','- Missing budgets require measurement and a frozen policy before qualification; no invented numbers.','- All implementation tasks remain unchecked. No installed/session changes or archive/promote.','- Conditional diagnostic export is deferrable. Research integration must preserve existing delivery priority and scope.','']
for c in rows:
 md +=[f"## {c['id']} — {c['title']}",'',c['ears'],'',f"Classification: {c['classification']}. Priority: {c['priority']}. Capability: {c['capability']}.",'','Mapping: '+', '.join(c['baselineIds'])+'; '+', '.join(c['workItems'])+'.','','Constraints: '+c['guardrails'],'','Tradeoffs: '+str(c['tradeoffs']),'']
 for s in c['scenarios']:md +=[f"### Scenario: {s['name']}",'- GIVEN '+s['given'],'- WHEN '+s['when'],'- THEN '+s['then'],'']
 md +=['Source proposals: '+', '.join(c['sourceProposals'])+'.','']
(ROOT/'CANDIDATES-V1.md').write_text('\n'.join(md)+'\n')
print(json.dumps({'candidates':len(rows),'scenarios':sum(len(c['scenarios']) for c in rows),'reports':len(reports),'ballotSHA256':hashlib.sha256(path.read_bytes()).hexdigest()}))
