"""Preserve first-round drafts/votes and resolve explicit reviewer corrections."""
from pathlib import Path
import collections,hashlib,json,shutil
ROOT=Path(__file__).resolve().parent;REPO=ROOT.parents[3]
original=json.loads((ROOT/'candidates-v1.json').read_text());j=json.loads((ROOT/'candidates-v1.json').read_text());rows=j['requirements'];byid={r['id']:r for r in rows}
votes=[]
for p in sorted((ROOT/'consensus').glob('*.votes.json')):votes.append(json.loads(p.read_text()))
assert len(votes)==10 and len({v['reviewer'] for v in votes})==10
assert all(len(v['votes'])==30 for v in votes)
changes=[]
def edit(n,field,value,why):
 r=rows[n-1];changes.append({'id':r['id'],'field':field,'before':r.get(field),'after':value,'resolution':why});r[field]=value
edit(2,'ears','WHEN retained records reach their configured bound, the authority SHALL reclaim only records whose obligations remain protected by proofs and replay floors, or report distinct capacity refusal while preserving unresolved and cleanup obligations until proof-safe reclamation permits admission.','Capacity refusal is not an outcome; proof-safe reclamation resolves sticky exhaustion without false Refused.')
edit(2,'guardrails',rows[1]['guardrails']+' Capacity refusal is distinct from the original operation outcome and clears when proof-safe reclamation is possible. Scope replay floors retire only through authority-certified scope retirement or equivalent retained proof.','Authority-certified floor retirement, no restart/age deletion.')
ss=rows[1]['scenarios'];ss[0]['then']='no mutation occurs; expired or retention disposition is distinct from definitive refusal of the original operation, and retained Unknown remains unchanged'
edit(2,'scenarios',ss,'Expired duplicates cannot fabricate operation outcomes.')
ss=rows[3]['scenarios'];ss[0]['then']='output equals the uncached oracle under the correct dependency revision; recomputation and whole-process resource results are measured separately for the adoption decision'
edit(4,'scenarios',ss,'Separate projection conformance from measured optimization benefit.')
edit(4,'guardrails',rows[3]['guardrails']+' Enable an optimization only after the frozen workload comparison shows an accepted benefit; equivalence alone does not justify adopting it.','Caching is a profiling-gated option, not a promised speedup.')
edit(5,'guardrails',rows[4]['guardrails']+' Every concrete state and command field is listed as mapped or explicitly reviewed quotient/stutter/ghost-only; an unlisted field fails coverage. Quotients preserve authentication/binding identity, clock/deadline and outcome meaning; reviewed opaque-nonce renaming is allowed without erasing those relations.','Total field coverage with explicit limited equivalence.')
ss=rows[4]['scenarios'];ss.append({'name':'unlisted-field-mutation','given':'a runtime mutant drops an Unknown reservation or changes an undeclared field','when':'abstraction coverage and coupled replay run','then':'verification fails at that field rather than silently observing only the visible model'})
edit(5,'scenarios',ss,'Add non-vacuous field-coverage witness.')
ss=rows[5]['scenarios'];ss[1]['given']='a malformed, untrusted or unauthorized payload that fails boundary admission';ss[1]['then']='no admitted event, native mutation or transaction settlement is produced; only a bounded allowlisted rejection diagnostic is retained, with no fabricated Refused outcome';ss.append({'name':'authenticated-historical-reconciliation','given':'an exact authenticated historical receipt for a retained obligation and its declared reconciliation route','when':'it arrives after frontend replacement','then':'only the historical obligation may settle; the receipt grants no authority to the replacement binding and renews no deadline'})
edit(6,'scenarios',ss,'Separate malformed rejection from valid historical proof.')
edit(6,'guardrails',rows[5]['guardrails']+' Terminal Refused requires exact authenticated native evidence or a validated definitive unsent certificate. Historical proof admission follows its explicit recovery contract.','No fabricated refusal.')
edit(7,'ears',"WHEN a native effect depends on a prerequisite, the controller SHALL admit its request only after matching authenticated evidence satisfies that operation's protocol-specific prerequisite, while native authority revalidates the dependency at commit.",'Native remains serialization authority; commitment cannot stand for presentation or physical cleanup.')
edit(7,'baselineIds',sorted(set(rows[6]['baselineIds']+['ELM-ARC-008','ELM-ARC-012'])),'Exact baseline native dependency mapping.')
edit(7,'guardrails',rows[6]['guardrails']+' Native revalidates prerequisite incarnation, generation and dependency revision. Preview drain/release/presentation require their own evidence; a window Committed receipt cannot substitute.','No frontend-only dependency authority.')
edit(8,'ears','WHEN a protocol event is received, each participant SHALL admit it only under the declared actor-specific transitions, version and outcome reachability with exact correlation; otherwise it SHALL reject it without authority, ownership or settlement effect and retain a bounded rejection diagnostic.','Illegal receive is fail-closed; diagnosis is not terminal refusal.')
edit(8,'baselineIds',sorted(set(rows[7]['baselineIds']+['ELM-ARC-004','ELM-ARC-007'])),'Protocol boundary/outcome mappings.')
edit(10,'tradeoffs','Metadata and clock/queue instrumentation; frontend timers may provide feedback or fail-closed withdrawal of unsent local intent, but cannot authorize, extend, settle or time native work or substitute for native original deadlines. Vector clocks are unnecessary.','Safe local fail-closed timers remain permitted.')
edit(11,'guardrails',rows[10]['guardrails'].replace('actionable localized text','actionable, reviewed text from a catalog that supports localization')+' Supporting localization does not add a translation release gate.','No silent localization scope expansion.')
ss=rows[11]['scenarios'];ss[1]['then']='a distinct policy-eligible update is exposed without restarting the effect or changing its deadline; unauthenticated, unrelated or unauthorized receipts cause no update, while exact authenticated historical evidence may reconcile retained Unknown through the declared recovery route'
edit(12,'scenarios',ss,'Old epoch is not necessarily foreign or unauthorized.')
edit(13,'baselineIds',sorted(set(rows[12]['baselineIds']+['ELM-QA-021','ELM-QA-023','ELM-REV-020','ELM-REV-021'])),'Use actual frozen budget IDs; no invented ELM-PER IDs.')
edit(13,'guardrails','Secrets, credentials, draft contents and captured pixels are always excluded from ordinary diagnostics under ELM-DEL-017. Raw port bodies, titles, arguments and paths are also excluded by this ordinary allowlist. A different scoped mode requires a separate reviewed contract and is outside this draft. Retention/loss counters remain bounded. Saturation cannot block native control/cleanup or compact durable authority.','Unconditional privacy exclusion and explicit scope boundary.')
edit(13,'tradeoffs',str(rows[12]['tradeoffs']).replace('ELM-PER obligations','ELM-QA-021/023 and ELM-REV-020/021')+' Measure under the actual ELM-QA-021/023 and ELM-REV-020/021 budget contract.','Correct inherited budget reference.')
ss=rows[13]['scenarios'];ss[1]['then']=ss[1]['then'].replace('the original recovery deadline remains enforced',"each affected operation's original deadline is unchanged and is not renewed by recovery")
edit(14,'scenarios',ss,'Do not invent a universal recovery deadline.')
edit(15,'status','deferred-conditional-draft','No product selection or extra mandatory release gate for export.')
edit(16,'ears','WHILE a shell focus scope is open, the host SHALL preserve an eligible focused control through unrelated publications and dispatch admitted keyboard or assistive activation only to that native AT-exposed identity, rejecting retired or changed-scope targets and applying the frozen fallback when focus becomes ineligible.','Focus identity and activation agree even without publication changes.')
edit(16,'pattern','state-driven','State invariant with current eligibility.')
edit(16,'guardrails','Publication, lease and incarnation captured at press remain authoritative at release. Preserve the surviving focused identity while eligible under the frozen per-surface policy; disabled-but-focusable controls remain focused when030 allows it, otherwise apply the declared fallback. Selection is distinct from focus. Keyed DOM is an implementation choice.','Fix removal-only wording; retain disabled-navigation policy.')
ss=rows[15]['scenarios'];ss.append({'name':'focus-without-publication','given':'Close has keyboard/native AT focus while another row is selected','when':'Enter or Space is admitted without an intervening publication','then':'only Close is invoked, no window intent is dispatched and selection cannot override focused identity'})
edit(16,'scenarios',ss,'Keyboard activation follows exposed focus without requiring a publication race.')
ss=rows[16]['scenarios'];ss[0]['then']="both projections expose the same refusal state for the same control identity and focus remains on the user's control; announcement count follows ELM-ADOPT-012";ss.append({'name':'stable-name-state-change','given':'a single-window group whose visible identity label is unchanged becomes active or pending','when':'native AT re-reads the control','then':'the accessible name remains aligned with the same visible label while state/description changes under the frozen naming policy'})
edit(17,'scenarios',ss,'Semantics is distinct from announcement behavior.')
edit(17,'guardrails',rows[16]['guardrails']+' Verify cross-surface relationships in the native AT tree; DOM-local relationships do not automatically cross WebView documents.','Native relationship proof required.')
edit(20,'ears','WHEN a shell action is unavailable or unresolved, the shell SHALL expose the correlated reason and safe next step, retain eligible focus and controls outside its dependency domain, and never queue, defer or automatically replay input not accepted in that state or a rejected or Unknown action.','Unavailable inputs are locally not accepted, not necessarily terminally Refused.')
edit(20,'guardrails','Unrelated refresh means an unchanged declared family/target dependency domain and must preserve a valid picker/focus. Do not require concurrent native transactions. Repeated input during Pending follows INTERACTION.md feedback policy and ELM-UI-015; no second intent or announcement storm.','Concrete existing feedback policy and scoped independence.')
ss=rows[19]['scenarios'];ss +=[{'name':'unrelated-observation-refresh','given':'a picker is open for a family','when':"an unrelated observation refresh completes with that family's dependency revision unchanged",'then':'picker identity and focus persist and no new intent is emitted'},{'name':'same-control-during-pending','given':'a native operation is Pending for a control','when':'the same control is activated again','then':'no second intent is emitted; one truthful not-accepted result is exposed under the frozen feedback policy without repeated announcement or later replay'}]
edit(20,'scenarios',ss,'Qualify refresh churn and Pending-input race.')
ss=rows[21]['scenarios'];ss[1]['then']='the closed demand remains cancelled and its existing owner/cleanup stays recorded; another authorized demand may use only independently available eligible capacity, never the held reservation before matching release'
edit(22,'scenarios',ss,'Demand closure does not globally prohibit unrelated authorized work.')
edit(27,'ears','WHILE authorized preview demand persists, WHEN tracked source content advances during outstanding capture, the provider SHALL retain bounded latest-revision demand and service it under the frozen pacing policy after eligible capacity returns, admitting none after closure or revocation.','Bound recurring rate as well as queue size.')
edit(27,'guardrails',rows[26]['guardrails']+' Pacing/refresh is frozen in the existing budget matrix before qualification; continuous change cannot create unbounded back-to-back capture. Latest revision is limited to native-tracked coverage, currently root-surface commits only; no subsurface/family fidelity expansion.','Do not silently claim missing source coverage.')
ss=rows[26]['scenarios'];ss.append({'name':'continuous-change-and-final-revision','given':'authorized visible demand, continuously changing tracked content and eventually available eligible capacity','when':'the provider runs and then content change stops','then':'capture follows the frozen pacing policy, the final tracked revision is serviced when eligible, and presentation impact is measured under026 with no original deadline renewal'})
edit(27,'scenarios',ss,'Pacing and final-update liveness under explicit admission assumptions.')
edit(29,'priority','existing-phase-P5; early-feasibility-only','Keep frozen ELM-UX-023 delivery phase; early owning-ABI spike is not completed keyboard scope.')
edit(30,'ears','WHEN a supported shell action becomes disabled, the shell SHALL retain its declared position, expose disabled state and any reason required by the frozen per-surface policy, and follow that navigation policy without dispatching it through pointer, keyboard or accessibility activation.','Disabled reasons follow the frozen product policy rather than a new universal requirement.')
edit(30,'relatedAmendmentIds',['ELM-RC-006','ELM-RC-017','ELM-RC-018'],'Right-click identities remain outside baseline mapping.')
for c in rows:
 if c['id']!='ELM-ADOPT-015':c['status']='draft-refinement-awaiting-ratification'
 assert len(c['ears'])<=500,c['id']
 c['scenarioIDs']=[c['id']+' '+s['name'] for s in c['scenarios']]
j.update(round='candidate-v2',status='corrected draft awaiting final explicit ten-reviewer ratification',firstBallotSHA256=hashlib.sha256((ROOT/'candidates-v1.json').read_bytes()).hexdigest(),corrections=changes)
assert not (ROOT/'candidates-v2.json').exists();(ROOT/'candidates-v2.json').write_text(json.dumps(j,indent=2)+'\n')
(ROOT/'consensus/correction-ledger.json').write_text(json.dumps({'schema':1,'firstVotes':votes,'resolutions':changes,'candidateV2SHA256':hashlib.sha256((ROOT/'candidates-v2.json').read_bytes()).hexdigest(),'acceptance':'No native or baseline acceptance; export15 deliberately deferred.'},indent=2)+'\n')
# Preserve original first-ballot philosophy; make a fresh revised name and doctrine.
s=(ROOT/'PHILOSOPHY-V1.md').read_text().replace('Accord','Aletheia')
s=s.replace('It names the agreement between user intent, visible state and native behavior. Naming remains a proposal pending the user\'s preference.','The Greek word means truth; the name evokes disclosure and intelligibility. The user requested an esoteric name; this is the working proposal. [Greek lexicon](https://atlas.perseus.tufts.edu/dictionaries/headword/%E1%BC%80%CE%BB%CE%AE%CE%B8%CE%B5%CE%B9%CE%B1/).')
s=s.replace('People should be able to act without wondering which window will receive a click or whether an action succeeded.','People should know which window receives an action and whether its outcome is confirmed, refused or still unconfirmed.')
s=s.replace('Maintain a single authoritative model of ordinary shell policy. Derive surfaces from it, make state changes explicit and keep effect descriptions inspectable.','Maintain one controller model of user intent and ordinary UI policy, with native facts held as read-only observations of native authority. Derive surfaces from it, make state changes explicit and keep effect descriptions inspectable.')
s=s.replace('requested, committed, presented and unconfirmed','requested, committed, refused, cancelled, presented and unconfirmed')
s=s.replace('Preserve independent controls and avoid replaying uncertain operations automatically.','Preserve independent controls and never automatically replay Unknown or uncertain operations; reconcile with native truth first.')
s=s.replace('Keep control identity, selection and focus stable when unrelated state changes.','Keep control identity stable through unrelated changes, and preserve eligible selection and focus as distinct states.')
s=s.replace('Qualify the native route, including constrained geometry, text enlargement and composition.','Qualify the native route, including constrained geometry, text enlargement and composition. Announcements reach the user once under the frozen attention policy, without moving focus.')
s=s.replace('Keep queues, retained history, captures and diagnostic records bounded.','Keep queues, retained history, captures and diagnostic records bounded through explicit admission and proof-safe reclamation. Never forget unresolved outcomes, cleanup obligations or replay floors to make space.')
s=s.replace('Suspend unnecessary recurring work when no consumer needs it.','Pace visible-consumer work under a frozen policy and suspend unnecessary recurring work when no consumer needs it. Diagnostics contain only allowlisted facts, never secrets, draft content or pixels, and never act as authority.')
s=s.replace('Continuity/accessibility:012,016–020,023,029,030.','Continuity/accessibility:012,016–020,023,029,030.')
s=s.replace('convergence draft','corrected convergence draft')
(ROOT/'PHILOSOPHY-V2.md').write_text(s)
print(json.dumps({'candidates':len(rows),'scenarios':sum(len(r['scenarios']) for r in rows),'corrections':len(changes),'firstReviewers':len(votes)}))
