"""Prepare owned current bounded qualification and preserve every foreign change."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');proof=json.loads((repo/'docs/warlock-preview/v91/report.json').read_text())
assert proof['passed'] and proof['nativeChecks']==2466 and proof['normalOwnedExits']==277 and proof['prior126FixedOrderedControls']==2458
out=repo/'docs/warlock-repository/v64/publication';assert not out.exists();out.mkdir(parents=True)
def put(name,s):ast.parse(s);(out/name).write_text(s)
prior='bc6dfc11c5efcf9447fb325d678a2e4b7aed4afa'
s=(repo/'docs/warlock-repository/v63/publication/publish.py').read_text().replace("BASE='8e68d74b293ebe134ba7f504064f81678ee0ff58'", "BASE='"+prior+"'").replace('8b9c5938ed8c35e1d4ec27c8286b8ae10373cd82..','50d42b2b6bdd0f11c19d071e2847f5fce46cb3bf..')
allowed=('docs/warlock-preview/v91/','docs/warlock-repository/v63/publication/','docs/warlock-repository/v64/publication/','implementation/warlock-preview-provider-v91/','implementation/warlock-preview-provider-v92/','implementation/warlock-client-provider-native-v127/','implementation/warlock-client-provider-native-v128/','openspec/changes/warlock-preview-actor-retirement/tasks.md','openspec/changes/warlock-preview-actor-retirement/specs/preview-actors/spec.md')
start=s.index('allowed=');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Qualify retained native completion processing in immutable Elm\n\nHeld GUI91 fixes loss of unconfirmed completion on close and zero-floor encoding: full95, Csocket14467 and standalone1530 controls. Current held GUI92/native128 on exact unchanged core16/plugin18 passes2466 checks/277 normal exits and full cleanup, preserving2458 original126 fixed controls and original allocator/expiry oracles. GUI92 full95/all original12/legacy retirement and control regressions pass. Explicit original-binding retained-channel activation, strict final wrappers, compact contiguous Elm processing prefix and transport ACK reject gap/foreign/premature/legacy downgrade and never reset. Forty-five compiled controls,14 selected Quint scenarios/34 actual optimized Elm traces/667 state-command comparisons, three exact model and three separately compiled Elm mutants pass. The actual C/socket/native/Elm round trip passes48 controls with original cancellation/proof ACK before readiness, lost final delivery and processing ACK, retained neighbor/counter, close barrier and normal exit. Synthetic native peer and untouched reservations are scoped separately from real WebKit/physical/native turnover. Preserve fixture failures and held127 preflight metadata failure without native launch. Mutable GUI93 readiness/poll work is excluded; additive contracts do not qualify it. Actual reliable outgoing host transport, WebKit retirement routing, captured resources, continuing >256 real windows, ordinary capture and all original GUI release gates remain open.\n'
s=s[:start]+" qualification=json.loads((REPO/'docs/warlock-preview/v91/report.json').read_text());assert qualification['passed'] and qualification['nativeChecks']==2466 and qualification['normalOwnedExits']==277 and qualification['prior126FixedOrderedControls']==2458 and qualification['retainedDeliveryScenarios']==14 and qualification['retainedDeliveryTraces']==34 and qualification['retainedDeliveryStates']==667 and qualification['unsafeRetainedDeliveryElmMutants']==3 and qualification['retainedNativeElmControls']==48 and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'+s[end:]
put('publish.py',s)
s=(repo/'docs/warlock-repository/v63/publication/record_delivery.py').read_text().replace('warlock-repository/v63','warlock-repository/v64').replace('warlock-preview/v89','warlock-preview/v91').replace('warlock-preview-provider-v89','warlock-preview-provider-v92').replace('warlock-client-provider-native-v126','warlock-client-provider-native-v128')
start=s.index("['PROGRESS PUBLIC exactowner publication63 ");end=s.index(",'progress'",start)
s=s[:start]+"['PROGRESS PUBLIC exactowner publication64 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. HeldGUI92/native128 exactcore16/plugin18 PASS2466/277normalclean/all2458prior126fixed, full95/alloriginal12 and original retirement/control regressions. Retained45/14selected/34actualElmtraces/667state-command comparisons/3model+3compiledElm mutants and48actualCnativeElm loss/ACK/neighbor/close/normalexit controls. Held91 close barrier and failed127 preflight preserved. MutableGUI93 retained readiness/poll excluded; inspect its actual running processes/reports and qualify before new publication. Actual reliable outgoing control and WebKit retirement routing, captured retirement, >256real windows and all original release gates remain. Main desktop/drafts/five foreign tracked changes preserved.']"+s[end:]
put('record_delivery.py',s)
s=(repo/'docs/warlock-repository/v63/publication/commit_receipt.py').read_text().replace('8e68d74b293ebe134ba7f504064f81678ee0ff58',prior).replace('Record public asynchronous Elm retirement qualification','Record public retained Elm completion qualification')
put('commit_receipt.py',s)
s=(repo/'docs/warlock-preview/v89/commit_owned.py').read_text().replace('b3a53964e6318a4024b9dfc3e96e2b301a37fcde','7e50cf82d6de4169eb25ada61c28be64220ba804')
old="[('warlock-preview-provider-v89',True),('warlock-preview-provider-v90',False),('warlock-client-provider-native-v126',True)]";assert s.count(old)==1
s=s.replace(old,"[('warlock-preview-provider-v91',True),('warlock-preview-provider-v92',True),('warlock-client-provider-native-v127',False),('warlock-client-provider-native-v128',True)]")
s=s.replace("[r/'docs/warlock-preview/v89',r/'docs/warlock-repository/v63/publication']","[r/'docs/warlock-preview/v91',r/'docs/warlock-repository/v64/publication']")
s=s.replace('Qualify asynchronous Elm retirement and retain completion delivery failure','Qualify retained native completion processing in immutable Elm')
ast.parse(s);(repo/'docs/warlock-preview/v91/commit_owned.py').write_text(s)
print(out)
