"""Hold actual C/Elm rejected-job settlement without a native acceptance claim."""
import hashlib,json,pathlib,resource,stat,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');root=repo/'implementation/warlock-preview-provider-v66';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
reports=list(root.glob('qa/rejected-check-*/report.json'));assert len(reports)==1;path=reports[0];d=json.loads(path.read_text());assert d['passed'] and d['evidence']['passed'] and d['evidence']['checks']==11 and all(row['exitCode']==0 for row in d['commands'])
for name,value in d['inputs'].items():assert sha(pathlib.Path(name))==value,name
for name,value in d['artifacts'].items():assert sha(path.parent/name)==value,name
parent=root.parent/'warlock-preview-provider-v65';parentManifest=parent/'component-manifest.json';held=json.loads(parentManifest.read_text());assert held['passed']
files={}
for p in sorted(root.rglob('*')):
 rel=p.relative_to(root)
 if any(part in {'__pycache__','elm-stuff','mutable-elm-home'} for part in rel.parts):continue
 assert not p.is_symlink(),p
 if p.is_file():files[str(rel)]={'kind':'file','sha256':sha(p),'size':p.stat().st_size,'mode':oct(stat.S_IMODE(p.stat().st_mode))}
manifest=root/'component-manifest.json';assert not manifest.exists();manifest.write_text(json.dumps({'schema':1,'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','passed':True,'sourceHeld':True,'evidenceIntegrityPassed':True,'productionUnchangedFrom':str(parentManifest),'productionParentManifestSHA256':sha(parentManifest),'rejectedEnrollmentReport':str(path),'compiledElm':d['compiledElm'],'buildReport':held['buildReport'],'files':files,'nativeAcceptance':False,'fullReleaseAccepted':False,'scope':'New actual compiled C/Broker rejection fixture and exact unchanged parent65 optimized Elm:11 controls verify actual NativeRejected job registration, early unknown proof without false correlation, acquire suppression/no actual native capture replay, wrong final sequence retention, exact Elm terminalACK leaving other original job and request floor, duplicateACK refusal and normal original remaining settlement. Synthetic authenticated socket/observation fault induces real Broker refusal; no actual compositor/pixels/hardware/new native66 or full release claim. All production source matches held65; native108 qualifies65 only.'},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
event=loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(root.relative_to(repo)),['PROGRESS public54/native108/GUI65 passes2416/269normalclean/dynamic95 and newenrollment8 577states3mutants, source d2ddb6c public0374bad7 localreceipt1893577. Fresh66 actualC+unchangedoptimizedElm rejection proof11 passes and is held; no actualnative66/new eligible source claim. Source review next: dynamic C resume currently routes through generic resume without original receiver epoch guard, and reserveImportedResume requires Started after Coordinator may have retained a NativeRejected terminal record; preserve/discover any such real job/proof rather than orphaning it. Resume Capacity also needs an explicit original unissued intent cutoff so repeat retries cannot renew it. Specify retained per-intent history/settlement and compile in fresh67, couple selected model/Elm/C controls, then owning native campaign. All originalS09/S01-S16/restore38/recovery34/deadlines/cursor/drag52/hardware/ATIME/resources/journeys/deploymentrollback remainactive; no externalblocker. All priorQA/pub handles terminal.'],'progress',[str(manifest.relative_to(repo)),str(path.relative_to(repo))]);print(json.dumps({'passed':True,'manifest':str(manifest),'files':len(files),'checks':11,'checkpoint':str(event)}))
