"""Own next GUI derivative for typed native admission without deadline renewal."""
import hashlib,json,pathlib,resource,shutil,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
repo=pathlib.Path('/home/hoskinson/omarchy-windows-parity');parent=repo/'implementation/warlock-preview-provider-v65';target=repo/'implementation/warlock-preview-provider-v66';manifest=parent/'component-manifest.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();data=json.loads(manifest.read_text());assert data['passed'] and not target.exists()
for rel,row in data['files'].items():assert sha(parent/rel)==row['sha256'],rel
shutil.copytree(parent,target,ignore=shutil.ignore_patterns('build-*','check-*','metadata-check-*','catalog-check-*','delivery-check-*','intent-check-*','enrollment-check-*','component-manifest.json','elm-stuff','mutable-elm-home','__pycache__','ANCESTRY.json','current-build.json'))
(target/'ANCESTRY.json').write_text(json.dumps({'schema':1,'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(parent),'parentManifestSHA256':sha(manifest),'purpose':'Actual retained native-rejected job registration and optimized Elm terminal settlement without capture replay, then typed unissued UI feedback integration. Capacity is local no-job/no-receipt feedback; reject renewed deadline or changed original intent, retain request floors and original legacy two-subject behavior. Current owning native105 qualifies previousGUI60 only.','nativeAcceptance':False,'fullReleaseAccepted':False},indent=2)+'\n')
sys.path.insert(0,str(repo/'implementation/elm-build-loop-v1'));import loop
event=loop.write_checkpoint(repo,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(target.relative_to(repo)),['PROGRESS public54 remote0374bad7c76b9696c8453bbc7cba75437d76ba68 exact8611ownerblobs/source d2ddb6c3c697787abdccf8d76e763d46ded50f70; GUI65/native108 actual2416/269normalclean/newdynamic95 controls/newenrollment8 577states3mutants held. Fresh66 owns dedicated real C Broker NativeRejected job registration/actualoptimized Elm proof/ACK settlement with no capture replay and typed unissued feedback. Derive actual refusal from retained incoherent native actor fixture, never invent Refused; retain original job/floor/journal. Parent65 production unchanged; native108 qualifies65 only. AlloriginalfullS09/S01-S16/hardware/recovery/drag/input/ATIME/resources/journeys/coherentdeployment remainactive, ordinaryeligible notpromoted. No live priorQA/pub handles'],'progress',['implementation/warlock-preview-provider-v66/ANCESTRY.json','docs/warlock-preview/v73/report.json'])
print(json.dumps({'source':str(target),'checkpoint':str(event)}))
