import hashlib,json,pathlib,resource,sys,time,subprocess,shlex,traceback
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
ROOT=pathlib.Path(__file__).resolve().parents[1];REPO=ROOT.parents[1];OUT=ROOT/'qa'/('prepare-'+str(time.time_ns()));OUT.mkdir()
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
r={'passed':False,'nativeLaunched':False,'nativeAcceptance':False,'fullReleaseAccepted':False}
try:
 parent=REPO/'implementation/warlock-client-provider-native-v34';old=parent/'qa/preflight.json';pre=json.loads(old.read_text());assert pre['passed']
 inputs=dict(pre['inputs'])
 for p,h in inputs.items():assert sha(p)==h,p
 inputs[str(old)]=sha(old)
 baseline=parent/'qa/native-1791257839724867928/report.json';accepted=json.loads(baseline.read_text());assert accepted['passed'] and accepted['cleanupPassed'] and len(accepted['checks'])==1351 and all(row['passed'] for row in accepted['checks']) and len(accepted['ownedExitCodes'])==125 and all(row['exitCode']==0 for row in accepted['ownedExitCodes'])
 for rel,h in accepted['artifacts'].items():assert sha(baseline.parent/rel)==h,rel
 inputs[str(baseline)]=sha(baseline);pre['retainedFamilyObserverReport']=str(baseline)
 owner=REPO/'implementation/warlock-family-style-crop-capture-v10';descriptor=owner/'native-build-report.json';pair=json.loads(descriptor.read_text());assert pair['result']=='pass' and sha(ROOT/'native-build-report.json')==sha(descriptor) and sha(pair['binary'])==pair['sha256'] and sha(pair['plugin']['path'])==pair['plugin']['sha256']
 build=pathlib.Path(pair['pluginBuildReport']);assert sha(build)==pair['pluginBuildReportSHA256'];compiled=json.loads(build.read_text());assert compiled['passed'] and not compiled['missingSymbols']
 coreReport=pathlib.Path(pair['buildReport']);assert sha(coreReport)==pair['buildReportSHA256'];coreBuilt=json.loads(coreReport.read_text());assert coreBuilt['passed'] and pathlib.Path(coreBuilt['ancestor']['report']).parent/'Hyprland'==REPO/'implementation/warlock-core-family-crop-v1/build-1791260322349568389/Hyprland'
 coreManifest=pathlib.Path(pair['coreComponentManifest']);assert sha(coreManifest)==pair['coreComponentManifestSHA256'];held=json.loads(coreManifest.read_text())
 for rel,row in held['files'].items():assert sha(coreManifest.parent/rel)==row['sha256'],rel
 for proof in [compiled,coreBuilt]:
  for key in ['dependencies','linkDependencies','linkedLibraries','tools']:
   for p,h in proof.get(key,{}).items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in compiled['inputs'].items():assert sha(owner/rel)==h,rel;inputs[str(owner/rel)]=h
 closure=pathlib.Path(pair['linkClosureReport']);assert sha(closure)==pair['linkClosureReportSHA256'] and not json.loads(closure.read_text())['missingSymbols']
 for p in [descriptor,build,closure,coreReport,coreManifest,pathlib.Path(pair['binary']),pathlib.Path(pair['plugin']['path']),*ROOT.glob('*'),*ROOT.joinpath('qa').glob('*.py')]:
  if p.is_file():inputs[str(p)]=sha(p)
 familyFD=REPO/'implementation/warlock-family-fd-qualification-v1/qa/test-report.json';pointer=json.loads(familyFD.read_text());familyFDReport=pathlib.Path(pointer['path']);assert sha(familyFDReport)==pointer['sha256'];proof=json.loads(familyFDReport.read_text());assert proof['passed'] and proof['evidence']['physicalFDClosed'] and proof['evidence']['physicalMappingClosed']
 for p,h in proof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in proof['artifacts'].items():assert sha(familyFDReport.parent/rel)==h,rel;inputs[str(familyFDReport.parent/rel)]=h
 inputs[str(familyFD)]=sha(familyFD);inputs[str(familyFDReport)]=sha(familyFDReport);pre['familyFDReport']=str(familyFDReport)
 cropFD=REPO/'implementation/warlock-family-crop-fd-qualification-v2/qa/test-report.json';pointer=json.loads(cropFD.read_text());cropReport=pathlib.Path(pointer['path']);assert sha(cropReport)==pointer['sha256'];cropProof=json.loads(cropReport.read_text());assert cropProof['passed'] and cropProof['evidence']['legacy']['checks']==150
 for p,h in cropProof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in cropProof['artifacts'].items():assert sha(cropReport.parent/rel)==h,rel;inputs[str(cropReport.parent/rel)]=h
 inputs[str(cropFD)]=sha(cropFD);inputs[str(cropReport)]=sha(cropReport);pre['cropFDReport']=str(cropReport)
 oldCombined=REPO/'implementation/warlock-client-provider-native-v37/qa/native-1791259128393147111/report.json';oldNative=json.loads(oldCombined.read_text());assert oldNative['passed'] and oldNative['cleanupPassed'] and len(oldNative['checks'])==1524
 inputs[str(oldCombined)]=sha(oldCombined);pre['retainedCombinedFamilyReport']=str(oldCombined)
 oldCrop=REPO/'implementation/warlock-client-provider-native-v38/qa/native-1791260728575460795/report.json';oldCropNative=json.loads(oldCrop.read_text());assert oldCropNative['passed'] and oldCropNative['cleanupPassed'] and len(oldCropNative['checks'])==1612
 inputs[str(oldCrop)]=sha(oldCrop);pre['retainedNativeCropReport']=str(oldCrop)
 styleModel=REPO/'implementation/warlock-family-style-revisions-v2/qa/model-report.json';pointer=json.loads(styleModel.read_text());styleReport=pathlib.Path(pointer['path']);assert sha(styleReport)==pointer['sha256'];styleProof=json.loads(styleReport.read_text());assert styleProof['passed'] and len(styleProof['selectedNames'])==9 and styleProof['states']==29
 for p,h in styleProof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in styleProof['artifacts'].items():assert sha(styleReport.parent/rel)==h,rel;inputs[str(styleReport.parent/rel)]=h
 inputs[str(styleReport)]=sha(styleReport);inputs[str(styleModel)]=sha(styleModel);pre['styleModelReport']=str(styleReport)
 retainedStyle=REPO/'implementation/warlock-client-provider-native-v41/qa/native-1791261901860161292/report.json';retained=json.loads(retainedStyle.read_text());assert retained['passed'] and retained['cleanupPassed'] and len(retained['checks'])==1636 and len(retained['ownedExitCodes'])==150 and all(row['exitCode']==0 for row in retained['ownedExitCodes'])
 for rel,h in retained['artifacts'].items():assert sha(retainedStyle.parent/rel)==h,rel
 inputs[str(retainedStyle)]=sha(retainedStyle);pre['retainedNativeStyleReport']=str(retainedStyle)
 styleCropFD=REPO/'implementation/warlock-family-style-crop-fd-qualification-v1/qa/test-report.json';pointer=json.loads(styleCropFD.read_text());styleCropReport=pathlib.Path(pointer['path']);assert sha(styleCropReport)==pointer['sha256'];styleCropProof=json.loads(styleCropReport.read_text());assert styleCropProof['passed'] and styleCropProof['evidence']['legacy']['checks']==150 and styleCropProof['evidence']['qualify']['checks']==295
 for p,h in styleCropProof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in styleCropProof['artifacts'].items():assert sha(styleCropReport.parent/rel)==h,rel;inputs[str(styleCropReport.parent/rel)]=h
 inputs[str(styleCropFD)]=sha(styleCropFD);inputs[str(styleCropReport)]=sha(styleCropReport);pre['styleCropFDReport']=str(styleCropReport)
 failed42=REPO/'implementation/warlock-client-provider-native-v42/qa/native-1791262614875927452/report.json';failure=json.loads(failed42.read_text());assert not failure['passed'] and any(row['name']=='stoppedNewLeaseRetainsOriginalNativeJob' and not row['passed'] for row in failure['checks']);inputs[str(failed42)]=sha(failed42);pre['retainedFailedStyleCropReport']=str(failed42)
 failed44=REPO/'implementation/warlock-client-provider-native-v44/qa/native-1791264636216724357/report.json';failed44Proof=json.loads(failed44.read_text());assert not failed44Proof['passed'] and failed44Proof['cleanupPassed'] and any(row['name']=='familyWebCanonicalFamilyCoverage' and not row['passed'] for row in failed44Proof['checks']);inputs[str(failed44)]=sha(failed44);pre['retainedFailedFamilyWebReport']=str(failed44)
 failed46=REPO/'implementation/warlock-client-provider-native-v46/qa/native-1791265271172342426/report.json';failed46Proof=json.loads(failed46.read_text());assert not failed46Proof['passed'] and failed46Proof['cleanupPassed'] and any(row['name']=='familyHistoricalMinimizeExactCommittedNativeEffect' and not row['passed'] and row['outcome']['reason']=='seat-grab' for row in failed46Proof['checks']);inputs[str(failed46)]=sha(failed46);pre['retainedFailedFamilyHistoricalReport']=str(failed46)
 failed48=REPO/'implementation/warlock-client-provider-native-v48/qa/native-1791265464350990212/report.json';failed48Proof=json.loads(failed48.read_text());assert not failed48Proof['passed'] and failed48Proof['cleanupPassed'] and any(row['name']=='familyHistoricalMinimizeExactCommittedNativeEffect' and not row['passed'] and row['outcome']['reason']=='seat-grab' for row in failed48Proof['checks']);inputs[str(failed48)]=sha(failed48);pre['retainedFailedFamilyGTKGrabReport']=str(failed48)
 failed49=REPO/'implementation/warlock-client-provider-native-v49/qa/native-1791265648045047174/report.json';failed49Proof=json.loads(failed49.read_text());assert not failed49Proof['passed'] and failed49Proof['cleanupPassed'] and not any(not row['passed'] for row in failed49Proof['checks']) and 'missing-popup' in failed49Proof['traceback'] and 'familyHistoricalEvidence' in failed49Proof;inputs[str(failed49)]=sha(failed49);pre['retainedFailedHistoricalCleanupReport']=str(failed49)
 failed51=REPO/'implementation/warlock-client-provider-native-v51/qa/native-1791266300446781817/report.json';failed51Proof=json.loads(failed51.read_text());assert not failed51Proof['passed'] and failed51Proof['cleanupPassed'] and 'JSONDecodeError' in failed51Proof['error'] and all(row['exitCode']==0 for row in failed51Proof['ownedExitCodes']);inputs[str(failed51)]=sha(failed51);pre['retainedFailedPartialLogReport']=str(failed51)
 failed52=REPO/'implementation/warlock-client-provider-native-v52/qa/native-1791266452818753324/report.json';failed52Proof=json.loads(failed52.read_text());assert not failed52Proof['passed'] and failed52Proof['cleanupPassed'] and any(row['name']=='config-shadow-power-oneTypedNativeCropCapture' and not row['passed'] for row in failed52Proof['checks']) and all(row['exitCode']==0 for row in failed52Proof['ownedExitCodes']);inputs[str(failed52)]=sha(failed52);pre['retainedFailedConfigBoundsReport']=str(failed52)
 failed53=REPO/'implementation/warlock-client-provider-native-v53/qa/native-1791266958319056482/report.json';failed53Proof=json.loads(failed53.read_text());assert not failed53Proof['passed'] and failed53Proof['cleanupPassed'] and failed53Proof['renderConfigurationEvidence']['bytesChanged'] and not failed53Proof['renderConfigurationEvidence']['styleEpochChanged'] and all(row['exitCode']==0 for row in failed53Proof['ownedExitCodes']);inputs[str(failed53)]=sha(failed53);pre['retainedNativeConfigCounterexample']=str(failed53)
 failed54=REPO/'implementation/warlock-client-provider-native-v54/qa/native-1791267146852469629/report.json';failed54Proof=json.loads(failed54.read_text());assert not failed54Proof['passed'] and failed54Proof['cleanupPassed'] and failed54Proof['renderConfigurationEvidence']['bytesChanged'] and not failed54Proof['renderConfigurationEvidence']['styleEpochChanged'] and all(row['exitCode']==0 for row in failed54Proof['ownedExitCodes']) and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in failed54Proof['checks']) and any(row['name']=='configStyleChangedNativePixelsRequireNewStyleEpoch' and not row['passed'] for row in failed54Proof['checks']);inputs[str(failed54)]=sha(failed54);pre['retainedFinalNativeConfigurationCounterexample']=str(failed54)
 configRoot=REPO/'implementation/warlock-family-style-revisions-v9';assert sha(owner/'native/style_revision.hpp')==sha(configRoot/'native/style_revision.hpp')
 for pointerName in ['model-report.json','test-report.json']:
  pointerPath=configRoot/'qa'/pointerName;pointer=json.loads(pointerPath.read_text());proofPath=pathlib.Path(pointer['path']);assert sha(proofPath)==pointer['sha256'];proof=json.loads(proofPath.read_text());assert proof['passed']
  if pointerName=='model-report.json':assert len(proof['selectedNames'])==34 and proof['states']==130
  else:assert proof['evidence']['checks']==395
  for p,h in proof['inputs'].items():assert sha(p)==h,p;inputs[p]=h
  for rel,h in proof['artifacts'].items():assert sha(proofPath.parent/rel)==h,rel;inputs[str(proofPath.parent/rel)]=h
  inputs[str(pointerPath)]=sha(pointerPath);inputs[str(proofPath)]=sha(proofPath);pre['configuration'+pointerName]=str(proofPath)
 retained55=REPO/'implementation/warlock-client-provider-native-v55/qa/native-1791267298767196849/report.json';retained55Proof=json.loads(retained55.read_text());assert retained55Proof['passed'] and retained55Proof['cleanupPassed'] and len(retained55Proof['checks'])==1853 and len(retained55Proof['ownedExitCodes'])==172 and all(row['exitCode']==0 for row in retained55Proof['ownedExitCodes']);inputs[str(retained55)]=sha(retained55);pre['retainedNativeConfigurationFreshnessReport']=str(retained55)
 failed56=REPO/'implementation/warlock-client-provider-native-v56/qa/native-1791267724171862557/report.json';failed56Proof=json.loads(failed56.read_text());assert not failed56Proof['passed'] and failed56Proof['cleanupPassed'] and 'familyConfigurationHistoricalEvidence' in failed56Proof and any(row['name']=='allOriginal1739OrderedAssertionsRetained' and not row['passed'] for row in failed56Proof['checks']) and all(row['exitCode']==0 for row in failed56Proof['ownedExitCodes']);inputs[str(failed56)]=sha(failed56);pre['retainedFailedConfigGUIFixtureReport']=str(failed56)
 retained57=REPO/'implementation/warlock-client-provider-native-v57/qa/native-1791267929432150447/report.json';retained57Proof=json.loads(retained57.read_text());assert retained57Proof['passed'] and retained57Proof['cleanupPassed'] and len(retained57Proof['checks'])==1880 and len(retained57Proof['ownedExitCodes'])==176 and all(row['exitCode']==0 for row in retained57Proof['ownedExitCodes']);inputs[str(retained57)]=sha(retained57);pre['retainedNativeLiveSourceHistoricalReport']=str(retained57)
 failed58=REPO/'implementation/warlock-client-provider-native-v58/qa/native-1791268407705509382/report.json';failed58Proof=json.loads(failed58.read_text());assert not failed58Proof['passed'] and failed58Proof['cleanupPassed'] and all(row['exitCode']==0 for row in failed58Proof['ownedExitCodes']) and any(row['name']=='config-glow-power-oneTypedNativeCropCapture' and not row['passed'] and row['reply']['reason']=='preview-probe-context-stale' for row in failed58Proof['checks']);inputs[str(failed58)]=sha(failed58);pre['retainedFailedGlowApplicationReport']=str(failed58)
 failed59=REPO/'implementation/warlock-client-provider-native-v59/qa/native-1791268662250358453/report.json';failed59Proof=json.loads(failed59.read_text());assert not failed59Proof['passed'] and failed59Proof['cleanupPassed'] and any(row['name']=='glowIndependentDecoderNormalExit' and not row['passed'] for row in failed59Proof['checks']);delta=pathlib.Path(failed59).parent/'private-evidence/pixels-glow-delta.log';pixels=json.loads(delta.read_text());assert pixels['changedFamilyPixels']==pixels['changedOutputPixels']==8696 and pixels['mismatchedBefore']==pixels['mismatchedAfter']==0 and pixels['changedCenterPixels']==12;inputs[str(failed59)]=sha(failed59);inputs[str(delta)]=sha(delta);pre['retainedFailedGlowContourOracleReport']=str(failed59)
 retained60=REPO/'implementation/warlock-client-provider-native-v60/qa/native-1791268932752885842/report.json';retained60Proof=json.loads(retained60.read_text());assert retained60Proof['passed'] and retained60Proof['cleanupPassed'] and all(row['exitCode']==0 for row in retained60Proof['ownedExitCodes']) and retained60Proof['glowConfigurationEvidence']['pixels']['passed'];inputs[str(retained60)]=sha(retained60);pre['retainedNativeGlowFidelityReport']=str(retained60)
 failed61=REPO/'implementation/warlock-client-provider-native-v61/qa/native-1791269093940842620/report.json';failed61Proof=json.loads(failed61.read_text());assert not failed61Proof['passed'] and failed61Proof['cleanupPassed'] and all(row['exitCode']==0 for row in failed61Proof['ownedExitCodes']) and any(row['name']=='config-opacity-halfIndependentNativeCompositedRoot' and not row['passed'] for row in failed61Proof['checks']) and 'opacityConfigurationEvidence' not in failed61Proof;inputs[str(failed61)]=sha(failed61);pre['retainedFailedOpacityFixtureBackgroundReport']=str(failed61)
 failed62=REPO/'implementation/warlock-client-provider-native-v62/qa/native-1791269530323836731/report.json';failed62Proof=json.loads(failed62.read_text());assert not failed62Proof['passed'] and failed62Proof['cleanupPassed'] and all(row['exitCode']==0 for row in failed62Proof['ownedExitCodes']) and len(failed62Proof['ownedExitCodes'])==193 and failed62Proof['opacityConfigurationEvidence']['bytesChanged'] and not failed62Proof['opacityConfigurationEvidence']['styleEpochChanged'] and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in failed62Proof['checks']) and any(row['name']=='opacityChangedNativePixelsRequireNewStyleEpoch' and not row['passed'] for row in failed62Proof['checks']);inputs[str(failed62)]=sha(failed62);pre['retainedNativeOpaqueRuleCounterexample']=str(failed62)
 retained63=REPO/'implementation/warlock-client-provider-native-v63/qa/native-1791269735621565040/report.json';retained63Proof=json.loads(retained63.read_text());assert retained63Proof['passed'] and retained63Proof['cleanupPassed'] and len(retained63Proof['checks'])==2057 and len(retained63Proof['ownedExitCodes'])==201 and all(row['exitCode']==0 for row in retained63Proof['ownedExitCodes']);inputs[str(retained63)]=sha(retained63);pre['retainedNativeOpaqueAndSamplingFactReport']=str(retained63)
 failed65=REPO/'implementation/warlock-client-provider-native-v65/qa/native-1791271084435994222/report.json';failed65Proof=json.loads(failed65.read_text());assert not failed65Proof['passed'] and failed65Proof['cleanupPassed'] and len(failed65Proof['checks'])==2086 and len(failed65Proof['ownedExitCodes'])==202 and all(row['exitCode']==0 for row in failed65Proof['ownedExitCodes']) and not failed65Proof['backgroundEffectEvidence']['creationEpochAdvanced'] and any(row['name']=='backgroundCreationBeforeCommitRequiresNewEpoch' and not row['passed'] for row in failed65Proof['checks']) and any(row['name']=='allOriginal1783OrderedAssertionsRetained' and row['passed'] for row in failed65Proof['checks']);inputs[str(failed65)]=sha(failed65);pre['retainedNativeBackgroundInputCounterexample']=str(failed65)
 retained66=REPO/'implementation/warlock-client-provider-native-v66/qa/native-1791271302348322684/report.json';retained66Proof=json.loads(retained66.read_text());assert retained66Proof['passed'] and retained66Proof['cleanupPassed'] and len(retained66Proof['checks'])==2088 and len(retained66Proof['ownedExitCodes'])==202 and all(row['exitCode']==0 for row in retained66Proof['ownedExitCodes']);inputs[str(retained66)]=sha(retained66);pre['retainedNativeRootBackgroundFactReport']=str(retained66)
 old50=REPO/'implementation/warlock-client-provider-native-v50/qa/native-1791265841870106110/report.json';old50Proof=json.loads(old50.read_text());assert old50Proof['passed'] and old50Proof['cleanupPassed'] and len(old50Proof['checks'])==1783 and all(row['exitCode']==0 for row in old50Proof['ownedExitCodes']);inputs[str(old50)]=sha(old50);pre['retainedNativeHistoricalFamilyReport']=str(old50)
 old45=REPO/'implementation/warlock-client-provider-native-v45/qa/native-1791264757369168051/report.json';old45Proof=json.loads(old45.read_text());assert old45Proof['passed'] and old45Proof['cleanupPassed'] and len(old45Proof['checks'])==1756 and all(row['exitCode']==0 for row in old45Proof['ownedExitCodes']);inputs[str(old45)]=sha(old45);pre['retainedNativeFamilyWebReport']=str(old45)
 old43=REPO/'implementation/warlock-client-provider-native-v43/qa/native-1791262717179444040/report.json';old43Proof=json.loads(old43.read_text());assert old43Proof['passed'] and old43Proof['cleanupPassed'] and len(old43Proof['checks'])==1739 and len(old43Proof['ownedExitCodes'])==159 and all(row['exitCode']==0 for row in old43Proof['ownedExitCodes']);inputs[str(old43)]=sha(old43);pre['retainedNativeStyleCropReport']=str(old43)
 provider=REPO/'implementation/warlock-preview-provider-v34';builds=list((provider/'qa').glob('build-*/report.json'));assert len(builds)==1;providerBuild=builds[0];providerProof=json.loads(providerBuild.read_text());assert providerProof['passed'] and all(row['exitCode']==0 for row in providerProof['commands'])
 for rel,h in providerProof['inputs'].items():assert sha(provider/rel)==h,rel;inputs[str(provider/rel)]=h
 for section in ['compilerDependencies','linkedLibraries','tools']:
  for path,row in providerProof[section].items():assert sha(path)==row['sha256'],path;inputs[path]=row['sha256']
 for rel,h in providerProof['artifacts'].items():assert sha(providerBuild.parent/rel)==h,rel;inputs[str(providerBuild.parent/rel)]=h
 binary=providerBuild.parent/'elm-host';assert sha(binary)==providerProof['binarySHA256'];inputs[str(binary)]=sha(binary);inputs[str(providerBuild)]=sha(providerBuild)
 pre['fullHostBinary']=str(binary);pre['fullHostAssets']=str(providerBuild.parent/'inputs/assets');pre['fullHostBackend']=str(providerBuild.parent/'inputs/adapter/daemon.py');pre['familyProviderBuild']=str(providerBuild)
 fixtureReport=REPO/'implementation/warlock-family-modal-fixture-v4/qa/client-build-1791272695610280553/report.json';fixtureProof=json.loads(fixtureReport.read_text());assert fixtureProof['passed'] and all(row['exitCode']==0 for row in fixtureProof['commands'])
 for key in ['inputs','dependencies','linkedLibraries','tools']:
  for p,h in fixtureProof[key].items():assert sha(p)==h,p;inputs[p]=h
 for rel,h in fixtureProof['artifacts'].items():assert sha(fixtureReport.parent/rel)==h,rel;inputs[str(fixtureReport.parent/rel)]=h
 assert sha(fixtureProof['client'])==fixtureProof['clientSHA256'];pre['fixtureClient']=fixtureProof['client'];inputs[str(fixtureReport)]=sha(fixtureReport);pre['backgroundEffectFixtureBuild']=str(fixtureReport)
 inputs['/usr/bin/grim']=sha('/usr/bin/grim')
 for line in subprocess.check_output(['ldd','/usr/bin/grim'],text=True).splitlines():
  assert 'not found' not in line
  for word in line.split():
   if word.startswith('/') and pathlib.Path(word).is_file():path=str(pathlib.Path(word).resolve());inputs[path]=sha(path)
 flags=shlex.split(subprocess.check_output(['pkg-config','--cflags','--libs','libpng'],text=True))
 for name,key in [('modal-pixels','modalPixelOracle'),('family-pixels','familyPixelOracle'),('crop-pixels','cropPixelOracle'),('family-web-pixels','familyWebPixelOracle'),('glow-pixels','glowPixelOracle'),('opacity-pixels','opacityPixelOracle')]:
  argv=['g++','-std=c++20','-O2','-Wall','-Wextra','-Werror',str(ROOT/(name+'.cpp')),*flags,'-o',str(OUT/name)];p=subprocess.run(argv,capture_output=True,text=True,timeout=180);(OUT/(name+'.stdout')).write_text(p.stdout);(OUT/(name+'.stderr')).write_text(p.stderr);assert p.returncode==0,p.stderr;inputs[str(OUT/name)]=sha(OUT/name);pre[key]=str(OUT/name)
 pre['pair']['core']={'path':pair['binary'],'sha256':pair['sha256']};pre['pair']['plugin']=pair['plugin'];pre['inputs']=inputs
 assert all(sha(p)==h for p,h in inputs.items());(ROOT/'qa/preflight.json').write_text(json.dumps(pre,indent=2)+'\n');r.update(passed=True,inputs=inputs,pair=pre['pair'])
except Exception as e:r['error']=repr(e);r['traceback']=traceback.format_exc()
(OUT/'report.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'passed':r['passed'],'report':str(OUT/'report.json'),'error':r.get('error')}));raise SystemExit(not r['passed'])
