import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=6415
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report113.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v113',['PROGRESS PUBLIC82 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI113 single Elm policy/typed native realms/scoped detachment: boundaries44/native C+Elm+outbox175/two epochs/unchanged Native grant/normal exits; Quint20/32/469/200 samples/six compiled variants; cold256/1549; original permanent45/native20+C34/model14/34/667; full103 retains98. Eight failed attempts and historical phases remain. Next actual typed shared-host realm/recovered transport/stable WebKit/Core integration and full Elm recovery. Native130 current110 legacy2518/278/full cleanup remains bounded actual baseline. Original full release gates open; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report113.json','implementation/warlock-preview-provider-v113/component-manifest.json','docs/warlock-repository/v82/publication/delivery.json']);print(e)
