"""Build a source-accounted, locally served catalog; no desktop policy here."""
from pathlib import Path
import hashlib,json,re,sys,resource
sys.path.insert(0,"/home/hoskinson/window-integration-qa")
from qa_launch import require_qa_scope
scope=require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
ROOT=Path(__file__).resolve().parents[1]; REPO=ROOT.parents[2]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
components=[]
def item(identity,name,selectors,files,states,behavior,accessibility,content,topic=None,gaps=None):
 components.append(dict(id=identity,name=name,selectors=selectors,files=files,states=states,behavior=behavior,accessibility=accessibility,content=content,topic=topic,gaps=gaps or [],status='Source',overview=name+' is part of the selected GUI519-derived source closure. Its browser specimen is isolated from the window system.'))
item('taskbar','Taskbar',['.surface-bar','.bar'],['SurfaceRenderer.elm','Bar.elm','Surface.elm'],['Attached','Detached','Reconciling','Ready','Exhausted'],'The bar projects application access, existing window groups and eligible recovery controls. Identity includes observed scope. Taskbar keyboard entry and native focus remain separate acceptance work.','The bar is keyed by control identity. Its status region is polite and visually hidden in the product stylesheet. The catalog keeps this status visible for inspection.',['Applications','Reconnect','Refresh windows'],'bar',['No complete native taskbar keyboard path is established by this catalog.'])
item('window-group','Window group',['.control-group'],['SurfaceRenderer.elm','Taskbar.elm','TaskbarShell.elm','Surface.elm'],['Inactive → Activate','Active → Minimize','Minimized → Restore','Unavailable','Multiple → Picker'],'The shipped call is Taskbar.primary False. One available family restores when minimized, minimizes when active, otherwise activates. Multiple families open a picker. Empty groups return Unavailable in this fixture; pinned launch is a function-level branch not reached by the shipped call.','The visible family label and the operation-prefixed accessible name currently differ. The target contract asks that the visible label be included consistently and status remain separately understandable.',['Family label','Family count','Awaiting native confirmation'],'bar',['The demonstration calls real primary logic but does not issue a native operation.'])
item('utility','Utility control',['.control-utility'],['SurfaceRenderer.elm','Surface.elm'],['Enabled','Unavailable','Attached','Detached'],'Applications, close, refresh and reconnect use typed scoped messages. Availability comes from the controller. A control label is never an executable command.','Rendered as a button, with disabled from the published enabled field. The catalog does not add missing product keyboard semantics.',['Applications','Windows','Close','Refresh','Reconnect'],'utility')
item('recovery','Observation refresh',['.control-recovery'],['SurfaceRenderer.elm','Surface.elm','Shell.elm'],['Pending','Unknown','Enabled','Blocked'],'Refresh window status reads observations without retrying the unresolved action. Dismissing a popup preserves its outstanding intents; cancellation does not prove physical retirement.','A plain label and reason describe the safe recovery action. Single-owner audible or braille delivery still needs native qualification.',['Refresh window status','Observation only','Window action awaits native confirmation.'],'status')
item('popup','Popup surface',['.surface-popup','.surface-controls','.popup'],['SurfaceRenderer.elm','Popup.elm','Surface.elm'],['Closed','Applications','Picker','Menu'],'One published mode determines the presented list. Publication and lease accompany input. The controller rejects stale envelopes. Popup dismissal changes presentation, not unresolved operation ownership.','Menu mode publishes role=menu; other modes publish role=group. Popup children currently use List.map, so keyed identity and qualified focus fallback remain gaps.',['Applications','Window actions','Choose a window'],'menu',['Popup rows are not keyed in this selected renderer.','The source popup renders its own h1; the embedded specimen preserves that source heading.'])
item('applications','Application list',[],['Surface.elm','Desktop.elm','Catalog.elm','Launch.elm'],['Loading','Ready','Submitted','Refused','Pending','Unknown','Unavailable'],'Entries come from declared application data. Pending and Unknown prevent replay. The guarded acknowledgement says the person checked; it is not a native receipt. Search is a proposed extension.','Buttons preserve declared names. Arrow and typeahead behavior for the complete native list remain release work.',['Open {application name}','Loading applications…','I checked; allow another launch'],'applications',['Catalog search below searches documentation, not desktop applications.'])
item('picker','Window picker',[],['Surface.elm','TaskbarShell.elm','PreviewPresenter.elm'],['Open','Minimized','Unavailable','Awaiting confirmation'],'Choosing a family uses captured scope and generation. The label asks to Restore a minimized family or Activate an open family. Context activation remains scoped to the same native family.','Preview pixels are decorative to the row name. Selection, focus, activation and native completion are independent concepts.',['Restore {window title}','Activate {window title}','Minimized','Open'],'picker',['This specimen presents rows; full picker dispatch is not implemented in the fixture wrapper.'])
item('menu','Window actions',[],['Menu.elm','MenuBridge.elm','Surface.elm'],['Ready','Pending','Refused','Cancelled','Unknown','Closed'],'ArrowUp, ArrowDown, Home and End use Menu.Navigate and skip unavailable items; the source context bridge moves focus to the enabled selected row. Tab alternates between that row and Close. Enter activates the selected item, or dismisses from Close. Escape dismisses. Pending and Unknown retain the intent and block replay; only an exact authority receipt settles it.','Disabled rows use the shipped HTML disabled policy. They are not claimed to remain focusable. Source Space/typeahead behavior and native focus fallback are not fully qualified.',['Restore','Move','Size','Minimize','Maximize','Close window','Always on top','Pin to taskbar'],'menu',['Checked toggle semantics are absent; the fixture does not invent aria-checked.'])
item('menu-item','Menu item',['.control-label','.control-detail'],['SurfaceRenderer.elm','Menu.elm','Surface.elm'],['Enabled','Unavailable','Selected','Pending','Unknown'],'Typed Action data carries an operation; labels cannot grant capabilities. Item identity, binding and the current publication must match before activation.','The selected detail currently drives aria-current. The proposed checked, selected and focused semantics require a renderer change and independent native validation.',['Declared action label','Selected','Awaiting native confirmation'],'menu',['No menuitemcheckbox is present in the selected source.'])
item('preview','Preview tile',['.window-preview'],['PreviewLifecycle.elm','PreviewPresenter.elm'],['Source Live','Historical','Loading','Unavailable'],'PreviewLifecycle owns the source-defined meaning of freshness. Authorized accepted pixels may remain Historical. Lock, expiry and invalid scope revoke eligibility; close requests release through typed commands.','The figure includes a caption. Product inlineView uses div/span within a row; pixels use empty alt and aria-hidden. Window title and state provide context.',['Live preview','Historical preview','Preview loading','Preview unavailable'],'preview',['Browser illustrations are fixture pixels, never native captures.'])
item('preview-image','Preview image',['.preview-image','.preview-icon'],['PreviewLifecycle.elm'],['Owned and signaled','Historical authorized','Revoked','Icon fallback'],'An admitted opaque handle references native-owned pixels via elm-shell://preview/. Presence in the DOM is not proof of presentation or physical release. Only the one documented fixture handle can be mapped to bundled artwork here.','Images are decorative to the named window, with alt="" and aria-hidden=true. Icons follow the same native URI ownership model.',['No draft text or pixel content enters diagnostics.'],'preview')
item('preview-caption','Preview caption',['.preview-title','.preview-state','.preview-fidelity'],['PreviewLifecycle.elm'],['Live preview','Historical preview','Preview loading','Preview unavailable','Family / source-plane fidelity'],'Caption state comes from real preview policy, not animation or elapsed browser time. Family, client or unqualified plane fidelity must be reported without upgrade.','The current render includes title, state and fidelity; application is supplied but not displayed by this module. The catalog records this source gap.',['Window title','Preview state','Fidelity'],'preview',['A stronger Live claim cannot be introduced through catalog copy.'])
item('status','Connection and outcome status',['.surface-status'],['Shell.elm','Surface.elm','SurfaceRenderer.elm','Launch.elm'],['Connecting','Ready','Connection lost','Pending','Refused','Unknown','Recovery unavailable'],'Connecting, transport, recovery and operation status are distinct facts. The interface offers an appropriate observation or reconnection action and never automatically retries Unknown.','Bar and popup both contain polite regions in the current source. A qualified single announcement owner is an outstanding product contract.',['Connecting…','Connection lost. Reconnect to continue.','Applying window change…','The operation could not be confirmed.'],'status',['Duplicate live-region paths are visible source findings, not accepted accessible delivery.'])
item('native-fallback','Native recovery surface',[],['../source/shared-host.c'],['Display stopped','Restart available'],'A GTK fallback owns a label and Restart button when the WebKit display stops. Restart invokes the native callback; it is not equivalent to settling unresolved operations.','Native GTK semantics and keyboard behavior require the owning native build and assistive-technology campaign. No HTML approximation qualifies this control.',['Desktop display stopped.','Restart'])
# Preserve the entire selected implementation, including policy and replay modules.
modules=[]; source=REPO/'DesignLanguage/research/v1/consensus-inputs/implementation/warlock-preview-provider-v1'
for p in sorted((ROOT/'src').glob('*.elm')):
 if p.name=='DesignDemo.elm':continue
 text=p.read_text();original=source/'src'/p.name;assert sha(p)==sha(original)
 modules.append({'file':'src/'+p.name,'sha256':sha(p),'imports':re.findall(r'^import ([\w.]+)',text,re.M),'viewDefinitions':re.findall(r'^(\w+)\s*:[^\n]*Html',text,re.M),'classes':sorted(set(re.findall(r'class "([^"]+)"',text))),'roles':sorted(set(re.findall(r'attribute "role" "([^"]+)"',text)))})
assets=[]
for p in sorted((ROOT/'source').rglob('*')):
 if p.is_file():assets.append({'file':str(p.relative_to(ROOT)),'sha256':sha(p)})
classes=set(c for m in modules for c in m['classes'])|{'control-group','control-recovery','control-utility','bar','popup'}
covered={s[1:] for c in components for s in c['selectors'] if s.startswith('.')};assert classes<=covered,(classes-covered)
# Source string inventory is an exact token inventory, not a claim that every policy string is rendered.
strings=[]
for p in sorted((ROOT/'src').glob('*.elm')):
 if p.name=='DesignDemo.elm':continue
 for line,txt in enumerate(p.read_text().splitlines(),1):
  for token in re.findall(r'"(?:\\.|[^"\\])*"',txt):strings.append({'file':'src/'+p.name,'line':line,'literal':token})
registry={'schema':1,'scope':'GUI519-derived warlock-preview-provider-v1 full selected closure','sourceModuleCount':len(modules),'components':components,'modules':modules,'assets':assets,'renderedClasses':sorted(classes),'coverage':{'allStaticClassesAssigned':True,'selectedClosureOnly':True},'integrationGaps':['Other archived/native/input lanes are not integrated into this selected closure.','No product renderer or native behavior is changed by catalog code.'],'nativeAcceptance':False,'fullReleaseAccepted':False}
(ROOT/'registry.json').write_text(json.dumps(registry,indent=2)+'\n');(ROOT/'content-inventory.json').write_text(json.dumps({'kind':'exact source string tokens; contextual rendered copy in registry','strings':strings},indent=2)+'\n')
brand=json.loads((REPO/'docs/warlock-brand/v1/tokens.json').read_text());dark=brand['colors'];light=brand['light']
themes={'dark':dict(background=dark['ink'],surface=dark['surface'],text=dark['parchment'],muted=dark['muted'],accent=dark['lilac'],positive=dark['mint'],warning=dark['gold'],danger=dark['danger'],border=dark['border']),'light':dict(background=light['background'],surface=light['surface'],text=light['text'],muted=light['muted'],accent=light['accent'],positive=light['mint'],warning=light['gold'],danger=light['danger'],border=light['border'])}
semantic={'page':'background','container':'surface','content':'text','secondary':'muted','action':'accent','confirmed':'positive','uncertain':'warning','refused':'danger','boundary':'border','focus':'accent','focus-gap':'surface'}
component={'control-bg':'container','control-fg':'content','control-border':'boundary','control-focus':'focus','control-focus-gap':'focus-gap','control-detail':'secondary','status-pending':'action','status-unknown':'uncertain','status-refused':'refused','reader-bg':'page','reader-fg':'content'}
pairs=[{'foreground':f,'background':b,'minimum':4.5,'purpose':'text'} for f in ['text','muted','accent','positive','warning','danger'] for b in ['background','surface']]+[{'foreground':f,'background':b,'minimum':3,'purpose':'boundary/focus'} for f in ['border','accent'] for b in ['background','surface']]
tokens={'schema':1,'brandReferenceSHA256':sha(REPO/'docs/warlock-brand/v1/tokens.json'),'reference':themes,'semantic':semantic,'component':component,'pairs':pairs,'geometry':{'minimumCatalogTargetPx':32,'controlRadiusPx':6,'specimenRadiusPx':12,'readerMeasureCh':70},'motion':{'demonstrations':'explicit actions; no timer','reducedMotion':'no recurring or automatic motion','nativeTiming':'unchanged; catalog values do not define product deadlines'}}
(ROOT/'tokens.json').write_text(json.dumps(tokens,indent=2)+'\n')
css=[]
for theme,values in themes.items():
 decl=['--ref-'+k+':'+v for k,v in values.items()]+['--'+k+':var(--ref-'+v+')' for k,v in semantic.items()]+['--'+k+':var(--'+v+')' for k,v in component.items()]
 css.append((':root' if theme=='dark' else ':root[data-theme="light"]')+'{'+ ';'.join(decl)+';color-scheme:'+theme+'}')
(ROOT/'tokens.css').write_text('\n'.join(css)+'\n')
contracts=json.loads((REPO/'DesignLanguage/research/v1/candidate-v2.json').read_text())['contracts']
(ROOT/'catalog-data.js').write_text('window.WARLOCK_CATALOG='+json.dumps({'registry':registry,'tokens':tokens,'contracts':contracts},ensure_ascii=False)+';\n')
print(json.dumps({'modules':len(modules),'components':len(components),'classes':len(classes),'sourceStrings':len(strings)}))
