"""Preserve113 native failure; select three actual same-picker-group subjects."""
import ast,hashlib,json,pathlib,resource,shutil,stat,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');p=r/'implementation/warlock-client-provider-native-v113';t=r/'implementation/warlock-client-provider-native-v114';sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
failure=next(p.glob('qa/native-*/report.json'));d=json.loads(failure.read_text());assert not d['passed'] and d['cleanupPassed'] and all(row['exitCode']==0 for row in d['ownedExitCodes']) and "waitingGUI=wait" in d['traceback'] and not t.exists()
for name,h in d['artifacts'].items():assert sha(failure.parent/name)==h,name
files={str(f.relative_to(p)):{'kind':'file','sha256':sha(f),'size':f.stat().st_size,'mode':oct(stat.S_IMODE(f.stat().st_mode))} for f in sorted(p.rglob('*')) if f.is_file() and '__pycache__' not in f.parts}
m=p/'component-manifest.json';assert not m.exists();m.write_text(json.dumps({'sourceHeld':True,'passed':False,'evidenceIntegrityPassed':True,'files':files,'nativeReport':str(failure),'nativeAcceptance':False,'fullReleaseAccepted':False,'failure':'New dynamic fullGUI fixture used importPeer from standalone C probe. That unrelated application is not an enabled picker subject, so only two actual same-group roots enrolled and no capacity feedback existed. Fresh114 uses the actual same-app companion from verified scene inventory. Original pool/deadlines/oracles stay unchanged; all113 owned processes exited normally.'},indent=2)+'\n')
def ignore(path,names):return [n for n in names if n in {'component-manifest.json','preflight.json','ANCESTRY.json','__pycache__'} or (pathlib.Path(path)==p/'qa' and n.startswith(('native-','prepare-')))]
shutil.copytree(p,t,ignore=ignore)
f=t/'qa/native.py';s=f.read_text();start=s.index("   fullLogName='full-imported-feedback'");end=s.index("   writeControl(growthControl,'2 quit');",start);phase=s[start:end]
marker="   fullLogName='full-imported-feedback'";addition="   feedbackFacts=request('scene-facts-request',minimumWatermark='0');feedbackPeers=[row['incarnation'] for row in feedbackFacts['facts']['windows'] if row['application']=='warlock-child-probe' and row['incarnation'] not in {subject,growthThird[0]}];check('feedbackGUIThreeSameAppCatalogSubjects',len(feedbackPeers)==1 and len({subject,feedbackPeers[0],growthThird[0]})==3,facts=feedbackFacts);feedbackPeer=feedbackPeers[0]\n"
phase=addition+phase.replace("subject,importPeer,growthThird[0]","subject,feedbackPeer,growthThird[0]").replace("=={subject,importPeer}","=={subject,feedbackPeer}")
assert phase.count('importPeer')==0;s=s[:start]+phase+s[end:];ast.parse(s);f.write_text(s)
f=t/'qa/prepare.py';s=f.read_text();marker=" assert all(sha(p)==h for p,h in inputs.items());";assert s.count(marker)==1
added=" failed113=REPO/'"+str(failure.relative_to(r))+"';proof113=json.loads(failed113.read_text());assert not proof113['passed'] and proof113['cleanupPassed'] and all(row['exitCode']==0 for row in proof113['ownedExitCodes']) and 'waitingGUI=wait' in proof113['traceback'];inputs[str(failed113)]=sha(failed113);pre['retainedFailedThreeSubjectPickerFixture']=str(failed113)\n"
s=s.replace(marker,added+marker);ast.parse(s);f.write_text(s)
(t/'ANCESTRY.json').write_text(json.dumps({'owner':'f6779148-8f5d-4bdf-8a0f-044184e486f2','parent':str(p),'parentManifestSHA256':sha(m),'purpose':'Unchanged fullGUI76 production; correct newnative fixture to three actual native same-app picker roots. Preserve failed113 all evidence, all original109 controls and every original deadline/pool limit/owningABI. Native acceptance/fullrelease remain open.'},indent=2)+'\n')
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2',str(t.relative_to(r)),['PROGRESS GUI76 component held/committed3b808ec; native113 failednewwaiting check dueunrelatedoutsidepickerfixture, allownednormalclean/evidenceretained. Fresh114 qualifies actual3sameapp native roots; original109 oracles/deadlines unchanged currentGUI76 exactsameproduction. Nextpreflightserializednative114; allfulloriginalreleasegatesremainactive.'],'progress',[str(m.relative_to(r)),str((t/'ANCESTRY.json').relative_to(r))]);print(json.dumps({'source':str(t),'checkpoint':str(e)}))
