import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>1000
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v88/report.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v125',['PROGRESS PUBLIC exactowner publication62 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. CurrentGUI88/native125 exactcore16/plugin18 PASS2464/277normalclean/all2456prior124fixed; full95/original12/C96/decoder13-25-439states-3mutants/aggregate9068through280synthetic/Elm33/Cprefix7-15-180states-3mutants/adapter10. Heldfailed87 and actual ancestor88 sibling-order counterexample preserved. MutableGUI89 full95/Elm33/async replay pass; next selected asynchronous refinement and native observation/readiness/completion routing with retained completion delivery, actual >256native/Elm turnover and all original release gates. Main desktop/drafts/five foreign tracked changes preserved.'],'progress',['docs/warlock-preview/v88/report.json','implementation/warlock-preview-provider-v88/component-manifest.json','implementation/warlock-client-provider-native-v125/component-manifest.json','docs/warlock-repository/v62/publication/delivery.json']);print(e)
