import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=8744
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report114.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v114',['PROGRESS PUBLIC83 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. GUI114 native proposal ingress/C+Elm+outbox192/two epochs/unchanged Native grant/normal exits; pure packetization43; Quint12/22 actualC traces/300 states/200 samples/five compiled variants; full104 retains103; current resource4+scoped4. Failed runner/freezer attempts retained. Popup typed ports compiled only, actual WebKit execution and host activation unqualified. Next GUI115 retain original Elm proposals before native ticket issuance; full Elm recovery/actual WebKit/Core/window and original release gates remain. Native130 legacy2518/278/full cleanup remains actual baseline; no installed changes.'],'progress',['docs/warlock-preview/v93/component-report114.json','implementation/warlock-preview-provider-v114/component-manifest.json','docs/warlock-repository/v83/publication/delivery.json']);print(e)
