// Exact unchanged product capture helper, actual QProcess/kernel observer.
// The server's native projection is the reviewed inert CPU fixture. This does
// not establish actual Quickshell Process, native capture or Pin UI authority.
#define main retained_generic_cpu_main
#include "retire_process_fixture.cpp"
#undef main
#include <fcntl.h>
#include <sys/stat.h>
#include <thread>
#include <cerrno>
#include <limits>
#include "cpu_typed_retire_adapter.hpp"
#include "cpu_durable_route_evidence.hpp"
int main(int argc,char**args){QCoreApplication app(argc,args);try{
 std::cout<<"{\"requesterPID\":"<<getpid()<<"}"<<std::endl;std::string payload;std::getline(std::cin,payload);const auto config=strictObject(QByteArray::fromStdString(payload));const auto path=config["configPath"].toString(),manifestPath=config["manifestPath"].toString();const auto raw=guardedRegular(path,0600,getuid(),1048576);const auto pin=strictObject(raw);const auto entry=pin["captureEntry"].toObject()["path"].toString();const auto input=config["publicJSON"].toString();const auto packet=strictObject(boundedFile(manifestPath,16*1024*1024),16*1024*1024);const auto wanted=pin["captureEntry"].toObject()["sha256"].toString().toLatin1();check(digest(guardedRegular(entry,0700,getuid(),1048576))==wanted,"actual unchanged product capture entry source");
 Registry base;ProcessRegistry observer(base);Case c(base,QStringList{entry,"capture",input});QObject independentRow;auto boundContext=std::make_unique<QQmlContext>(c.engine.rootContext());QQmlEngine::setContextForObject(&independentRow,boundContext.get());auto spec=c.arm(packet);if(config["registryCase"].toString()=="context-retire"||config["registryCase"].toString()=="pending-context-retire")spec.row=&independentRow;spec.role="CPUProductCaptureFixture";spec.kernel.executable=pin["interpreter"].toObject()["path"].toString();spec.kernel.executableSHA256=pin["interpreter"].toObject()["sha256"].toString().toLatin1();spec.kernel.argv=argv(QStringList{"/usr/bin/python3","-I","-S",entry,"capture",input});spec.kernel.environment.clear();const auto selectors=pin["selectors"].toObject();QProcessEnvironment env;for(auto i=selectors.begin();i!=selectors.end();++i){env.insert(i.key(),i.value().toString());spec.kernel.environment[i.key().toUtf8()]=i.value().toString().toUtf8();}env.insert("PATH","/usr/bin");spec.kernel.environment["PATH"]="/usr/bin";
 const auto declaredObserver=pin["requestRoots"].toArray()[0].toObject();spec.kernel.observerExecutable=declaredObserver["executable"].toString();spec.kernel.observerSHA256=declaredObserver["executableSHA256"].toString().toLatin1();QStringList declaredARGV;for(const auto&part:declaredObserver["argv"].toArray())declaredARGV<<part.toString();spec.kernel.observerARGV=argv(declaredARGV);spec.kernel.observerCgroup=declaredObserver["cgroup"].toString().toUtf8();for(auto i=selectors.begin();i!=selectors.end();++i)if(qEnvironmentVariableIsSet(i.key().toUtf8().constData()))spec.kernel.observerEnvironment[i.key().toUtf8()]=qgetenv(i.key().toUtf8().constData());spec.kernel.observerEnvironment["PATH"]=declaredObserver["environment"].toObject()["PATH"].toString().toUtf8();
 spec.sourceGuard=[&]{if(guardedRegular(path,0600,getuid(),1048576)!=raw||digest(guardedRegular(entry,0700,getuid(),1048576))!=wanted)throw Refused("Actual immutable product helper/config changed");};
 auto receiptFor=[&](QString input){return [&,input](const QByteArray&out,const QByteArray&err,const KernelWitness&w,int code){
  if(code!=0||!err.isEmpty())throw Refused("Actual unchanged capture helper positive exit required");const auto r=strictObject(out),authority=r["authority"].toObject(),frontend=authority["frontend"].toObject();if(r["result"]!=QJsonValue("captured")||r["nativeWrites"]!=QJsonValue(0)||r["automaticRetries"]!=QJsonValue(0)||r["nativeCompletionClaimed"]!=QJsonValue(false)||frontend!=QJsonObject{{"pid",w.pid},{"start",w.start},{"parent",w.parent},{"pgid",w.group}})throw Refused("Actual capture helper kernel/outcome projection differs");const auto requester=authority["requester"].toObject(),root=pin["requestRoots"].toArray()[0].toObject()["identity"].toObject(),server=pin["compositor"].toObject()["identity"].toObject();if(requester!=root||requester["pid"].toInt()!=getpid()||authority["compositor"].toObject()!=server||authority["role"]!=QJsonValue("harness"))throw Refused("Actual private requester/server projection differs");const auto transport=r["transport"].toObject(),peer=transport["peer"].toObject();if(transport["sendStarted"]!=QJsonValue(true)||transport["completeServerEOF"]!=QJsonValue(true)||peer["pid"]!=server["pid"]||peer["uid"].toInt()!=int(getuid())||r["publicIdentity"].toObject()!=strictObject(input.toUtf8()))throw Refused("Actual private capture identity/peer/EOF differs");const auto captured=r["captured"].toObject();if(captured!=r["rawNativeResult"].toObject()||captured["compositorPid"]!=server["pid"]||captured["compositorStart"]!=server["start"])throw Refused("Actual capture token projection differs");const auto file=pin["evidenceDirectory"].toString()+'/'+QString::number(w.pid)+'-'+w.start+".json";if(strictObject(guardedRegular(file,0600,getuid(),1048576))!=r)throw Refused("Actual durable private helper receipt differs");
 };};spec.receiptGuard=receiptFor(input);
 const auto rearmSpec=spec;const auto lease=observer.arm(std::move(spec));int helperStartedSignals=0;QObject::disconnect(&c.process.child,&QProcess::started,&c.process,nullptr);QObject::connect(&c.process.child,&QProcess::started,&c.process,[&]{++helperStartedSignals;emit c.process.started();const auto pendingCase=config["registryCase"].toString();if(pendingCase=="pending-retire"||(pendingCase=="cancelled-changed-command"&&helperStartedSignals==1))observer.cancel(&c.process);else if(pendingCase=="pending-context-retire")boundContext.reset();else if(pendingCase=="pending-source-retire"){const auto encoded=path.toUtf8();const int fd=open(encoded.constData(),O_WRONLY|O_CLOEXEC);check(fd>=0,"Actual owned pending source mutation FD");check(pwrite(fd," ",1,raw.size())==1&&fsync(fd)==0,"Actual pending source mutation persisted");close(fd);}}); // actual started, no generic fixture stdin barrier
 c.process.child.setProcessEnvironment(env);c.process.child.setProgram(entry);c.process.child.setArguments({"capture",input});QEventLoop loop;QTimer timer;timer.setSingleShot(true);timer.setInterval(4000);QObject::connect(&timer,&QTimer::timeout,&loop,&QEventLoop::quit);QTimer observe;observe.setInterval(1);QObject::connect(&observe,&QTimer::timeout,&loop,[&]{if(c.process.child.state()==QProcess::NotRunning&&observer.terminalInventory()["allWorkersJoined"].toBool())loop.quit();});timer.setInterval(2000);timer.start();c.process.child.start();observe.start();loop.exec();observe.stop();const auto inventory=observer.terminalInventory();const auto state=observer.state(&c.process);const auto pendingCase=config["registryCase"].toString();if(pendingCase=="pending-retire"){
 const bool closed=c.process.child.state()==QProcess::NotRunning&&state["historicalKernelProof"].toBool()&&state["normalLifecycle"].toBool()&&state["kernelGone"].toBool()&&state["receiptVerified"].toBool()&&state["stdoutEOF"].toBool()&&state["stderrEOF"].toBool()&&state["workerJoined"].toBool()&&!state["current"].toBool()&&!state["kernelBound"].toBool()&&!state["complete"].toBool();
 if(!closed){std::cout<<QJsonDocument(QJsonObject{{"result","fail"},{"phase","corrected-original-pending-cancel-gap"},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)}}).toJson(QJsonDocument::Compact).constData()<<std::endl;return 1;}
 const auto oldWatcher=observer.diagnosticWorker(&c.process,lease);const auto nextLease=observer.arm(rearmSpec);check(nextLease>lease,"Rearm occurs only after historical actor normal closure");const auto next=observer.state(&c.process);check(!oldWatcher.isNull()&&QMetaObject::invokeMethod(oldWatcher.data(),"finished",Qt::DirectConnection),"Actual old registered Qt watcher notification emitted");const auto unchanged=observer.state(&c.process);const bool pass=unchanged==next&&next["lease"].toULongLong()==nextLease&&!next["started"].toBool()&&observer.terminalInventory()["allWorkersJoined"].toBool();std::cout<<QJsonDocument(QJsonObject{{"result",pass?"pass":"fail"},{"registryCase",pendingCase},{"closedOldActor",QJsonObject::fromVariantMap(state)},{"newRecordBeforeOldSignal",QJsonObject::fromVariantMap(next)},{"newRecordAfterOldSignal",QJsonObject::fromVariantMap(unchanged)},{"terminalInventory",QJsonObject::fromVariantMap(observer.terminalInventory())},{"oldWatcherActualSignal",true},{"automaticHelperRetries",0},{"helperLaunches",1}}).toJson(QJsonDocument::Compact).constData()<<std::endl;return pass?0:1;
 }if(pendingCase=="pending-source-retire"){const auto changed=guardedRegular(path,0600,getuid(),1048576);const bool sourceChanged=changed==raw+" "&&strictObject(changed)==pin;const bool pass=sourceChanged&&c.process.child.state()==QProcess::NotRunning&&inventory["allWorkersJoined"].toBool()&&state["fault"].toBool()&&!state["complete"].toBool()&&!state["kernelBound"].toBool()&&!state["normalLifecycle"].toBool()&&!state["historicalKernelProof"].toBool();bool refused=false;try{observer.arm(rearmSpec);}catch(const Refused&){refused=true;}std::cout<<QJsonDocument(QJsonObject{{"result",pass&&refused?"pass":"fail"},{"registryCase",pendingCase},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)},{"sourceChangedBytesButExactJSON",sourceChanged},{"sourceBeforeSHA256",QString::fromLatin1(digest(raw))},{"sourceAfterSHA256",QString::fromLatin1(digest(changed))},{"rearmRefused",refused},{"actualChildNormalExit",c.process.child.exitStatus()==QProcess::NormalExit},{"actualChildExitCode",c.process.child.exitCode()},{"actualQSProcessAccepted",false},{"helperLaunches",1},{"helperRetries",0}}).toJson(QJsonDocument::Compact).constData()<<std::endl;return pass&&refused?0:1;}if(pendingCase=="pending-context-retire"){const bool observed=c.process.child.state()==QProcess::NotRunning&&c.process.child.exitStatus()==QProcess::NormalExit&&c.process.child.exitCode()==0&&inventory["allWorkersJoined"].toBool()&&!state["complete"].toBool()&&!state["kernelBound"].toBool();std::cout<<QJsonDocument(QJsonObject{{"result",observed?"pass":"fail"},{"registryCase",pendingCase},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)},{"actualChildNormalExit",c.process.child.exitStatus()==QProcess::NormalExit},{"actualChildExitCode",c.process.child.exitCode()},{"installedQSProcessAccepted",false}}).toJson(QJsonDocument::Compact).constData()<<std::endl;return observed?0:1;}const bool baseline=c.process.child.state()==QProcess::NotRunning&&state["normalLifecycle"].toBool()&&(state["complete"].toBool()||(pendingCase=="cancelled-changed-command"&&!state["current"].toBool()&&!state["kernelBound"].toBool()&&state["historicalKernelProof"].toBool()&&state["workerJoined"].toBool()&&state["receiptVerified"].toBool()));if(!baseline){std::cout<<QJsonDocument(QJsonObject{{"result","fail"},{"phase","unchanged-fast-helper-baseline"},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)}}).toJson(QJsonDocument::Compact).constData()<<std::endl;return 1;}QVariantList negatives;QVariantMap negativeEvidence;const auto scenario=config["registryCase"].toString();
 auto record=[&](const QString&name,bool passed){negatives<<QVariantMap{{"name",name},{"passed",passed}};if(!passed)std::cout<<QJsonDocument(QJsonObject{{"result","fail"},{"actualRegistryNegatives",QJsonArray::fromVariantList(negatives)},{"negativeObservation",QJsonObject::fromVariantMap(negativeEvidence)},{"failedObservation",QJsonObject::fromVariantMap(negativeEvidence)}}).toJson(QJsonDocument::Compact).constData()<<std::endl;check(passed,qPrintable(name));};
 if(scenario=="normal-changed-command"||scenario=="cancelled-changed-command"||scenario=="same-command-reuse"){
  ProcessRetireScope scope;scope.engine=&c.engine;scope.provider=&c.provider;scope.objects={&c.menu,&c.row,&c.popup,&c.process,&c.out,&c.err};scope.lease=lease;scope.sourceGuard=rearmSpec.sourceGuard;
  persistRouteEvidence(config["beforeHookEvidencePath"].toString(),QJsonObject{{"phase","before-terminal-route"},{"registryCase",scenario},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)},{"helperLaunches",1},{"helperRetries",0}});
  CpuTypedRetireAdapter adapter(observer,scope);QVariantMap result;QVariantList typedRefusals;
  const std::vector<QVariant>bad={QVariant(true),QVariant(QString::number(lease)),QVariant(1.25),QVariant(std::numeric_limits<double>::quiet_NaN()),QVariant(std::numeric_limits<double>::infinity()),QVariant(0),QVariant(qulonglong(SAFE_MAX)),QVariant(QVariantList{})};
  for(const auto&value:bad){const auto before=observer.state(&c.process);check(QMetaObject::invokeMethod(&adapter,"retireProcess",Qt::DirectConnection,Q_RETURN_ARG(QVariantMap,result),Q_ARG(QVariant,value)),"Actual adapter QMetaMethod invocation required");const bool refused=result.contains("error")&&result["nativeWrites"].toInt()==0&&observer.state(&c.process)==before;typedRefusals<<QVariantMap{{"type",QString::fromLatin1(value.metaType().name())},{"refused",refused}};check(refused,"Typed parser refusal preserves exact selected state");}
  if(scenario!="same-command-reuse"){
   if(scenario=="cancelled-changed-command"){
    // Genuine JS -> QObject Q_INVOKABLE -> QVariant marshalling, CPU adapter.
    QQmlEngine::setObjectOwnership(&adapter,QQmlEngine::CppOwnership);c.engine.globalObject().setProperty("terminalRoute",c.engine.newQObject(&adapter));
    const auto answer=c.engine.evaluate(QString("terminalRoute.retireProcess(%1)").arg(lease));check(!answer.isError(),"Actual QML JS marshalling did not throw");result=answer.toVariant().toMap();
   }else{const QVariant exact=QVariant::fromValue(qulonglong(lease));check(QMetaObject::invokeMethod(&adapter,"retireProcess",Qt::DirectConnection,Q_RETURN_ARG(QVariantMap,result),Q_ARG(QVariant,exact)),"Actual exact integer metaobject retire call required");}
   check(!result.contains("error")&&result["terminalRetired"].toBool()&&result["lease"].toULongLong()==lease&&!result["current"].toBool()&&!result["kernelBound"].toBool()&&!result["complete"].toBool(),"Actual typed retirement seals normal actor without current authority");
  }
  const auto secondInput=config["secondPublicJSON"].toString();check(!secondInput.isEmpty(),"Actual independent second helper request required");
  check((scenario=="same-command-reuse")== (secondInput==input),"Only explicit retired route may change command");
  auto nextSpec=rearmSpec;nextSpec.command={entry,"capture",secondInput};nextSpec.kernel.argv=argv(QStringList{"/usr/bin/python3","-I","-S",entry,"capture",secondInput});nextSpec.receiptGuard=receiptFor(secondInput);
  c.process.selected=nextSpec.command;const auto nextLease=observer.arm(std::move(nextSpec));check(nextLease>lease,"Actual fresh lease required after normal actor closure");
  const auto armed=observer.state(&c.process);check(!armed["started"].toBool()&&!armed["historicalKernelProof"].toBool()&&!armed["stdoutEOF"].toBool()&&!armed["stderrEOF"].toBool()&&!armed["receiptVerified"].toBool()&&!armed["complete"].toBool(),"Second invocation has no first actor kernel EOF receipt proof");
  persistRouteEvidence(QFileInfo(config["beforeHookEvidencePath"].toString()).absolutePath()+"/before-second-helper.json",QJsonObject{{"phase","fresh-second-arm-before-launch"},{"registryCase",scenario},{"state",QJsonObject::fromVariantMap(armed)},{"terminalRetire",QJsonObject::fromVariantMap(result)},{"helperLaunches",1},{"helperRetries",0}});
  c.process.child.setProgram(entry);c.process.child.setArguments({"capture",secondInput});timer.start();observe.start();c.process.child.start();loop.exec();observe.stop();
  const auto second=observer.state(&c.process);const auto secondInventory=observer.terminalInventory();
  const auto firstReceipt=strictObject(state["stdout"].toString().toUtf8()),secondReceipt=strictObject(second["stdout"].toString().toUtf8());const auto firstActor=firstReceipt["authority"].toObject()["frontend"].toObject(),secondActor=secondReceipt["authority"].toObject()["frontend"].toObject();
  const bool distinct=firstActor!=secondActor&&(firstActor["pid"]!=secondActor["pid"]||firstActor["start"]!=secondActor["start"]);
  const bool passed=second["lease"].toULongLong()==nextLease&&second["kernelBound"].toBool()&&second["complete"].toBool()&&second["normalLifecycle"].toBool()&&second["historicalKernelProof"].toBool()&&second["workerJoined"].toBool()&&second["receiptVerified"].toBool()&&second["stdoutEOF"].toBool()&&second["stderrEOF"].toBool()&&second["kernelGone"].toBool()&&distinct&&secondInventory["allWorkersJoined"].toBool();
  std::cout<<QJsonDocument(QJsonObject{{"result",passed?"pass":"fail"},{"registryCase",scenario},{"first",QJsonObject::fromVariantMap(state)},{"typedRefusals",QJsonArray::fromVariantList(typedRefusals)},{"terminalRetire",QJsonObject::fromVariantMap(result)},{"freshArmed",QJsonObject::fromVariantMap(armed)},{"second",QJsonObject::fromVariantMap(second)},{"terminalInventory",QJsonObject::fromVariantMap(secondInventory)},{"independentSecondActor",distinct},{"helperLaunches",2},{"helperRetries",0},{"cpuAdapterOnly",true},{"actualQSProcessAccepted",false},{"publicInstalledQSRetireAccepted",false}}).toJson(QJsonDocument::Compact).constData()<<std::endl;return passed?0:1;
 }else if(scenario=="fault-after-disconnect-source-boundary"){
  ProcessRetireScope scope;scope.engine=&c.engine;scope.provider=&c.provider;scope.objects={&c.menu,&c.row,&c.popup,&c.process,&c.out,&c.err};scope.lease=lease;scope.sourceGuard=rearmSpec.sourceGuard;
  const auto beforeInventory=observer.terminalInventory();int injections=0;bool requested=false;bool foreignSignalReturned=false;std::unique_ptr<std::thread>foreign;
  const auto evidencePath=config["beforeHookEvidencePath"].toString();const auto evidenceParent=QFileInfo(evidencePath).absolutePath();struct stat evidenceDirectory{};
  check(evidencePath==evidenceParent+"/before-hook.json"&&QFileInfo(evidenceParent).canonicalFilePath()==evidenceParent&&lstat(evidenceParent.toUtf8().constData(),&evidenceDirectory)==0&&S_ISDIR(evidenceDirectory.st_mode)&&evidenceDirectory.st_uid==getuid()&&(evidenceDirectory.st_mode&07777)==0700,"Exact private diagnostic evidence directory required");
  const auto beforeHook=QJsonDocument(QJsonObject{{"phase","before-disconnect-hook"},{"registryCase",scenario},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(beforeInventory)},{"helperLaunches",1},{"helperRetries",0}}).toJson(QJsonDocument::Compact);
  const int directoryFD=open(evidenceParent.toUtf8().constData(),O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);struct stat openedDirectory{};
  check(directoryFD>=0&&fstat(directoryFD,&openedDirectory)==0&&openedDirectory.st_dev==evidenceDirectory.st_dev&&openedDirectory.st_ino==evidenceDirectory.st_ino&&openedDirectory.st_uid==getuid()&&(openedDirectory.st_mode&07777)==0700,"Exact opened private evidence directory required");
  const int evidenceFD=openat(directoryFD,"before-hook.json",O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC,0600);check(evidenceFD>=0,"Exclusive before-hook evidence FD required");
  qsizetype written=0;while(written<beforeHook.size()){const auto n=write(evidenceFD,beforeHook.constData()+written,size_t(beforeHook.size()-written));if(n<0&&errno==EINTR)continue;check(n>0,"Complete before-hook evidence write required");written+=n;}
  struct stat evidenceFile{},namedDirectory{};check(fstat(evidenceFD,&evidenceFile)==0&&S_ISREG(evidenceFile.st_mode)&&evidenceFile.st_uid==getuid()&&(evidenceFile.st_mode&07777)==0600&&evidenceFile.st_size==beforeHook.size(),"Exact complete diagnostic evidence file required");
  check(fsync(evidenceFD)==0&&close(evidenceFD)==0&&fsync(directoryFD)==0&&lstat(evidenceParent.toUtf8().constData(),&namedDirectory)==0&&namedDirectory.st_dev==openedDirectory.st_dev&&namedDirectory.st_ino==openedDirectory.st_ino&&namedDirectory.st_mode==openedDirectory.st_mode&&namedDirectory.st_uid==openedDirectory.st_uid&&close(directoryFD)==0,"Before-hook evidence file/directory persisted before installation");
  // QObject::disconnect has returned before this source guard is called.
  // Preserve original source verification; real Qt emission/join occurs here,
  // outside sender/receiver notification locks, while out remains connected.
  scope.sourceGuard=[&]{rearmSpec.sourceGuard();if(requested&&!foreign)foreign=std::make_unique<std::thread>([&]{emit c.out.streamFinished();foreignSignalReturned=true;});if(foreign&&foreign->joinable())foreign->join();};
  c.process.disconnectProbe=[&](const QMetaMethod&){
   // Plain C++ handoff only: no QObject methods/emission/thread start/join.
   if(injections==0){++injections;requested=true;}
  };
  bool refused=false;QString refusal;
  try{observer.retire(scope);}catch(const Refused&e){refused=true;refusal=QString::fromUtf8(e.what());}
  if(foreign&&foreign->joinable())foreign->join(); // retire has returned; outside Qt disconnect locks
  c.process.disconnectProbe={};
  QVariantMap after;bool stillSelected=true;try{after=observer.state(&c.process);}catch(const Refused&){stillSelected=false;}
  const auto afterInventory=observer.terminalInventory();
  const bool passed=refused&&injections==1&&requested&&foreignSignalReturned&&foreign&&!foreign->joinable()&&stillSelected&&after["lease"].toULongLong()==lease&&after["fault"].toBool()&&!after["normalLifecycle"].toBool()&&!after["kernelBound"].toBool()&&!after["complete"].toBool()&&after["historicalKernelProof"].toBool()&&after["workerJoined"].toBool()&&afterInventory["records"].toList().size()==beforeInventory["records"].toList().size()&&afterInventory["allWorkersJoined"].toBool();
  // Persist observations before assertion; a baseline refusal above also
  // persists its full original state and is never retried to obtain success.
  std::cout<<QJsonDocument(QJsonObject{{"result",passed?"pass":"fail"},{"registryCase",scenario},{"before",QJsonObject::fromVariantMap(state)},{"after",QJsonObject::fromVariantMap(after)},{"beforeInventory",QJsonObject::fromVariantMap(beforeInventory)},{"afterInventory",QJsonObject::fromVariantMap(afterInventory)},{"actualDisconnectNotifyInjections",injections},{"retirementRefused",refused},{"refusal",refusal},{"oldRecordStillSelected",stillSelected},{"actualCollectorForeignSignalReturned",foreignSignalReturned},{"actualQtSignalAtOutsideSourceBoundary",foreignSignalReturned},{"actualQtSignalInsideDisconnectNotify",false},{"notificationPlainCppHandoff",true},{"diagnosticThreadJoined",foreign&&!foreign->joinable()},{"primitiveFinalAdmissionProof",false},{"helperLaunches",1},{"helperRetries",0},{"helperDelayAdded",false},{"actualQSProcessAccepted",false},{"nativePinEffectAccepted",false}}).toJson(QJsonDocument::Compact).constData()<<std::endl;
  return passed?0:1;
 }else if(scenario=="old-current-rearm"){
  const auto before=observer.state(&c.process);const auto invBefore=observer.terminalInventory();for(int kind=0;kind<=4;++kind)observer.callback(&c.process,lease-1,kind,3,QProcess::CrashExit);record("actual old owner-thread callbacks preserve accepted exact record",observer.state(&c.process)==before&&observer.terminalInventory()==invBefore);
  std::thread old([&]{for(int kind=0;kind<=4;++kind)observer.callback(&c.process,lease-1,kind,3,QProcess::CrashExit);});old.join();record("actual old foreign callbacks drain inert before query",observer.state(&c.process)==before&&observer.terminalInventory()==invBefore);QCoreApplication::processEvents();record("actual queued old callbacks remain inert",observer.state(&c.process)==before);
  std::thread current([&]{observer.callback(&c.process,lease,2);});current.join();bool refused=false;try{observer.arm(rearmSpec);}catch(const Refused&){refused=true;}const auto after=observer.state(&c.process);record("actual current foreign callback immediately before rearm cannot become stale",refused&&after["lease"]==before["lease"]&&after["fault"].toBool()&&!after["kernelBound"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());QCoreApplication::processEvents();record("queued current fault retains normal joined worker inventory",observer.terminalInventory()["allWorkersJoined"].toBool());
 }else if(scenario=="duplicate-worker-notification"){
  const auto watcher=observer.diagnosticWorker(&c.process,lease);record("actual registered watcher allocation selected",!watcher.isNull());record("first exact current watcher signal emitted",QMetaObject::invokeMethod(watcher.data(),"finished",Qt::DirectConnection));record("second exact current watcher signal emitted",QMetaObject::invokeMethod(watcher.data(),"finished",Qt::DirectConnection));const auto after=observer.state(&c.process);negativeEvidence={{"after",after}};record("duplicate current native watcher notification denies authority and normal closure",after["fault"].toBool()&&!after["kernelBound"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="duplicate-eof"){
  emit c.out.streamFinished();const auto after=observer.state(&c.process);negativeEvidence={{"before",state},{"after",after}};record("actual native collector duplicate current EOF clears current authority",after["fault"].toBool()&&!after["kernelBound"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool()&&after["historicalKernelProof"].toBool());
 }else if(scenario=="duplicate-start"){
  emit c.process.started();const auto after=observer.state(&c.process);record("actual native Process duplicate current Started faults",after["fault"].toBool()&&!after["complete"].toBool());
 }else if(scenario=="source-replacement"){
  const auto encoded=path.toUtf8();const int fd=open(encoded.constData(),O_WRONLY|O_CLOEXEC);check(fd>=0,"Owned private config mutation fixture FD");check(pwrite(fd," ",1,raw.size())==1&&fsync(fd)==0,"Owned private config mutation persisted");close(fd);const auto after=observer.state(&c.process);record("actual source bytes replacement revokes accepted completion",after["fault"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="context-retire"){
  const auto oldContext=QQmlEngine::contextForObject(&independentRow);QPointer<QQmlContext>observed(oldContext);boundContext.reset();const auto after=observer.state(&c.process);negativeEvidence={{"oldContextActuallyDestroyed",observed.isNull()},{"after",after}};record("actual bound QQmlContext retirement revokes completion",observed.isNull()&&after["fault"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="context-replacement"){
  const auto priorContext=QQmlEngine::contextForObject(&c.row);QQmlContext replacement(c.engine.rootContext());QQmlEngine::setContextForObject(&c.row,&replacement);const auto observedContext=QQmlEngine::contextForObject(&c.row);const auto after=observer.state(&c.process);negativeEvidence={{"contextActuallyChanged",observedContext!=priorContext},{"newContextActuallySelected",observedContext==&replacement},{"after",after}};record("actual lexical QQmlContext replacement revokes completion",after["fault"].toBool()&&!after["complete"].toBool()&&!after["normalLifecycle"].toBool());
 }else if(scenario=="retire"){
  observer.cancel(&c.process);const auto after=observer.state(&c.process);record("actual current consumer retire forbids completion retains historical normal life",!after["current"].toBool()&&!after["complete"].toBool()&&after["normalLifecycle"].toBool()&&after["workerJoined"].toBool());
 }else if(scenario=="collector-pointer"){
  StdioCollector foreign;c.process.outAllocation=&foreign;const auto after=observer.state(&c.process);record("actual native parser getter pointer replacement revokes completion",after["fault"].toBool()&&!after["complete"].toBool());
 }else throw Refused("Declared exact registry negative scenario required");
 record("all actual readonly worker jobs remain normally joined",observer.terminalInventory()["allWorkersJoined"].toBool());const bool pass=true;QJsonObject report{{"result",pass?"pass":"fail"},{"lease",qint64(lease)},{"registryCase",scenario},{"actualRegistryNegatives",QJsonArray::fromVariantList(negatives)},{"negativeObservation",QJsonObject::fromVariantMap(negativeEvidence)},{"state",QJsonObject::fromVariantMap(state)},{"terminalInventory",QJsonObject::fromVariantMap(inventory)},{"actualUnchangedFastCaptureHelperExecuted",true},{"actualUnchangedFastCaptureHelperRegistryAccepted",pass},{"syntheticNativeServerOnly",true},{"actualQSProcessAccepted",false},{"nativePinEffectAccepted",false},{"helperWaitSleepOrRetryAdded",false},{"originalHelperTransactionSeconds",2}};std::cout<<QJsonDocument(report).toJson(QJsonDocument::Compact).constData()<<std::endl;return pass?0:1;
 }catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
