"""Check deliverable integrity/contrast and inspect the actual offline browser render."""
import functools,hashlib,http.server,json,pathlib,re,resource,shutil,subprocess,sys,threading,time,xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0,'/home/hoskinson/window-integration-qa')
from qa_launch import require_qa_scope
scope=require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
OUT=ROOT/'qa'/('verify-'+str(time.time_ns()));OUT.mkdir();report={'passed':False,'scope':scope,'checks':[],'nativeAcceptance':False,'fullReleaseAccepted':False};server=None
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def check(name,ok):report['checks'].append({'name':name,'passed':bool(ok)});assert ok,name
try:
 for p in (ROOT/'identity').glob('*.svg'):
  svg=ET.fromstring(p.read_text());check('valid labeled SVG '+p.name,svg.find('{http://www.w3.org/2000/svg}title') is not None and svg.attrib.get('viewBox'))
 check('JavaScript parses',subprocess.run(['node','--check',str(ROOT/'preview.js')],capture_output=True).returncode==0)
 for document in ['index.html','tokens.css','preview.css']:
  text=(ROOT/document).read_text()
  pattern=r'(?:src|href)="([^"]+)"' if document.endswith('.html') else r'url\(([^)]+)\)'
  for rel in re.findall(pattern,text):
   if rel.startswith('#'):continue
   check(document+' local resource '+rel,not rel.startswith(('http:','https:','//')) and (ROOT/rel).is_file())
 fonts=json.loads((ROOT/'fonts/provenance.json').read_text());check('all six font/license bytes verified',len(fonts['files'])==6 and all(sha(ROOT/x['file'])==x['sha256'] for x in fonts['files']))
 def luminance(color):
  values=[int(color[i:i+2],16)/255 for i in [1,3,5]];v=[x/12.92 if x<=.04045 else ((x+.055)/1.055)**2.4 for x in values];return .2126*v[0]+.7152*v[1]+.0722*v[2]
 def contrast(a,b):
  aa,bb=sorted([luminance(a),luminance(b)]);return (bb+.05)/(aa+.05)
 tokens=json.loads((ROOT/'tokens.json').read_text());rows=[]
 for theme in ['dark','light']:
  colors=tokens['colors'] if theme=='dark' else tokens['light'];backgrounds=[colors['ink'],colors['surface']] if theme=='dark' else [colors['background'],colors['surface']]
  text=colors['parchment'] if theme=='dark' else colors['text'];accent=colors['lilac'] if theme=='dark' else colors['accent'];border='#68718c' if theme=='dark' else '#838a9a'
  for role,c,threshold in [('text',text,4.5),('secondary',colors['muted'],4.5),('accent',accent,4.5),('control-boundary',border,3)]:
   for bg in backgrounds:
    ratio=contrast(c,bg);rows.append({'theme':theme,'role':role,'foreground':c,'background':bg,'ratio':ratio,'minimum':threshold});check(theme+' '+role+' contrast on '+bg,ratio>=threshold)
 report['contrast']=rows
 originals=[('warlock-brand-board.png','exec-83b6f6ce-45bd-477f-9470-f7379fec84c3.png','01-brand-board.txt',False),('warlock-mark-transparent.png','exec-376cddcb-a1cc-48c7-ba32-be840696d9ea.png','02-mark-transparent.txt',True),('warlock-flow-wallpaper.png','exec-3e247eef-7571-401d-a5de-1ee0041f2073.png','03-wallpaper.txt',False)];assets=[]
 for name,original,prompt,transparent in originals:
  path=ROOT/'art'/name;native=pathlib.Path('/home/hoskinson/.codex/generated_images/01a10577-e8bd-79d0-9344-518f3a72c97f')/original;check('generated bytes preserved '+name,sha(path)==sha(native))
  result=subprocess.check_output(['/usr/bin/magick','identify','-format','%w %h %[channels] %[opaque]',str(path)],text=True).split();width,height=int(result[0]),int(result[1]);opaque=result[-1]=='True';check('expected transparency '+name,opaque!=transparent)
  assets.append({'file':'art/'+name,'sha256':sha(path),'width':width,'height':height,'alpha':not opaque,'prompt':'prompts/'+prompt,'promptSHA256':sha(ROOT/'prompts'/prompt),'mode':'built-in image_gen tool','originalFile':str(native)})
 (ROOT/'asset-manifest.json').write_text(json.dumps({'schema':1,'brand':'Warlock','rasterAssets':assets,'vectorCompanions':'Original editable vector companions following the generated art direction; not raster conversion','fonts':'fonts/provenance.json'},indent=2)+'\n')
 served=[]
 class Handler(http.server.SimpleHTTPRequestHandler):
  def __init__(self,*args,**kwargs):super().__init__(*args,directory=str(ROOT),**kwargs)
  def log_message(self,format,*args):served.append({'path':self.path,'message':format%args})
 server=http.server.ThreadingHTTPServer(('127.0.0.1',0),Handler);thread=threading.Thread(target=server.serve_forever,daemon=True);thread.start()
 browser='/opt/brave-bin/brave';profile=OUT/'private-profile';url='http://127.0.0.1:'+str(server.server_address[1])+'/index.html'
 command=[browser,'--headless=new','--disable-gpu','--disable-background-networking','--disable-component-update','--disable-sync','--disable-extensions','--no-first-run','--no-default-browser-check','--password-store=basic','--user-data-dir='+str(profile),'--hide-scrollbars','--window-size=1440,2400','--timeout=15000','--virtual-time-budget=2500','--screenshot='+str(OUT/'brand-preview.png'),'--dump-dom',url]
 p=subprocess.run(command,capture_output=True,text=True,timeout=75);(OUT/'browser.stdout').write_text(p.stdout);(OUT/'browser.stderr').write_text(p.stderr);report['browser']={'command':command,'exitCode':p.returncode,'served':served}
 check('actual headless browser exits normally',p.returncode==0);check('screenshot produced',(OUT/'brand-preview.png').is_file());check('correct rendered title','Warlock — Crafted for flow' in p.stdout);check('all three bundled fonts loaded',all(any('/fonts/'+name in r['path'] for r in served) for name in ['space-grotesk-bold.woff2','inter-variable.woff2','jetbrains-mono-regular.woff2']))
 report['screenshotSHA256']=sha(OUT/'brand-preview.png');report['passed']=True
except Exception as error:
 report['error']=repr(error)
 if isinstance(error,subprocess.TimeoutExpired):
  (OUT/'browser-timeout.stdout').write_bytes(error.stdout or b'')
  (OUT/'browser-timeout.stderr').write_bytes(error.stderr or b'')
finally:
 if server:server.shutdown();server.server_close()
 profile=OUT/'private-profile'
 if profile.exists():shutil.rmtree(profile)
(OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'passed':report['passed'],'report':str(OUT/'report.json'),'error':report.get('error')}));sys.exit(not report['passed'])
