import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=584
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/native-report131.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v131',['PROGRESS PUBLIC89 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. Native131 current GUI119 legacy host/assets/backend on core16/plugin19/AQ155: actual2518 checks/278 normal owned exits/full cleanup, all2510 original130 fixed controls plus actual allocator/original expiry/deadlines/pixels/receipts/teardown retained. Resource49/snapshots11/independent FD closures2. Shared visual helper refactor qualifies current actual legacy DOM/host only. Native JSC policy/channel/pure renderer/controlled URI route remains inactive. Failed nominal count freezer preserved; v2 audits original optional readonly polling counts without changing any campaign/oracle/deadline. Next actual controlled host durable input/native-ticket custody/retry and WebKit callback/lease/async frame/physical concealment/URI barriers. GUI119 CPU channel/pure renderer/full115 remains separate. Uncertain worker/revoked delayed proposals/>256 actual native windows/full release gates stay open; installed/foreign paths preserved.'],'progress',['docs/warlock-preview/v93/native-report131.json','implementation/warlock-client-provider-native-v131/component-manifest.json','docs/warlock-repository/v89/publication/delivery.json']);print(e)
