#include "MappingDiagnostic.hpp"
#include "ProcessRegistry.hpp"
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <sys/sysmacros.h>
#include <unistd.h>
#include <cerrno>
#include <filesystem>
#include <sstream>
namespace Lifetime {
namespace {
QString link(const QString&path){return QString::fromStdString(std::filesystem::read_symlink(path.toStdString()).string());}
QVariantMap statValue(const struct stat&s){return {{"device",qulonglong(s.st_dev)},{"major",qulonglong(major(s.st_dev))},{"minor",qulonglong(minor(s.st_dev))},{"inode",qulonglong(s.st_ino)},{"mode",qulonglong(s.st_mode)},{"uid",qulonglong(s.st_uid)},{"gid",qulonglong(s.st_gid)},{"nlink",qulonglong(s.st_nlink)},{"size",qlonglong(s.st_size)},{"mtimeSeconds",qlonglong(s.st_mtim.tv_sec)},{"mtimeNanoseconds",qlonglong(s.st_mtim.tv_nsec)}};}
QVariantMap statxValue(int fd,const char*name,int flags){struct statx s{};if(statx(fd,name,flags,STATX_BASIC_STATS|STATX_MNT_ID|STATX_SUBVOL,&s))return {{"errno",errno}};return {{"errno",0},{"mask",qulonglong(s.stx_mask)},{"major",qulonglong(s.stx_dev_major)},{"minor",qulonglong(s.stx_dev_minor)},{"inode",qulonglong(s.stx_ino)},{"mode",qulonglong(s.stx_mode)},{"uid",qulonglong(s.stx_uid)},{"gid",qulonglong(s.stx_gid)},{"nlink",qulonglong(s.stx_nlink)},{"size",qulonglong(s.stx_size)},{"mountID",qulonglong(s.stx_mnt_id)},{"subvolumeID",qulonglong(s.stx_subvol)},{"mtimeSeconds",qlonglong(s.stx_mtime.tv_sec)},{"mtimeNanoseconds",qulonglong(s.stx_mtime.tv_nsec)}};}
QVariantMap childIdentity(int pid){const auto root=QString("/proc/%1/").arg(pid);struct stat st{};if(stat((root+"status").toUtf8().constData(),&st)||st.st_uid!=getuid())throw Refused("Diagnostic child ownership refused");const auto raw=boundedFile(root+"stat");const auto index=raw.lastIndexOf(')');if(index<0)throw Refused("Diagnostic child stat syntax");const auto fields=raw.mid(index+2).simplified().split(' ');if(fields.size()<20||fields[1]!=QByteArray::number(getpid()))throw Refused("Diagnostic child parent differs");QVariantMap ns;for(const auto*key:{"user","mnt","net","pid","ipc","uts","cgroup"})ns[QString::fromLatin1(key)]=link(root+"ns/"+key);return {{"pid",pid},{"start",QString::fromLatin1(fields[19])},{"parent",QString::fromLatin1(fields[1])},{"group",QString::fromLatin1(fields[2])},{"executable",link(root+"exe")},{"argvSHA256",QString::fromLatin1(digest(boundedFile(root+"cmdline")))},{"cgroupSHA256",QString::fromLatin1(digest(boundedFile(root+"cgroup")))},{"namespaces",ns}};}
QVariantMap pathSnapshot(const QString&name){QVariantMap r;try{r["link"]=link(name);}catch(const std::exception&e){r["linkError"]=QString::fromLocal8Bit(e.what());}struct stat s{};if(stat(name.toUtf8().constData(),&s))r["statErrno"]=errno;else{r["statErrno"]=0;r["stat"]=statValue(s);}r["statx"]=statxValue(AT_FDCWD,name.toUtf8().constData(),0);const int fd=open(name.toUtf8().constData(),O_RDONLY|O_CLOEXEC);if(fd<0)r["openErrno"]=errno;else{r["openErrno"]=0;if(fstat(fd,&s))r["fstatErrno"]=errno;else r["openedStat"]=statValue(s);close(fd);}return r;}
QVariantMap fdSnapshot(int fd){struct stat s{};if(fstat(fd,&s))throw Refused("Diagnostic source FD fstat refused");struct statfs fs{};if(fstatfs(fd,&fs))throw Refused("Diagnostic source FD filesystem refused");const auto prefix=QString("/proc/self/");return {{"stat",statValue(s)},{"statx",statxValue(fd,"",AT_EMPTY_PATH)},{"filesystemType",qulonglong(fs.f_type)},{"fdTarget",link(prefix+QString("fd/%1").arg(fd))},{"rawFDInfo",QString::fromLatin1(boundedFile(prefix+QString("fdinfo/%1").arg(fd)))}};}
QString selectedMount(const QByteArray&raw,qulonglong id){QStringList matches;for(const auto&line:raw.split('\n'))if(line.startsWith(QByteArray::number(id)+' '))matches<<QString::fromLatin1(line);if(matches.size()!=1)throw Refused("Diagnostic exact mount ID lookup ambiguous/missing");return matches[0];}
}
QVariantMap mappingDiagnostic(int pid,const QString&path,const QByteArray&row){QVariantMap r{{"schema","owned-map-device-diagnostic-v1"},{"mappingAuthority",false},{"strictOriginalPredicateUnchanged",true},{"rawLine",QString::fromLatin1(row)},{"path",path}};int fd=-1;
 try{
  r["identityBefore"]=childIdentity(pid);std::istringstream parsed(row.toStdString());std::string range,perms,offset,device,inode;parsed>>range>>perms>>offset>>device>>inode;if(range.empty()||range.find_first_not_of("0123456789abcdef-")!=std::string::npos)throw Refused("Diagnostic range syntax");const auto mapsName=QString("/proc/%1/maps").arg(pid),mapFile=QString("/proc/%1/map_files/%2").arg(pid).arg(QString::fromStdString(range));const auto mapsBefore=boundedFile(mapsName,2*1024*1024);r["mapsBeforeSHA256"]=QString::fromLatin1(digest(mapsBefore));r["selectedRowBeforePresent"]=mapsBefore.split('\n').contains(row);r["mapFilesBefore"]=pathSnapshot(mapFile);
  const auto named=path.toUtf8();struct stat before{};if(lstat(named.constData(),&before)||!S_ISREG(before.st_mode))throw Refused("Diagnostic named regular source refused");r["namedBefore"]=statValue(before);fd=open(named.constData(),O_RDONLY|O_NOFOLLOW|O_CLOEXEC);if(fd<0){r["sourceOpenErrno"]=errno;throw Refused("Diagnostic source FD refused");}r["fdBefore"]=fdSnapshot(fd);
  const auto ns=link(QString("/proc/%1/ns/mnt").arg(pid));r["observerMountNamespace"]=link("/proc/self/ns/mnt");r["childMountNamespace"]=ns;
  const auto observerMounts=boundedFile("/proc/self/mountinfo",2*1024*1024),childMounts=boundedFile(QString("/proc/%1/mountinfo").arg(pid),2*1024*1024);const auto x=r["fdBefore"].toMap()["statx"].toMap();r["observerMountInfoSHA256"]=QString::fromLatin1(digest(observerMounts));r["childMountInfoSHA256"]=QString::fromLatin1(digest(childMounts));if(x["errno"].toInt()==0&&(x["mask"].toULongLong()&STATX_MNT_ID)){const auto id=x["mountID"].toULongLong();r["observerSelectedMount"]=selectedMount(observerMounts,id);r["childSelectedMount"]=selectedMount(childMounts,id);}
  if(lseek(fd,0,SEEK_SET)<0)throw Refused("Diagnostic FD seek refused");QByteArray bytes;char chunk[65536];off_t at=0;for(;;){const auto n=pread(fd,chunk,sizeof(chunk),at);if(n<0)throw Refused("Diagnostic FD read refused");if(!n)break;bytes.append(chunk,n);at+=n;if(bytes.size()>128*1024*1024)throw Refused("Diagnostic FD read bound");}r["selectedBackingSHA256"]=QString::fromLatin1(digest(bytes));r["fdAfter"]=fdSnapshot(fd);struct stat after{};if(lstat(named.constData(),&after))throw Refused("Diagnostic named source disappeared");r["namedAfter"]=statValue(after);
  const auto observerMountsAfter=boundedFile("/proc/self/mountinfo",2*1024*1024),childMountsAfter=boundedFile(QString("/proc/%1/mountinfo").arg(pid),2*1024*1024);r["observerMountInfoAfterSHA256"]=QString::fromLatin1(digest(observerMountsAfter));r["childMountInfoAfterSHA256"]=QString::fromLatin1(digest(childMountsAfter));if(x["errno"].toInt()==0&&(x["mask"].toULongLong()&STATX_MNT_ID)){const auto id=x["mountID"].toULongLong();r["observerSelectedMountAfter"]=selectedMount(observerMountsAfter,id);r["childSelectedMountAfter"]=selectedMount(childMountsAfter,id);r["selectedMountUnchanged"]=r["observerSelectedMount"]==r["observerSelectedMountAfter"]&&r["childSelectedMount"]==r["childSelectedMountAfter"];}r["mapFilesAfter"]=pathSnapshot(mapFile);const auto mapsAfter=boundedFile(mapsName,2*1024*1024);r["mapsAfterSHA256"]=QString::fromLatin1(digest(mapsAfter));r["selectedRowAfterPresent"]=mapsAfter.split('\n').contains(row);r["identityAfter"]=childIdentity(pid);r["identityUnchanged"]=r["identityBefore"]==r["identityAfter"];r["sourceFDUnchanged"]=r["fdBefore"]==r["fdAfter"];r["namedUnchanged"]=r["namedBefore"]==r["namedAfter"];r["mapFilesUnchanged"]=r["mapFilesBefore"]==r["mapFilesAfter"];r["diagnosticCompleted"]=true;
 }catch(const std::exception&e){r["diagnosticError"]=QString::fromLocal8Bit(e.what());r["diagnosticCompleted"]=false;try{r["identityAfter"]=childIdentity(pid);r["identityUnchanged"]=r["identityBefore"]==r["identityAfter"];}catch(const std::exception&after){r["identityAfterError"]=QString::fromLocal8Bit(after.what());}}
 if(fd>=0)close(fd);return r;
}
}
