'use strict';
const fs=require('fs'),assert=require('assert/strict');
const app=require(process.argv[2]).Elm.MenuSurfaceReplay.init({flags:null});
const base=JSON.parse(fs.readFileSync(process.argv[3],'utf8')),geo=JSON.parse(fs.readFileSync(process.argv[4],'utf8'));
const copy=x=>JSON.parse(JSON.stringify(x)),native=frame=>({kind:'native',frame});
const baseline=[{kind:'owner',frame:base.owner},native(base.attached),native(base.projection),native({protocolVersion:3,kind:'host-geometry-negotiate'}),native(geo.attach),native(geo.facts)];
const notification=native({protocolVersion:3,kind:'host-refresh'}),cases=[];
const timer=setTimeout(()=>{throw Error('Notification replay deadline')},20000);
function replay(events){return new Promise(resolve=>{const cb=rows=>{app.ports.outgoing.unsubscribe(cb);resolve(rows)};app.ports.outgoing.subscribe(cb);app.ports.incoming.send(events)})}
async function check(name,events,verify){let rows;try{rows=await replay(events);verify(rows,rows.at(-1));cases.push({name,passed:true,rows})}catch(error){cases.push({name,passed:false,error:String(error),rows});console.error(name,error.stack)}}
const stage=require('./stage.cjs')(replay);
const context=frame=>({kind:'action',action:{surfaceProtocol:2,kind:'surface-context',surface:'bar',publication:frame.publication,lease:frame.lease,id:'bar:group:application:org.a',trigger:'pointer',x:40,y:20}});
const action=(frame,id)=>({kind:'action',action:{surfaceProtocol:2,kind:'surface-action',surface:'popup',publication:frame.publication,lease:frame.lease,id}});
const projection=(request='4',revision='2',minimized=false)=>{const p=copy(base.projection);p.requestId=request;p.context.revision=p.scene.revision=revision;p.scene.windows.filter(w=>['10','11'].includes(w.incarnation)).forEach(w=>w.minimized=minimized);return p};
const facts=(request='5',revision='102',sequence='2',mode='maximized',minimized=false)=>{const f=copy(geo.facts);f.requestId=request;f.revision=revision;f.sequence=sequence;const row=f.facts.windows[0];row.nativeMode=row.clientMode=mode;row.logicalGeometry=row.visualGeometry=mode==='maximized'?[0,0,800,600]:[123,81,300,200];row.minimized=minimized;row.geometryEligible=!minimized;row.ordinaryPlacementKnown=false;row.capabilities={maximize:mode==='ordinary'&&!minimized,restoreGeometry:false};f.facts.windows[1].minimized=minimized;return f};
const outcome=(status='Committed')=>({...copy(geo.maxCommand),kind:'effect-outcome',status,reason:'',revision:'102',outputGeneration:'1'});
(async()=>{
 const ready=(await replay(baseline)).at(-1).frame,opened=[...baseline,context(ready)],menu=(await replay(opened)).at(-1);
 const refresh=[...opened,notification];
 await check('external host notification emits separate correlated legacy and geometry requests',refresh,(_,last)=>{assert.deepEqual(last.requests,[{protocolVersion:3,kind:'projection-request',binding:base.binding,requestId:'4'},{protocolVersion:3,kind:'geometry-facts-request',geometryProtocol:1,binding:base.binding,requestId:'5',minimumWatermark:'1'}]);assert.equal(last.shell.available,false);assert.equal(last.registry,0);assert.equal(last.outstanding,0)});
 await check('notification preserves old observations without allowing mutation',refresh,(_,last)=>{assert.equal(last.geometry.windows[0].mode,'ordinary');assert(last.frame.popup.filter(x=>x.id.startsWith('menu:')).every(x=>!x.enabled));assert.equal(last.shell.effects.request,'0')});
 await check('old scoped Maximize callback cannot dispatch while notification refresh awaits',[...refresh,action(menu.frame,'menu:1:2')],(_,last)=>{assert.equal(last.requests.length,0);assert.equal(last.registry,0);assert.equal(last.shell.effects.request,'0')});
 const observed=[...refresh,native(projection()),native(facts())];
 await check('external MAX updates independently observed geometry after admission',observed,(_,last)=>{assert.equal(last.geometry.windows[0].mode,'maximized');assert.equal(last.geometry.revision,'102');assert.equal(last.shell.effects.windows[0].minimized,false);assert.equal(last.frame.mode,'closed');assert.equal(last.requests.length,0)});
 const externalMenu=[...observed,context((await replay(observed)).at(-1).frame)];
 await check('external MAX without owned origin cannot infer RestoreGeometry capability',externalMenu,(_,last)=>{assert.deepEqual(last.frame.popup.map(x=>[x.label,x.enabled]),[['Close',true],['Restore',false],['Minimize',true],['Maximize',false]]);assert.equal(last.shell.effects.request,'0')});
 const moved=[...refresh,native(projection()),native(facts('5','102','2','ordinary'))];
 await check('external move revision retires old frozen menu without sending effect',moved,(_,last)=>{assert.equal(last.geometry.revision,'102');assert.equal(last.frame.mode,'closed');assert.equal(last.registry,0);assert.equal(last.shell.effects.request,'0')});
 const bursts=[...refresh,...Array(20).fill(notification)];
 await check('many notifications bound allocations to one batch and one dirty bit',bursts,(_,last)=>{assert.equal(last.shell.request,'5');assert.equal(last.requests.length,0);assert.equal(last.shell.notificationQueued,true);assert.equal(last.shell.effects.request,'0')});
 const partial=[...bursts,native(projection())];
 await check('legacy response alone never drains pending geometry batch',partial,(_,last)=>{assert.equal(last.requests.length,0);assert.equal(last.shell.request,'5');assert.equal(last.shell.notificationQueued,true);assert.equal(last.shell.available,false)});
 const drained=[...partial,native(facts())];
 await check('admitted pair drains exactly one deferred dual observation batch',drained,(_,last)=>{assert.deepEqual(last.requests.map(x=>[x.kind,x.requestId]),[['projection-request','6'],['geometry-facts-request','7']]);assert.equal(last.shell.request,'7');assert.equal(last.shell.notificationQueued,false);assert.equal(last.geometry.revision,'102')});
 await check('late old geometry response cannot consume newer correlation',[...drained,native(facts('5','103','3','ordinary'))],(_,last)=>{assert.equal(last.geometry.revision,'102');assert.equal(last.requests.length,0);assert.equal(last.shell.available,false)});
 await check('late old legacy response cannot consume newer correlation',[...drained,native(projection('4','99',true))],(_,last)=>{assert.equal(last.shell.effects.windows[0].minimized,false);assert.equal(last.requests.length,0);assert.equal(last.shell.available,false)});
 const complete=[...drained,native(projection('6','3')),native(facts('7','102','3'))];
 await check('drained batch becomes ready without an infinite notification loop',complete,(_,last)=>{assert.equal(last.requests.length,0);assert.equal(last.shell.request,'7');assert.equal(last.shell.notificationQueued,false);assert.equal(last.shell.available,true);assert.equal(last.geometry.windows[0].mode,'maximized')});
 await check('matching request with obsolete geometry revision is refused',[...drained,native(projection('6','3')),native(facts('7','100','3','ordinary'))],(_,last)=>{assert.equal(last.geometry.revision,'102');assert.equal(last.shell.available,false);assert.equal(last.requests.length,0)});
 const dispatch=await stage([...opened,action(menu.frame,'menu:1:2')]);
 const pending=[...dispatch,...Array(20).fill(notification)];
 await check('notifications during Pending defer without observation or effect allocation',pending,(_,last)=>{assert.equal(last.requests.length,0);assert.equal(last.shell.request,'5');assert.equal(last.shell.effects.request,'1');assert.equal(last.registry,1);assert.equal(last.unresolved[0].status,'Pending');assert.equal(last.shell.notificationQueued,true)});
 const receipt=[...pending,native(outcome())];
 await check('receipt drains queued notification with fresh observations not replayed effect',receipt,(_,last)=>{assert.deepEqual(last.requests.map(x=>[x.kind,x.requestId]),[['projection-request','6'],['geometry-facts-request','7']]);assert.equal(last.shell.notificationQueued,false);assert.equal(last.shell.effects.request,'1');assert.equal(last.registry,0);assert.equal(last.geometry.windows[0].mode,'ordinary')});
 await check('Unknown receipt also refreshes while retaining native barrier',[...pending,native(outcome('Unknown'))],(_,last)=>{assert.equal(last.requests.length,2);assert.equal(last.registry,1);assert.equal(last.unresolved[0].status,'Unknown');assert.equal(last.shell.effects.request,'1');assert.equal(last.shell.notificationQueued,false)});
 const unsupportedAttach=copy(geo.attach);unsupportedAttach.capabilities.effects=false;unsupportedAttach.capabilities.operations=[];const unsupportedFacts=copy(geo.facts);unsupportedFacts.facts.windows.forEach(w=>w.capabilities={maximize:false,restoreGeometry:false});
 const unsupported=[...baseline.slice(0,3),native({protocolVersion:3,kind:'host-geometry-negotiate'}),native(unsupportedAttach),native(unsupportedFacts),notification];
 await check('unsupported geometry causes no extra geometry notification traffic',unsupported,(_,last)=>{assert.deepEqual(last.requests.map(x=>x.kind),['projection-request']);assert.equal(last.shell.effects.request,'0')});
 const minimized=[...refresh,native(projection('4','2',true)),native(facts('5','102','2','maximized',false))];
 const incoherentMenu=[...minimized,context((await replay(minimized)).at(-1).frame)];
 await check('independent minimized mismatch cannot expose mixed actionable provider',incoherentMenu,(_,last)=>{assert.equal(last.frame.mode,'closed');assert.equal(last.requests.length,0);assert.equal(last.registry,0)});
 const wrong=facts();wrong.binding.frontend='299';
 await check('old binding facts cannot clear notification bookkeeping',[...refresh,native(projection()),native(wrong)],(_,last)=>{assert.equal(last.geometry.revision,'101');assert.equal(last.shell.available,false);assert.equal(last.requests.length,0)});

 const higher=facts();higher.outputGeneration='2';higher.facts.windows.forEach(w=>{w.outputOwnershipGeneration='61';w.workAreaRevision='71'});
 const higherProjection=projection();higherProjection.context.output='2';
 const outputAdmitted=[...refresh,native(higherProjection),native(higher),notification];
 const backwards=facts('7','103','3');backwards.outputGeneration='1';
 await check('matching request cannot roll geometry output generation backward',[...outputAdmitted,native(backwards)],(_,last)=>{assert.equal(last.geometry.output,'2');assert.equal(last.geometry.revision,'102');assert.equal(last.shell.available,false);assert.equal(last.requests.length,0)});
 const attaching=[...baseline.slice(0,3),native({protocolVersion:3,kind:'host-geometry-negotiate'}),notification];
 const refusedAttach={protocolVersion:3,kind:'geometry-unavailable',binding:base.binding,requestId:'2',reason:'unavailable'};
 await check('attach failure drains queued external notification as legacy-only refresh',[...attaching,native(refusedAttach)],(_,last)=>{assert.equal(last.shell.notificationQueued,false);assert.deepEqual(last.requests.map(x=>[x.kind,x.requestId]),[['projection-request','3']]);assert.equal(last.shell.effects.request,'0')});
 const passed=cases.every(x=>x.passed);fs.writeFileSync(process.argv[5],JSON.stringify({passed,checks:cases.length,cases,scope:'Compiled actual dual observation notification lifecycle; synthetic native envelopes, no GUI'},null,2)+'\n');clearTimeout(timer);if(!passed)process.exitCode=1;
})().catch(error=>{clearTimeout(timer);console.error(error.stack);process.exitCode=1});
