/* Documentation navigation and transport only. Desktop decisions stay in Elm. */
'use strict';
const DATA=window.WARLOCK_CATALOG, components=DATA.registry.components;
const main=document.getElementById('main'), nav=document.getElementById('nav'), toc=document.getElementById('toc');
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=values=>'<ul>'+values.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul>';
const section=(id,title,body)=>`<section aria-labelledby="${id}"><h2 id="${id}">${esc(title)}</h2>${body}</section>`;
const note=body=>`<div class="evidence-note">${body}</div>`;
const foundations=[['overview','Welcome'],['philosophy','Philosophy'],['foundations','Identity & foundations'],['tokens','Tokens'],['states','Interaction & outcomes']];
const patterns=[['patterns','Desktop patterns'],['accessibility','Accessibility'],['library','Proposed controls'],['references','Reference decisions'],['evidence','Evidence & limits'],['changelog','Changelog']];
const links=[...foundations,...components.map(c=>['component/'+c.id,c.name]),...patterns];
let currentRoute='overview', demo=null, unsubscribe=null;
function buildNav(query=''){
 const q=query.trim().toLocaleLowerCase();let count=0;let html='';
 for(const [heading,items] of [['Foundations',foundations],['Components',components.map(c=>['component/'+c.id,c.name])],['Practice',patterns]]){
  const found=items.filter(([id,name])=>{const c=components.find(c=>'component/'+c.id===id);return !q||(name+' '+(c?c.states.join(' ')+' '+c.content.join(' ')+' '+c.behavior:id)).toLocaleLowerCase().includes(q);});
  if(found.length){html+=`<h2>${heading}</h2>`+found.map(([id,name])=>{count++;return `<a href="#${id}"${id===currentRoute?' aria-current="page"':''}>${esc(name)}</a>`;}).join('');}
 }
 nav.innerHTML=html||'<p class="empty">No matching pages. Try “preview”, “focus” or “Unknown”.</p>';
 document.getElementById('search-status').textContent=q?`${count} matching ${count===1?'page':'pages'}`:'';
}
function demoMarkup(topic){
 let actions='';
 if(topic==='menu')actions=['committed','refused','cancelled','unknown'].map(outcome=>`<button type="button" data-outcome="${outcome}">Simulate ${outcome}</button>`).join('')+'<button type="button" data-dismiss>Dismiss menu</button>';
 if(topic==='preview')actions=[['load','Request fixture'],['frame','Supply fixture frame'],['historical','Source becomes historical'],['lock','Lock source'],['expire','Advance fixture clock'],['close','Close preview']].map(([id,label])=>`<button type="button" data-preview="${id}">${label}</button>`).join('');
 if(topic==='bar')actions='<label>Family state <select id="profile">'+['inactive','active','minimized','unavailable','multiple','empty'].map(p=>`<option value="${p}">${p}</option>`).join('')+'</select></label>';
 return `<div class="demo" data-demo="${topic}"><div class="demo-head"><p>Actual Elm modules · simulated authority</p><button type="button" id="fixture-reset">Start a new fixture session</button></div><div id="elm-demo"></div><div class="fixture-controls">${actions}</div>${topic==='preview'?'<p class="caption">Fixture pixels use the original Warlock illustration. No window is captured. Fixture clock ticks are illustrative; original native deadlines stay unchanged.</p>':''}<details class="fixture-output"><summary>Inspect typed state and effect descriptions</summary><pre id="observed">Initializing Elm fixture…</pre></details></div>`;
}
function componentPage(c){
 return `<h1>${esc(c.name)}</h1><p class="scope"><span class="status-chip">Source</span>Selected GUI519-derived closure · native acceptance open</p>`+
 section('overview','Overview',`<p>${esc(c.overview)}</p>${c.topic?demoMarkup(c.topic):note('<p>This native GTK control has no HTML substitute in the catalog.</p>')}`)+
 section('anatomy','Anatomy & states',`<p>Published content, stable control identity and eligibility determine the surface. Interaction and operation outcomes are independent.</p><ul class="states">${c.states.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>${c.selectors.length?'<p>Source selectors: '+c.selectors.map(s=>`<code>${esc(s)}</code>`).join(', ')+'.</p>':''}`)+
 section('behavior','Behavior & keyboard',`<p>${esc(c.behavior)}</p>`)+
 section('accessibility','Accessibility',`<p>${esc(c.accessibility)}</p>${c.gaps.length?note('<p>Open source findings:</p>'+list(c.gaps)):''}`)+
 section('content','Content',`<p>Source copy is inventoried separately from proposed improvements.</p>${list(c.content)}<p><a href="content-inventory.json">Inspect exact source string tokens</a>.</p>`)+
 section('evidence','Evidence',`<p>The source registry records exact hashes. The compiled fixture demonstrates pure Elm behavior; it cannot establish compositor input, frame presentation, physical release, audible or braille delivery.</p>${list(c.files)}<p><a href="registry.json">Source registry</a> · <a href="src/${esc(c.files[0])}">Primary source</a></p>`);
}
function page(route){
 if(route.startsWith('component/')){const c=components.find(c=>c.id===route.split('/')[1]);if(c)return componentPage(c);}
 if(route==='overview')return `<h1>A desktop you can<br>reason about.</h1><p class="lead">Warlock keeps user intent, visible state and native behavior in agreement so people can work with confidence.</p><p>Crafted for flow. A design language for sustained windowed work, built around one immutable Elm model, typed events and observed native outcomes.</p><img class="intro-art" src="assets/art/warlock-flow-wallpaper.png" width="1672" height="941" alt="Warlock flow illustration: folded forms and event streams in ink, lilac, mint and gold"><p class="caption">Original generated brand artwork. Decorative streams are not protocol evidence.</p>`+
 section('start','Start with an interaction',`<p>Explore a widget, inspect its states and see what is already in source. Every component uses the same six sections.</p><ul class="component-list">${['menu','window-group','preview'].map(id=>{const c=components.find(c=>c.id===id);return `<li><a href="#component/${id}">${c.name}</a><p>${id==='menu'?'Intent survives uncertainty.':id==='preview'?'Freshness and pixel ownership stay explicit.':'One family, one predictable primary decision.'}</p></li>`;}).join('')}</ul>`)+
 section('model','Intent becomes an observed outcome','<div class="stream" aria-label="Architecture flow"><span>Typed intent</span><span>Elm Update</span><span>Native effect request</span><span>Observed facts</span><span>Derived view</span></div><p>FRP informs how change propagates. Modern Elm uses Model, Update and View. Requests and observations enter the same controller; view surfaces project its state. Native authority determines what actually happened.</p>')+
 section('scope','What this catalog establishes',note('<p>The design is agreed in 30 contracts. This catalog documents 14 source component families across the full selected 49-module closure. Implementation and qualification are claim-specific. The full GUI release remains in development.</p><p><a href="#evidence">Read the evidence boundaries</a>.</p>'));
 if(route==='philosophy')return '<h1>Crafted for flow.</h1><p class="statement">Keep intent, visible state and native behavior in agreement.</p>'+section('commitment','A commitment to the person using it','<p>One coherent model records intent and observed state; typed events make changes explicit, and native authority determines what actually happened. Familiar conventions and coherent defaults reduce decisions. Accessibility belongs to every control. Failures remain understandable and recovery preserves unresolved obligations.</p>')+section('manifesto','The manifesto',list(['Optimize for confidence. Keep the action target and its outcome understandable.','Keep one coherent account of the desktop. Derive surfaces from immutable state.','Let native reality settle physical claims. Sending is not confirmation.','Respond promptly and report honestly. Reconcile uncertainty before repeating an action.','Make continuity part of correctness. Preserve identity through change.','Make accessibility a complete interaction path. Qualify the native route.','Design ownership and recovery together. Cleanup needs its own evidence.','Provide coherent defaults and principled customization.','Spend resources deliberately. Bound admission without forgetting obligations.','Make evidence govern change. Preserve failures and ship a tested rollback path.']));
 if(route==='foundations')return '<h1>Identity & foundations</h1><p class="lead">Esoteric character, familiar controls.</p>'+section('mark','The flow sigil','<div class="logos"><img src="assets/identity/warlock-mark.svg" alt="Warlock folded W with central diamond"><img src="assets/identity/warlock-mark-mono.svg" alt="Monochrome Warlock mark"><img class="small" src="assets/identity/warlock-mark-mono.svg" alt="24 pixel monochrome mark"></div><p>Use the detailed mark at 32px and above. At 24–31px, use monochrome. Below 24px, use a plain W. Keep one central-diamond width clear on all sides.</p>')+section('type','Type and rhythm','<p>Space Grotesk gives headings their voice. Inter carries body text and controls; JetBrains Mono is reserved for code and measurements. Fonts and licenses are bundled.</p><p>Reader measure is 70 characters. Catalog control targets are at least 32px. Density and product timing still need their own native and accessibility evidence.</p>')+section('surface','Solid surfaces, clear signals','<p>Ink and parchment ground the two appearances. Lilac identifies actions and focus. Mint, gold and the danger tone support confirmed, uncertain and refused outcomes, always with words. Decoration cannot confer authority.</p><p><a href="#tokens">Inspect reference, semantic and component tokens</a>.</p>');
 if(route==='tokens')return '<h1>Tokens</h1><p class="lead">Reference → semantic role → component role.</p>'+section('palette','Reference palette',`<div class="table-wrap"><table><thead><tr><th>Role</th><th>Dark</th><th>Light</th></tr></thead><tbody>${Object.keys(DATA.tokens.reference.dark).map(k=>`<tr><th>${esc(k)}</th><td><code>${DATA.tokens.reference.dark[k]}</code></td><td><code>${DATA.tokens.reference.light[k]}</code></td></tr>`).join('')}</tbody></table></div>`)+section('semantic','Semantic roles',`<div class="table-wrap"><table><thead><tr><th>Semantic</th><th>Reference</th></tr></thead><tbody>${Object.entries(DATA.tokens.semantic).map(([k,v])=>`<tr><td><code>--${k}</code></td><td><code>--ref-${v}</code></td></tr>`).join('')}</tbody></table></div>`)+section('component','Component roles',`<div class="table-wrap"><table><thead><tr><th>Component</th><th>Semantic</th></tr></thead><tbody>${Object.entries(DATA.tokens.component).map(([k,v])=>`<tr><td><code>--${k}</code></td><td><code>--${v}</code></td></tr>`).join('')}</tbody></table></div>`)+section('contrast','Pairs and adaptations','<p>Declared text pairs target 4.5:1. Boundaries and focus target 3:1 against their actual containers. Hover changes the boundary, disabled controls retain readable text, and focus uses an accent ring separated by the container color. No opacity overlay weakens text.</p><p>Forced colors use Canvas, CanvasText, ButtonText, LinkText and Highlight. These are browser catalog mappings; native support remains independently qualified.</p><p><a href="tokens.json">Machine-readable tokens and pair declarations</a> · <a href="tokens.css">Generated CSS mappings</a></p>');
 if(route==='states')return '<h1>Interaction & outcomes</h1><p class="lead">Focus, selection and completion answer different questions.</p>'+section('axes','Two independent axes','<p>Interaction describes how a person engages a control: resting, hover, focus, pressed, selected, current or unavailable. Outcome describes the operation: Pending, Committed, Refused, Cancelled or Unknown. A focused control has no special power to confirm its effect.</p>')+section('outcomes','Outcome vocabulary','<div class="outcomes"><p class="outcome-pending">Pending — the request awaits an authoritative result.</p><p>Committed — the correlated native result confirms the operation.</p><p class="outcome-refused">Refused — the authority rejected the operation; show the reason.</p><p>Cancelled — a correlated cancellation result, distinct from a cleanup request.</p><p class="outcome-unknown">Unknown — the result is unconfirmed; reconcile before repeating.</p></div>')+section('eligibility','Eligibility and focus','<p>The declared per-surface policy determines whether a blocked control can hold focus. The selected source uses HTML disabled for blocked menu actions. A proposed focusable unavailable pattern cannot silently rewrite that source behavior.</p><p><a href="#component/menu">Exercise actual menu policy</a>.</p>');
 if(route==='patterns')return '<h1>Desktop patterns</h1>'+section('choose','Choose the right window','<p>Window groups use actual primary decisions. Multiple families open a picker; an individual row asks to activate or restore the specific observed family. Scope and generation remain attached to the action.</p>')+section('recover','Recover without replay','<p>Refresh status reads observations. Unknown blocks another operation against its target until reconciliation establishes a safe disposition. Closing a menu never erases the outstanding operation.</p>')+section('extend','Guarded extensions','<p>Launcher search, settings, snapping and workspace presentation are design targets. Native workspace ownership, capability admission, coherent settings guarantees and frozen placement behavior must precede integration. Catalog navigation is not desktop launcher search.</p>')+section('motion','Continuity and motion','<p>Motion follows actual presented geometry and current preferences. It cannot settle an operation or refresh a deadline. These examples advance only by explicit fixture input and have no recurring timer. Native reduced-motion, reversal, cadence and presentation remain release gates.</p>');
 if(route==='accessibility')return '<h1>Accessibility is a path.</h1><p class="lead">Names, roles, states, focus and announcements must agree.</p>'+section('keyboard','Keyboard and focus','<p>The catalog has a skip link, native links and form controls, searchable navigation and visible two-tone focus. Component source contracts determine keyboard behavior inside fixtures. Tab remains native browser navigation; menu arrows operate the selected item, distinct from focus.</p>')+section('adapt','Appearance and adaptation','<p>Light, dark and system appearance preserve the same action targets. At narrow widths, navigation becomes a disclosure. Forced colors use system tokens. Text reflows, labels wrap and the document supports browser enlargement. No automatic motion is required to understand a state.</p>')+section('gaps','Current product findings',list(['Popup children are not keyed in the selected renderer.','Selected detail drives aria-current; checked toggle semantics are absent.','The bar and popup both publish polite live regions. A single delivery owner is not yet qualified.','Operation-prefixed accessible names need an explicit visible-label convention.','Complete native keyboard, assistive-technology, IME, speech and braille paths remain release work.']))+section('verify','Qualify the complete route','<p>DOM and browser checks can establish catalog behavior only. The owning native GUI must separately prove focus continuity, input eligibility, announcements, composition and constrained geometry.</p>');
 if(route==='library')return '<h1>Proposed controls</h1><p class="scope"><span class="status-chip">Proposed</span>Style specimens; these are not shipped desktop features.</p>'+section('controls','Buttons and fields','<div class="demo"><div class="fixture-controls"><button type="button" id="library-inspect">Inspect specimen</button><button type="button" disabled>Unavailable in this specimen</button></div><label class="proposed-field">Example name<input type="text" placeholder="Your workspace name" maxlength="80"><small>Catalog-only text; never sent to the desktop.</small></label><label><input type="checkbox"> Example preference</label><p id="library-result" role="status" aria-live="polite"></p></div><p>Native button and field semantics are used here to show type, spacing and focus. The example preference is local to the page. It does not configure Warlock.</p>')+section('criteria','Before product adoption','<p>Each control needs a typed model, defined eligibility, honest pending and error states, stable identity and an accessible native route. Tabs, progress, settings and launcher extensions remain proposals until integrated and qualified.</p>');
 if(route==='references')return '<h1>Reference decisions</h1><p class="lead">Borrow the useful rule. Preserve Warlock’s own identity.</p>'+section('adoption','What we adopt',`<div class="table-wrap"><table><thead><tr><th>Reference</th><th>Warlock decision</th></tr></thead><tbody>${[
 ['Material Design','https://m3.material.io/','Use consistent component documentation, token tiers and explicit state anatomy; choose Warlock colors and measured geometry.'],['Impeccable','https://github.com/pbakaus/impeccable/tree/87a6ab0c145adb85cbd428a99fa1377305e0818d','Use Read/Operate modes, readable measure, original identity and a bounded finish review.'],['iOS','https://developer.apple.com/design/human-interface-guidelines/','Adopt continuity, clear feedback and accessible adaptation; macOS guidance is a labeled desktop supplement.'],['Plasma / KDE','https://develop.kde.org/hig/','Adopt familiar desktop navigation and principled customization, keeping native scope guarantees.'],['GNOME','https://developer.gnome.org/hig/','Adopt approachable copy, purposeful surfaces and understandable recovery.'],['Windows / Fluent','https://learn.microsoft.com/en-us/windows/apps/develop/input/keyboard-interactions','Adopt explicit keyboard and focus contracts, operation feedback and contrast adaptation.']].map(([name,url,decision])=>`<tr><th><a href="${url}" rel="noreferrer">${name}</a></th><td>${esc(decision)}</td></tr>`).join('')}</tbody></table></div>`)+section('boundaries','What needs its own evidence','<p>Platform metrics, durations, blur, shadows, density and application behavior are not adopted from snippets or resemblance. A design proposal cannot weaken original deadlines, native authority or accessibility contracts. No platform art or proprietary assets are copied.</p>');
 if(route==='evidence')return '<h1>Evidence & limits</h1><p class="lead">Attach evidence to the claim it actually tests.</p>'+section('records','Claim-specific records',`<div class="table-wrap"><table><thead><tr><th>Record</th><th>Scope</th></tr></thead><tbody><tr><th>Agreed design</th><td>Five reviewers accepted the exact second candidate: 30 contracts, additive EARS/OpenSpec.</td></tr><tr><th>Source</th><td>49 original Elm modules, source styles/input bridge and native fallback; hashes in the registry.</td></tr><tr><th>Demo</th><td>Actual pure modules with explicit fixture outcomes and clocks. No native IPC.</td></tr><tr><th>Build / CPU</th><td>Pinned Elm compilation and claim-specific checks. Retained failures remain available.</td></tr><tr><th>Browser</th><td>Requires the catalog’s own responsive, keyboard and behavioral receipts.</td></tr><tr><th>Native</th><td>Requires the original scenario, receipt and exact owning core/plugin ABI. This catalog grants none.</td></tr></tbody></table></div>`)+section('open','Release work stays open','<p>Eligible client/family capture, native preview13, original restore/recovery and drag/resize campaigns, coherent input/popup integration, hardware/output, assistive technology/IME, resource budgets, representative journeys and reversible deployment remain separate release gates.</p>')+section('source','Inspect the packet','<p><a href="registry.json">Source registry</a> · <a href="content-inventory.json">Exact source strings</a> · <a href="tokens.json">Token declarations</a> · <a href="ANCESTRY.json">Catalog ancestry</a></p><p>Other archived integration lanes are not silently treated as part of this coherent selected source closure. Evidence labels never change because a person clicks a fixture button.</p>');
 if(route==='changelog')return '<h1>Changelog</h1>'+section('agreed','Design agreement','<p>The first consensus ballot retained dissent. The second candidate corrected disabled-focus policy, the shipped Taskbar.primary False call, original preview meanings and the iOS reference scope. All five reviewers accepted all 30 contracts.</p>')+section('catalog','Catalog implementation','<p>The first fixture failed Elm indentation; the second exposed missing operation patterns. Both failed source versions and compile receipts are retained. The third compiled against the pinned GUI toolchain and supplies this catalog’s demos.</p>');
 return '<h1>Page not found</h1><p>This page is not in the catalog. <a href="#overview">Return to the overview</a>.</p>';
}
function startDemo(topic){
 const host=document.getElementById('elm-demo');demo=Elm.DesignDemo.init({node:host,flags:{topic}});const app=demo;
 const observed=value=>{document.getElementById('observed').textContent=JSON.stringify(value,null,2);window.fixtureObservation=value;};app.ports.fixtureObserved.subscribe(observed);unsubscribe=()=>app.ports.fixtureObserved.unsubscribe(observed);
 const send=value=>app.ports.fixtureInput.send(value);send({kind:'inspect'});
 document.getElementById('fixture-reset').onclick=()=>send({kind:'reset'});
 document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>send({kind:'authority',outcome:b.dataset.outcome}));
 document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>send({kind:'preview',action:b.dataset.preview}));
 const dismiss=document.querySelector('[data-dismiss]');if(dismiss)dismiss.onclick=()=>send({kind:'dismiss'});
 const profile=document.getElementById('profile');if(profile)profile.onchange=()=>send({kind:'profile',value:profile.value});
 const root=document.querySelector('.demo');
 const capture=b=>{const surface=b.closest('[data-publication][data-lease]');if(surface)send({kind:'surface-action',surfaceProtocol:2,surface:surface.classList.contains('surface-bar')?'bar':'popup',publication:surface.dataset.publication,lease:surface.dataset.lease,id:b.dataset.surfaceControl});};
 root.addEventListener('click',event=>{const b=event.target.closest('[data-surface-control]');if(b&&!b.disabled)capture(b);});
 root.addEventListener('keydown',event=>{
  if(topic!=='menu'||!event.target.closest('.elm-specimen'))return;
  if(['ArrowUp','ArrowDown','Home','End'].includes(event.key)){event.preventDefault();send({kind:'navigate',key:event.key});}
  else if(event.key==='Escape'){event.preventDefault();send({kind:'dismiss'});}
  else if(event.key==='Enter'){const b=root.querySelector('[aria-current="true"]');if(b&&!b.disabled){event.preventDefault();capture(b);}}
 });
 // Presentation-only URI adapter: a single explicit fixture token, never pixels from a window.
 const adapt=()=>root.querySelectorAll('img[src="elm-shell://preview/'+ '1'.repeat(64)+'"]').forEach(img=>{img.dataset.fixtureOriginalUri=img.getAttribute('src');img.src='assets/art/warlock-flow-wallpaper.png';});
 const observer=new MutationObserver(adapt);observer.observe(root,{subtree:true,childList:true,attributes:true,attributeFilter:['src']});const prior=unsubscribe;unsubscribe=()=>{observer.disconnect();prior();};
}
function render(focus=false){
 const parts=decodeURIComponent(location.hash.slice(1)||'overview').split('/');const route=parts[0]==='component'?parts.slice(0,2).join('/'):parts[0];const anchor=parts[0]==='component'?parts[2]:parts[1];
 if(route!==currentRoute||!main.querySelector('article')){
  if(unsubscribe)unsubscribe();unsubscribe=null;demo=null;window.fixtureObservation=null;currentRoute=route;
  main.innerHTML='<article>'+page(route)+'</article>';buildNav(document.getElementById('search').value);
  toc.innerHTML='<p>On this page</p>'+[...main.querySelectorAll('h2[id]')].map(h=>`<a href="#${route}/${h.id}">${esc(h.textContent)}</a>`).join('');
  document.title=(components.find(c=>'component/'+c.id===route)?.name||links.find(([id])=>id===route)?.[1]||'Design language')+' — Warlock';
  const d=main.querySelector('[data-demo]');if(d)startDemo(d.dataset.demo);
  const inspect=document.getElementById('library-inspect');if(inspect)inspect.onclick=()=>document.getElementById('library-result').textContent='Style specimen inspected. No desktop action was issued.';
  if(focus)main.focus({preventScroll:true});window.scrollTo(0,0);
 }
 if(anchor)document.getElementById(anchor)?.scrollIntoView();
 if(matchMedia('(max-width:720px)').matches)document.getElementById('navigation').open=false;
}
const theme=document.getElementById('theme'), system=matchMedia('(prefers-color-scheme:light)');
function applyTheme(){document.documentElement.dataset.theme=theme.value==='auto'?(system.matches?'light':'dark'):theme.value;}
try{theme.value=localStorage.getItem('warlock-catalog-appearance')||'auto';}catch(_){}applyTheme();
theme.onchange=()=>{applyTheme();try{localStorage.setItem('warlock-catalog-appearance',theme.value);}catch(_){}};system.addEventListener('change',applyTheme);
document.getElementById('search').addEventListener('input',event=>buildNav(event.target.value));
window.addEventListener('hashchange',()=>render(true));render();
