import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>1000
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v91/report.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-client-provider-native-v128',['PROGRESS PUBLIC exactowner publication64 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. HeldGUI92/native128 exactcore16/plugin18 PASS2466/277normalclean/all2458prior126fixed, full95/alloriginal12 and original retirement/control regressions. Retained45/14selected/34actualElmtraces/667state-command comparisons/3model+3compiledElm mutants and48actualCnativeElm loss/ACK/neighbor/close/normalexit controls. Held91 close barrier and failed127 preflight preserved. MutableGUI93 retained readiness/poll excluded; inspect its actual running processes/reports and qualify before new publication. Actual reliable outgoing control and WebKit retirement routing, captured retirement, >256real windows and all original release gates remain. Main desktop/drafts/five foreign tracked changes preserved.'],'progress',['docs/warlock-preview/v91/report.json','implementation/warlock-preview-provider-v92/component-manifest.json','implementation/warlock-client-provider-native-v128/component-manifest.json','docs/warlock-repository/v64/publication/delivery.json']);print(e)
