"""Prepare exact-owner successor publication over verified prior public history."""
import ast,json,pathlib,resource,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');report=json.loads((r/'docs/warlock-preview/v81/report.json').read_text());assert report['passed'] and report['sameHostExpiryReopenImageACKQualified']
out=r/'docs/warlock-repository/v57/publication';assert not out.exists();out.mkdir(parents=True)
s=(r/'docs/warlock-repository/v56/publication/publish.py').read_text()
s=s.replace("BASE='e79e5e7dc4027e559444b50f44ddd44f8f19cf52'","BASE='498df7d93c334137711c87de7915a7e936ba2074'")
s=s.replace('1d5bbecf561cb3ba9b9f8e5ef6cc0556e324b5fe..','d62345012d19181d05b2c1c97eabd5461413c807..')
allowed=('docs/warlock-preview/v79/','docs/warlock-preview/v80/','docs/warlock-preview/v81/','docs/warlock-repository/v56/publication/','docs/warlock-repository/v57/publication/','openspec/changes/warlock-preview-next-intent/','openspec/changes/warlock-preview-unissued-priority/','implementation/warlock-preview-provider-v77/','implementation/warlock-preview-provider-v78/','implementation/warlock-preview-provider-v79/','implementation/warlock-preview-provider-v80/','implementation/warlock-client-provider-native-v115/','implementation/warlock-client-provider-native-v116/')
start=s.index('allowed=(');end=s.index('\nassert all',start);s=s[:start]+'allowed='+repr(allowed)+s[end:]
start=s.index(' qualification=');end=s.index('\n published=',start)
message='Admit later preview requests after native expiry\n\nAdd explicit successor enrollment only after original native expiry and strictly later picker publication and lease. Preserve owner/incarnation/clock, bounded predecessor, original same-stamp cutoff, issued ownership and request floors. Prioritize unissued dynamic subjects before resumed actors. Full95 build, ten selected successor cases/22 ledger-Broker traces/447 state comparisons/two unsafe native mutations, actual C45/Elm21 and original component/model regressions pass. Native116 uses the exact owning ABI and the same full GUI host to qualify expiry, real pointer close/reopen, the third first job with its new native two-second cutoff, owned image loading and exact ACK/physical drain. All stable114 controls are retained and failed115 fixture evidence preserved. Native/full release, ordinary eligible capture, AT/hardware, resume-intent succession and proof-safe actor/history longevity remain open.\n'
new=" qualification=json.loads((REPO/'docs/warlock-preview/v81/report.json').read_text());assert qualification['passed'] and qualification['nextIntentStates']==447 and qualification['nextIntentScenarios']==10 and qualification['nativeCControls']==45 and qualification['elmWireControls']==21 and qualification['sameHostExpiryReopenImageACKQualified'] and qualification['nativeChecks']>=2428 and not qualification['nativeAcceptance'] and not qualification['fullReleaseAccepted']\n message="+repr(message)+'\n'
s=s[:start]+new+s[end:];ast.parse(s);(out/'publish.py').write_text(s)
s=(r/'docs/warlock-repository/v56/publication/record_delivery.py').read_text().replace("d['ownedFiles']>7000","d['ownedFiles']>1000").replace('docs/warlock-preview/v78','docs/warlock-preview/v81').replace('warlock-client-provider-native-v114','warlock-client-provider-native-v116').replace('warlock-preview-provider-v76','warlock-preview-provider-v80').replace('warlock-repository/v56','warlock-repository/v57')
start=s.index("['PROGRESS PUBLIC exactowner publication56 ");end=s.index(",'progress'",start)
notes="['PROGRESS PUBLIC exactowner publication57 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' blobs. FullGUI80 explicit successor/nativeexpiry/laterpublease/boundedpredecessor/unissuedpriority; full95/new10/22/447states/C45Elm21/originalcomponentModels passed; native116 '+str(report['nativeChecks'])+'/'+str(report['normalOwnedExits'])+'normalclean samehost pointerexpiryreopen thirdfirstjob/native2s/ownedimage/exactACK/physicaldrain, all114stableguards preserved, failed115 selector held. All publication work terminal. Next resume-intent succession, proof-safe actor/history retirement, ordinary eligibility and all original release gates. Main desktop/drafts/foreignchanges preserved, no fullreleaseclaim.']"
s=s[:start]+notes+s[end:];ast.parse(s);(out/'record_delivery.py').write_text(s);print(out)
