import json,pathlib,resource,subprocess,sys
sys.path.insert(0,'/home/hoskinson/window-integration-qa');from qa_launch import require_qa_scope
require_qa_scope();assert resource.getrlimit(resource.RLIMIT_CORE)==(1,1)
r=pathlib.Path('/home/hoskinson/omarchy-windows-parity');base=pathlib.Path(__file__).parent;d=json.loads((base/'delivery.json').read_text());assert d['pushCompleted'] and d['ownedFiles']>=1968
v=json.loads(subprocess.check_output(['gh','repo','view','CharlesHoskinson/Warlock','--json','name,url,visibility'],text=True));assert v['visibility']=='PUBLIC';(base/'visibility.json').write_text(json.dumps(v,indent=2)+'\n')
observed=subprocess.check_output(['gh','api','repos/CharlesHoskinson/Warlock/branches/feature%2Felm','--jq','.commit.sha'],text=True).strip();assert observed==d['publishedCommit']
(base/'branch.json').write_text(json.dumps({'commit':observed,'verified':True},indent=2)+'\n')
report=json.loads((r/'docs/warlock-preview/v93/component-report129.json').read_text())
sys.path.insert(0,str(r/'implementation/elm-build-loop-v1'));import loop
e=loop.write_checkpoint(r,'f6779148-8f5d-4bdf-8a0f-044184e486f2','implementation/warlock-preview-provider-v129',['PROGRESS PUBLIC95 '+d['publishedCommit']+' verified '+str(d['ownedFiles'])+' exact owned blobs. SAFEGUI129 normalNative14029checks13normalexits and separate actual delayed-resultNative14118checks8normalexits; original16 admission/drain retained. One actual original WebKit result/view/scope held without early finish, real closure invalidates projection, same result finished once/rejected/no stale artifact, original policy/native input/ticket/physical/journal/confirmation duties drain through strict close. Both cleanups/full119/deadline6/core16/plugin19/AQ155 pass, opacity0/single policy/original native issuer/physical product/no grant reset unchanged. Bounded after-close snapshot callback qualified; broader stale callbacks/normal realm reopen/reload/process/uncertain recovery/physical frame/reveal/pressure/workload/RSS/full preview/release remain open. Next safe original native realm lifecycle and actual ongoing frame/reveal qualification, retaining all accepted/failed/unsafe evidence. Installed/drafts/foreign untouched.'],'progress',['docs/warlock-preview/v93/component-report129.json','implementation/warlock-preview-provider-v129/component-manifest.json','implementation/warlock-client-provider-native-v140/component-manifest.json','implementation/warlock-client-provider-native-v141/component-manifest.json','docs/warlock-repository/v95/publication-v2/delivery.json']);print(e)
