--- window-integration-qa/modal-ancestor-discovery-v2/native-candidate/Makefile
+++ window-integration-qa/toolkit-interruption-v3/native-candidate/Makefile
@@ -11,7 +11,7 @@
 LIBS = `pkg-config --libs cairo`
 
 SRC = main.cpp barDeco.cpp BarPassElement.cpp dragBridge.cpp familyBridge.cpp ancestorHit.cpp snapshotBridge.cpp atlasRenderer.cpp atlasAdapter.cpp
-TARGET = hyprbars-v19-modal-candidate.so
+TARGET = hyprbars-v20-interruption-candidate.so
 
 all: $(TARGET)
 
